### ISSUE TITLE
No text highlighted in source on Change concluded License page

### ISSUE THREAD

**Issue by djznidarsic** [fossology/fossology#1042]
Using: Version: [3.2.0], Branch: [master], Commit: [#a62a3c] 2018/03/07 08:44 UTC built @ 2018/03/14 02:59 UTC

In the "Change concluded License" page, for some of my files, even though there is a license listed in the pane on the right side found by, say, ninka or nomos, and a legend, there is no text highlighted in the pane on the left side. I do understand that sometimes the highlight is difficult to see when only a couple characters are highlighted, but in some files I can find no highlight even after removing the legend and scrolling all the way to the right.

Is this a bug or a feature? That is, should the text that triggers a found license always be highlighted? If not, what are the conditions under which no text would be highlighted when a license is listed?

Thanks,
David

**Comment by mcjaeger** [comment]
@djznidarsic I am sorry that this issue has been lying around for such a long time.

Because the answer is no for Nomos and Monk. Ninka does not provide highlighting information, so maybe this is the issue?

 If the issue persist, would you mind to send a screenshot?

**Comment by mcjaeger** [comment]
@djznidarsic please reopen if issue persists
