### ISSUE TITLE
"Next" Button does not save "No License Known" decision

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1044]
Tested in 3.2.0 version.

When selecting "Identified", clicking the _Next_ button automatically saves the decision and moves on to the next file (as expected and described in the [basic-workflow](https://www.fossology.org/get-started/basic-workflow/) )

However, it the behaviour is not the same when selecting "No license known", the decision is simply ignored.
 
To reproduce:

1. Go to a "Change concluded License " page
1. Select "No license known" radio button
1. Save current URL
1. Click the _Next_ (right arrow) button
1. Navigate back to the previous URL
1. The clearing status of the file has not changed.

Everything work as expected when clicking on the Submit button though.

**Comment by mcjaeger** [comment]
tested as of now: fixed
