### ISSUE TITLE
Bug about "Clearing decision type"

### ISSUE THREAD

**Issue by binhth1307** [fossology/fossology#1054]
Hi all,

I'm using FOSSology-3.1.0. and i have a problem like #637 . When I click “No license know” and submit, final result is “identified” in "Clearing decision type". Is this a bug?

Thanks and Best Regards,
BinhTH.

**Comment by shaheemazmalmmd** [comment]
Hello BinhTH, 

I think it is not a bug. Because if you click on "No license known" and submit, All the licenses associated with that file gets removed and then the decision type is set to "Identified" for the removed licenses.

**Comment by binhth1307** [comment]
Hi shaheemazmalmmd,

Thank you for your attention. I got it. But I think it's better to still be "no license know", so any viewers can see that this is really "no license know". 

Thanks and Best Regards,
BinhTH

**Comment by mcjaeger** [comment]
appears to be duplicate with https://github.com/fossology/fossology/issues/1054
