### ISSUE TITLE
Delagent refer to tables which don't exist

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1057]
Delagent is referring to 3 tables which does not exist any more:

>  licterm_name, agent_lic_status, agent_lic_meta

Check here: https://github.com/fossology/fossology/blob/master/src/delagent/agent/util.c#L281

**Comment by shaheemazmalmmd** [comment]
We need to re-work on deletion of licenses as well as clearing decisions related to upload-id in delagent.
