### ISSUE TITLE
nomos: changes to exception detection, approval needed

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#1060]
I'm preparing changes to nomos exception detection. The aim is to detect correctly all SPDX exceptions.

Currently most of the exceptions, but not all, are detected like GPL-2.0-with-autoconf-exception. Some exceptions are shown separately f.ex. GPL-2.0, GPL-exception.

My plan, to which I would like to have comments, is to remove GPL-XX-with-YY-exception type of results totally and detect exceptions separately. That clarifies the code and the same exception does not need to be identified with all GPL/LGPL versions.

However, in this approach the reporting tool needs to add WITH keyword to license reports. For example scanner result may be GPL-3.0, libtool-exception and reporting should be GPL-3.0 WITH libtool-exception.

Because this approach differs from the current nomos approach and may need changes also to other part of the tool, I would like to have the acceptance for the approach before digging into details of nomos exception detection.

**Comment by mcjaeger** [comment]
since it was merged, the approval was there.
