### ISSUE TITLE
/usr/bin/ld: cannot find -lfossology

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1062]
In documentation, there is written that for adding new licenses, you need to make some changes in nomos: https://github.com/fossology/fossology/wiki/Nomos#how-to-add-a-new-license-signature

Today, I wanted to try it out (because of a ticket I created some weeks ago). I am using Fossology as docker container for my try. So, these were my steps

1.    `git clone https://github.com/fossology/fossology.git`
2.    Under `fossology/install/docker-compose.yml`, I changed the port from `8081:8081` to `80:8081`
3.    In directory `fossology/install` I entered the command `docker-compose up`
4.    When docker finished setting up images and starting container, I changed into the `fossology-web1` container with `docker exec -u 0 -it db02b434f1e9 /bin/bash`
5.    There, I changed into the directory `/fossology/src/nomos/agent` .
6     Then I simply called `make` without any changes on any file. I got this error message: 

> ...
> ./CHECKSTR
> CHECKSTR: 1142 phrases, 383 contain wild-cards
> gcc -c _precheck.c  -I/usr/include/postgresql -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I../../../src/lib/c -g -O2 -Wall -D_FILE_OFFSET_BITS=64
> gcc -c _autodata.c  -I/usr/include/postgresql -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I../../../src/lib/c -g -O2 -Wall -D_FILE_OFFSET_BITS=64
> gcc nomos.o licenses.o list.o parse.o process.o nomos_regex.o util.o nomos_gap.o nomos_utils.o doctorBuffer_utils.o  _precheck.o _autodata.o -I/usr/include/postgresql -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I../../../src/lib/c -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -Werror -lfossology -L../../../src/lib/c -lglib-2.0  -lpq  -o nomos
> /usr/bin/ld: cannot find -lfossology
> collect2: error: ld returned 1 exit status
> Makefile:32: recipe for target 'nomos' failed
> make: *** [nomos] Error 1
>

**Comment by kohldampfer** [comment]
Found a solution here: https://lists.linuxfoundation.org/pipermail/fossology/2012-July/005775.html

> 1)      About the compile error
> 
> Before compiling nomos, primarily please compile src/lib/c.
> 
> Usually, we 'make' and 'sudo make install' in ../src directory.

Maybe this should be added to the documentation?

**Comment by GMishx** [comment]
Fixed by #1359
