### ISSUE TITLE
How to add license text

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1065]
For testing purposes, I ran the file `parse.c` from the Fossology repository through Fossology on web. After that, I got a list of licenses. Then, I opened `parse.c` and got this (see picture)

![fossology-1](https://user-images.githubusercontent.com/20419801/38737024-2cacdaae-3f2e-11e8-97b5-c22716d37d11.png)

Then I clicked on `unRAR restriction` and got this:

![fossology-2](https://user-images.githubusercontent.com/20419801/38737042-3ffefba0-3f2e-11e8-93f5-4cf7d636ae53.png)

How to change this `License by Nomos.` part? This is not only shown on `unRAR restriction`, but also in a license I added recently in nomos itself (https://github.com/fossology/fossology/wiki/Nomos#how-to-add-a-new-license-signature)?

**Comment by kohldampfer** [comment]
I found this text https://github.com/fossology/fossology/wiki/License-Ref-Table and could answer my question with the link and some PostgreSQL commands. 

But, there is another question: In the web part of Fossology, is there a way to change the text of a license?

**Comment by ag4ums** [comment]
yes, you can do it from "Admin->License Admin->Select License" 
--> now select all or License Family from the drop-down list and submit to find the licenses.
-->now the license you would like to from the edit field.

**Comment by kohldampfer** [comment]
@ag4ums Thank you for your reply! That worked. From my side, this ticket can be closed.
