### ISSUE TITLE
Add a link to the license-ref table

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1069]
I am just reading this wiki page: https://github.com/fossology/fossology/wiki/Monk

The first paragraph mentions the license-ref table

> The monk license scanner is a full text license scanner searching for any license text contained in the license-ref table.

In my opinion, it would be good, if there is a link to the license-ref table. I assume, this is the correct link: https://github.com/fossology/fossology/wiki/License-Ref-Table, i.e.

> The monk license scanner is a full text license scanner searching for any license text contained in the [license-ref table](https://github.com/fossology/fossology/wiki/License-Ref-Table).

**Comment by steffen-weber** [comment]
Good point. Just adjusted it as you suggested.
