### ISSUE TITLE
Binary analysis for open source discovery

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#107]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2451, http://www.fossology.org/issues/2451
Original Date: 2012/06/15

---

None

**Comment by mcjaeger** [comment]
still valid, I think there is a server version of the BAT needed. @armijnhemel, any updates?

**Comment by mcjaeger** [comment]
closing because not pickup near, reopen if needed.
