### ISSUE TITLE
Adding existing license

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1070]
Let's assume this situation: You added a license this way

> Organize -> Licenses -> New License

And let's assume, you have written some short, let's say **shortname_v1**

After that, you go to

> Admin -> License Admin -> Add License

and try to add another license with shortname **shortname_v1**. You get this message

> ERROR: The shortname or license text already exist in the license list. License not added.

But all the text you have written into **Short name**, **Full name**, **License Text** and maybe other inputs are now gone, so I have to add all this stuff again. In my opinion, this is not a good behaviour. After trying to add a license with a shortname which already exists, I would let the input in the text boxes, so a user have the chance to change such stuff quicker.

![fossology-empty-add-license](https://user-images.githubusercontent.com/20419801/38931838-c34eeabc-4314-11e8-95c4-14fbc5eb738a.png)

**Comment by ag4ums** [comment]
hello @kohldampfer, its just a message that the shortname can not be same, you can reopen the license and check your data is lost or not, 

returning the blank page may be a issue,

**Comment by mcjaeger** [comment]
I came across the same but luckily it was there when going back using the browser buttons. just re-upload of the same page would be nicer, admitted.
