### ISSUE TITLE
Binary analysis for open source discovery 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#108]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2457, http://www.fossology.org/issues/2457
Original Date: 2012/06/15

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/07/27 19:19:16 +0000

---

Low priority, but it would be good to unpack and discover the open source packages in binaries in addition to those from the source code.

**Comment by mcjaeger** [comment]
duplicate of #107
