### ISSUE TITLE
Rescan of projects / repos

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1085]
Let's assume, I've done a scan of a project with **Upload** -> **From Version Control System** and now I see all the possible licenses, scanned with Nomos and Monk. 

And now, one of the team members changes a license of a file, e.g. the team member adds a license in a file, where it was missing before.

Is it possible, to rescan the whole project? As far as I can see, I would again first go to **Upload**, then go to **From Version Control System** and type all the stuff again. And after clicking on **Upload**, I would see two directories. The first directory would be the one I checked some time ago, and the second directory would be the one I checked now.

But, wouldn't it be better, that I could click at something like a button *Rescan*, which rescans the project and shows me maybe only the difference to the last time I checked the project. With source code, which comes from a git or svn repo, this would be relatively easy, I think.

**Comment by mcjaeger** [comment]
I understand the idea, but this is not how fossology works. It is not meant to be able to change files which are part of an upload. I am not sure, if that would be better - being able to change any of the files bound to an upload once uploaded. The user can choose to delete an upload. 

fossology stores every file only once - regardless it is appearing in two or more uploads. As such, reuploading does not mean putting more files to the server (except from the packaged archive in case an archive needs to be unpacked). Rather it creates a new database structure connecting an upload with existing files already on server.

As such, rescanning also takes place only at files not scanned before. Note  that if a new version of the scanner is installed as an update, this allows the user to rescan.

Maybe fossology is already there at your use case, but just preserving two uploads in the list in the browse view and you are asking more just for having a button for pulling an update?

**Comment by mcjaeger** [comment]
@kohldampfer I am not sure if my answer clarifies it or not?

**Comment by mcjaeger** [comment]
(please reopen if issue still persists)

**Comment by moonblood2** [comment]
@mcjaeger  So if I want to rescan the git repo I uploaded earlier, The upload process and form submitting need to be done again?

**Comment by moonblood2** [comment]
In fact, I want to know if it is possible to run the scan on the repo periodically like once a day. Is this possible with fossology along?

**Comment by mcjaeger** [comment]
Hello, I do not think that there is a timer functionality in FOSSology. I think all of the way of using fossology are kind of like, "call FOSSology if you would like to do something". My question qould be if it would be actaully so difficult to consider

* `cp2foss`(command line tool for fossology uploading)
* us a crontab entry to call cp2foss. Examples can be found at: `http://archive15.fossology.org/projects/fossology/wiki/Cp2foss`

**Comment by NicolasToussaint** [comment]
@moonblood2 you could also consider calling the Fossology scans from your CVS server, like GitLab for example, via the REST API.

That would allow you to either schedule your scan regularly, or when a new commit - I have projects for which the Fossology scan is configured in GitLab, but needs to be triggered manually (one click to run a new scan on the fresh source code)
