### ISSUE TITLE
Archived reports 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#110]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2469, http://www.fossology.org/issues/2469
Original Date: 2012/06/15

---

Archived reports - simple text file dump, PDF reports, eventually full web archive of all analysis reports. Or else just don't throw away any data. Nomos and buckets already can do this but there is still no guarantee that someone doesn't subvert this process (see ars tables).

**Comment by mcjaeger** [comment]
no pickup since 2012 ...
