### ISSUE TITLE
Fossology Report Generation Failed

### ISSUE THREAD

**Issue by Sampathvijayakumar** [fossology/fossology#1100]
Hi ,
When we are trying to generate reports(SPDX and README) from fossology 3.3.0 release, Scheduler process is getting killed. Anyone facing similar kind of issues ? 
If so please help us to resolve the issue.
**Note** : Running via Docker instance
		 After restarting scheduler is running fine and reports are generated successfully. But at the very firts time we are facing the above mentioned issue.

**Comment by mcjaeger** [comment]
ehem, rare. But maybe it was a pull-in of a character sequence that is not properly escaped at generation of the files and then PHP word does not like it.  

Is the package disclosable where this has happened?

**Comment by Sampathvijayakumar** [comment]
Hello,
We have recently noticed and found that we are able to generate reports SPDX and ReadMeOSS. The issue is when we select the "Whole Folder option" in browse page, When this option  is selected  we are unable to generate the report and the Job is getting failed with below error 

" agent failed, code: 255 "

But When the option is selected as "Marked folders" and particular upload is selected its working fine.

We also noticed that when the Whole folder option is tested for a folder with single file it works and incase if the folder contains a zip file upload in this case it fails. Is this expected or how the whole folder report generation is supposed to work ?

**Comment by GMishx** [comment]
The failure of scheduler might have been an issue solved in #1113
Try to pull a new image and run the same jobs again. Please let us know if you are still facing the issues.

**Comment by GMishx** [comment]
Regarding "Marked folders | Whole folders" button, they are supposed to work irrespective of the files in uploads/folders. It might have been a different issue we need to look into.

**Comment by mcjaeger** [comment]
I think the nasty scheduler issue was solved.
