### ISSUE TITLE
Consider using COPY instead of INSERT INTO

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1103]
Consider using COPY instead of INSERT INTO in `install/db/licenseref.sql`. Since INSERT INTO operation is very slow compared to COPY FROM and thus can save large amount of time.

Sample entries
```
--
+-- Data for Name: license_ref; Type: TABLE DATA; Schema: public; Owner: fossy
+--
+
+COPY public.license_ref (rf_pk, rf_shortname, rf_text, rf_url, rf_add_date, rf_copyleft, "rf_OSIapproved", rf_fullname, "rf_FSFfree", "rf_GPLv2compatible", "rf_GPLv3compatible", rf_notes, "rf_Fedora", marydone, rf_active, rf_text_updatable, rf_md5, rf_detector_type, rf_source, rf_risk, rf_spdx_compatible) FROM stdin;
+210	AGPL-1.0	AFFERO GENERAL PUBLIC LICENSE\nVersion 1, March 2002\n\nCopyright © 2002 Affero Inc.\n510 Third Street - Suite 225, San Francisco, CA 94107, USA	http://www.affero.org/oagpl.html	\N	\N	\N	Affero General Public License 1.0	\N	\N	\N		\N	f	t	f	f24d9d5f3794d72434867b019a1e524c	1	\N	\N	t
+348	LGPL-2.1	GNU LESSER GENERAL PUBLIC LICENSE\n\nVersion 2.1, February 1999	http://www.gnu.org/licenses/old-licenses/lgpl-2.1-standalone.html	\N	\N	\N	GNU Lesser General Public License v2.1 only	\N	\N	\N		\N	f	t	f	3e8a0da7ddcfc529776d35d2110feeac	1	\N	\N	t
+509	BSD-style	According to BSD license, add some modifications		\N	\N	\N	BSD-style	\N	\N	\N		\N	f	t	f	10215fc49d301bf3addf289bcad2b238	1	\N	\N	f
+\.
```

COPY instruction is there in PostgreSQL since 7.1 so there will be no backward compatibility issues.

**Comment by GMishx** [comment]
There are more than 397 INSERT INTO operations in the file.

>  The COPY FROM command operates much faster than a normal INSERT command because the data is read as a single transaction directly to the target table. On the other hand, it is a very strict format, and the entire COPY procedure will fail if just one line is malformed.
Source: https://www.safaribooksonline.com/library/view/practical-postgresql/9781449309770/ch04s03.html

**Comment by mcjaeger** [comment]
since the licenseref.sql is sometimes it could be better to have it inserting, even tough it would presumeably only affect developers?

**Comment by GMishx** [comment]
The current implementation of FOSSology can not support `COPY`.

Closing the issue as of now.
