### ISSUE TITLE
Problem while changing current user's username

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1112]
## Current issue
When I try to change my username by going to Admin->Users->Edit user account and change the value of username, the session is not update. This creates problem while accessing FOSSology pages as the user information is taken from the current session's cookie which does not reflect updated values. It won't be fixed until I log out and login again.

## How to reproduce
1.  Go to Admin->Users->Edit user account.
2.  Change the value of username for the current user (with active session).
3.  Hit Update Account.

    ![image](https://user-images.githubusercontent.com/18077542/40597180-6d57dd36-625d-11e8-941b-c4072a207c01.png)

4.  Goto Upload->(any page which allows selection of agents)
![image](https://user-images.githubusercontent.com/18077542/40597115-f750d12e-625c-11e8-8a15-89180ecf9f8d.png)

## Possible solutions
1.  Update the session cookie while updating username of current user.
2.  Don't allow to change username.

**Comment by shaheemazmalmmd** [comment]
i think it would be better to keep the Username as it is. We will not allow user to do modifications on username ?

**Comment by GMishx** [comment]
As the user should be allowed to change the username in case of any typo, what if we logout the user if they change their own user name? This will also update the session cookie.

**Comment by Aman-Codes** [comment]
@GMishx Can I work on this issue 
https://github.com/fossology/fossology/blob/f6ba00362685916e099a5337e3b195e0b9925cef/src/www/ui/user-edit.php#L106-L114

Adding the below 3 lines after line 111 in the above code might solve the issue
```php
        if($user_pk == $user_pk_to_modify) {
          $_SESSION['User'] = $UserRec['user_name'];
        }
```

**Comment by GMishx** [comment]
Hello @Aman-Codes , sounds like a good solution.

Also, noting @shaheemazmalmmd 's comments, it will be nice to restrict the username editing to just the admin users (`Auth::isAdmin()`).
