### ISSUE TITLE
Support for Distributing Non-Distributing Files

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1114]
Right now, persons use the irrelevant feature for marking files that do not go into the distribution. Intention of this feature is to save work, when analyzing the files. However, for some cases, the files do not go into the distribution, but are relevant for licensing. 

Therefore a new clearing decision type "Non-Functional", "Not-Distributing" would be required.

**Comment by GMishx** [comment]
See https://github.com/fossology/fossology/pull/1560 and https://github.com/fossology/fossology/pull/2142 for sample implementation.
