### ISSUE TITLE
Problem running docker image

### ISSUE THREAD

**Issue by Spiralis** [fossology/fossology#1117]
Hi, 

I was going to try out fossology, but the docker run command fails:

```
λ docker run -p 8081:80 fossology/fossology
Unable to find image 'fossology/fossology:latest' locally
latest: Pulling from fossology/fossology
9f0706ba7422: Pull complete
4c923f78d862: Pull complete
ede481492540: Pull complete
75ea7235c767: Pull complete
c93a142b988f: Pull complete
1f1d1090f169: Pull complete
6a397298f21a: Pull complete
cda0dd5869da: Pull complete
eef8f1690cd6: Pull complete
8c12281d75a7: Pull complete
f1cf5af2c600: Pull complete
Digest: sha256:46d6555df3f377001f7307784d13c0f8a237cfaef857a533c134d21d224c8f7f
Status: Downloaded newer image for fossology/fossology:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint inspiring_davinci (e3e5aafaccf3e83bdc9ce9dca9dc629a96834decc651c9c417d9f0f7ff3aa8aa): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8081:tcp:172.17.0.2:80: input/output error.
```

As far as I can tell, the 8081 port is not in use locally according to `netstat -a`.

Any idea why it fails?

**Comment by maxhbr** [comment]
Please add some more information, e.g. which OS do you use and which version of docker you use.

This looks more like a docker related issue then a fossology related one.

**Comment by Spiralis** [comment]
Ok, I was hoping that this was trivial, so I didn't add much info. 

- I am running Windows 10 Enterprise, v1709
- Docker Community Edition:  ![image](https://user-images.githubusercontent.com/64342/41408576-6fc9f8e6-6fd3-11e8-9efe-6c86de079041.png)
- and Docker is set to use Linux containers.
- I followed the recipe from the fossology readme, and ran `docker run -p 8081:80 fossology/fossology` as instructed, when the error appears.

I am not very good at Docker management, but I understand enough to do basic stuff. 
Is there any additional commands or options I could try that could help me progress?

**Comment by mcjaeger** [comment]
hello, is it maybe related to this issue? https://stackoverflow.com/questions/40668908/running-docker-for-windows-error-when-exposing-ports

**Comment by Spiralis** [comment]
I returned to this task today, and "lo and behold" this time it just worked... Have no idea why, it could be what @mcjaeger mentioned, but I really don't know.

**Comment by Spiralis** [comment]
BTW: Closing as there is no issue anymore, but guessing that if anyone else finds this issue in the future then maybe they will re-open it.
If you (repo owners/mods want to keep it open then you are obviously free to do so).
