### ISSUE TITLE
Easy way to install buttons/links on micro menu to run system utilities/scripts on a file.

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#112]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2481, http://www.fossology.org/issues/2481
Original Date: 2012/06/15

---

Easy way to install buttons/links on micro menu to run system utilities/scripts on a file. For example, .ko files could have an nm link, and a modinfo link. The script may need a way to determine if it should be added to menu or not. For example, nm applies to object files, but modinfo only applies to .ko. The purpose is to process fossology files in real time with system scripts/apps.

**Comment by mcjaeger** [comment]
closing because of missing pickup since 2012
