### ISSUE TITLE
Scheduler keeps failing in docker

### ISSUE THREAD

**Issue by JannikZed** [fossology/fossology#1120]
Our university groups needs to use fossology for a project this semester. Everybody in our class has major troubles using the docker container. For everybody it's the same problem: the scheduler is stopping all the time. Sometimes, after finishing one job but sometimes also without any visible reason. I have one server environment running and set the /etc/init.d/fossology file to debug mode. Logs are not showing anything that seems interesting. The web frontend always shows: 
`Unable to pause job. Connection to the scheduler failed. Is the scheduler running?
socket_connect() failed. Reason: () Connection refused`.  

It's possible to do a `/etc/init.d/fossology start` to restart it again, but on my server side environment this is also no longer working, as the scheduler always breaks down short after it.. 
Could anybody give us some advice on that? Is this the normal behavior?

**Comment by mcjaeger** [comment]
No it is not, and I am not sure if that is connected to the platform you are running on. Coincidentally, it was also reported to the mailing list today. Maybe some thing got into the master now. Thanks for reporting this.

**Comment by JannikZed** [comment]
actually version pinning to `3.3.0` seems to work. The scheduler is not stopping all the time now. It still doesn't feel like it's running as expected, but scheduler process is running.

**Comment by JannikZed** [comment]
I can confirm, that this problem only happend when using the `latest` tag in docker. Maybe you should write something in the docs or on dockerhub, that the `latest` tag might not be the stable one?

**Comment by GMishx** [comment]
Hello @JannikZed,

Just a reminder, can you please confirm the problem still exists on the latest tag after the merge of #1126?

**Comment by JannikZed** [comment]
Hi,
Sorry I forgot to answer.. the problem is no longer existing. Can be closed from my side. Thank you very much.

________________________________

**Comment by GMishx** [comment]
Closed after user confirmation.
