### ISSUE TITLE
ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81

### ISSUE THREAD

**Issue by JannikZed** [fossology/fossology#1121]
When trying to setup a docker environment with dedicated postgres host, I only receive the following error:
```
PHP Warning:  pg_query(): Query failed: ERROR:  column "option_value" of relation "sysconfig" already exists in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
18.6.2018 11:47:46 [2018-06-18 09:47:46] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "option_value" of relation "sysconfig" already exists [] []
18.6.2018 11:47:46 PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: ALTER TABLE "sysconfig" ADD COLUMN "option_value" character varying(40) DEFAULT NULL
18.6.2018 11:47:46 
18.6.2018 11:47:46 ERROR:  column "option_value" of relation "sysconfig" already exists' in /usr/local/share/fossology/lib/php/Db/DbManager.php:141
18.6.2018 11:47:46 Stack trace:
18.6.2018 11:47:46 #0 /usr/local/share/fossology/lib/php/Db/DbManager.php(205): Fossology\Lib\Db\DbManager->checkResult(false, 'ALTER TABLE "sy...')
18.6.2018 11:47:46 #1 /usr/local/share/fossology/lib/php/libschema.php(280): Fossology\Lib\Db\DbManager->queryOnce('ALTER TABLE "sy...')
18.6.2018 11:47:46 #2 /usr/local/share/fossology/lib/php/libschema.php(142): fo_libschema->applyTables()
18.6.2018 11:47:46 #3 /usr/local/lib/fossology/fossinit.php(169): fo_libschema->applySchema('/usr/local/shar...', false, 'fossology', Array)
18.6.2018 11:47:46 #4 {main}
18.6.2018 11:47:46   thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 141
```

I'm using the official fossology docker container with env variables as described. Furthermore, I'm using the official postgres 9 docker container ..

How should I proceed?

**Comment by GMishx** [comment]
There is a problem with the `latest` tag. Can you please try using the `3.3.0` tag, i.e.:
`docker run -p 8081:80 fossology/fossology:3.3.0`

**Comment by JannikZed** [comment]
So the problem here was, that I used the wrong database. This produced this error. It's not a very logic error message but from my side we can close this issue.

**Comment by GMishx** [comment]
Thanks for letting us know. Can you please tell the steps you follow so we can reproduce the issue?

**Comment by JannikZed** [comment]
Setup empty postgres database with db "fossology", admin user "fossology" and PW "fossology". Use the docker image of fossology and use the db connection with environment variables. Use db "postgres" with user "fossology" and pw "fossology"  :D 
So fossology could successfully connect to postgres itself but can't find the DB "fossology". 
The error handling could be improved, but the error itself was created but wrong usage of me..
