### ISSUE TITLE
Error displayed in Apache log  during installation of Fossology

### ISSUE THREAD

**Issue by Lancelof** [fossology/fossology#1123]
Hello ,

Thanks for your time to review the question:-)

I met one issue when I tried to load fossology portal.

Environment :centos 7 X86-64,fossology-3.3.0,Apache/2.4.6 (CentOS)

I have completed the steps listed in portal:https://github.com/fossology/fossology/wiki/Install-from-Source

. Install dependencies

# utils/fo-installdeps
NOTE (OPTIONAL):This program requires the lsb_release command. On Debian based systems this is probably in the lsb-release package, on Fedora/RedHat systems it is probably the redhat-lsb package. For example for centos7:

# yum install redhat-lsb
2. Build FOSSology

$ make
If you want to do a non-standard build, see the file fossology/HACKING

On centos7 the fo-installdeps script does not (yet) install the development tools, including the c++ compiler which is needed for the copyright agent for example (most of the original agents are written in c and php, but the copyright agent for example is written in c++). Thus you might want to install the gnu c++ compiler tools

# yum groupinstall 'Development Tools'
2.5 Install Composer (optional, some versions prior 3.1-RC3)

Composer is a PHP package management tool which is not installable as package on some Linux distros, therefore we need to install it at some versions of the fossology master (the composer installation needed some adjustments over some time):

# make composer_download
The reason for separating download and and install is to easily avoid downloading in some scripted cases, so then:

# make composer_install
3. Install FOSSology

To install (finally) FOSSology

# make install
4. Configure and tune the system

5. Run the postinstall script

# /usr/local/lib/fossology/fo-postinstall

6. Login to FOSSology with the default fossy/fossy user and password and:

create yourself a user with administrative privileges
change the default password for user fossy
7. Test that things are installed correctly

# /usr/local/etc/fossology/mods-enabled/scheduler/agent/fo_scheduler -t
(result displayed null)

Then I execute the last step and open portal:

##########################################
Here is the information during installation:

3)run /usr/local/lib/fossology/fo-postinstall

[root@localhost conf]# /usr/local/lib/fossology/fo-postinstall
Running postinstall for everything ***
Running postinstall for common actions***
Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
Making sure needed dirs exist with right ownership/permissions ***
clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.  We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.  Admin > Dashboard will show you the last time vacuum and analyze have been run.
Running postinstall for web-only actions***
Setting up the FOSSology database ***
NOTE: fossology database already exists, not creating
Checking for plpgsql support ***
NOTE: plpgsql already exists in fossology database, good
update the database and license_ref table ***
PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /usr/local/share/fossology/vendor/monolog/monolog/src/Monolog/Logger.php on line 233
Old release was 3.1.0
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
Update reference licenses
PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /usr/local/share/fossology/vendor/monolog/monolog/src/Monolog/Logger.php on line 233
Database connectivity is good.
Setting up scheduler ***
Setting up the web interface ***
NOTE: Adding user apache to group fossy
FOSSology postinstall complete, but sure to complete the remaining
############################################################

8. Start the fossology scheduler daemon

# /etc/init.d/fossology start

But I get the failed information:

[Wed Jun 20 03:07:59.266136 2018] [auth_digest:notice] [pid 34798] AH01757: generating secret for digest authentication ...
[Wed Jun 20 03:07:59.267120 2018] [lbmethod_heartbeat:notice] [pid 34798] AH02282: No slotmem from mod_heartmonitor
[Wed Jun 20 03:07:59.308484 2018] [mpm_prefork:notice] [pid 34798] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.36 configured -- resuming normal operations
[Wed Jun 20 03:07:59.308527 2018] [core:notice] [pid 34798] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jun 20 03:08:18.884451 2018] [:error] [pid 34804] [client 192.168.217.141:44580] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:18.884496 2018] [:error] [pid 34804] [client 192.168.217.141:44580] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:19.565286 2018] [:error] [pid 34800] [client 192.168.217.141:44582] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:19.565330 2018] [:error] [pid 34800] [client 192.168.217.141:44582] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:19.895017 2018] [:error] [pid 34801] [client 192.168.217.141:44584] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:19.895061 2018] [:error] [pid 34801] [client 192.168.217.141:44584] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:20.103256 2018] [:error] [pid 34802] [client 192.168.217.141:44586] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 03:08:20.103300 2018] [:error] [pid 34802] [client 192.168.217.141:44586] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37

I tested the performance of  html ,php file under the path of http://localhost/repo/test.php or test.html and got normal result.

Please check the attachment for your reference.

I have one concern whether there is any problem in configuration of  postgresql because I just followed the steps from portal .And I am not quite sure what kind of configuration has been done during the default installation by using scripts utils/fo-installdeps.

Can some one provide any hint or suggestion?

Thanks in advance!

![fossology_app](https://user-images.githubusercontent.com/40276088/41643799-cc7f9000-745b-11e8-92a2-b8b040a2a9d3.jpg)
![html](https://user-images.githubusercontent.com/40276088/41643800-ccb49df4-745b-11e8-9d30-b11646106a1d.jpg)
![php](https://user-images.githubusercontent.com/40276088/41643801-ccdc99b2-745b-11e8-8a2d-ffae689c5616.jpg)

**Comment by ag4ums** [comment]
if this works, also please consider creating a pull request with the changes

**Comment by Lancelof** [comment]
Hello @ag4ums ,thanks for your advice,I have tried to change the owner from root to fossology,but it does not work.Could you please take a look at this?Could it be one possibility that the database has no connection with fossology?


Still the issue exists:

[Wed Jun 20 05:43:16.992031 2018] [:error] [pid 46309] [client 192.168.217.141:44690] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 05:43:17.158261 2018] [:error] [pid 46310] [client 192.168.217.141:44692] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Wed Jun 20 05:43:17.158296 2018] [:error] [pid 46310] [client 192.168.217.141:44692] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37



[root@localhost httpd]# cd /var/local/
[root@localhost local]# cd cache
[root@localhost cache]# ll
total 0
drwxr-sr-x. 2 fossy fossy 27 Jun 18 14:23 fossology
[root@localhost local]# cd cache
[root@localhost cache]# ll
total 0
drwxr-sr-x. 2 fossy fossy 27 Jun 18 14:23 fossology

**Comment by Lancelof** [comment]
Hello ,@ag4ums 

May I know the meaning of guidance about "remove the fossology cache folder,
change the owner from www-data to apache in fo-postinstall
and then run fo-postinstall agian"?

Which application belongs to www-data ?

Thanks!

**Comment by mcjaeger** [comment]
actually, I am not happy that multiple persons are looking at the same issue: I think I have answered this issue on the mailing list on Mi 20.06.2018 21:32 CEST

 @Lancelof are you "vito Lion"?

**Comment by Lancelof** [comment]
Hello Michael,



Thanks for your reply.


The account belongs to me.


Best regards.



________________________________
发件人: Michael <notifications@github.com>
发送时间: 2018年6月27日 21:09
收件人: fossology/fossology
抄送: Lancelof; Mention
主题: Re: [fossology/fossology] Error displayed in Apache log during installation of Fossology (#1123)


actually, I am not happy that multiple persons are looking at the same issue: I think I have answered this issue on the mailing list on Mi 20.06.2018 21:32 CEST

@Lancelof<https://github.com/Lancelof> are you "vito Lion"?

―

**Comment by Lancelof** [comment]
Hello ,

The issue has been fixed.

The root cause is due to the  configuration of selinux which forbids files to be transferred to the /tmp .

Please set selinux to be disabled by using command or editing the file under /etc/sysconfig/selinux.

Best regards.
