### ISSUE TITLE
fo_ninka_license_list returns monk licenses

### ISSUE THREAD

**Issue by TE-tatuonagamatu** [fossology/fossology#1129]
**Description**

fo_ninka_license_list does not returns ninka licenses, but monk's one

**Reproduce Steps**

1. load source tree and execute agents
<pre>
# cp2foss --username fossy --password fossy -q all /src
</pre>

2. wait for agents jobs
<pre>
# fossupload_status  --username fossy --password fossy --uploadId N
</pre>

3. get ninka license list
<pre>
# fo_ninka_license_list --username fossy --password fossy -u N
</pre>

**Cause**

fo_ninka_license_list.php is the same with fo_monk_license_list.php

https://github.com/fossology/fossology/blob/master/src/cli/fo_ninka_license_list.php#L139

**Comment by TE-tatuonagamatu** [comment]
<pre>
diff --git a/src/cli/fo_ninka_license_list.php b/src/cli/fo_ninka_license_list.php
index 238298b4b..478b679c8 100755
--- a/src/cli/fo_ninka_license_list.php
+++ b/src/cli/fo_ninka_license_list.php
@@ -111,7 +111,7 @@ if (empty($return_value))
 
 
 /**
- * @brief get monk license list of one specified uploadtree_id
+ * @brief get ninka license list of one specified uploadtree_id
  *
  * @param int $uploadtree_pk - uploadtree id
  * @param int $upload_pk - upload id
@@ -135,8 +135,8 @@ function GetLicenseList($uploadtree_pk, $upload_pk, $showContainer, $excluding,
       $uploadtree_pk = $uploadtreeRec['uploadtree_pk'];
   }
 
-  /* get last monk agent_pk that has data for this upload */
-  $AgentRec = AgentARSList("monk_ars", $upload_pk, 1);
+  /* get last ninka agent_pk that has data for this upload */
+  $AgentRec = AgentARSList("ninka_ars", $upload_pk, 1);
   if ($AgentRec === false)
   {
     echo _("No data available \n");
</pre>

**Comment by GMishx** [comment]
Thank you @TE-tatuonagamatu for point out this issue.

Can you please create a pull request for the same in FOSSology?

**Comment by TE-tatuonagamatu** [comment]
@GMishx Can you assign me push permission for this repository?

**Comment by GMishx** [comment]
@TE-tatuonagamatu You can fork fossology and push your code in the fork. You can then create a pull request for the same.
