### ISSUE TITLE
Add a unit test for Adj2Nest

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#113]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2523, http://www.fossology.org/issues/2523
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
still not there (folders are empty), but doubt if this will be picked up
