### ISSUE TITLE
Also Weird copyright statements should be matched in full

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1133]
If a copyright statement is there like 

`Copyright(c) 2018 Michael C. Jaeger`

then it is matched by FOSSology like

`(c) 2018 Michael C. Jaeger`

because a space is missing before the bracket. users apparently find this confusing. it should be the copyright statement in full.

**Comment by GMishx** [comment]
The space on [line 30 on copyright.conf](https://github.com/fossology/fossology/blob/master/src/copyright/agent/copyright.conf#L30) can be made optional {0,2}.
