### ISSUE TITLE
Ignore files with no info in SPDX reports

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1161]
### Description

When Fossology generates SPDX reports, it includes an entry for each file (at least 8 lines + 2 empty lines).
When dealing with large projects, this leads to huge SPDX reports (>200MB in my case), which are too large to be processed by existing SPDX tools.

However, many files avec no relevent information (no asserted licence, no copyright, no comment, ...) and could be safely excluded from these reports.

For example, I have no use for such an entry:
```
##File

FileName: foo/bar.png
SPDXID: SPDXRef-item462
FileChecksum: SHA1: 0678ec334dd25118f83e099fca0502b9eb9c2863
FileChecksum: MD5: 0cb846a3fed64741f62e67ca6b6ea157
LicenseConcluded: NOASSERTION
LicenseInfoInFile: NOASSERTION
FileCopyrightText: NOASSERTION
```

#### Steps followed and expected result

When generating an SPDX report, the user would be able to select a "Light-SPDX" report, in which  entries for which no meaningful information are not included.

**Comment by NicolasToussaint** [comment]
If ever useful to anyone, I came up with this AWK script to remove all entries that have `NOASSERTION` for both `LicenseConcluded` and `FileCopyrightText` from a SPDX-TV file.

[clean-spdx-files.awk.txt](https://github.com/fossology/fossology/files/2331802/clean-spdx-files.awk.txt)

**Comment by ChristopheRequillart** [comment]
I will implement it.

**Comment by NicolasToussaint** [comment]
I suggest that we turn this feature into an option associated to the upload properties - this way, the export dropbox is not overloaded with new entries.

Similarly to https://github.com/fossology/fossology/issues/645#issuecomment-412525572, we could add an option:
> `6. Do not include file without Concluded License nor Copyright information in the SPDX exports`

![image](https://user-images.githubusercontent.com/22956329/49591222-1d69ec80-f96e-11e8-8479-55c8d1fcf51d.png)

**Comment by silverhook** [comment]
As long as this is an option (preferably off by default), it seems like a good idea.

**Comment by NicolasToussaint** [comment]
Tested the feature, and the main feature is working fine.

However, it requires PHP >5.6, and therefore does not work on current Docker images ; it does work fine with php version 7.0 (tested with @maxhbr's PR https://github.com/fossology/fossology/pull/1327 to bump php version to 7.0).

@ChristopheRequillart , there is however a problem with the added option: 
_Organize_ -> _Uploads_ -> _Edit Properties_ -> _Ignore files with no info in SPDX reports:_

The files are always ignored, whether this option is checked or not.

**Comment by ChristopheRequillart** [comment]
@NicolasToussaint 

Sorry you have a problem. I don’t see it on my installation. Can you verify in database that ignore_files_wo_infos in upload table is at f (false) when "ignore files" is unchecked?

**Comment by NicolasToussaint** [comment]
@ChristopheRequillart 
Just checked, the database (table _upload_, column _ignore_files_wo_infos_) is correctly updated when I un/select the checkbox and click the 'edit' button.
But in both cases the SPDX reports contains only the one file that has a concluded licence.

**Comment by NicolasToussaint** [comment]
@ChristopheRequillart 
Very sorry, all works great after a fresh install !

**Comment by maxhbr** [comment]
> However, it requires PHP >5.6, and therefore does not work on current Docker images ; it does work fine with php version 7.0 (tested with @maxhbr's PR #1327 to bump php version to 7.0).

We currently still support PHP 5.6 (for e.g. Debian Jessie) and thus we can not have features in FOSSology, which only support >5.6 until we officially have done the jump to only support PHP >=7.0.
