### ISSUE TITLE
Refactor info page with twig template

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1165]
### Description

remove the old code and refactor the info page with twig template

**Comment by GMishx** [comment]
Also, consider changing the check-box here to radio buttons:


Attribute | Info
-- | --
| Source / binary integration notes | [ ] no critical files found, source code and binaries can be used as is |
|| [ ] critical files found, source code needs to be adapted and binaries possibly re-built |
| Dependency notes | [ ] no dependencies found, neither in source code nor in binaries |
|| [ ] dependencies found in source code (see obligations) |
|| [ ] dependencies found in binaries (see obligations) |
| Export restrictions by copyright owner | [ ] no export restrictions found |
|| [ ] export restrictions found (see obligations) |
| Restrictions for use (e.g. not for Nuclear Power) by copyright owner | [ ] no restrictions for use found |
|| [ ] restrictions for use found (see obligations) |
