### ISSUE TITLE
Scheduler fails on boot if database is not available

### ISSUE THREAD

**Issue by swinslow** [fossology/fossology#1171]
### Description

When using the Debian package version of Fossology 3.3.0, the Fossology scheduler tries to run on system boot. However, it fails because the PostgreSQL database is also booting but is not yet available.

This may occur in other situations that use the Fossology init script, beyond the Debian package.

#### How to reproduce

1. Install Fossology using the Debian package for 3.3.0
2. Reboot the system
3. The Fossology scheduler will try to run and will fail, leaving the following message in `/var/log/fossology/fossology.log`:

```
2018-08-19 11:01:07 scheduler [705] :: FATAL database.c.669: Unable to connect to the database: "ERROR: Unable to connect to the database
2018-08-19 11:01:07 scheduler [705] ::    Connection string: 'dbname=************** host=************** user=************** password=**************'
2018-08-19 11:01:07 scheduler [705] ::    Connection status: '1'
2018-08-19 11:01:07 scheduler [705] ::   Check: /usr/local/etc/fossology/Db.conf
2018-08-19 11:01:07 scheduler [705] :: "
2018-08-19 11:01:07 scheduler [705] :: FATAL errno is: Success
```

### Versions

* Last commit id on master: 9fb9c7 (according to header within Fossology interface)
* Operating System (lsb_release -a):
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```

### Fossology logs

See snippet pasted above

### Fix

One fix appears to be as simple as telling the init script to wait until postgresql is available. I'm going to submit this as a PR.

I think this would fix it for situations like the Debian package (where the scheduler and PostgreSQL are on the same system). However, this solution may not work for people who are using the init script in a context where the database is remote.

**Comment by maxhbr** [comment]
The first fix to this problem was proposed by @swinslow in #1172: 
```diff
diff --git a/src/scheduler/agent/defconf/init.d/fossology.in b/src/scheduler/agent/defconf/init.d/fossology.in
index bfef6e29f..f6fa018a6 100644
--- a/src/scheduler/agent/defconf/init.d/fossology.in
+++ b/src/scheduler/agent/defconf/init.d/fossology.in
@@ -8,8 +8,8 @@
 #
 ### BEGIN INIT INFO
 # Provides:          {$PROJECT}
-# Required-Start:    $network $local_fs $remote_fs $syslog $named
-# Required-Stop:     $network $local_fs $remote_fs $syslog $named
+# Required-Start:    $network $local_fs $remote_fs $syslog $named postgresql
+# Required-Stop:     $network $local_fs $remote_fs $syslog $named postgresql
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: FOSSology scheduler daemon
```

But since this breaks the init script on a system which does not control the database, this was reverted. 

@swinslow suggested in https://github.com/fossology/fossology/pull/1172#issuecomment-414131419:
> Perhaps there should be separate init scripts for the packaged install, vs. for people who are experienced and familiar enough with Fossology setup to be able to configure a PostgreSQL database on a separate instance?

**Comment by mcjaeger** [comment]
good catch, sometimes it happened on our instances too.

**Comment by maxhbr** [comment]
possible solutions:
- provide two different `/etc/init.d/fossology` scripts or
- provide a patch to add the suggested changes above and apply it to instances, where fossology has the control over the database (e.g. the debian packages) or
- apply the patch above and expect manual changes by the users, where fossology is started via init.d but the database is not under control of it

**Comment by swinslow** [comment]
Thanks @maxhbr, agreed on the options here. I don't have a particular preference either way, and I'm not familiar enough with the packaging process to add meaningful input here. 

I think that as long as Fossology works "out of the box" for the users who want to use e.g. the Debian packages, then any of these are reasonable solutions.
