### ISSUE TITLE
libboost-* are missing runtime dependencies

### ISSUE THREAD

**Issue by robertvolkmann** [fossology/fossology#1175]
Fossology needs libboost-regex and libboost-program-options as runtime dependencies. But in the debian world these runtime packages have their version information in their package name.

| Code name | libboost-* version | default version of libboost-all-dev |
| --- | --- | --- |
| Trusty | 1.54.0, 1.55.0 | 1.54.0 |
| Jessie | 1.55.0 | 1.55.0 |
| Xenial | 1.58.0 | 1.58.0 |
| Stretch | 1.62.0 | 1.62.0 |
| Bionic | 1.62.0, 1.65.1 | 1.65.1 |
| Buster | 1.62.0, 1.67.0 | 1.62.0 |

**Comment by GMishx** [comment]
So we need to add `libboost-program-options-dev` and `libboost-regex-dev` to the Debian based runtime dependencies.

Is it working in RedHat based systems?

**Comment by GMishx** [comment]
The following code need to be inserted in the runtime dependency?
```
case "$DISTRO" in
      Debian|Ubuntu|LinuxMint)
         case "$CODENAME" in
            trusty)
               apt-get "$YesOpt" install libboost-program-options1.54.0 libboost-regex1.54.0;;
            jessie)
               apt-get "$YesOpt" install libboost-program-options1.55.0 libboost-regex1.55.0;;
            xenial)
               apt-get "$YesOpt" install libboost-program-options1.58.0 libboost-regex1.58.0;;
            stretch|buster|sid)
               apt-get "$YesOpt" install libboost-program-options1.62.0 libboost-regex1.62.0;;
         esac
         ;;
      Fedora|RedHatEnterprise*|CentOS)
         yum "$YesOpt" install boost;;
esac
```
