### ISSUE TITLE
Is there a way to Migrate a Single Project/Upload from one instance/Server to another ?

### ISSUE THREAD

**Issue by DineshDevarajan** [fossology/fossology#1185]
### Description

Say I have a Project in one of the Fossology instance and i need to migrate it to another instance along with all the clearing decisions made. What is the procedure to migrate or create a replica of it  from one instance to another.

**Comment by GMishx** [comment]
You can do that with an SPDX report.
1. Once you have cleared the upload on one instance, you can generate an SPDX RDF report.
1. Upload the same package on new instance.
1. Goto "Upload -> Import Report" and upload the generated report for the intended package.

It will import all your clearings and main licenses.

Please refer to PR #882 for more info.

**Comment by GMishx** [comment]
Hello @DineshDevarajan, do you have progress with the issue?

**Comment by DineshDevarajan** [comment]
Yes it is still failing with agent timeout.

**Comment by mcjaeger** [comment]
What would be the upload actually that you are doing. I think there is size issues with the uploaded SPDX RDF file. We have seen that an RDF for the gcc package is about 140MB and that is almost improssible to process today with FOSSology's facilities of RDF import.

**Comment by DineshDevarajan** [comment]
@mcjaeger  No it didnt work for me. I am seeing timeout issues with large projects. It works for small projects.

**Comment by mcjaeger** [comment]
Maybe you could share how large is large? how large is the upload (no. of files) and how large is the resulting SPDX file?

**Comment by mcjaeger** [comment]
please reopen, if you would like to follow up on the issue. For me it sounds like adjusting php maximum memory sounds like an option.
