### ISSUE TITLE
Package dependecy missing (mbstring) for source install on u16.04LTS

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1186]
Package dependecy missing `php-mbstring` for source install on u16.04LTS

#### How to reproduce

when trying to install composed deps for source install, the composer step breaks because mbstring package is missing.

#### Screenshots

shell:
```
sudo utils/fo-installdeps -e -y
...
sudo make install
...
    - easyrdf/easyrdf 0.9.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - easyrdf/easyrdf 0.9.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for easyrdf/easyrdf 0.9.* -> satisfiable by easyrdf/easyrdf[0.9.0, 0.9.1].
```

### Versions

* Last commit id on master:49ffd7397c827acb27b073850fba708e6700c28c
* Operating System (lsb_release -a): Xenial Ubuntu 16.04.5 LTS

### Any other info

n.a.

**Comment by GMishx** [comment]
Is this related to #1150?

**Comment by robertvolkmann** [comment]
No, it is not related to #1150. On Trusty and Jessie PHP5 is compiled with mbstring support, but with the move to PHP7 it is a [separate package](https://packages.debian.org/stretch/php-mbstring).
