### ISSUE TITLE
Add functional tests for BucketsDiff

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#120]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2577, http://www.fossology.org/issues/2577
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
