### ISSUE TITLE
Add unit tests for NomosDiff

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#121]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2583, http://www.fossology.org/issues/2583
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
