### ISSUE TITLE
Change Nomos’ PHP-2.0.2 license (name) to PHP-2.02

### ISSUE THREAD

**Issue by silverhook** [fossology/fossology#1213]
### Description

Nomos lists _PHP-2.02_ license as “PHP-2.0.2”, which is wrong.
Monk lists _PHP-2.02_ correctly though.

#### How to reproduce

Scan a file that includes _PHP-2.02_ license text – e.g. its actual upstream: http://www.php.net/license/2_02.txt

What happens is that:

- Monk 100% matches it with: PHP-2.02
- Nomos matches it with: PHP-2.0.2

What should happen:

- both match it with PHP-2.02

### Versions

* Last commit id on master:  Version: [3.2.0], Branch: [master], Commit: [#c83160] 2018/02/08 04:39 EST built @ 2018/02/12 17:00 EST 
* Operating System (lsb_release -a): 
  ```
  No LSB modules are available.
  Distributor ID: Debian
  Description:    Debian GNU/Linux 8.11 (jessie)
  Release:        8.11
  Codename:       jessie
  ```

**Comment by mcjaeger** [comment]
uhh, good catch.

**Comment by muarachmann** [comment]
@mcjaeger i would love to work on this can it be assigned to me

**Comment by silverhook** [comment]
@mcjaeger, on a meta-discussion level, is there already any work on standardising the license names (and data) with SPDX? Also, how technical would that be? I would be interested in tackling it, but I’d rather not touch any PHP and C(++).
