### ISSUE TITLE
Missing authentication regarding REST API

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1219]
### Description and How to Reproduce

I tried to use the REST API from the example written here https://github.com/fossology/fossology/wiki/REST-API#fossology-restful-interface, i.e. 

```
wget -O - --post-file b http://some.fossology.host:8081/repo/?mod=agent_nomos_once
```

But there was no new job and the output of my request gave me

> Module unavailable or your login session timed out.

I assumed, that this was because of missing authentication. But in the whole REST API wiki page (https://github.com/fossology/fossology/wiki/REST-API), there is no example, how authentication works with REST API.

I saw the comment https://github.com/fossology/fossology/issues/592#issuecomment-163885186 where someone has written down, how to do it, but why not put that part into the documentation?

### Versions

From the installed Fossology software: 
>  Version: [3.3.0], Branch: [master], Commit: [#e84fd3] 2018/09/24 09:58 UTC built @ 2018/10/03 11:36 UTC 

### Logs

I don't think, any logs are needed here.

**Comment by GMishx** [comment]
We have two PRs going on to implement REST in FOSSology. You can check them here:
1. Version 1: #1198 
2. Version 2: #1214
