### ISSUE TITLE
Add functional tests for NomosDiff

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#122]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2589, http://www.fossology.org/issues/2589
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
