### ISSUE TITLE
Missing fossology.log in docker container

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1220]
### Description

When calling `sudo find / -name "fossology.log" -type f` in the docker container `fossology_scheduler_1` and `fossology_web_1`, there is not result. The file seems to be missing.

#### How to reproduce

I started several jobs, but all failed. Then I wanted to see, what was written down in `fossology.log` file, but could not find this file. I tried it with this command as root: `find / -name "fossology.log" -type f`

### Versions

*  Version: [3.3.0], Branch: [master], Commit: [#e84fd3] 2018/09/24 09:58 UTC built @ 2018/10/04 13:14 UTC

**Comment by kohldampfer** [comment]
I don't know if this is relevant, but I also tried with a working job.

I started a new job an used `https://github.com/fossology/fossology` as source code. When the job finished, I tried again to find the file `fossology.log`.

**Comment by GMishx** [comment]
The fossology logs are redirected to `stdout` here:

https://github.com/fossology/fossology/blob/master/docker-entrypoint.sh#L63

Therefore, the `fossology.log` file is not created.

**Comment by GMishx** [comment]
Ping @robertvolkmann

**Comment by robertvolkmann** [comment]
Yes, the logs are redirected to `stdout`. @kohldampfer please try the following commands to see the content of `stdout`:
`$ docker-compose logs scheduler`
`$ docker-compose logs web`

**Comment by mcjaeger** [comment]
@kohldampfer can we consider closing it or are you advocating having the logfile written inside the docker container or in a shared directory?

**Comment by kohldampfer** [comment]
@mcjaeger The output in the docker logs is the same like in fossology.log? If yes, you can close this issue.

**Comment by bharathkumar522** [comment]
Hi @robertvolkmann,
           I am running fossology without using docker, please let me know where can I find the log file

**Comment by GMishx** [comment]
@bharathkumar522 , the fossology.log can be found under `/var/log/fossology/fossology.log`. Also, you may find some logs related to fossology with Apache under `/var/log/apache/error.log` along with the per job logs under **Geeky Scan Details** (click on job number in recent job view).

**Comment by bharathkumar522** [comment]
thanks @GMishx ...
