### ISSUE TITLE
Using select 2 library for all large drop-down menus in FOSSology

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1223]
### Description

Most of the drop-downs in FOSSology grow large which makes it difficult to find required options in them.
Especially in the case of Folders drop-down, the indentation makes it not searchable in Firefox.

#### Steps followed and expected result

It will be better to utilize the search functionality provided by the [select2](https://github.com/select2/select2) library.

##### Not so friendly in Firefox
![old](https://user-images.githubusercontent.com/18077542/46937634-693f9a00-d07f-11e8-8bc6-e4c305158ec2.png)

##### Proposed UI
![new](https://user-images.githubusercontent.com/18077542/46937632-693f9a00-d07f-11e8-9ebf-83607ff1ce7b.png)

**Comment by mcjaeger** [comment]
note that select2 in fossology is actually use of the  minified version of 4.0.5 which is plain MIT (opposed to that the 4.0.5 release contains apache-2.0 test classes)
