### ISSUE TITLE
Empty Dashboard site

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#1229]
### Description

Dashboard shows empty page.

#### How to reproduce

1. `git clone https://github.com/fossology/fossology`
2. `cd fossology`
3. `docker-compose up -d`
4. When `docker-compose` finished, visit Fossology and login with `fossy` / `fossy`
5. Visit the Fossology site `/repo/?mod=dashboard`

### Versions

* Last commit id on master: `Version: [3.4.0], Branch: [master], Commit: [#1aed21] 2018/10/18 08:23 UTC built @ 2018/10/22 19:37 UTC`

* Operating System (lsb_release -a):

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

**Comment by kohldampfer** [comment]
When typing `docker logs fossology_web_1`, I saw these messages:

> [Mon Oct 22 20:05:37.502834 2018] [:error] [pid 133] [client XX.XX.XX.XX:YYYYY] PHP Warning:  pg_prepare(): Query failed: ERROR:  column &quot;procpid&quot; does not exist\nLINE 1: SELECT procpid processid, current_query, query_start, now()-...\n               ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 62
> 
> [Mon Oct 22 20:05:37.503221 2018] [:error] [pid 133] [client XX.XX.XX.XX:YYYYY] [2018-10-22 20:05:37] default.CRITICAL: ERROR:  column "procpid" does not exist LINE 1: SELECT procpid processid, current_query, query_start, now()-...                ^ [] []
> 
> [Mon Oct 22 20:05:37.503451 2018] [:error] [pid 133] [client XX.XX.XX.XX:YYYYY] PHP Fatal error:  Uncaught exception 'Fossology\\Lib\\Exception' with message 'error executing: SELECT procpid processid, current_query, query_start, now()-query_start AS elapsed FROM pg_stat_activity WHERE current_query != '<IDLE>' AND datname = 'fossology' ORDER BY procpid -- dashboard::DatabaseQueriesqueryFor_current_query_orderBy_procpid\n\nERROR:  column "procpid" does not exist\nLINE 1: SELECT procpid processid, current_query, query_start, now()-...\n               ^' in /usr/local/share/fossology/lib/php/Db/DbManager.php:140\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(51): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'SELECT procpid ...')\n#1 /usr/local/share/fossology/www/ui/admin-dashboard.php(235): Fossology\\Lib\\Db\\ModernDbManager->prepare('dashboard::Data...', 'SELECT procpid ...')\n#2 /usr/local/share/fossology/www/ui/admin-dashboard.php(374): dashboard->DatabaseQueries()\n#3 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(392): dashboard->Output()\n#4 /usr/local/share/fossology/lib/ph in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 140
>
> 37.201.4.181 - - [22/Oct/2018:20:05:37 +0000] "GET /repo/?mod=dashboard HTTP/1.1" 500 4744 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**Comment by GMishx** [comment]
It appears an issue with Postgres to me. Maybe need to fix the version of Postgres in the composer yaml file.

Currently I am no able to build docker images on my system. Will update once tested.
