### ISSUE TITLE
Source Install for 3.4.0rc2 misses dependency on Debian Jessie / Trusty 

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1239]
### Description

When installting from source using the instruction from the github wiki, the installation of the json cpp lib is required manually at make / make install:

```
sudo apt-get install libjsoncpp0
```

#### How to reproduce

Just execute make or make install (do not remeber exactly) on a machine where this lib has not been installed.

Installed two times, first on ubuntu trusty and second on debian 8 jessie.

**Comment by GMishx** [comment]
User is supposed to run `sudo ./utils/fo-installdeps -ye` before running `make` / `make install`.

It is already there:
https://github.com/fossology/fossology/wiki/Install-from-Source#1-install-dependencies

**Comment by mcjaeger** [comment]
I am not quite sure about this, because "user" is executing since ages this command listed here:

https://github.com/fossology/fossology/wiki/Install-from-Source

and here much more in the past:

http://archive15.fossology.org/projects/fossology/wiki/SysConfigSrc

if you change this just out of blue it is just annoying to find out how to get this right.

I am not sure to ask the user to install "everything" to get the "make / make install" combo running.
