### ISSUE TITLE
Add functional tests for UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#124]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2613, http://www.fossology.org/issues/2613
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
