### ISSUE TITLE
Automatically ignore SCM data when scaning

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1251]
### Description

When scanning an upload, I need to automatically ignore SCM specific data (Git, SVN, ... files).
Issue #703 hints at this, but also at ignoring other parts of the upload, so I would rather create a new issue concerning the SCM data specifically.

Not sure about the exact list of SCM solutions to be integrated (at least Git, SVN and TFS)

#### Steps followed and expected result

When uploading a new package for scanning (any type, really: from file, server, URL, SCM, TFS), a new option would enable the feature. See image below, where a new `4. Ignore SCM files` has been inserted.
When selected, the scan automatically discards all files related to known SCM solutions.

#### Screenshots

![image](https://user-images.githubusercontent.com/22956329/49231919-3cf39900-f3f3-11e8-8be5-bf9b5431d9e9.png)

**Comment by ChristopheRequillart** [comment]
Thanks, I will work on it.

**Comment by mcjaeger** [comment]
I think it is important not to limit it to SCM, but have a general mechanism where the user could enter / parameterize a black list of files or folders that could be switched on / off.

I am not sure how to do that though. because there could be different solutions for "discarding" files:
* ommit the files at ununpack and have them entirely out of the file tree
* it could be marked "green" at deciding agent?
* or maybe marked "grey"?

**Comment by NicolasToussaint** [comment]
I was thinking that these would be two separate features.

Since the more general "ignore" feature was discussed in https://github.com/fossology/fossology/issues/703 , I created this new issue to separate the discussion on purpose :)

To me, the SCM specific files need to be completely hidden away from the user (like *ommit the files at ununpack*). It will never contain relevant information, and the contents can be easily identified without further configuration from the user (a "tick box" is enough).

For the other issue, then, further discussion would be needed to decide 1/ how to configure and 2/ how to show the 'discarded' files.

@mcjaeger, would you rather treat the two issues as one ?

**Comment by mcjaeger** [comment]
my opinion is that the PR is Ok for the first as it is.

**Comment by NicolasToussaint** [comment]
Great work, thanks @ChristopheRequillart and everyone !
