### ISSUE TITLE
Rest end point serving upload id for Hash value

### ISSUE THREAD

**Issue by arunazhakesan** [fossology/fossology#1255]
### Description

Fossology should be able to return search results based on the hash value of the uploaded package.

#### Steps followed and expected result

- User should be able to provide a hash value as search string
- Fossology should return list of uploads/upload with the matching hash
- User should be able to review the scanned results and regenerate the reports, SPDX rdf file and CLI files.

**Comment by GMishx** [comment]
Hello @arunazhakesan, does PR #1748 solves your purpose?

**Comment by arunazhakesan** [comment]
> Hello @arunazhakesan, does PR #1748 solves your purpose?

As far as I understood PR #1748, I guess it solves the purpose.

**Comment by GMishx** [comment]
Thank you @arunazhakesan , I'll tag the issue in the PR then.
