### ISSUE TITLE
Add functional tests for Tagging

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#126]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2625, http://www.fossology.org/issues/2625
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
