### ISSUE TITLE
GSOC 2019: Feedback for Application

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1266]
GSOC 2019! - let's apply for it.

Notice! moved to https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals

## General

- [x] Persons who would like to volunteer as mentors
- [x] Organisational input for the application
- [x] Make the org application
- [x] Topic Proposals
- [ ] Students (later)

Please see the 2018 info page: https://wiki.fossology.org/gsoc-2018

## Mentors

Who would be volunteering as mentor for this effort? (at best fill in here)

* @ag4ums 
* @shaheemazmalmmd 
* @mcjaeger 
* @amanjain97 
* @GMishx 

## Org Input

* Process application on Google.
* see timeline here: https://developers.google.com/open-source/gsoc/timeline

## Topics

Just initial thoughts - please feel free to add:

* License compatibility agent: checks the occurrence of incompatible licenses in an upload. teh result could be displayed on Web pages or put in the Unified Report.
* Connect with clearly Defined REST API to make a Clearly defined agent to fetch curated license data for uploads based on the SHA1 hashes. Or maybe add a UI to browser / query clearly defined rest API to pick a curated dataset for having it in FOSSology.
* Search in FOSSology needs to enhanced: currently it is not nice to search for a file / folder / upload or "all packages which contain a license X."
* Extend the REST API: align it with Richardson model level 3
* Continuation of Atarashi: Topics for continuation of fossology/atarashi
* Managing jobs, dashboard for what Jobs are running on the server and how to control the load better
* Software heritage connection: There is a REST API there and a simple agent could just connect with this REST API to check if the file is already in the repo of software heriateg.
* Own snippet scanner based public data in integrated to fossology: create the snippet algorithm and fossology integration, not focussing on the repository data itself.

**Comment by OliverFendt** [comment]
I like the compatibility agent, the connection to Clearly Defined and Software Heritage. Further I want to see the autoconclusion enhanced via voting or other algorthims in order to minimize the human effort.

**Comment by silverhook** [comment]
I may be able to co-mentor re the compatibility agent – at least from the legal PoV.

OTOH, apart from Software Heritage and Clearly Defined, there is also the OSADL compatibility list, and OSLiC.

**Comment by amanjain97** [comment]
Thank you @mcjaeger for considering me. 
Here are some improvements that can be done for Atarashi.
- Integrate Atarashi to Fossology. 
  - Their is already an existing project to connect ClearlyDefined API to Fossology. So, I don't think there is need to create a new project for Atarashi and Clearly Defined.
- New suggestions for improving the algorithm is welcome. (I will also suggest)

**Comment by ChandranshuKumar** [comment]
Hello everyone,
I would like to work on this project as a student in GSoC 2019 projects.
So please let me know on how to get started.

**Comment by shradha-khapra** [comment]
Hey everyone,
I am interested in working for the project under GSoC'19. Can anyone please help me to get started with it ?

**Comment by Victbery** [comment]
Hello Sir / MA, I am interested in working on your project during GSoC 2019. I need a start guidelines. Thanks

**Comment by mcjaeger** [comment]
Hello @ChandranshuKumar, @shradha-khapra, @Victbery,

thank you so much for your interest in this project. How about having a call at 10:30 am CET? If that does not work for you, please indicate another time on Thursday or Friday?

Join using the Circuit web client (ideally Chrome) or mobile app:
https://circuit.siemens.com/guest?token=55e3cb5c-26e6-4b02-bc1b-fca5d61aa3d2

**Comment by mcjaeger** [comment]
an other than that:
1. you could test fossology using docker or vagrant
2. please see the basic workflow: https://www.fossology.org/get-started/basic-workflow/
3. some introductory information here: https://github.com/fossology/fossology/wiki/New-at-FOSSology%2C-You-Could-...
4. Guess you have seen the current of proposed topics? https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals

**Comment by shradha-khapra** [comment]
Hey,
I am fine with 10:30 am tomorrow.
Regards
Shradha Khapra

**Comment by Victbery** [comment]
Please the communication mean - circuit is not active or the trial is not
working for my country..
Victery or victor Ekeghe Mba

**Comment by hastagAB** [comment]
Hey Everyone!
Some of the project Topics seems interesting to me. I would like to work on the project under GSoC 2019. Is there any community platform where we can discuss the details?

**Comment by anantjain6** [comment]
Hey everyone,
I am interested in working for the project under GSoC'19. Can anyone please tell the detailed requirements?

**Comment by mcjaeger** [comment]
Hi, this sounds great, I have updated:
https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals
-> first start should be there

**Comment by mcjaeger** [comment]
also you could check:
* https://www.fossology.org/get-started/basic-workflow/
* https://www.fossology.org/get-started/basic-training/

**Comment by sandipbhuyan** [comment]
Hello I am sandip bhuyan. I like to contribute to fossology this year. I was a GSoC 2018 intern for FOSSi Foundation you can find my work [here](https://www.sandipbhuyan.com/blog-content/13). I need some stater issue to work on to know the codebase

**Comment by sandipbhuyan** [comment]
I want to join the slack workspace to discuss about ideas can anyone add me in the group

**Comment by Gauthams1** [comment]
Hey Everyone!
Few of the Topics seems interesting to me. I would like to work on the project. Is there any way you can add me to the group

**Comment by Gauthams1** [comment]
Hey!
I would like to work on the project under GSoC 2019. I have interest in a few of mentioned project and I would really like to contribute.can you please add me to the group so we can discuss.

**Comment by mcjaeger** [comment]
@sandipbhuyan hello, if you would like to join the slack (fossology.slack.com) we need your e-mails that you would prefer for invitation

to all: all except Gauthams1 should have recieved an email from one of the mentors. please let us know if you did not receive an e-mail.

@Gauthams1 have you checked the resources listed already? if you talk about the group, is it slack? what is your preferred invitation email?

**Comment by GMishx** [comment]
> Hey Everyone!
> Some of the project Topics seems interesting to me. I would like to work on the project under GSoC 2019. Is there any community platform where we can discuss the details?

Hello @hastagAB, we really appreciate your interest towards FOSSology. Can you please share your email address with us for future communications?

**Comment by mcjaeger** [comment]
hello to all, you could consider to have a look at the wiki

https://github.com/fossology/fossology
-> "Contributing to FOSSology"

And then pick a small issue for exercising the contribution workflow with a pull request. You could pick one issue that you like or check:

https://github.com/fossology/fossology/issues?q=is%3Aopen+is%3Aissue+label%3A%22ready+for+newbies%22

**Comment by Victbery** [comment]
My email to receive slack invitation : victorekesnr@gmail.com

On Mar 15, 2019 9:45 AM, "Michael" <notifications@github.com> wrote:

hello to all, you could consider to have a look at the wiki

https://github.com/fossology/fossology
-> "Contributing to FOSSology"

And then pick a small issue for exercising the contribution workflow with a
pull request. You could pick one issue that you like or check:

https://github.com/fossology/fossology/issues?q=is%3Aopen+
is%3Aissue+label%3A%22ready+for+newbies%22

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossology/fossology/issues/1266#issuecomment-473204256>,
or mute the thread

**Comment by sandipbhuyan** [comment]
Thanks My mail is sandipbhuyan@gmail.com

**Comment by Gauthams1** [comment]
@mcjaeger yes I have checked resources list, [here ](mailto:gs@es.iitr.ac.in) is my Email id and yes I was referring to slack group. Thank you

**Comment by hastagAB** [comment]
Hey There!
Email : classicayush@gmail.com is my primary email.
Thanks!

**Comment by muarachmann** [comment]
@mcjaeger sorry i missed this don't know how but i would very much like to work on the Extend the REST API: align it with Richardson model level 3

**Comment by muarachmann** [comment]
Here is my email for the slack group muarachmann@gmail.com

**Comment by vivekaindia** [comment]
Hey Everyone,

I have seen the project proposal and gone through the link as mentioned.
The project is fantastic, further more i would like to work on the project on GSOC 2019.
I would be great experience to work on these modules.

Please help me more to understand the project and get started with it.

**Comment by gmeinwik** [comment]
Would it be possible to add the following to the list?

1. if a component is uploaded to Fossology for scanning via REST API to make it configurable how this upload is to be  
- use/not use auto-conclude
- use/not use existing bulk phrase recognition
- reuse results from an earlier upload (if existing upload id is known and provided)
2. if a clearing result is to be downloaded via REST API
- access to the clearing finished flag (clearing status information)
- trigger creation of reports like (OSS Readme and SPDX in dedicated flavour)
- trigger of creating a component clearing information package (source, OSS Readme, SPDX, configurable?)

**Comment by mcjaeger** [comment]
@vivekaindia thanks for your interest. I the page https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals and this thread contain a lot of good information. I think also that you might want to try to solve and easy issue and see if you can make a pull request from it - see the issue tag `ready for newbies`

**Comment by GMishx** [comment]
Hello everyone,

I hope all of you have received email from either one of the mentors. If you have received the email, kindly reply to the same for our confirmation from your side. If you have not received any email from us, kindly check your spams as well.

If you still can not find a email from us, please drop me an email at mishra.gaurav@siemens.com.

Happy coding.

**Comment by GMishx** [comment]
Thank you @gmeinwik for your suggestions. Most of the points pointed out by you have already been implemented by https://github.com/fossology/fossology/pull/1214. Kindly verify once and keep your suggestions coming.

**Comment by Victbery** [comment]
Please can the slack invitation link, be resend to me -
victorekesnr@gmail.com, I wasn't received properly.
Thanks
Victor Ekeghe Mba

**Comment by Shreyansh0001** [comment]
Hello Everyone,
All the projects of Fossology are interesting and I would really like to work on these projects under GSOC. After going through the descriptions I have some queries regarding the project. Please help me through it.

**Comment by Akash-Sareen** [comment]
Hello Everyone,
I would like to work on the project under GSoC 2019 as its quite exciting. The projects are interesting and I would really like to contribute to the project.

**Comment by sjha2048** [comment]
Hi There,
The ideas are quite exciting and I would like to work on the project under GSoC 2019.
can I get the invitation link to the slack channel, I am sharing my email below.

sjha200000@gmail.com

**Comment by Kaushl2208** [comment]
Hi there!! 
   I found the ideas very interesting. I would love to work on the projects under GSoC 2019. Is there any community platform where I can keep myself updated. I share my email id below 

kaushlendrapratap.9837@gmail.com

**Comment by mcjaeger** [comment]
hello, sent to you invitation to our slack channel (fossology.slack.com) you ask quick questions there.

@all please contact us in case you have questions about your application or if we should discuss your ideas ...

**Comment by mcjaeger** [comment]
we can close it I guess ...
