### ISSUE TITLE
Add functional tests/automation for migration testing

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#127]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2637, http://www.fossology.org/issues/2637
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
