### ISSUE TITLE
Apache based authentication delegation

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1273]
We are currently working on a solution enabling us to authenticate into Fossology, via an authentication framework configured in the Apache web server.

### Description
The idea is to rely on an external service to authenticate users within Fossology.
An authentication module in Apache handles the authentication process against an external service, and forwards all necessary information in HTTP header, to be used by Fossology.

### Steps followed and expected result
1. When accessing a Fossology page, the user is redirected to an authentication page  (anything supported by an Apache module: OIDC, LDAP, etc.)
2. Apache injects the authentication information in new HTTP headers (login, name, email address, etc.)
3. Fossology reads this info through environment variables and authenticates the user.
4. If the user account does not exist, it is automatically created with a null password in database

**Comment by NicolasToussaint** [comment]
We have coded the feature, and are using it on two internal production servers, with LDAP authentication.

However, before pushing this as a PR, we should decide what should be done with the *logout* link.
Today, clicking the *logout* link is ineffective, and rightfully, imho: even if we logged the user out, it would be logged back in automatically.

What do you think should be the correct behaviour for this link ?
My own opinion is that the link should be removed from the interface when the user is logged in via this mechanism.

**Comment by GMishx** [comment]
I have a few questions about this implementation:
1. Why the session management is replaced by authentication headers? If you continue with session management, you can implement the logout as well.
    - I would like to suggest an approach like OAuth:
        1. User opens FOSSology and is presented with a link for authentication via OAuth, LDAP, etc.
        1. The user will be redirected to external auth provider which in turn provides some identifier on callback (which can be mapped to the users table).
        1. Then callback handler then sets the session.
    - In this manner, user will have a choice to go for either old auth method, or some external auth. Also, the session can be managed easily (instead of injecting the user information in HTTP headers).
1. What will happen to the old authentication (with the FOSSology DB)?
1. What will happen with the REST API?

**Comment by NicolasToussaint** [comment]
Hi @GMishx,

1.The idea of moving the authentication mechanism to Apache + injecting the authentication information in the HTTP headers was to quickly build a universal login feature in Fossology. Whatever authentication scheme supported by an Apache module will work.
   - I guess the logout _could_ be implemented - we didn't go this way, thinking that as long as the user is authenticated on her-his machine, s-he might just as well be authenticated on Fossology.
But I agree that it could make some sense in some situation.
   - The OAuth approach you suggest makes sense ; but we went for a simplified solution at first:
      - If configured in Apache, the user is automatically directed to the specified authentication solution
      - if configured in Fossology, it first checks the HTTP headers for authentication information
      - if authentication fails, it should be possible (haven't tried) to setup a local login fallback
2. The users are still managed in the DB, like before. Upon authentication, any non-existing user is created with a dummy password. Nothing else has been touched concerning the DB.
3. Good question, I have no idea what the impact is on the REST API :-/

I have pushed the changes on this branch: [external-authentication-delegation](https://github.com/Orange-OpenSource/fossology/commits/feat/orange-opensource/1273/external-authentication-delegation)
There are 3 separate commits: 
- https://github.com/Orange-OpenSource/fossology/commit/8fa0e4908fe0f49286ea567f7ea03213260b7741
- https://github.com/Orange-OpenSource/fossology/commit/cef223456558dee6d21ef7190d409946d7c66121
- https://github.com/Orange-OpenSource/fossology/commit/f0c7b287468d78c31c1dd54882af8ea22fdc0ea1

**Comment by GMishx** [comment]
I have seen the 3 commits you've mentioned here. The approach looks nice. It appears that you are just getting the auth params from external service and continuing the old authentication method passing these new values. So this will set the session for the user as earlier. Maybe you can use/set another session to prevent another redirect to auth service in case the user signs out (can be a case if user wants to login as another user like admin).

**Comment by suppadeliux** [comment]
I am not able to find the doc about how to implement LDAP with fossology.

Is this still on?

Thank you,

**Comment by NicolasToussaint** [comment]
Hi @suppadeliux ,

We have been using the LDAP authentication feature for quite some time now, but I have not yet proposed a PR because no "logout" feature has been implemented yet.

This means that once a user has logged in, s-he has to restart or use another browser, or open a private window to log in as another user (which is, IMHO no such a big deal)

I can push a fresh version of the feature the corresponding source code in a separate branch, with a configuration example.

I can also propose a PR, if it's OK for maintainers to integrate it "as is" (without "logout" feature) for the moment
@GMishx , @mcjaeger what do you think ?

**Comment by NicolasToussaint** [comment]
I have pushed our current implementation for external authentication in Fossology:
https://github.com/Orange-OpenSource/fossology/tree/feat/orange-opensource/1273/external-authentication-delegation-2

The accounts are created on the fly if they do not exist when the user logs in.

**How to use** (I will propose a proper doc in the wiki if/when the branch gets merged)

**Configure Apache to perform authentication**
Simple example for LDAP - I have a working example for SAML if required.

In this example:
- Web site URL are: `http://fossology.fqdn/repo/*`
- REST API URL are: `http://fossology.fqdn/api/*` -> the requests are redirected to `/repo/api` on local port 8880

```
<VirtualHost *:80>
ServerName fossology.fqdn
Alias /repo /usr/local/share/fossology/www/ui

<Directory "/usr/local/share/fossology/www/ui">
        AllowOverride None
        Options FollowSymLinks MultiViews

        AuthLDAPBindDN ""
        AuthLDAPBindPassword ""

        AuthType Basic
        AuthName "AD Credentials"
        AuthBasicProvider ldap
        AuthLDAPDereferenceAliases never
        LDAPReferrals off
        AuthLDAPUrl "ldap://..." NONE
        AuthLDAPGroupAttributeIsDN on
        AuthLDAPGroupAttribute member
        AuthLDAPMaxSubGroupDepth 1
        Require valid-user
        AuthUserFile /dev/null
</Directory>
</VirtualHost>
```

**Example with REST API**
The problem with the REST URL is that Apache will request external authentication... 
The workaround is to redirect  `/api/*`URL to a different port, where no authentication is configured.

```
Listen 8880

<VirtualHost *:80>

    ServerName <fqdn>
    Alias /repo /usr/local/share/fossology/www/ui

    <Location "/api">
        ProxyPass http://<fqdn>:8880/repo/api
        ProxyPassReverse http://<fqdn>:8880/repo/api
    </Location>

    <Location "/repo">
        Options Indexes FollowSymLinks MultiViews ExecCGI
        AllowOverride None
        Order allow,deny
        allow from all

        AuthLDAPBindDN ""
        AuthLDAPBindPassword ""

        AuthType Basic
        AuthName "Blah blah Credentials"
        AuthBasicProvider ldap
        AuthLDAPDereferenceAliases never
        LDAPReferrals off
        AuthLDAPUrl "ldap://..." NONE
        AuthLDAPGroupAttributeIsDN on
        AuthLDAPGroupAttribute member
        AuthLDAPMaxSubGroupDepth 1
        Require valid-user
        AuthUserFile /dev/null
        require valid-user
</Location>
</VirtualHost>

<VirtualHost 127.0.1.1:8880>
    ServerName <fqdn>
    Alias /repo /usr/local/share/fossology/www/ui
    <Location "/repo">
        Options Indexes FollowSymLinks MultiViews ExecCGI
        AllowOverride None
        Order allow,deny
        allow from all
    </Location>
</VirtualHost>

```

- Configure `fossology.conf`: here: [fossology.conf.in#L80](https://github.com/Orange-OpenSource/fossology/blob/5122cace85bc398ea426ddca0b77a931d2dfb4d7/install/defconf/fossology.conf.in#L80)

Here you should enable external authentication, and configure the environment variables in which Apache will store the information from the authentication process.

The last option forces the login to lowercase, to avoid creating multiple accounts with different case.

```
; Use external Authentication
CONF_EXT_AUTH_ENABLE=false
; Environment variable where to find the User name
CONF_EXT_AUTH_ENV_USER=
; Environment variable where to find the User email
CONF_EXT_AUTH_ENV_MAIL=
; Environment variable where to find the User Description
CONF_EXT_AUTH_ENV_DESC=
; Set to true to use lowercase usernames
CONF_EXT_AUTH_ENV_LOWERCASE_USER=
```

**Comment by GMishx** [comment]
Hi @NicolasToussaint, would you be okay to create a WIKI page to setup LDAP?

**Comment by NicolasToussaint** [comment]
> Hi @NicolasToussaint, would you be okay to create a WIKI page to setup LDAP?

Done: https://github.com/fossology/fossology/wiki/External-authentication-configuration

Hope it's clear enough, please let me know otherwise.

**Comment by GMishx** [comment]
That's just perfect. Thanks a ton. ☺

**Comment by NicolasToussaint** [comment]
My pleasure ; that's a feature branch less for me to maintain :-D

**Comment by suppadeliux** [comment]
Thank you so much for the update!!!! 👏
