### ISSUE TITLE
Add functional tests/automation for cluster testing

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#128]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2643, http://www.fossology.org/issues/2643
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
