### ISSUE TITLE
Add unit tests for the RESTful UI for PTS

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#129]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2649, http://www.fossology.org/issues/2649
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
