### ISSUE TITLE
Copyright CLI tool searches config in wrong folder

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#1298]
### Description

If one starts the latest vagrant images with https://github.com/fossology/fossology/commit/69629cc1f45f2cbde7e1318dba8cf96a3ac3de8a one can observe the following behaviour:
```
$ cd /fossology
$ src/copyright/agent/copyright -J NOTICES
cannot open regex definitions in conf: /usr/local/share/fossology//mods-enabled/copyright/agent/copyright.conf
```
The folder `/usr/local/share/fossology//mods-enabled/` does not exist and `/usr/local/share/fossology/copyright/agent/copyright.conf` might be the correct path.

**Comment by sweetca** [comment]
Same on latest Docker image of fossology/fossology
When I trying to exec inside docker simple test of any file for copyright agent:
`
/usr/local/etc/fossology/mods-enabled/copyright/agent/copyright -J --files test-main.js
`
Im getting error:
`
cannot open regex definitions in conf: /usr/local/share/fossology//mods-enabled/copyright/agent/copyright.conf
`
If I trying to lunch copyright agent with flag `--config`:
`
/usr/local/share/fossology/copyright/agent/copyright --config /usr/local/share/fossology/copyright/copyright.conf --json --files test-main.js 
`
Still same error
