### ISSUE TITLE
Values of two fields in the Obligations and Risks Administration view always set to "default"

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1306]
### Description

when modifying an obligation in the Obligations and Risks Administration view of FOSSology the values for

"Type of obligation" (Opbigation, restriction ....)

and the values for:

"Optional: level of attention this obligation should raise in the clearing process" (green, white, yellow)

seem to be not stored in the DB or the display is not correct.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.
When I have e.g. changed the value of "Type of obligation" to "restriction" then click on update and open it after a while again (the same record) then the selection is again "obligation" The same pplies for "Optional: level of attention this obligation should raise in the clearing process"
#### Screenshots

![image](https://user-images.githubusercontent.com/3418977/54528368-17c46f80-497d-11e9-99ff-cc59a113eb69.png)

### Versions

since some months still in master

**Comment by sandipbhuyan** [comment]
I want to pick up this issue

**Comment by GMishx** [comment]
Fixed by #1329
