### ISSUE TITLE
Add functional tests for Copyright agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#131]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2667, http://www.fossology.org/issues/2667
Original Date: 2012/06/15
Original Assignee: Mary Laser

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
