### ISSUE TITLE
Dockerhub currently builds images from all branches, not only master

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#1326]
### Description

Currently docker builds the HEADs of all branches, not only of master, and tags it as `latest`. This results in the awkward state, where the current image `fossology/fossology:latest` on dockerhub is build from the commit https://github.com/fossology/fossology/commit/aea86d376d31b2d61817ba57096184e0ce7bb760 of the feature branch https://github.com/fossology/fossology/pull/1325 instead of latest master (i.e. https://github.com/fossology/fossology/commit/2c57a6629585abe7696489d4ef9ea1d41b33b1f3)
![2019-04-06_10:06:27](https://user-images.githubusercontent.com/1187050/55666831-50f15080-5854-11e9-82e8-c0c05ca76520.png)

This means that `docker pull fossology/fossology` might pull a totally different, outdated, broken or unexpected image.

**Comment by GMishx** [comment]
I just checked from my side. On the Docker hub, the tests which run for the PRs are marked as `latest` for the PR alone and have nothing to do with the master branch.

I tried to do a pull from Docker
```bash
$ docker pull fossology/fossology:latest
latest: Pulling from fossology/fossology
2a639da97f77: Already exists 
d5675606884b: Pull complete 
585dfadf9734: Pull complete 
e1fdaf9ac0d8: Pull complete 
6a97908c5f64: Pull complete 
c9667d196086: Pull complete 
566477975007: Pull complete 
719d7f6e1eb1: Pull complete 
d34ec61916c6: Pull complete 
27fdceae7b1e: Pull complete 
f60300306390: Pull complete 
4e4a0b540b11: Pull complete 
ba9fad1daedb: Pull complete 
Digest: sha256:6435515413e6e3657bc3eac442e0252bdab07f2932ac3a8de4548c23cc19f16c
Status: Downloaded newer image for fossology/fossology:latest
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
fossology/fossology   latest              1785d0b480b8        4 days ago          564MB
$ docker pull fossology/fossology:latest
latest: Pulling from fossology/fossology
Digest: sha256:6435515413e6e3657bc3eac442e0252bdab07f2932ac3a8de4548c23cc19f16c
Status: Image is up to date for fossology/fossology:latest
$ docker pull fossology/fossology
Using default tag: latest
latest: Pulling from fossology/fossology
Digest: sha256:6435515413e6e3657bc3eac442e0252bdab07f2932ac3a8de4548c23cc19f16c
Status: Image is up to date for fossology/fossology:latest
```

And compared it with the build logs from the Docker hub and found that the image ID pulled was from the latest commit build on `master` branch and not from other PR commits.

| Docker image ID | Origin |
| ---: | :--- |
| `1e0cc148a149` | Tests in 'maxhbr:maxhbr/bumpDockerBaseImageToStretch' (9c1bf18a) |
| `1785d0b480b8` | Build in 'master' (2c57a66) |

I would suggest not to rely on the Docker hub UI.

**Comment by mcjaeger** [comment]
Is it still a problem? because @ag4ums and I just reviewed the docker hub config and it looks like we have
* testing of internal branches
* build for latest master

**Comment by maxhbr** [comment]
what does `testing of internal branches` mean?

**Comment by mcjaeger** [comment]
I think it is OK to run the tests on the open pull request in fossy repo which I was referring to when mentioning "internal branches", sorry:
![image](https://user-images.githubusercontent.com/3418977/61211648-6ce07a00-a700-11e9-9fe5-a45cbf3c189c.png)

Is it OK for now and close, @maxhbr ?

**Comment by maxhbr** [comment]
I frequently get messages that some docker build of fossology on some branch failed. But these results seem to be ignored.
It is OK for me to close this issue, but I still have some open questions and we do not leverage the potential.
