### ISSUE TITLE
Add SHA256 hashes (at least for SPDX export)

### ISSUE THREAD

**Issue by swinslow** [fossology/fossology#1334]
### Description

Currently, SPDX files are generated with MD5 and SHA1 hashes listed. I'm told that both of these hash algorithms are vulnerable or broken. It would be ideal if exported SPDX documents could also include SHA256 hashes, which is permitted by the SPDX spec.

#### Steps followed and expected result

1. Export an SPDX document for a cleared upload (I'm using tag-value export).
2. `PackageChecksum` lines list MD5 and SHA1 checksums, but not SHA256.
3. Similarly, for each file `FileChecksum` lines list MD5 and SHA1 checksums, but not SHA256.

#### Comments

The spdx2tv agent gets the file hashes by calling [getUploadHashes()](https://github.com/fossology/fossology/blob/master/src/lib/php/Dao/UploadDao.php#L480). 

From looking at the database schema, it appears that only MD5 and SHA1 checksums are being stored in the `pfile` table. So I am guessing that there is not an easy templating fix to enable SHA256 hashes. At least, it looks to me like this would require changing the database table schema to add a column for SHA256, then generate and store those hashes when the upload is being unpacked / scanned.

**Comment by mcjaeger** [comment]
(from discussion)
* separate column needed
* display in the UI (file info page etc)
* maybe display in unified reporting
* output in spdx2 rdf and tag-value
... in general there could be a REST endpoint that delivers file or upload for hash ...

**Comment by GMishx** [comment]
With PR #1370, we have SHA256 is pfile table. It will be much simple now to add the checksum in the reports.
