### ISSUE TITLE
Add functional tests for Package Agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#134]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2691, http://www.fossology.org/issues/2691
Original Date: 2012/06/15
Original Assignee: Dong Ma

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
