### ISSUE TITLE
Deactivated manual copyright text findings are not visible in the UI

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1344]
### Description

If I add a manual copyright finding to a file in the **"View Copyright/Email/Url Analysis"** page (`mod=copyright-view`) it appears in a table called **Current decisions:**, but as soon as I disable the disable the statement and reload the page, it disappears from the UI and I can only find it in the DB.

#### How to reproduce

1. Add a manual copyright finding for a file.
1. Disable the copyright.
1. Reload the page.

#### Screenshots

Disabling a text finding:

![image](https://user-images.githubusercontent.com/18077542/57118652-6342a980-6d82-11e9-94ea-5ab6ae903fb7.png)

Reloaded the page:

![image](https://user-images.githubusercontent.com/18077542/57118655-6e95d500-6d82-11e9-848c-36d96a43d458.png)

### Versions

* Last commit id on master: 6c4fc48251ef296d077f8f8870b8d2d753798e9b

**Comment by codeakki** [comment]
I will start working on this issue sir if u provide me some guidelines! if this is the open issue?

**Comment by GMishx** [comment]
Hello @codeakki , you can look to file `src/copyright/ui/CopyrightView.php` which loads the data and `src/copyright/ui/template/ui-xp-view_rhs.html.twig` which is the template for the page.
You can try to copy the working of the **Scanner findings** tables.
**Note:** The scanner findings table works on `copyright` table whereas **Current decisions** table works on `copyright_decision` table.

**Comment by bighnesh0404** [comment]
I would like to work on this issue

**Comment by teekhandekar** [comment]
@GMishx  can I work on this ?

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by shaheemazmalmmd** [comment]
@ArijeetBanerjee sure You can work on this issue.

**Comment by Abhyuday03** [comment]
Is the issue still available, would like to work on it
