### ISSUE TITLE
At job detail page - replace 3 dots which gives access to full report 

### ISSUE THREAD

**Issue by gmeinwik** [fossology/fossology#1346]
### Description

In order to see the details of a job in the job overview page, the job number needs to be clicked to open the "Geeky Scan Details" page. Scrolling down, the report is cut at some line. Below the report, there are 3 dots displayed, which - after clicking - gives access to the full report. I did not recognize the dots to represent a link. 

#### Steps followed and expected result

I would propose to replace the 3 dots with text "display full log" in order to make it clear for the user, that the information is available but hidden. See link displayed at the bottom left of the screenshot. It should be clear, that a link is represented by the dots...
![Screenshot-LogLink](https://user-images.githubusercontent.com/18732654/57253350-ca947e00-704e-11e9-8de1-611a1853a91e.png)

**Comment by prondubuisi** [comment]
Hello @GMishx has this been fixed? I have been trying to see this locally and I can't see to find the three dots mentioned,
![Fossology](https://user-images.githubusercontent.com/22311928/65870565-657e5380-e374-11e9-8b71-045d0eedb417.png)

 also I don't know how to make this UI change, I have followed your instructions on Slack about figuring out what files power Fossology web pages and this is the file it is pointing to https://github.com/fossology/fossology/blob/master/src/www/ui/showjobs.php#L121

**Comment by GMishx** [comment]
No @prondubuisi, the issue is not resolved. You are not getting the `...` since the log is too small. You can try to upload a package with some binary files and check the logs for **monk** to recreate it.

And you've reached to the correct page **showjobs.php** but the page actually loads data with another Ajax call to `mod=ajaxShowJobs` which will lead you to the following code:

https://github.com/fossology/fossology/blob/9d0765c2eda0b72c4a5aaac640322d4f59ffd7f4/src/www/ui/async/AjaxShowJobs.php#L156-L166

**Comment by prondubuisi** [comment]
Hello @GMishx can you recommend any packages I could upload to recreate this? All the packages I have return small logs. Thanks

**Comment by GMishx** [comment]
You can try uploading tensorflow.

Download any zip from https://github.com/tensorflow/tensorflow

**Comment by prondubuisi** [comment]
I have been trying to see the log but I get the same log message for both .zip and .tar.xz
`2019-09-30 11:41:42 ununpack [0] :: JOB[9].ununpack[3584.localhost]: "ERROR traverse.c.229: pfile 3855 Command zcat failed on: /srv/fossology/repository/ubuntu-xenial/ununpack/353645l/2d8087a8a0c69e682298e0a784053f167e511eed.8b1169554f6db9066d639aa969468058.52446767.dir/tensorflow-master/third_party/icu/data/icu_conversion_data.c.gz.aa"`
Any idea what am doing wrong @GMishx

**Comment by GMishx** [comment]
There seems to be some issue with ICU file in the package (`third_party/icu/data/icu_conversion_data.c.gz.aa`). It can not be unpacked in GNU/Linux systems.

You can try using version [1.12.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0) release. It should work fine.

Or else, you can use [logback v1.1.7](https://github.com/qos-ch/logback/releases/tag/v_1.1.7) which will ununpack easily and will give you big enough logs in monk.

**Comment by prondubuisi** [comment]
@GMishx super thanks for the prompt response. Will be checking this out!

**Comment by prondubuisi** [comment]
Hello @GMishx is there a demo version of fossology available online? I think my Vagrant installation is not working well

**Comment by GMishx** [comment]
Hi @prondubuisi, you can get the instance IP from this wiki page.

https://wiki.fossology.org/handson

It is at the bottom and the username/password are mentioned there. Since it is a public instance, please respect the limitations.
