### ISSUE TITLE
Window for choosing package to be reused should be resized

### ISSUE THREAD

**Issue by gmeinwik** [fossology/fossology#1347]
### Description

Uploading a new version of an already cleared package. The configuration page of the new upload at section 8 "(Optional) Reuse" just offers a small window to scroll for selecting the respective upload. 

#### Steps followed and expected result

The window "Upload to reuse" should be a pull-down menu with a reasonable size to make it easier to scroll and find a particular existing upload. Showing only 1-4 lines within the window makes it really hard to locate the upload, if there are many uploads available

![Screenshot-ReuseConfig](https://user-images.githubusercontent.com/18732654/57254213-f4e73b00-7050-11e9-83cd-157285b1507d.png)

**Comment by vivekaindia** [comment]
Hello all,
Can I work on this issue?

**Comment by mcjaeger** [comment]
@vivekaindia that sounds great, of course you can
