### ISSUE TITLE
Add functional tests for Wget_Agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#135]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2703, http://www.fossology.org/issues/2703
Original Date: 2012/06/15
Original Assignee: larry shi

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
