### ISSUE TITLE
Show User Names rather than User ID

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1351]
### Description
In the group management page (for example, there may be other relevant places), one add users to a given group. The users are selected from a drop-down list (see screen shot)

The thing is that only the User ID are shown in this list - in my case the one cannot guess the user name from its ID easily, and that makes this drop down list very impractical.

#### Steps followed and expected result

Maybe we could:
1) change the UserID in the list with the user's Full Name (if it is available)
1) maybe make this configurable if some users would rather use the UserID (I would guess so)
1) show both UserUID and user's Full Name

My own preference goes for 3).

#### Screenshots

![image](https://user-images.githubusercontent.com/22956329/57701304-06859f80-765c-11e9-8c34-ad12c60edaae.png)

**Comment by sandipbhuyan** [comment]
Shall I pick this issue

**Comment by GMishx** [comment]
Yes @sandipbhuyan, you can can. Would you like to discuss your approach over slack?

**Comment by sandipbhuyan** [comment]
Yup that will be greate

**Comment by NicolasToussaint** [comment]
Thanks @sandipbhuyan, the feature looks great !
