### ISSUE TITLE
Setting the default group for a user.

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1353]
### Description

The problem is that when creating a new user in fossology, the user is automatically assigned to the user's group (which has the same name as the user name).

If you run a server, where multiple users work on same uploads, then usually also a common group is present.

However, the common user group needs to be switched manually when the user is logged in: from the personal group of the user to the common group for jointly working on uploads.

This is annoying, especially, when you consider that new users must  be explained to switch the group one time first before start working.

If you have single-sign-on solutions in place, you cannot even login for a new user and switch the group assignment for them.

Solution would be to allow an admin, who creates an user, to set the default group at user creation. Then, the first login of the user will already show the right group for starting working.

**Comment by muarachmann** [comment]
@mcjaeger can i pick this up.
