### ISSUE TITLE
Adding Copyright entry from GUI (copyright-view)

### ISSUE THREAD

**Issue by piotreke12** [fossology/fossology#1362]
### Description

On copyright-view page it is possible do deactivate or edit copyright entry found in file. 
It would be also useful to have possibility to add new copyright directly from the GUI - in case that there was no coyright entry in file but we know that specific file should have one.

#### Steps followed and expected result

I suppose it could look like this:
1. Find file without proper copyright entry
2. Go to Copyright/Email/Url/Author menu entry
3., Enter proper Copyright text to some text field (probably existing with 'Replace' label can be used
4. Click new Add button - new copyright entry should be added and persisted for this specific file

#### Screenshots

Please find GUI page I'm writing about:

![image](https://user-images.githubusercontent.com/12530337/58546619-08c42e00-8206-11e9-96ff-6985b8a6f124.png)

**Comment by piotreke12** [comment]
As a requester, I would like to implement this feature - of course if there are no objections for this feature

**Comment by GMishx** [comment]
Hello @piotreke12,

If am not wrong, you want to manually add a copyright to a file where no match was found by the agent. Correct?

If I understood you correctly, then you can do so in current implementation by filling out the **Description** (optional), **Text finding** and **Comment** (optional) field on the same page and select the **Issue Type** as **Identified** and hitting the submit button.

If I misunderstood your requirement, can you please elaborate your situation a little more?

Thanks.

**Comment by piotreke12** [comment]
Hello @GMishx,

thank you for your answer.
Filling out Description, Text finding and Comment fileds and hitting submit button creates new entry, but like this:
![image](https://user-images.githubusercontent.com/12530337/58620970-9ec08d00-82c8-11e9-9abc-a930c70dc4b6.png), invisible on any report

Our goal is to be able to add new Copyright entry (for example when developer deleted copyright notice from file while we know it should be present).
What is more, we need this new, added copyright notice to be seen on report generated (under FileCopyrightText field)

Is my explanation clear enough?

**Comment by shaheemazmalmmd** [comment]
Hello @piotreke12,

The values you have entered from UI for new finding of the copyright will be there in table with the below heading(In unified report).

**13. Copyrights (User Findings)**

hope this had answered your query.

**Comment by piotreke12** [comment]
Ok, you are right, thank you for explanation.

The thing is we use SPDX reports and there is no info on user-desicion copyrights there.

I can see that user-decision copyrights are placed in copyright_decision table, maybe this is why they are not present on SPDX report.

Don't you think SPDX reports should take into account user-decision copyrights and include them in FileCopyrightText tag?

**Comment by NicolasToussaint** [comment]
Hi,

If Piotr's understanding is correct, then it's more a Bugfix than a Feature Request :-)

We'll start working on including manually added Copyrights in the SPDX reports, unless someone thinks that's not the way to go.

**Comment by NicolasToussaint** [comment]
Hi @shaheemazmalmmd ,

My understanding of the situation is that there are two distinct type of Copyrights
- **Scanner findings:** the one detected automatically by the agent
   - listed on the *View Copyright/Email/Url Analysis* view for a given file
   - listed on the *Copyright Browser * view for the whole upload
   - included in the Unified Report (section: *12. Copyrights*)
   - Included in the SPDX reports
   - stored in the DB in table `copyright`
- **Current decisions:** Manually added in the *View Copyright/Email/Url Analysis* page
   - listed on the *View Copyright/Email/Url Analysis* view for a given file
   - **Not** listed on the  *Copyright Browser * view
   - included in the Unified Report (section: *13. Copyrights (User Findings)*)
   - **Not** Included in the SPDX reports
   - stored in the DB in table `copyright_decision` table

Is there a reason why the *User Decision Copyrights* are not displayed in the general * Copyrights* view, and not included in the SPDX Reports ?

**Comment by GMishx** [comment]
> Is there a reason why the _User Decision Copyrights_ are not displayed in the general * Copyrights* view

There is a PR #1311 for the same.

> and not included in the SPDX Reports ?

This supposedly is a bug and needs to be fixed.

**Comment by NicolasToussaint** [comment]
> There is a PR #1311 for the same.
Thanks for the pointer.

> > and not included in the SPDX Reports ?
> This supposedly is a bug and needs to be fixed.

Would it be OK if @piotreke12 started working on this specific problem ?
According to https://github.com/fossology/fossology/pull/1316#pullrequestreview-229101849 , copyrights are not included in dep5, spdx-rdf, spdx-tv reports.

**Comment by GMishx** [comment]
Yes sure, @piotreke12 can work on the SPDX report and other reports as well.

I am assigning the issue to him. Hope that is okay.
