### ISSUE TITLE
Bucket menu entry shown in "main" menu bar

### ISSUE THREAD

**Issue by piotreke12** [fossology/fossology#1366]
### Description

To see results for Bucket analysis it is necessary to click **Info** from menu bar and just then we can see **Bucket** link in menu.

It would bu much easier to find it if it would be in main menu bar for other views, just like Copyright, ECC, keyword etc.

## Screenshots 

Now, Bucket menu link shows only in certain mods (e.g. view_info mod):

![image](https://user-images.githubusercontent.com/12530337/58624573-d6cbce00-82d0-11e9-9e29-e5604e1d7926.png)

I think, link shoud be visible in menu for other mods:

![image](https://user-images.githubusercontent.com/12530337/58624170-ee568700-82cf-11e9-9183-6e4186f915d0.png)

**Comment by piotreke12** [comment]
As a requester, I would like to implement this feature - of course if there are no objections for this

**Comment by mcjaeger** [comment]
Hi, thanks for bringing this ... I think there are no issues against it. You plan to unify the yellow navigation area for the different views w.r.t. bucket...? I think that sounds very fine.

**Comment by piotreke12** [comment]
Yes, In my opinion there is no point that link to Bucket summary is visible only sometimes (depending on view).
For example:
- for mod=license - we can browse folders, but to find Bucket summary I have to go to Info and then Bucket, and only then I can see Bucket summary for whole upload or folder
- for mod=view-license - there is direct Bucket link im the menu that shows me Bucket summary for this specific file

That's why I think Bucket menu entry should be always visible as there is specific Bucket summary view for whole upload/folder

I hope I've described it precisely enough :)

**Comment by mcjaeger** [comment]
I think it sounds good, pls feel free to go ahead
