### ISSUE TITLE
cp2foss in CI Pipeline

### ISSUE THREAD

**Issue by RaphaelHerd** [fossology/fossology#1375]
hi all,

I'm currently evaluating Fossology for using it in our company. I'm stucked at the point of how to use it in an CI/CD pipeline (e.g. in a bash script, etc.). I saw cp2foss but on the CLI tool itself I was not able to find an option to set the remote server instance of the Fossology instance. Also cp2foss is written in PHP which is very unconformable. But this is another story. My plan would be to launch the docker container where the CLI (cp2foss) is in and use the CLI to upload it to another remote instance located at (http://myinstance.com/...). 

Can someone help me with my thoughts?

Thanks in advance

**Comment by GMishx** [comment]
Hello @RaphaelHerd,

cp2foss works only for instances running FOSSology locally.

You can give the REST API a try. Here is a wiki with basic steps: https://github.com/fossology/fossology/wiki/FOSSology-REST-API

**Comment by mcjaeger** [comment]
and there is also https://github.com/fossology/fossdriver

-> do these two things go into the direction you thought of? I think cp2foss was designed only to run on the machine where fossology is installed.

**Comment by RaphaelHerd** [comment]
thx I will look into it

**Comment by mcjaeger** [comment]
@RaphaelHerd could we close it?

**Comment by GMishx** [comment]
Closing the issue for now. @RaphaelHerd please reopen if needed.
