### ISSUE TITLE
Handling SPDX options in report configuration page

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1377]
### Description
When loading the new Report Configuration page, the two SPDX related options are improperly loaded from the database.

In fact, I realized that:
- the option ` Show SPDX license comments` is properly checked if and only if the other option 
`Source / binary integration notes | no critical files found, ...` is also checked
- similar behaviour wrt to `Ignore files with no info in SPDX ` and `Source / binary integration notes | critical files found, ...`

The saving of the options in the `report_info` ir correct, only the display of the saved value in the GUI is wrong.

#### How to reproduce
1. Upload & Scan
1. Browse to the `Report Configuration` page
1. Check the two bottom SPDX options
1. Click Submit 
   - The page is reloaded without the options checked
   - The options are properly saved in DB
1. Select again the two SPDX options, as well as two ` Source / binary integration notes`options.
1. Click Submit 
   - This time, all four options are loaded correctly

#### Screenshots
![image](https://user-images.githubusercontent.com/22956329/59832168-939ad300-9343-11e9-91bf-23780d440783.png)

### Versions

* Last commit id on master: 4d03f6
* Operating System (lsb_release -a): Docker, based on Stretch

**Comment by NicolasToussaint** [comment]
I identified the problem ; we are reading the values from the wrong array: https://github.com/fossology/fossology/commit/453da1f130fcdb8d51f8c5aed9d7ab404be88720#r34009324

**Comment by GMishx** [comment]
Hello @NicolasToussaint, does fix by #1380 works for you?

**Comment by NicolasToussaint** [comment]
@GMishx, I'm a bit late, but the fix does work great on Master, thanks !
