### ISSUE TITLE
Add unit tests for Upload UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#138]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2721, http://www.fossology.org/issues/2721
Original Date: 2012/06/15
Original Assignee: Dong Ma

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dan Stangel** 
Original Date: 2012/07/31 23:48:54 +0000

---

Bumping to iteration 6.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dan Stangel** 
Original Date: 2012/08/01 00:39:27 +0000

---

Set rank to 2 (is this correct?)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/08/06 07:40:41 +0000

---

mary,
how to add unit tests for Upload UI tasks, do you have any suggestions? thanks, I have no idea for now.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/08/06 23:51:20 +0000

---

Unit testing Upload UI are part of the larger task identified in #2505 "Need to provide samples of good unit and functional tests."

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/08/13 20:49:48 +0000

---

Resetting rank back to 6 so it is prioritized correctly with the other work.

**Comment by mcjaeger** [comment]
we did already a suite of five basic tests with selenium (can be run also headless, nice!) should contribute them probably at one day.

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
