### ISSUE TITLE
Add an "inverse search" in URL page

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1387]
### Description

When clearing the URLs, we sometimes like to remove all links that do not contain the work _license_, and there is no simple solution to do that.

The only solution we have is:
1. remove all URL
2. search for the work licence
3. un-remove the results

We would like to add the possibility the perform a search of all URL that *do not contain* a search term.

An idea would be an new checkbox (see screenshot), but it could also be another button, another textfiled+button, ...

#### Steps followed and expected result
1. Enter a search term
1. Click the _inverse search results_ checkbox
1. Click _Search_
1. All URL *not containing* the searched term are displayed.

#### Screenshots
![image](https://user-images.githubusercontent.com/22956329/60265937-41c7ef00-98e7-11e9-9eb7-4571c1bfb30a.png)

**Comment by teekhandekar** [comment]
Can I work on this ?

**Comment by teekhandekar** [comment]
@GMishx can I work on this ?

**Comment by GMishx** [comment]
Really you do not need to tag anyone on the issue. Just comment you are working on it so others do not start at the same time as you.
It is just filling my notifications @teekhandekar
