### ISSUE TITLE
Add functional tests for Upload UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#139]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2727, http://www.fossology.org/issues/2727
Original Date: 2012/06/15
Original Assignee: larry shi

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/07/27 07:51:55 +0000

---

do not take this job temporarily.

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
