### ISSUE TITLE
Upload a specific GIT branch

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1390]
### Description

When performing an Upload from Git, one **has to** clone the *master* branch - it is not possible to scan a specific branch.

However, Git allows to clone directly a specific branch, in one command:
`git clone --single-branch -b "release/2.6" git@___:___/___.git`

We need a feature to select a branch in the *Upload* page.

#### Steps followed and expected result

1. Go to *Upload* page
1. Select *"Version Control System"*
1. Select *Git*
1. Enter the Git clone https URL
1. **in a new optional field** enter the branch or tag to be cloned
1. Click *Upload*

The git command is run with the extra arguments *--single-branch -b <branch>*

#### Screenshots
![image](https://user-images.githubusercontent.com/22956329/60352580-66e05e80-99c8-11e9-8d5c-c30e173ddca4.png)

**Comment by NicolasToussaint** [comment]
When this issue is tackled, the REST API should be updated too, following @GMishx 's [PR 1493](https://github.com/fossology/fossology/pull/1493), allowing creating an VCS upload via the REST API.

**Comment by piotreke12** [comment]
I can work on it

**Comment by GMishx** [comment]
Thank you for putting a reminder here @NicolasToussaint. Maybe we can create a REST API label and tag every issue which needs to be reflected in REST API.

**Comment by NicolasToussaint** [comment]
> Maybe we can create a REST API label and tag every issue which needs to be reflected in REST API.
Good idea!

**Comment by NicolasToussaint** [comment]
I assigned the ticket to @piotreke12 , hope that's OK :)
