### ISSUE TITLE
nomos hangs when scanning GPLv2 on OSX

### ISSUE THREAD

**Issue by xizhao** [fossology/fossology#14]
I built nomos on OSX.  Scanning most files works fine, but scanning a GPL2 license hangs & takes 10+ minutes. Is this normal?

**Comment by mcjaeger** [comment]
First suggestion is to keep this and if someone has the abilities to work on this (using macosx). But, I am not sure about a high priority for this. Also it would be possible to ...

1) use the vagrant on macosx (that is what I do)
2) try to get Docker running on macosx

**Comment by bufferoverflow** [comment]
As mentioned here https://github.com/fossology/fossology#installation
> FOSSology is available for multiple versions of Linux.

There is also a Docker version available.
