### ISSUE TITLE
Add unit tests for Jobs UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#140]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2733, http://www.fossology.org/issues/2733
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
