### ISSUE TITLE
Incomplete SPDX report generated through the REST API when an agent is running 

### ISSUE THREAD

**Issue by avneetsngh** [fossology/fossology#1402]
### Description

When a SPDX report generation is requested through the REST API, Fossology allows the report to be generated even when multiple scanners/jobs might be running.

This results in a report being generated that contains incomplete data.

Currently, there is no way to know from the REST API if the agents/scanners/jobs have completed running

Expectation:

1. The status of a job can be queried using the REST API, so that the user can request report generation/download only when all the jobs for a particular upload have finished, or

1. FOSSology should prevent an incomplete report from being generated/downloaded

Possible solutions:

1. More details about the scanner status in the /jobs endpoint so that job status is known 
       * Implement github issue #1301 
       * Patch: [proposal-1_return-job-status.patch.txt](https://github.com/fossology/fossology/files/3396212/proposal-1_return-job-status.patch.txt)

1. An error message from FOSSology if there is a request to generate the report before all the agents/scanners have finished running
        * Patch: [proposal-2_return-error-when-incomplete-report-reuested.patch.txt](https://github.com/fossology/fossology/files/3396213/proposal-2_return-error-when-incomplete-report-reuested.patch.txt)

#### How to reproduce

* Upload a file

     I used `http://mirror.cse.iitk.ac.in/ubuntu/pool/main/e/elfutils/elfutils_0.165.orig.tar.bz2`

        $ curl -k -s -S -X POST http://localhost:8081/repo/api/v1/uploads \
                -H "folderId: 1" \
                -H "public: public" \
                -H "Content-Type: multipart/form-data" \
                -H "Authorization: Bearer ${BEARER_TOKEN}" \
                -F 'fileInput=@"/tmp/b/elfutils_0.165.orig.tar.bz2";type=application/octet-stream'

         -> {"code":201,"message":2,"type":"INFO"}

* Schedule scan using any agent

        $ curl -k -s -S -X POST http://localhost:8081/repo/api/v1/jobs \
                -H "folderId: 1" \
                -H "uploadId: 2" \
                -H "Authorization: Bearer ${BEARER_TOKEN}" \
                -H 'Content-Type: application/json' \
                  --data '{
                     "analysis": {
                     "bucket": true,
                     "copyright_email_author": true,
                     "ecc": true, "keyword": true,
                     "mime": true,
                     "monk": true,
                     "nomos": true,
                     "package": true
                  },
                  "decider": {
                     "nomos_monk": true,
                     "bulk_reused": true,
                     "new_scanner": true
                  }
                }'
      
      -> {"code":201,"message":3,"type":"INFO"}

* Generate a report while the scan is still running

        $ curl -X GET http://localhost:8081/repo/api/v1/report \
                -H "Authorization: Bearer ${BEARER_TOKEN}" \
                -H "reportFormat: spdx2tv" \
                -H "uploadID: 2"

        -> {"code":201,"message":"localhost\/repo\/api\/v1\/report\/4","type":"INFO"}

* Download the generated report

        $ curl -X GET http://localhost:8081/repo/api/v1/report/4 \
                -H "Authorization: Bearer ${BEARER_TOKEN}" \
                -H "reportFormat: spdx2tv" \
                -H "uploadID: 2"

        ->
            SPDXVersion: SPDX-2.1
            DataLicense: CC0-1.0

            ##-------------------------
            ## Document Information
            ##-------------------------

            DocumentNamespace: http://1a4f1267c0a9/repo/SPDX2TV_elfutils_0.165.orig.tar.bz2_1562841416.spdx
            DocumentName: /srv/fossology/repository/report
            SPDXID: SPDXRef-DOCUMENT

            ...
            ...

##### Example of incomplete report
![example-incomplete-report](https://user-images.githubusercontent.com/52908571/61281026-89e77c80-a7d6-11e9-9eff-a9599394f171.png)

Please see the attached screenshot "example-incomplete-report.png"
Here it is seen that there is no data file or license data under the respective sections at `File Information` or `License Information`

##### Expected report
![example-expected-report](https://user-images.githubusercontent.com/52908571/61281048-94097b00-a7d6-11e9-933d-9ab2badac4e1.png)

Please see the attached screenshot "example-expected-report.png"

* File data is available under the section `File Information`
* Scanner information is also visible as `PackageLicenseComments` under the `Package Information` section

### Versions

* Last commit id on master:

       171d4d

* Operating System (lsb_release -a):

        No LSB modules are available.
        Distributor ID: Ubuntu
        Description:    Ubuntu 16.04.6 LTS
        Release:    16.04
        Codename:   xenial

* Docker fossology image tag

        3.5.0

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

No errors/Warnings observed

#### Apache logs

Logs generated under /var/log/apache2/error.log

0 bytes

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

N/A

**Comment by GMishx** [comment]
Hello @avneetsngh,

Does the PR #1415 provide a solution to this issue?

**Comment by avneetsngh** [comment]
Hello @GMishx ,

Thank you for the fix.

The new job status returned by the /jobs endpoint has made it possible to verify if all jobs have been completed before downloading a report, hence ensuring that it contains all the data
