### ISSUE TITLE
restApi: Don't get list all user

### ISSUE THREAD

**Issue by hieupvtsdv** [fossology/fossology#1409]
### Description
When get list all user or other users on FOSSology by REST API, result is info of user generater this token using.
#### How to reproduce
Request:
curl -i -X GET "http://localhost/repo/api/v1/users" \
-H "accept: application/json" \
-H "Authorization: Bearer <token>"

Response: only token's user
Although, Server have three users.

### Versions
* Version : 3.5.0
* Last commit id on master: 5cc1802b011ae091c1cdc22d6d18df448ce14fd6
* Operating System (lsb_release -a): Debian 8

**Comment by ag4ums** [comment]
Hello @hieupvtsdv , this issue is resolved here, #1382, and merged.
