### ISSUE TITLE
Add functional tests for Search UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#143]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2751, http://www.fossology.org/issues/2751
Original Date: 2012/06/15
Original Assignee: larry shi

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
