### ISSUE TITLE
Add functional tests for Browse UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#145]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2763, http://www.fossology.org/issues/2763
Original Date: 2012/06/15
Original Assignee: Dong Ma

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
