### ISSUE TITLE
Missing build dependencies

### ISSUE THREAD

**Issue by dhMat** [fossology/fossology#1458]
## Description

I try to install fossology from source as described in https://github.com/fossology/fossology/wiki/Install-from-Source

After running utils/fo-installdeps still some dependencies are missing

Following packages I have installed manually:
- libjsoncpp-dev
- libssl-dev
- libjson-c-dev
- libboost-filesystem-dev

to complete the compilation process. Please add them to the build dependencies.

#### How to reproduce

- Vanilla Debian
- utils/fo-installdeps
- make

### Versions

* Last commit id on master: 2b7881bf
* Operating System (lsb_release -a):
Distributir ID: Debian
Description:   Debian GNU/Linux 9.3 (stretch)
Release:         9.3
Codename:    stretch

**Comment by GMishx** [comment]
Hello @dhMat,

Thanks for reporting the issue, but I am unable to reproduce the issue. Will it be possible for you to send the logs generated by `utils/fo-installdeps` ?

As you can see in `fo-installdeps`, additional dependencies (agent specific) are installed by agent's own `mod-deps`
https://github.com/fossology/fossology/blob/2b7881bf0b8aec8240228b10369cdeae2f592606/utils/fo-installdeps#L235

For example, `libjsoncpp-dev` is used by copyright agent and is defined here:
https://github.com/fossology/fossology/blob/2b7881bf0b8aec8240228b10369cdeae2f592606/src/copyright/mod_deps#L80

**Comment by dhMat** [comment]
Where are the logs of `utils/fo-installdeps` stored?

**Comment by GMishx** [comment]
`fo-installdeps` does not create logs in any file but you can send anything you get on your STDOUT and STDERR.

**Comment by dhMat** [comment]
After I have installed the missing packages by hand the problem no longer occur. So now it is a little bit difficult to get the output of fo-installdeps.

I also have tested the build process at home on a Ubuntu machine and the problem did not occur. It looks like the problem was related to the setup at work. I have to use a PC without internet connections. The debian package repository is available as a mirror on a external hdd.

My assumption for now is that it is a problem of our PC setup and not of fossology. Sorry for the effort.
