### ISSUE TITLE
Remove additional C files from ununpack agent

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1462]
### Description

OpenSSL provides functions to calculate different digests MD5, SHA1 and SHA256.

In this way, we can remove additional files and make it as a library dependency.

https://github.com/openssl/openssl/tree/OpenSSL_1_0_1/crypto/sha
https://github.com/openssl/openssl/tree/OpenSSL_1_0_1/crypto/md5

### Versions

* Last commit id on master: a0de8e9490a69b03e6d831e13d188e409f9845fd

**Comment by andi8086** [comment]
Good idea. It is always better to use existing library functions instead of writing one's own.

**Comment by andi8086** [comment]
It seems we must add an exemption cause to the GPL license of fossology to be able to link to the OpenSSL library. I am not a specialist for this. See the following other issue on another project:

https://github.com/yann2192/pyelliptic/issues/13

However, on gnome.org people say that one may link a GPL program to a non-GPL library, if it is part of the operating system and usually distributed with it, which is the case in Linux.

https://people.gnome.org/~markmc/openssl-and-the-gpl

The interpretation is unclear and they come to the same exemption case as stated in the first link.

Any other opinions on this besides adding the following exemption to the Fossology License?

-- SNIP
* In addition, as a special exception, the copyright holders give
 * permission to link the code of portions of this program with the
 * OpenSSL library under certain conditions as described in each
 * individual source file, and distribute linked combinations
 * including the two.
 * You must obey the GNU General Public License in all respects
 * for all of the code used other than OpenSSL.  If you modify
 * file(s) with this exception, you may extend this exception to your
 * version of the file(s), but you are not obligated to do so.  If you
 * do not wish to do so, delete this exception statement from your
 * version.  If you delete this exception statement from all source
 * files in the program, then also delete it here.
-- SNIP

**Comment by mcjaeger** [comment]
There is also the licensing issue (move to Apache-2.0 license) at OpenSSL 3.0.0, which also someone on slack mentioned.

**Comment by GMishx** [comment]
How about using [libgcrypt](https://dev.gnupg.org/source/libgcrypt/) which is licensed under GPL-2.0?
