### ISSUE TITLE
REST API: New upload using VCS (like git clone)

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1467]
### Description

Today, via the REST API, the only way to create an upload is by transferring a binary file.
It would be nice to enrich the API to trigger an scan by other means (in particular a git clone)

#### Steps followed and expected result

Use REST command such as this to create a new Upload, triggering a new Git Clone
```
POST .../api/v1/uploads
 -F 'vcsUrl="https://github.com/fossology/fossology.git"'
 -F 'vcsUsername="<my_username>"'
 -F 'vcsPassword="<my_password>"'
  (...)
```

**Comment by GMishx** [comment]
We can reuse wget agent's capabilities and provide additional flags in REST call which user can set to denote VCS URLs.

**Comment by GMishx** [comment]
Hello @NicolasToussaint,

Can you please test PR #1493 and see if it is aligned with your request?

**Comment by NicolasToussaint** [comment]
Hi @GMishx 

Many thanks for the PR, I did plan to give a check indeed
