### ISSUE TITLE
Add functional tests for Organize UI tasks

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#147]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2775, http://www.fossology.org/issues/2775
Original Date: 2012/06/15
Original Assignee: Paul Holland

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/07/03 10:40:55 +0000

---

HI paul, 

sorry, I did not capture what do you mean 'Add functional tests for Organize UI tasks', you mean adding UI-Based tests into functional test automation framework to confirm whether the legacy functions of fossology or new check in work or not, correct?
if yes, it is a pity, I can not start this task, till now, our web-based test framework does not work, mary is investigating test framework, perhaps she can give us some suggestion.

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
