### ISSUE TITLE
Fail to upload huge source archive.

### ISSUE THREAD

**Issue by leimaohui** [fossology/fossology#1470]
### Description

When I want to upload a huge source archive(about 2.5G) to fossology, error occurred.
So, I want to know the maximum size that fossology can handle or is there any way to config the value?

**Comment by ag4ums** [comment]
Hello @leimaohui, It will be really helpful if you can provide more information when mentioning `error occurred` in the ticket, we would like to know what kind of error has occurred, is it only the file limit reported in UI or any other issue.

* maximum file upload size supported(commanded) by fossology is 700MB and it is mentioned in the `upload -> From File` page
![image](https://user-images.githubusercontent.com/6360640/64599609-4fb1ea00-d3d7-11e9-955f-ef81f661c679.png)

* anyway you can update/increase the limit by updating `upload_max_filesize` field in the `php.ini` file.

**Comment by leimaohui** [comment]
Thank you for your reply, I modified upload_max_filesize. Then login container and restart fossology service.
`
# cat /etc/php/7.0/cli/php.ini | grep upload_max_filesize
upload_max_filesize = 3G
`
After that, I tried to upload this file by REST API and GUI,   but succeeded in neither.

-  If I upload archive(2.5G) by REST API, got the error result as following:

`
$ curl -k -s -S -X POST http://......
{"code":500,"message":["Missing file","File fileInput missing from request"],"type":"ERROR"}
`

- If I upload it by GUI, the GUI will block about 10 minutes. But in the end, I can't see this upload job in jobs list.

**Comment by leimaohui** [comment]
Thanks, this error maybe  because my upload file has something wrong.

**Comment by rahulsachdeva2** [comment]
Increased the upload_max_filesize and post_max_size in php.ini and restarted the apache and fossology service but the new update size not reflecting in fossology

**Comment by ka-els** [comment]
I found 2 files php.ini:
/etc/php/7.2/cli/php.ini
/etc/php/7.2/apache2/php.ini

The one in apache2 directory did the right update of 'upload_max_size'. 

But still I have the same problem as mentioned above:
If I upload it by GUI, the GUI will block and in the end, I can't see this upload job in jobs list.
Currently I use only the GUI at a Ubuntu 18.04.
Any hints ?
