### ISSUE TITLE
Provide information about the version of the REST API

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology#1474]
I would like to retrieve the version and other meta information about the API via some endpoint like: `.../api/v1/info`

**Comment by GMishx** [comment]
Can you please describe what could be the **other meta information**?

**Comment by deveaud-m** [comment]
E.g. the information from the OpenAPI description as JSON object:
```
info:
  title: FOSSology API
  description: Automate your fossology instance using REST API
  version: 1.0.3
servers:
  - url: 'http://localhost/repo/api/v1'
    description: Localhost instance
security:
  - bearerAuth: []
```
