### ISSUE TITLE
Get list of folders under a given parent via REST API

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology#1475]
It seems like I just can list the folders under the root folder using the endpoint `.../folders`.

I would expect a possibility to list folders under a given "parent" folder, e.g. by passing the parent folder id via the header.

**Comment by mcjaeger** [comment]
it is lositing all forlders visible with their parent relation, I do not think it is limited to the folders being direct child of the root folder.

**Comment by deveaud-m** [comment]
as far as I could test it (I can access version 3.6.0), I only get the first level of subfolders from this endpoint, not a recursive list of all accessible folders

when using the endpoint `.../folders/{id}` I only get the details about the folder but not the children, it could be another option to access the list of subfolders

**Comment by deveaud-m** [comment]
Tested again, it works as expected. Sorry for the noise.
