### ISSUE TITLE
Add more metadata to candidate licenses

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1477]
### Description

Add metadata to candidate licenses
* date of creation
* user name created
* user name last modified
* date of last modified

#### Steps followed and expected result

Add this as metadata to get more understand who created these records.

#### Additonal 1

Please rename all UI occurrences to "Candidate Licenses". Sometime it is called "Advice Licenses" which is confusing.

#### Additonal 2

Existing licenses should be inited with fossy (general admin account)

**Comment by shivamgoyal7** [comment]
Hello, @mcjaeger @GMishx I want to take up this task.

**Comment by GMishx** [comment]
Hello @shivamgoyal7 , yes you can work on the issue. Mind if I assign it to you?
