### ISSUE TITLE
Missing information in core-schema.dat

### ISSUE THREAD

**Issue by andi8086** [fossology/fossology#1483]
### Description

While reverse-engineering fossology to add a new agent, I found the file "core-schema.dat".
Inside it says: "This file is generated by."  - By what??

**Comment by GMishx** [comment]
The file `core-schema.dat` should be generated by https://github.com/fossology/fossology/blob/master/src/cli/schema-export.php and the function defined at https://github.com/fossology/fossology/blob/6de69ee3cfb26a6d6f15e9fe5ff7507170c1e40a/src/lib/php/libschema.php#L919

But I don't remember last time when this script was used. It is manipulated by hand now.

**Comment by andi8086** [comment]
Despite it says don't edit this file :D Then we should remove the warning...

**Comment by sjha2048** [comment]
Hey @GMishx can I work on this one?

**Comment by GMishx** [comment]
Yes, please go ahead.

**Comment by sjha2048** [comment]
Thanks, @GMishx for assigning me this issue, by removing the warning you mean just clearing out the warning or finding that file?
