### ISSUE TITLE
[Help] How to batch process a package's licence?

### ISSUE THREAD

**Issue by LiXiaoming-FNST** [fossology/fossology#1484]
### Description

Hi, FOSSology guys

I have a oss package. And I want to assign the all the files in this package with the same licence(Suppose that these files are all writen by me). 

Solution I:  modify the files one by one.
Solution II: Is my question? Can I just click some icons to cover all the files or the selected files  in one time?  It will save me much time.  

Thank you.

**Comment by GMishx** [comment]
You have following options to choose from:

1. If you want to add decision for all files under a given folder (without any condition), you can choose **Edit** right next to the folder and you'll get this pop-up from where you can add/remove licenses:

    ![snap](https://user-images.githubusercontent.com/18077542/65481376-b4c70e80-deb2-11e9-9aae-d3c7f1323f65.png)

1. You can make use of bulk option. For doing so, you just need to open a single file and you'll get the button called **Bulk Recognition ...**. You have to provide a text which should occur in the file and then you can select the license which should be added or removed.

    As in the example you can see most of the zlib files contains the line **see copyright notice in zlib.h** which is not recognized by nomos and zlib.h contains Zlib license. But you can add this text to the bulk recognition and add Zlib license and schedule the scan. All the files with the text will get a decision on Zlib as license.
    ![snap](https://user-images.githubusercontent.com/18077542/65481471-18513c00-deb3-11e9-994c-ec64fb524688.png)

Hope this will solve you query.

**Comment by LiXiaoming-FNST** [comment]
@GMishx  Thanks .  It surely do much help to me.

**Comment by LiXiaoming-FNST** [comment]
@GMishx 's reply resolve my issue, so I need to close it.

**Comment by NicolasToussaint** [comment]
Maybe we should consider adding this nice explanation to the FAQ ?
