### ISSUE TITLE
Irrelevant documentation

### ISSUE THREAD

**Issue by andi8086** [fossology/fossology#1485]
Throughout the whole code, subversion is referenced as cvs. Don't we use git as default?

**Comment by NicolasToussaint** [comment]
Actually, I made the (tiny) modification to select GIT by default when uploading a package via CVS.
I meant to propose that as a PR ; I can do that quick if people think it's a good idea.

And also, of course, the documentation should be changed ;-)

**Comment by andi8086** [comment]
@prondubuisi Thank you. But I think the man who changed the code knows best what to change in the docs.
@NicolasToussaint Thanks. I just wondered. I think if this is not a big deal it would be better.

**Comment by NicolasToussaint** [comment]
Sure, I can prepare a PR for that.
As for the documentation, that doesn't mean I'm the best person to update it ;-)
@andi8086 can you please point to the places that need to be changed ? Is that in the Wiki or in the source code ?

**Comment by andi8086** [comment]
source code,

grep -svn\ 

for example

nomos/agent/transition.notes:version of the nomos agent checked into FOSSology's svn archive on 

What is FOSSology's svn archive, made me wonder.

**Comment by NicolasToussaint** [comment]
I think the example you give dates back to when the source code was moved from the SourceForge SVN repository, in May 2011: https://github.com/fossology/fossology/commit/54bcb13fcc43dec37599681aab6b4ab50c56b24f

Grepping for SVN shows indeed a few places where Git should be mentioned along SVN, and CVS removed.

An example here: https://github.com/fossology/fossology/blob/e56f51b6f5b81a1f55195d316d176a8d1a3d539c/src/cli/cp2foss.php#L82
