### ISSUE TITLE
Add functional tests for User Permissions

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#149]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2787, http://www.fossology.org/issues/2787
Original Date: 2012/06/15
Original Assignee: Dong Ma

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
