### ISSUE TITLE
Why is the host encoded in the JwtToken?

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#1512]
The corresponding code is:
https://github.com/fossology/fossology/blob/23a2687cf81f565ec76a225dab5090afe261c657/src/www/ui/api/Controllers/AuthController.php#L124-L126
and
https://github.com/fossology/fossology/blob/23a2687cf81f565ec76a225dab5090afe261c657/src/www/ui/api/Helper/AuthHelper.php#L211-L222

# My Problem
In my Setup I have fossology running via docker compose and some client running in another container. And I want to setup a connection between these two. If I go to FOSSology on `localhost` as usual, I can only generate a token which can not be used by the client. This token is only valid for clients, which access a fossology on localhost.

To generate a working token, I have to go to `172.17.0.2:8081/repo/...` and generate a token, since `172.17.0.2` is the IP used by my client to connect to FOSSology.

## But the problem gets more annoying: 
The IP space `172.17.0.*` might be used by another setup, and docker might choose to setup everything on `172.18.0.*` and the token is now invalid again.

# My Question:

- What is the reason for having the hostname in the token?

It might be good to add a help message to the application, which explains that.

**Comment by GMishx** [comment]
Hostname is added to prevent token forgery as this information will affect the checksum of the token and it will help in finding for which the token was generated.

Also, the host from where you get the token should be the same from where you use the REST end points as a sever should have only one entry point.

If the situation is complex, it will be easy to use the `/token` endpoint to generate the token from server where the token is intended to be used later on.

**Comment by maxhbr** [comment]
But to prevent forgery you would change the private key, with which it is signed? Adding the hostname does not make the token more secure in my opinion.
