### ISSUE TITLE
can't build example_wc_agent

### ISSUE THREAD

**Issue by chanrai** [fossology/fossology#1520]
### Description

I can't build example_wc_agent with make command.

#### Steps followed and expected result

```
make wc_agent
gcc wc_agent.c -I/usr/include/postgresql -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../..//src/lib/c -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -lfossology -L../../..//src/lib/c -lglib-2.0 -lpq  -o wc_agent
wc_agent.c: In function ‘main’:
wc_agent.c:202:3: error: too few arguments to function ‘fo_scheduler_connect’
   fo_scheduler_connect(&argc, argv);
```

What arguments are required?

thanks

**Comment by GMishx** [comment]
As you can see at the function definition, it requires PostgreSQL connection object as the third parameter.
https://github.com/fossology/fossology/blob/7c6c20a1970a392281ce708a30fac7c4307c0991/src/lib/c/libfossscheduler.c#L331

You can get the object from here
https://github.com/fossology/fossology/blob/7c6c20a1970a392281ce708a30fac7c4307c0991/src/example_wc_agent/agent/wc_agent.c#L222-L228

And move it before calling `fo_scheduler_connect()`.

**Comment by chanrai** [comment]
Thank you for your reply. I understand.
