### ISSUE TITLE
Add unit tests for libfossscheduler

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#153]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2811, http://www.fossology.org/issues/2811
Original Date: 2012/06/15
Original Assignee: Mary Laser

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/08/15 20:56:53 +0000

---

There are tests written for libfossscheduler that currently do not work. Don't know how much extra work is needed to get them working again.

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
