### ISSUE TITLE
Add functional tests for sqlCopy

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#156]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2835, http://www.fossology.org/issues/2835
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
