### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1561]
API documentation does not contains the case 'Upload a package' described at https://www.fossology.org/get-started/basic-rest-api-calls/ 

#### How to reproduce

Paste 
https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml to http://editor.swagger.io/

### Versions

* Last commit id on master:

**Comment by GMishx** [comment]
Hello,

I can see all the endpoints mentioned by https://www.fossology.org/get-started/basic-rest-api-calls/ in https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml.

Can you please describe more what is the difficulty you are facing?

**Comment by jb68** [comment]
Yes, you are right endpoint is upload, method is POST , and it uploads a form having a file
On the  https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml.
/uploads:
-----------  
  post:
      tags:
        - Upload
      summary: Post new upload to FOSSology
      description: |
        Endpoint to create a new upload in FOSSology
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VcsUpload'
          multipart/form-data:
            schema:
              type: object
              properties:
                fileInput:
                  type: string
                  format: binary. 

Unfortunately this doesn't translate in anything usable for me on swagger, or might be I am wrong.
Maybe a swagger bug?

**Comment by GMishx** [comment]
Can you please check in the **Upload** tab?
![image](https://user-images.githubusercontent.com/18077542/72874311-b8ab5600-3d17-11ea-8793-a6e1e73b8780.png)

**Comment by jb68** [comment]
Hi Gmishx,
I did that, what I am trying to say is that using swagger is impossible for me to figure out how to upload a file. 
All I get is:
`{
  "vcsType": "svn",
  "vcsUrl": "string",
  "vcsName": "string",
  "vcsUsername": "string",
  "vcsPassword": "string"
}`

**Comment by GMishx** [comment]
You'll have to change the request type to `multipart/form-data` from `application/json`

![snap](https://user-images.githubusercontent.com/18077542/73444053-d878f480-437d-11ea-9345-062792b8827a.png)

**Comment by jb68** [comment]
Thanks, good point. 
Maybe adding some explanation somewhere visible all the time would make it more easy for people like.
Something like ( File Upload: use request body to multipart/form-data )
