### ISSUE TITLE
REST API: Cover upload from URL

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1562]
### Description

I am migrating our current CI implementation to use REST API. 
Currently we upload a file to fossology using  
`cp2foss -n $PROJECT_NAME -f $PROJECT_PATH -P 1 -q "$agent_list" $ARCHIVE_FILE`
where project path is an url
I have tried to use the API following the example from https://www.fossology.org/get-started/basic-rest-api-calls/

#### Steps followed and expected result
I tried something like this:
```bash
curl -k -s -S -X POST http://localhost:8081/repo/api/v1/uploads \
   -H "folderId: 1" \
   -H 'uploadDescription: created by REST' \
   -H 'public: public' -H 'Content-Type: multipart/form-data' \
   -F 'fileInput="http://mydomain.com/rc3-17-g32cdc05.tar.bz2";type=application/octet-stream' \
   -H "Authorization":"Bearer eyJ0eXAiOiJKV1QiLC..."
```
got error `{"code":400,"message":"Missing vcsUrl\nvcsUrl should be passed.","type":"ERROR"}`

The best I could get was:
`{"code":500,"message":"Missing input\nSend file with parameter fileInput or JSON with VCS parameters.","type":"ERROR"}` using 
```bash
curl -X POST "http://localhost:8081/repo/api/v1/uploads" -H  "accept: application/json" -H  "folderId: 1" -H  "uploadDescription: Some test" \
-H  "public: public" -H  "ignoreScm: false" -H  "groupId: 3" -H  "Content-Type: application/json" \
-H "Authorization":"Bearer eyJ0eXAiOiJKV...o" \
-F "Url:http://mydomain.com/rc3-17-g32cdc05.tar.bz2;type=application/text" \
```

**Comment by GMishx** [comment]
Thank you @jb68 for the suggestion.

However, I would prefer following input format:
```bash
curl -X POST "http://localhost/repo/api/v1/uploads" \
  -H  "folderId: 1" \
  -H  "uploadDescription: created by REST" \
  -H  "public: public" \
  -H  "Content-Type: application/json" \
  -d "{\"Url\":\"http://mydomain.com/rc3-17-g32cdc05.tar.bz2\",\"Name\":\"Upload from FTP\",\"Accept\":\"some-pattern\",\"Reject\":\"some-pattern\",\"Max-recursion-depth\":3}"
```

It will help in providing more data as done by **Upload from URL** page in FOSSology.

**Comment by jb68** [comment]
Hi,
I don't mind the format.. but yes, I would prefer a json

**Comment by bharathkumar522** [comment]
Hi GMishx,
    curl -k -s -S -X POST http://localhost/repo/api/v1/uploads \
   -H "folderId: 8" \
   -H 'uploadDescription: created by REST' \
   -H 'public: public' -H 'Content-Type: multipart/form-data' \
   -F 'fileInput=@"/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz";type=application/octet-stream' \
   -H "Authorization: Bearer eyJ0eXAiOi..." 

The above code works perfectly. 
**when I tried to upload the data through rest API, I am getting a file not found an error. Please let me know where i am missing.**
Note:.tar.gz file is available in the location

![image](https://user-images.githubusercontent.com/5959431/86100282-431d9000-bad6-11ea-9071-6f78602ec741.png)

**Comment by NicolasToussaint** [comment]
Hi @bharathkumar522 ,

You seem to have quote problem here.
The filename taken into account here is: `"/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz";type`

You could try
- `-F "fileInput=@/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz;type=application/octet-stream"`
- `-F "fileInput=@\"/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz\";type=application/octet-stream"`

**Comment by bharathkumar522** [comment]
Hi @NicolasToussaint ,
          I tried both the ways you mentioned it doesn't work.

          I am getting an API error with python code.
          1. I converted the curl command with online tool(**https://onlinedevtools.in/curl**)
o/p  of the online tool is:

import requests
headers = {
    'folderId': '8',
    'uploadDescription': 'created by REST',
    'public': 'public',
    'Content-Type': 'multipart/form-data',
    'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTYwNDczOTksIm5iZiI6MTU5MzM2OTAwMCwianRpIjoiTWk0eiIsInNjb3BlIjoid3JpdGUifQ.Z9I6eBFIqRVYomOmHRJOU8PW5Inn39JF1VAGoqgemTI',
}

files = {
    'fileInput': ('"/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz";type', open('"/home/bharath/Documents/Software/zlib-1.2.0.9.tar.gz";type', 'rb')),
}

response = requests.post('http://172.17.0.1/repo/api/v1/uploads', headers=headers, files=files, verify=False)
print(response.content)

**Comment by deveaud-m** [comment]
@bharathkumar522 the `files` parameter should look like this:
```
 files = {"fileInput": open("filepath", "rb")}
```

See also the `requests` documentation: https://requests.readthedocs.io/en/master/user/quickstart/#post-a-multipart-encoded-file.

As an alternative you can also use the `fossology-python` wrapper: https://pypi.org/project/fossology/, it abstracts all the API calls for you!

**Comment by bharathkumar522** [comment]
Thanks @deveaud-m.

Fossy wrapper simplified my work.

**Comment by bharathkumar522** [comment]
HI @NicolasToussaint @deveaud-m, 
            Is there any API available to get only copyrights, License found instead of report.

**Comment by GMishx** [comment]
Hello @bharathkumar522 

You can export copyrights from the UI as of now. Just open the package, check the **Export List** option from the yellow bar, then head on to **Copyright List**.

There is an issue open #1716 to get this list from REST API as well.

**Comment by deveaud-m** [comment]
Regarding the licenses, they can be accessed via the API using `GET /api/v1/uploads/{id}/licenses`

See also the method [`upload_licenses` in fossology-python](https://fossology.github.io/fossology-python/uploads.html#fossology.uploads.Uploads.upload_licenses)

**Comment by bharathkumar522** [comment]
Hi @GMishx, @deveaud-m,
           Please give your comments below.
            1. Through Rest API I successfully uploaded the .tar file to a folder.
            2. Triggered an Analysis job and getting the below error.
![image](https://user-images.githubusercontent.com/5959431/86330537-6fb3e200-bc65-11ea-98b5-d349fb8bbf92.png)
3. Upload id is also available please let me know how to give write access to the folder.
Note: API token I gave read/write access

**Comment by GMishx** [comment]
Hello @bharathkumar522,

Please check the issue https://github.com/fossology/fossology/issues/1751

Maybe you are not waiting for the upload to finish. You can try using the `wait` and `timeout` parameters for `schedule_jobs()` https://fossology.github.io/fossology-python/jobs.html#fossology.jobs.Jobs.schedule_jobs

**Comment by bharathkumar522** [comment]
> Regarding the licenses, they can be accessed via the API using `GET /api/v1/uploads/{id}/licenses`
> 
> See also the method [`upload_licenses` in fossology-python](https://fossology.github.io/fossology-python/uploads.html#fossology.uploads.Uploads.upload_licenses)

Hi @deveaud-m,
         I tried the approach which you suggested and I am getting o/p as none. I checked with different scanner agents but output is empty.

--> LicenseAgent= foss.upload_licenses(foss.detail_upload(61),LicenseAgent.OJO,False)
print(LicenseAgent)


![image](https://user-images.githubusercontent.com/5959431/86451550-b292ba00-bd38-11ea-9d52-5abd308c43d9.png)

**Comment by deveaud-m** [comment]
Thanks for the feedback.

I didn't test the API call with all license agents... what do you get when using cURL:

* ``` /api/v1/uploads/{id}/licenses?agent=ojo```
* ``` /api/v1/uploads/{id}/licenses?agent=nomos```
* ``` /api/v1/uploads/{id}/licenses?agent=monk```
* ``` /api/v1/uploads/{id}/licenses?agent=ninka```

**Comment by bharathkumar522** [comment]
> Thanks for the feedback.
> 
> I didn't test the API call with all license agents... what do you get when using cURL:
> 
> * ` /api/v1/uploads/{id}/licenses?agent=ojo`
> * ` /api/v1/uploads/{id}/licenses?agent=nomos`
> * ` /api/v1/uploads/{id}/licenses?agent=monk`
> * ` /api/v1/uploads/{id}/licenses?agent=ninka`

I am getting the below error:
curl -k -s -S -X GET "http://172.17.0.1/repo/api/v1/uploads/61/licenses?agent=nomos" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTM4ODczOTksIm5iZiI6MTU5MzcxNDYwMCwianRpIjoiTkRJdU13PT0iLCJzY29wZSI6IndyaXRlIn0.CAaFUK2hlM5_WWkkRkt6xkywvAEkf3JbZ_a6F7RbLP0"


![image](https://user-images.githubusercontent.com/5959431/86457723-bbd45480-bd41-11ea-9e21-4e9b1499c1fd.png)

**Comment by bharathkumar522** [comment]
even I tried an alternate approach.
**Step 1:** I pushed the document through the rest API.

FOSS_URL = "http://172.17.0.1/repo"
FOSS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTM4ODczOTksIm5iZiI6MTU5MzcxNDYwMCwianRpIjoiTkRJdU13PT0iLCJzY29wZSI6IndyaXRlIn0.CAaFUK2hlM5_WWkkRkt6xkywvAEkf3JbZ_a6F7RbLP0"
username = "fossy"
foss = Fossology(FOSS_URL, FOSS_TOKEN, username)

**Step 2:**  Upload a folder
e = foss.upload_file(
        foss.detail_folder(8),
        file="/home/bharath/Documents/Software/zlib-1.2.0.12.tar.gz",
        description="My product package",
        access_level=AccessLevel.PUBLIC,
    )
Note:
Checking the upload id : 
f= foss.list_uploads()
for x in range(len(f)):
    print("upload details:{}".format(f[x]))

**Step 3:**
 ##H = foss.upload_licenses(foss.detail_upload(61),LicenseAgent.OJO,False)
H = foss.upload_licenses(foss.detail_folder(8),LicenseAgent.OJO,False)
print(H)

o/p:
![image](https://user-images.githubusercontent.com/5959431/86459247-25556280-bd44-11ea-800e-aed890825ce1.png)

**Comment by deveaud-m** [comment]
You need to make sure license scan jobs have been scheduled for your upload before getting the resulting licenses.

By default only the `unpack` agent is started if you didn't configure any other job by default. This can be done via the UI or via the REST API, see this code for example: https://github.com/fossology/fossology-python/blob/master/tests/test_base.py#L55

I think we should move this discussion to this project: https://github.com/fossology/fossology-python.
I created an issue to document a typical scan workflow using the Python library, it should help new users familiarize with the way Fossology scan work: https://github.com/fossology/fossology-python/issues/29

**Comment by bharathkumar522** [comment]
Hi @GMishx, @deveaud-m,
            I installed fossology in Linux VM and it got suddenly crashed so I installed everything freshly from source code and the observations are:
            1. I am seeing only one scanner and screenshot attached below.
             2. I use to communicate fossology through rest API(pip install fossology) but today class function names are changed and I updated the code on the basis of this URL last (https://fossology.github.io/fossology-python/fossology.html)
             ex: from fossology import Fossology
                   foss = Fossology(FOSS_URL, FOSS_TOKEN, username)
                   a = foss.get_version()
Please let me know is there any way the two issues
![image](https://user-images.githubusercontent.com/5959431/91286595-3d79b900-e7ac-11ea-9a74-81831ba94081.png)
