### ISSUE TITLE
duplicate file conflict under /src/nomos/agent_tests/testdata/NomosTestfiles/MPL

### ISSUE THREAD

**Issue by bogdanionitabp** [fossology/fossology#1567]
### Description

Under the specified path (/src/nomos/agent_tests/testdata/NomosTestfiles/MPL) there are two files with the same name (only differing in letter casing). This is fine on unix-like systems, but produces a conflict on windows systems, where file names are not case sensitive - thus only one of the two files can exist at any given time.

Please remove one of the duplicates or rename it.

#### How to reproduce

on a windows machine:
```
$ git clone
$ git status

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/nomos/agent_tests/testdata/NomosTestfiles/MPL/License.txt

```

Checking out the file will replace it with the other variant and then back again, the conflict cannot be resolved solely on the client.

### Versions

* Last commit id on master: 4c5b760edc55cc673fd2113518905fbddc351ae8
* Operating System (lsb_release -a): Ms Windows 10

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by ag4ums** [comment]
Ok, but both the files have different text. may be renaming one will solve the issue.
Are you using windows/wsl as your dev env?
