### ISSUE TITLE
Asynchronous scan status event

### ISSUE THREAD

**Issue by suppadeliux** [fossology/fossology#1579]
Hello,

I am testing all the fossology API calls, and it works pretty good. Now I am confronted to another trouble with the status of the jobs.

Until now, after scheluding an analysis with the POST _/jobs_ API call, I had to do a GET _/upload/{id}_  call every time I needed to get the status.

I know a scan may take some time, but is there a way to retrieve the status from the scan job, **with an event** for exemple?

Do I need to use a library to enable scriptable control of a FOSSology API like https://github.com/fossology/fossdriver?

Will this be available in the future?

Thank you for yours answers.

**Comment by NicolasToussaint** [comment]
Hi @suppadeliux ,

I don't think there are events to get notified that a jobs has terminated yet ;

Concerning the use of Fossology REST API, there are also REST Clients, depending on what you're trying to achieve:
- A [Shell script REST Client](https://github.com/fossology/FOSSology.REST.shell) that triggers a scan
- And a [.Net REST client](https://github.com/fossology/FOSSology.REST.dotnet)
- I think there are others, not in the Fossology space (yet?)

**Comment by ag4ums** [comment]
event no...may be email if you configure
over rest you can use the eta to get the job status again.

**Comment by GMishx** [comment]
You can look into [api/v1/jobs/{id}](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml#L512). It will return the ETA and status (Completed, Failed, etc.) of the job.

**Comment by GMishx** [comment]
Adding to @NicolasToussaint's list, there is a [python REST library](https://github.com/fossology/fossology-python) available too.

**Comment by NicolasToussaint** [comment]
Thanks @GMishx, I missed it - maybe the project should be named `FOSSology.REST.python` ?

**Comment by GMishx** [comment]
> Maybe the project should be named `FOSSology.REST.python` ?

\cc @deveaud-m You will be the right person to respond.

I also found another library written in python on PyPi called [py-fossology](https://pypi.org/project/py-fossology/)

**Comment by deveaud-m** [comment]
@NicolasToussaint we already discussed the name of the library and decided to stick to `fossology-python` since it better fits the Python "world". 

The package can also be [installed using pip](https://pypi.org/project/fossology/)

**Comment by suppadeliux** [comment]
Thanks to all for the answers, I have already read some info about the phyton Rest library for fossology, but since the app I am working in is written in Go, I started to look for something else.

**Comment by GMishx** [comment]
Since there are no further conversations, closing the ticket for now. Please reopen if needed.
