### ISSUE TITLE
Add functional tests for repcopyin

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#158]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2847, http://www.fossology.org/issues/2847
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
