### ISSUE TITLE
Ideas for GSoC 2020

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1587]
### **(transferred to https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals-2020)**

We are planning to apply for GSoC 2020 as an organization this year as well.

Opening this issue to gather ideas form community which we can propose in this year's application.

@everyone please feel free to comment.

Edit1:
**Note:** If you are looking to contribute to FOSSology, we have label called [ready for newbies](https://github.com/fossology/fossology/issues?q=is%3Aissue+is%3Aopen+label%3A%22ready+for+newbies%22) which can help you get started.

**Comment by ag4ums** [comment]
Hello @GMishx , thank you for posting this : my suggestions are 
* compatibility agent : check incompatible license/s in a upload, 
* snippet scanner : create a snippet scanner based on small offline data. (experimental)
* dashboard: well organized dashboard with upload statistics 
     - filter upload during a time-period (may be using a external tool like Prometheus/Gafana ) 
     - max-min upload using group 
     - repeated upload/file
     - reused upload..... etc etc
*

**Comment by NicolasToussaint** [comment]
> * compatibility agent : check incompatible license/s in a upload,

Yes: a possibility to define "Use Cases", or "Business Context" as worded [here](https://github.com/Open-Source-Compliance/Sharing-creates-value/blob/defining-capability-map/Tooling-Landscape/Unanimous-Understanding/OC-Reference-Tooling-Capabilities-Glossary.md)) - then associate compatible/warning/incompatible licences.

> * dashboard: well organized dashboard with upload statistics 

We have started exporting some data to Graphite/Grafana, from Fossology, we could build on that

* Help determining the origin of binary files using something like Google's "[Search from Image](https://www.google.com/imghp?hl=en)" feature

**Comment by srichinna17** [comment]
I would like to see the following features
* Fossology being part of CI/CD pipeline so that any license violations can be identified early on.
* Incremental file scans (if not already available)

**Comment by mcjaeger** [comment]
@srichinna17 what would be incremental file scans for you?

**Comment by srichinna17** [comment]
Hello Michael,

Incremental Scan,

a. The ability to scan only code snippets that are checked in new or the
libraries that are added new
b. Rather than on-demand, The ability to detect license modifications in
the existing libraries that are part of my package and notify users.

Regards,
Chinnamma

**Comment by mcjaeger** [comment]
@srichinna17 Thank you very much for suggestions. ... hm, but I am not sure about both of the points. Regarding the ability to scan for "code snippets" appears difficult for me, it is maybe not focus of FOSSology and secondly, it is a huge topic and there fore I doubt if there is enough time during the weeks of a google summer of code run. Moreover I am not sure if it is a good approach to catch up on this topic with a person who is new to the topic. In fact, Philippe from nexB has given insights on the topics on one of the last tooling meetings, and it appears to be non-trivial. Note that with Software Heritage integration, recognition of entire files is already possible.

As for the point" The ability to detect license modifications in
the existing libraries" I am not sure if I quite get that. So you are referring for detecting license changes in a library between two versions of a library?

**Comment by NicolasToussaint** [comment]
> As for the point" The ability to detect license modifications in
> the existing libraries" I am not sure if I quite get that. So you are referring for detecting license changes in a library between two versions of a library?

Maybe the ability to find and compare a given upload to its original upstream version, and identify any modifications? If that is the case, not sure it's doable in Fossology (or a lot of work!)

**Comment by GMishx** [comment]
Moved the information collected to wiki: https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals-2020

Thank you everyone for your suggestions.
Keeping the issue open for more ideas and proposals.

**Comment by mcjaeger** [comment]
> > As for the point" The ability to detect license modifications in
> > the existing libraries" I am not sure if I quite get that. So you are referring for detecting license changes in a library between two versions of a library?
> 
> Maybe the ability to find and compare a given upload to its original upstream version, and identify any modifications? If that is the case, not sure it's doable in Fossology (or a lot of work!)

Hi, I think this could be covered by the software heritage plugin ...

**Comment by GMishx** [comment]
The GSoC 2020 was a success. Kudos to @darshank15, @hastagAB and @Kaushl2208 on completing their projects under GSoC program.
And a huge thanks to @NicolasToussaint, @ag4ums, @shaheemazmalmmd, @sandipbhuyan, @amanjain97, @mcjaeger and @GMishx for mentoring the students and giving your time.

PRs from the GSoC 2020 can be found with [GOSC-20](https://github.com/fossology/fossology/pulls?q=is%3Apr+label%3AGSOC-20) label on fossology and [GSOC-20](https://github.com/fossology/atarashi/pulls?q=is%3Apr+label%3AGSOC-20) label on atarashi project.

You can visit the official GSoC-2020 page for FOSSology project to get more information:
https://summerofcode.withgoogle.com/archive/2020/organizations/6163301563629568/#projects
