### ISSUE TITLE
Command: make composer_download is not working on latest source

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1606]
### Documentation update

Please describe your issue in few words here.

#### I was trying to build fossology from source: 
https://github.com/fossology/fossology/wiki/Install-from-Source

Describe the bug and list the steps you used when the issue occurred.

When i ran "make composer_download"
I get
```
make -C ./src composer_download
make[1]: Entering directory '/home/dinesh/osstool/fossology/src'
make[1]: *** No rule to make target 'composer_download'.  Stop.
make[1]: Leaving directory '/home/dinesh/osstool/fossology/src'
Makefile:90: recipe for target 'composer_download' failed
make: *** [composer_download] Error 2
```

### Versions

* Last commit id on master: https://github.com/fossology/fossology/commit/8b3ce9c536612e27216c0c91df20154a05e8a50b
* Operating System (lsb_release -a): Ubuntu 18.04 running in virtual box

**Comment by GMishx** [comment]
Thank you for pointing that out @dineshr93.

The command should have been
```
# ./utils/install_composer.sh
```
I've updated the command in the wiki.

**Comment by dineshr93** [comment]
@GMishx Now its works fine Thanks!
