### ISSUE TITLE
Email notification, SMTP Exchange configuration

### ISSUE THREAD

**Issue by woznik** [fossology/fossology#1607]
Currently in the version 3.7.0 there is no configurations to set up smtp account parameters for exchange server

### Description

up from the version 3.3.0 released in Sep'18 Fossology provides a section to configure SMTP parameters but two SMTP varialbles are merged together: "smtp-login-auth" and "from" 
To work properly with SMTP Exchange server these two variables need to be separated: for "login" and "sender email"
This is still missing in the version 3.7.0
### Screenshot

![image](https://user-images.githubusercontent.com/17202024/74252541-21219d80-4cee-11ea-8fd9-470081b42338.png)

### Actions

As a matter of fact I am able to deliver that change

It requires modification of two files in the src 

`src/lib/php/common-sysconfig.php`
and
`src/scheduler/agent/database.c`

What do you think?

**Comment by GMishx** [comment]
Thank you @woznik for the suggestion.

That sound like good improvement to me!

If you would be working on this, mind if I assign this issue to you?

**Comment by woznik** [comment]
Yes, please. In fact I could ship the changes very soon
