### ISSUE TITLE
Rest API: Get license conclusions for individual files by their hash value.

### ISSUE THREAD

**Issue by mmurto** [fossology/fossology#1611]
### Description

Add an API endpoint to get file level license conclusions by entering their hash values. This would help with integrating Fossology into different workflows.

#### Approaches

As the number of files that one may want to request license conclusions for may be in tens of thousands, the most efficient way would probably be for the API to accept a list of hash values as an input, while providing a similar list with license conclusions of the files added as an output.  

Another approach, maybe more in line with the current API design, would be to accept API calls with individual hash values as input. If the networking costs for individual API calls is significant, this may get somewhat expensive in many use cases.  

Many other approaches could also work here. The desired outcome is to input hash values of files and receive license conclusions for the files, be it as a list or individual values.

**Comment by mmurto** [comment]
Here's a suggestion on how the API could work. As the requests can be quite large, a POST is probably better than a GET. The request body is a list of hash values and the response is the list with concluded licenses added.

If a pure database query is required, we've found the information needed by going through these tables:
- get pfile_pk by matching the supplied SHA256 value with pfile_sha256 in pfile table,
- get clearing_decision_pk values by matching the pfile_pk values with pfile_fk in clearing_decision table,
- get clearing_event_fk by matching the clearing_decision_pk values with clearing_decision_fk in clearing_decision_event table,
- get rf_fk values by matching the clearing_event_fk values with clearing_event_pk in clearing_event table,
- get rf_shortname values by matching the the rf_fk values with rf_pk in license_ref table.

This should return all of the license concluded for the file.

Here an OpenAPI specification for a possible endpoint.

```YAML
  /conclusions/:
    post:
      summary: Get license conclusions for a list of files by their SHA256 hash values

      requestBody:
        description: A list of SHA256 hash values
        required: true
        content:
          application/json:
            schema:
              type: array
              items: 
                type: string
                description: A SHA256 hash value of a source file
                example: 4F9794224BF9FEE747BA6A5DB2F052986DAE4A652865BA3859E95D2EC41F0AA9

      responses:
        '200':
          description: A list of the supplied hash values with license conclusions added
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hash:
                      type: string
                      description: The supplied hash value
                    license:
                      type: string
                      description: MIT identifiers of licenses concluded for the file
                  example:
                    hash: 4F9794224BF9FEE747BA6A5DB2F052986DAE4A652865BA3859E95D2EC41F0AA9
                    license: GPL-2.0+
```

**Comment by mmurto** [comment]
We've built a small mock API to demonstrate how the query could work [here.](https://github.com/doubleopen-project/fossology-hash-api)

**Comment by mcjaeger** [comment]
thanks for coming to this, actually just have seen the message by Martin as well. generally speaking, probably this would be a good place to implement the logic:

https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/UploadController.php
