### ISSUE TITLE
Add functional tests for Common UI modules

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#162]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2871, http://www.fossology.org/issues/2871
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests 

Add tests for the following modules:
1. common-active.php
2. common-agents.php
3. common-cache.php
4. common-buckets.php
5. common-compare.php
6. common-db.php
7. common-job.php
8. common-license-file.php
9. common.php
   1. common-plugin.php
   2. common-repo.php
   3. common-tags.php
   4. bootstrap.php

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
