### ISSUE TITLE
Documentation Error. Make command of composer_install not working

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1624]
### Description

Below make command of [composer ](https://github.com/fossology/fossology/wiki/Install-from-Source#25-install-composer-optional-some-versions-prior-31-rc3) in documentation.

> # make composer_install

is not working. 

### Versions

* Last commit id on master: 6bf816d
* Operating System (lsb_release -a): UBUNTU-16.04

**Comment by ag4ums** [comment]
composer is prerequisite and the command is also in the same section.
for me its working fine.
* first install the composer from `utils/install_composer.sh`
* and then run `sudo make composer_install` ( in ubuntu), it should work

**Comment by dineshr93** [comment]
I was running the above command inside the utils folder. When i ran at root I ran. Is this below output from running the command 

```
make -C ./src composer_install
make[1]: Entering directory '/home/dinesh/src/fossology/src'
current dir: '/home/dinesh/src/fossology/src'
/usr/bin/install -D -m 644 composer.json composer.lock /usr/local/share/fossology
(cd /usr/local/share/fossology; export COMPOSER_HOME=/dev/null; composer install --no-plugins --no-scripts --no-dev)
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Generating autoload files
make[1]: Leaving directory '/home/dinesh/src/fossology/src'
``` 
Nothing to worry about `container-interop` is it? as it is saying it is abandoned.?

**Comment by GMishx** [comment]
`container-interop/container-interop` is dependency of another package `slim/slim` but it is okay and should not cause any issue.
