### ISSUE TITLE
File size is small but ununpack job take so long time

### ISSUE THREAD

**Issue by vn-duhq** [fossology/fossology#1637]
### Description

I uploaded a file that have size is small (~7MB) https://github.com/vn-duhq/fossology-server/blob/master/e2fsprogs-1.43.8-r0-patched.tar.gz to fossology docker server. but when i check task ununpack job in the server this take so long time  (run only one this package)

Check job in fossology database
            _jq_starttime          		             |          jq_endtime  
            2020-02-26_ 10:01:36.366281+00 | 2020-02-27 00:39:23.264347+00_

#### How to reproduce
Upload this file https://github.com/vn-duhq/fossology-server/blob/master/e2fsprogs-1.43.8-r0-patched.tar.gz to fossology server docker 3.6.0

Check job status by query: SELECT * FROM jobqueue;

### Versions
3.6.0

#### Job logs

>..
> Logs generated under Geeky Scan Details (Job history => click on agent's job id)
> e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_extent_int_bad_csum/image.gz.dir/image.dir/[SYS]/Journal"
> 2020-02-27 01:12:25 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Open ERROR: Can not open the file as [Ext] archive"
> 2020-02-27 01:12:25 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERRORS:"
> 2020-02-27 01:12:25 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Headers Error"
> 2020-02-27 01:12:25 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Unexpected end of archive"
> 2020-02-27 01:12:26 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERROR: /srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_extent_int_bad_csum/image.gz.dir/image.dir/a"
> 2020-02-27 01:12:26 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Can not open the file as archive"
> 2020-02-27 01:14:39 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERROR: Unsupported Method : motd"
> 2020-02-27 01:14:39 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "WARNING pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 Unable to extract permission"
> 2020-02-27 01:14:39 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "LOG pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 WARNING: Unable to extract permission from /srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_extent_bad_node/image.gz.dir/image"
> 2020-02-27 01:14:39 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "WARNING pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 File extraction failed"
> 2020-02-27 01:14:39 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "LOG pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 WARNING: Extraction failed (rc=1): icat -f 'linux-ext' '/srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_extent_bad_node/image.gz.dir/image' '12' > '/srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_extent_bad_node/image.gz.dir/image.dir/motd' 2>/dev/null"
> 2020-02-27 01:14:43 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERROR: /srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_ext_zero_len/image.gz.dir/image.dir/issue"
> 2020-02-27 01:14:43 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Can not open the file as archive"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERROR: /srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_ext_journal/journal.gz.dir/journal"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "/srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_ext_journal/journal.gz.dir/journal"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Open ERROR: Can not open the file as [Ext] archive"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "ERRORS:"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Headers Error"
> 2020-02-27 01:14:47 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "Unexpected end of archive"
> 2020-02-27 01:14:48 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "WARNING pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 Unable to extract permission"
> 2020-02-27 01:14:48 ununpack [0] :: JOB[4].ununpack[13073.localhost]: "LOG pfile 4CCD8B65134965ECCF98C589DCE667063EC33946.0F0C73C12ADDC05B3FE4CD330BB4F300.7514424 WARNING: Unable to extract permission from /srv/fossology/repository/3b67cb017bf6/ununpack/167861l/4ccd8b65134965eccf98c589dce667063ec33946.0f0c73c12addc05b3fe4cd330bb4f300.7514424.dir/e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_ext_journal/

**Comment by GMishx** [comment]
From the logs, it appears that the archive is malformed. Can you please try with another archive?

**Comment by NicolasToussaint** [comment]
For info, I tried the file on my instance, I get the same logs ; 
And the file in question untars nicely with "tar xf ..."

**Comment by vn-duhq** [comment]
malformed? i don't think this. I tried with file http://archive.ubuntu.com/ubuntu/pool/main/e/e2fsprogs/e2fsprogs_1.42.13.orig.tar.gz 
and result is same.

**Comment by ag4ums** [comment]
hello @vn-duhq , 
e2fsprogs-1.43.8-r0-patched.tar.gz is a small package in size, but a interesting one, when it unpacks it has around 182,617 files , if I compare the same with a linux kernel package that has around 60K files. (Note : ununpack is a recursive agent unlike tar).

Now from the error  ` ./e2fsprogs-1.43.8-r0-patched.tar.dir/spdx_temp/git/tests/f_* ` folders under test has multiple file-system image files, and though unpack tried to extract the fs , but some of the file-systems are not supported.

Also, I think that docker has a overhead, as it may take additional time to expand the file-system (it took around 33 mins in VM with 4 vcpus and 8gb vram).

**Comment by vn-duhq** [comment]
@ag4ums  thanks for your information
