### ISSUE TITLE
Add functional tests for Common UI modules (Larry)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#164]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2883, http://www.fossology.org/issues/2883
Original Date: 2012/06/15
Original Assignee: larry shi

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

Add tests for the following modules:
1. common-cli.php
2. common-dir.php
3. common-folders.php
4. common-menu.php
5. common-ui.php

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
