### ISSUE TITLE
Is there any backup-restore script for fossology deployed via containers?

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1642]
### Description
By default, all the 3 containers deployed via docker-compose uses volume as defined in [docker-compose.yml](https://github.com/fossology/fossology/blob/94985b93c9f9007bacd27c5f8b7e12dca95d69bf/docker-compose.yml)

1. [repository:/srv/fossology/repository/](https://github.com/fossology/fossology/blob/94985b93c9f9007bacd27c5f8b7e12dca95d69bf/docker-compose.yml#L32)
2. [repository:/srv/fossology/repository/](https://github.com/fossology/fossology/blob/94985b93c9f9007bacd27c5f8b7e12dca95d69bf/docker-compose.yml#L57)
3. [database:/var/lib/postgresql/data](https://github.com/fossology/fossology/blob/94985b93c9f9007bacd27c5f8b7e12dca95d69bf/docker-compose.yml#L67)

I can see there are commands to do [backup & restore volumes](https://docs.docker.com/storage/volumes/#backup-restore-or-migrate-data-volumes) 

Is there any script already written for backing up container volumes?

**Comment by GMishx** [comment]
Hello @dineshr93,

There are backup scripts for FOSSology server in general: https://github.com/fossology/fossology/tree/master/utils/backup

They can backup your DB and srv repository from one server to another over SSH. But there is nothing in particular for Docker.

**Comment by NicolasToussaint** [comment]
Hi @dineshr93 ,

I have written scripts to deploy Fossology with Docker, and automatically configure what I needed.
In particular, I have backup and restore script that do just what you need :)

I will share them asap on GitHub (should have done it earlier, really)

**Comment by dineshr93** [comment]
@NicolasToussaint:  Thanks. I will wait for your upload then

**Comment by NicolasToussaint** [comment]
Hi @dineshr93 ,

Here are the scripts: https://github.com/Orange-OpenSource/Fossology-Docker-Deploy-Scripts

It's actually a whole bunch of script files, and their configuration files.

What you are looking for is:
- Backup script: [docker-backup.sh](https://github.com/Orange-OpenSource/Fossology-Docker-Deploy-Scripts/blob/master/docker-backup.sh)
- Restore script: [docker-backup-restore.sh](https://github.com/Orange-OpenSource/Fossology-Docker-Deploy-Scripts/blob/master/docker-backup-restore.sh)
- Configuration example: [docker_backup.conf.example](https://github.com/Orange-OpenSource/Fossology-Docker-Deploy-Scripts/blob/master/conf/docker_backup.conf.example)

You can configure to keep a certain number of backup files, and trash older ones.
