### ISSUE TITLE
Add unit tests for Common UI Modules (Alex)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#165]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2889, http://www.fossology.org/issues/2889
Original Date: 2012/06/15
Original Assignee: Mary Laser

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

Add tests for the following modules:
1. common-scheduler.php
2. common-sysconfig.php

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
