### ISSUE TITLE
Restrict characters set in Token so they can be masked in GitLab-CI

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#1653]
# Description
Generated REST API token contains characters that make them incompatible with the ["masked variables" feature](https://gitlab.forge.orange-labs.fr/help/ci/variables/README#masked-variables) in GitLab.
> The value must be in a single line.
> The value must only consist of characters from the Base64 alphabet (RFC4648).
> In GitLab 12.2 and newer, @ and : are also valid values.
> The value must be at least 8 characters long.

This feature replaces the occurrences of the contents variables with `xxx` characters.

#### Steps followed and expected result

An extra option could limit the character set to the Base64 alphabet.

#### Screenshots

![image](https://user-images.githubusercontent.com/22956329/76207900-ecc2d380-61fe-11ea-8416-13abd9b2978d.png)

**Comment by mcjaeger** [comment]
hm, but I would assume that JWT, since it is used in http headers would be Ok to this regard, but what is the character which causing the problem here in your example?

**Comment by mcjaeger** [comment]
dot is not there: https://en.wikipedia.org/wiki/Base64

**Comment by GMishx** [comment]
JWT uses dot to separate header, body and signature. There can be two ways to overcome this:

1. Create 3 different variables in GitLab and combine them using dot whenever required in the CI.
2. Base64 encode the resulting JWT token in FOSSology and decode it when authenticating.

**Comment by NicolasToussaint** [comment]
Indeed, in my example, the dots were the problem.
Thanks for the suggestions:

>     1. Create 3 different variables in GitLab and combine them using dot whenever required in the CI.

The # 1 goal of GitLab integration is to make things simpler for the developers, requiring the users to split and enter 3 different values would be walking against the wind :-/
 
>     2. Base64 encode the resulting JWT token in FOSSology and decode it when authenticating.

That would work !

Would that mean:
1. Fossology provides both token formats (raw and Base64 encoded) 
1. and accept them indifferently ?

**Comment by GMishx** [comment]
> Indeed, in my example, the dots were the problem.
> Thanks for the suggestions:
> > ```
> > 1. Create 3 different variables in GitLab and combine them using dot whenever required in the CI.
> > ```
> 
> The # 1 goal of GitLab integration is to make things simpler for the developers, requiring the users to split and enter 3 different values would be walking against the wind :-/

Agree with you on that. But it's a dirty fix to keep the things running :-P

> > ```
> > 2. Base64 encode the resulting JWT token in FOSSology and decode it when authenticating.
> > ```
> 
> That would work !
> 
> Would that mean:
> 
>     1. Fossology provides both token formats (raw and Base64 encoded)

I am not sure if we should provide different token formats. It should either be raw or Base64. What's your idea on it?

**Comment by NicolasToussaint** [comment]
>  Create 3 different variables in GitLab and combine them using dot whenever required in the CI.

Another possibility could be manually replacing the `.` with `:` or `@`, and reverse it in the REST client that execute the REST queries.

Fossology could also generate the tokens directly with `:` or `@`, characters.
The separator could even be made configurable.

> I am not sure if we should provide different token formats. It should either be raw or Base64. What's your idea on it?

I was initially thinking that we could show both formats (two distinct lines, or with a radio button or drop down list)
But now I think about it, I like the idea above better (less confusing, less work)

**Comment by NicolasToussaint** [comment]
Well it looks like the problem healed itself... the `.` has been added to the list of supported characters for masked variables.

See: https://gitlab.com/gitlab-org/gitlab/-/issues/37469

(although [the doc](https://gitlab.forge.orange-labs.fr/help/ci/variables/README#mask-a-custom-variable) is not up-to-date yet)
