### ISSUE TITLE
Ability to Delete the uploaded file in Browse section.

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1657]
### Description

Ability to delete the uploaded file in Browse section would be good feature

#### Screenshots

![image](https://user-images.githubusercontent.com/4498415/76328475-56cb9d80-6311-11ea-968f-4a13c3b8d6e4.png)

**Comment by mcjaeger** [comment]
indeed, OTHO, deleting an upload is a heavy thing (because some analysis work might be lost)

**Comment by MrMichaelJKelly** [comment]
We use Fossology for separate projects - so when a project is done, it's done and want to be able to remove it.  Right now we can only delete at the entire Software Repository folder which seems wrong.  I'd like to be able to delete an old project (including the analysis work).

**Comment by GMishx** [comment]
Hey @MrMichaelJKelly , you do not need to delete entire folder. You can goto "Organize > Uploads > Delete Uploaded File" and select the uploads you wish to remove.
You can also use the REST API to do the same.

You can also create separate folder for each project and create a heirarchy out of them in FOSSology.

The issue here is to have an option to delete the uploads from Browse page itself.

**Comment by teekhandekar** [comment]
Can I work on this ?

**Comment by teekhandekar** [comment]
@GMishx  can I work on this ?

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by simran142002** [comment]
Hello is this issue still available? Can I work on this?

**Comment by MrMichaelJKelly** [comment]
I'm not sure.. Let me take a look

**Comment by simran142002** [comment]
Yeah please let me know if its available. Thank you very much

**Comment by shaheemazmalmmd** [comment]
@simran142002 : The issue is still available for work.

**Comment by simran142002** [comment]
Thank you for your response sir! I am working on it.

**Comment by shaheemazmalmmd** [comment]
Feature...Now available with FOSSology.
