### ISSUE TITLE
Add functional tests for Common UI modules (Alex)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#166]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2895, http://www.fossology.org/issues/2895
Original Date: 2012/06/15
Original Assignee: Mary Laser

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

Add tests for the following modules:
1. common-scheduler.php
2. common-sysconfig.php

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
