### ISSUE TITLE
Copyright information in ReadMeOss Report is replacing &lt; and &gt; instead of symbols '<' and '>' respectively

### ISSUE THREAD

**Issue by lakshmibhavani1** [fossology/fossology#1660]
### Description
Copyright information in ReadMeOss Report is replacing &lt; and &gt; instead of symbols '<' and '>' respectively. SPDX RDF report has no such problem.

#### How to reproduce

1.Upload a project in fossology which has copyrights containing '<' and '>'.
2. Generate read_me_oss report for that project.
3 In the report check the same copyright where '<' and '>' was present which is replaced by &lt and &gt respectively.

**Comment by mcjaeger** [comment]
@lakshmibhavani1 thanks for letting us know. But I am not sure, could you pls elaborate what you would like to see here? like just the brackets without html escaping?

**Comment by lakshmibhavani1** [comment]
@mcjaeger I would like to see the same brackets < and > instead of the symbols  &lt and &gt respectively in the report.
