### ISSUE TITLE
Add functional tests for Common UI modules (Vincent)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#168]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2907, http://www.fossology.org/issues/2907
Original Date: 2012/06/15
Original Assignee: Dong Ma

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

Add tests for the following modules:
1. common-auth.php
2. common-parm.php
3. common-perms.php
4. common-pkg.php
5. libschema.php

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
