### ISSUE TITLE
Generated upload_id name is wrong after uploads deletion

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1684]
I have a lot of jobs that remains stuck in the system but they are not show on scheduler queue

```
curl -k -s -X GET http://${FOSSOLOGY_SERVER}/repo/api/v1/jobs?upload=1370    \
  -H "Authorization: ${FOSSOLOGY_TOKEN}"   \
  -H "accept: application/json" | jq
[
  {
    "id": 10904,
    "name": "wget",
    "queueDate": "2020-03-26 15:33:04.726304+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 11162,
    "name": "Delete",
    "queueDate": "2020-03-29 07:08:01.615635+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 11766,
    "name": "Delete",
    "queueDate": "2020-04-05 07:07:18.154656+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12194,
    "name": "Delete",
    "queueDate": "2020-04-09 22:22:24.766278+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12221,
    "name": "Delete",
    "queueDate": "2020-04-09 22:42:05.837449+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12478,
    "name": "Delete",
    "queueDate": "2020-04-13 17:01:22.007652+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12522,
    "name": "Delete",
    "queueDate": "2020-04-13 23:51:35.632504+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12562,
    "name": "Delete",
    "queueDate": "2020-04-14 15:45:57.915125+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12580,
    "name": "Delete",
    "queueDate": "2020-04-14 16:10:08.860434+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12598,
    "name": "Delete",
    "queueDate": "2020-04-14 18:06:56.265448+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  },
  {
    "id": 12616,
    "name": "Delete",
    "queueDate": "2020-04-14 22:06:42.708373+00",
    "uploadId": "1370",
    "userId": "3",
    "groupId": "3",
    "eta": 0,
    "status": "Queued"
  }
]
```

On the other hand the scheduler thinks there are no jobs to do. Any idea? 

### Versions
3.7

**Comment by GMishx** [comment]
Hello @jb68,
Have you tried navigating to "Admin > Scheduler" and check the status of the jobs? Anything is stuck?

If nothing works, please check the `/var/log/fossology/fossology.log` and try restarting the scheduler.

**Comment by jb68** [comment]
Hi GMish, 
I did all of those, but according to scheduler there is nothing on queue. 

On the other hand I discovered that I have some orphan uploads. By orphan I mean uploads in DB that have an upload_pk but not a co-respondent folder_pk
i run ``` SELECT * FROM upload WHERE NOT EXISTS ( select * from folderlist WHERE upload.upload_pk = folderlist.upload_pk )```
and this returned about 20 enties

Then I went Admin > Maintenance and checked everything. 
This fixed both the orphan issue and the scheduler issue. 
This happened in last 1 month so no idea why.

**Comment by GMishx** [comment]
That is interesting that maintenance solved the issue.
Can you please explain the procedure with which you uploaded the packages and scheduled the job?
Maybe it's a bug in the file upload not in scheduler.

**Comment by jb68** [comment]
File upload is done through docker using: 
`docker exec "$DOCKER_NAME" cp2foss -n $PROJECT_NAME -f $PROJECT_PATH -P 1 $ARCHIVE_FILE > result`

Then:
`upload_pk=$(cat result | awk '/UploadPk is:/ {print $3}' | sed "s|'||g")
folder_pk=$(cat result | awk '/FolderPk is:/ {print $3}' | sed "s|'||g")`

`FOSS_JOB_STATUS=$(curl -k -s -X GET http://${FOSSOLOGY_SERVER}/repo/api/v1/jobs?upload=$upload_pk \
    -H "Authorization: ${FOSSOLOGY_TOKEN}" \
    -H "accept: application/json")
  FOSS_JOB_STATUS=$(echo $FOSS_JOB_STATUS | jq ".[] | select (.name==\"wget\")" | jq -sr .[-1].status)`

After the wget job status is completed:
`  # schedule an analysis
  FOSSOLOGY_RESPONSE=$(curl -k -s -S -X POST http://${FOSSOLOGY_SERVER}/repo/api/v1/jobs \
    -H "folderId: ${folder_pk}" \
    -H "uploadId: ${upload_pk}" \
    -H "Authorization: ${FOSSOLOGY_TOKEN}" \
    -H "Content-Type: application/json" \
      --data "{
          \"analysis\": {
          \"bucket\": true,
          \"copyright_email_author\": true,
          \"ecc\": true,
          \"keyword\": true,
          \"mime\": true,
          \"monk\": true,
          \"nomos\": true,
          \"ojo\": true,
          \"package\": true
        },
        \"decider\": {
          \"nomos_monk\": true,
          \"bulk_reused\": true,
          \"new_scanner\": true,
          \"ojo_decider\": true
        },
        \"reuse\": {
          \"reuse_upload\": $reuse_upload_pk,
          \"reuse_group\": $reuse_group_pk,
          \"reuse_main\": true,
          \"reuse_enhanced\": true
        }
      }"
  )`

**Comment by jb68** [comment]
I was able to reproduce the issue. This happens when I run a script that is suppose to clean and delete some of the builds.. 
The commands is:
`local response=$(curl -s -X DELETE "http://${FOSSOLOGY_SERVER}/repo/api/v1/uploads/$upload_pk" \
            -H  "accept: application/json" \
            -H "Authorization: ${FOSSOLOGY_TOKEN}")`
However this does add a job on the job queue for a few seconds and then disappear. Looks more like a bug in the api/v1 because I am seeing this after moving to api.

**Comment by GMishx** [comment]
Thank you sharing the steps @jb68 .

I will try to replicate it and get back to you.

**Comment by jb68** [comment]
At this moment my fossology instance became not usable. 
Any new upload get an upload ID that was used before so that's why I get this error. It doesn't matter if I use cp2foss or the web interface the result is the same, upload_id is wrong. 

I also was wrong,  maintenance did not solved the issue.
 
Here is the example for upload 1471 first time generated 23 Apr, then reused on 24 and now again on 28.
![foss1](https://user-images.githubusercontent.com/15733222/80515067-3ba30480-8936-11ea-910d-59c32e622178.png)
I think the initial bug name is wrong so I changed to: generated upload_id name is wrong after uploads deletion.

**Comment by GMishx** [comment]
Seems like the idea to keep the upload jobs but deleting the upload itself was wrong. We should not delete the entry from `upload` table, just deactivate it or should delete the jobs associated to the upload as well.
