### ISSUE TITLE
Export list of files with copyright statement but without license statement.   

### ISSUE THREAD

**Issue by deepaudupi** [fossology/fossology#1687]
### Description

It will be very helpful if fossology tool provides option to export without license files path 

#### Screenshots

![IMG_20200417_122807](https://user-images.githubusercontent.com/46257268/79562462-c418de00-80c8-11ea-9a62-ee865ff8994a.jpg)

**Comment by GMishx** [comment]
Have you checkout following REST API endpoints?

https://github.com/fossology/fossology/blob/d9464a91d411c24038c7600c4adad926ca4e0d5c/src/www/ui/api/documentation/openapi.yaml#L363

https://github.com/fossology/fossology/blob/d9464a91d411c24038c7600c4adad926ca4e0d5c/src/www/ui/api/documentation/openapi.yaml#L326

**Comment by deepaudupi** [comment]
Hi GMishx,
I mentioned title as very confusing. Sorry for that. 
Below is the brief description about my requirement. 

My Requirement is to export list of files which is not having license statement (file which is having pure copyright statement without having license statements). 
Whatever file I uploaded in fossology which consist of both copyrighted files(pure copyrights) and opensource files(copyrights with license (eg GNU, GPL)). 
By using "show files without licences" filter I can get all copyrights file path in UI. I want it in excel sheet. 
 I tried to export unified report but which is including both the file list. 
Please help to know is there any way to export only pure copyright statement file path list. 
I attached screenshots for your reference.
![IMG_20200417_122539](https://user-images.githubusercontent.com/46257268/79585652-b9bd0b00-80ed-11ea-8332-ca51ff0a3f44.jpg)
![IMG_20200417_122554_1](https://user-images.githubusercontent.com/46257268/79585659-bcb7fb80-80ed-11ea-827c-e28afe5efa22.jpg)

![IMG_20200417_123002](https://user-images.githubusercontent.com/46257268/79585668-c04b8280-80ed-11ea-9361-f89a7ee6193a.jpg)

![IMG_20200417_122807](https://user-images.githubusercontent.com/46257268/79585863-056fb480-80ee-11ea-9b04-859890812a47.jpg)

**Comment by GMishx** [comment]
Hello @deepaudupi , thank you for the clarification.

There is no such functionality existing in FOSSology as of now. But you may however use the SPDX reporting format. Unlike Unified report, SPDX does not segregate license listing and Copyright listing in different sections. You can ignore entries with SDPXID (license name).
Till the feature is ready, you can utilize SPDX report but definitely it will be a lengthy process.

![snap](https://user-images.githubusercontent.com/18077542/79727123-8060e700-8309-11ea-93a4-eede3f72d1eb.png)

**Comment by NicolasToussaint** [comment]
Hi @deepaudupi ,

I used this simple Awk script in the past to filter out SPDX-TV entries which had *no LicenseConcluded* **and** *no FileCopyrightText*.
I guess you could adapt it easily for your need.

[clean-spdx-files.awk](https://github.com/fossology/fossology/files/4550232/clean-spdx-files.awk.txt)
