### ISSUE TITLE
Add functional testing/automation for checking system dependencies

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#169]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2913, http://www.fossology.org/issues/2913
Original Date: 2012/06/15
Original Assignee: Dan Stangel

---

Fills in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

Add tests to check for the following dependencies:
1. PostgreSQL
2. Apache httpd
3. Glib
   ...

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
