### ISSUE TITLE
Fossology free-up space

### ISSUE THREAD

**Issue by jb68** [fossology/fossology#1696]
### Description

Our HD space is running out. Deleting some uploads didn't help much, after almost 2 years I ended up with something like this:
```
sudo ls repository/
018a83ac2505  2c2443a1ee51  3d44396e70a6  5a061f540d59	6688653572b5  7cd74a313979  9f0676270272  ac2b59426179	c6881d6dadc7  e6f84221c3c6  f67e27895c39  fd60cba89138
05bb4f287481  2cb9d744c6ea  420fd14a4126  5a66a5526382	6f35b1b0e77c  86dda0b8cdba  a1b58e21d6af  af6f1045b199	cb849393261d  eb74eec06b6c  f6c0e6475bad  localhost
05cd61e442ef  2ed30752f0de  4388f5e2cfe8  5fbfd24218ad	700ac7c9240a  8c7ae7f9e04b  a41692f7721f  b9fc0680dc44	cd501f11eb2c  ed0814edd8e6  f701887a069d  logs
19a9b9d9bedf  3338a3a6791b  46ed39e26d1b  60ccfdf1f061	72da42d7b318  8fbdbd93301a  a740fa008b49  bd1e1689a106	d0f608d5f769  ee3bd2285b96  faa12468b3be  report
28bdef5beb24  33c87b3ba577  4f8c69d516f3  612f1aa23187	74be1bb2c281  9682b3b1cb92  a8586a57d38e  bda9f2e57fda	d408e021ec01  f4885b6e399f  fb787b69549d
29b4996102c1  3c854675f735  5648ed801fad  65f360a33f6b	783e6cfa80d7  9dfb22970556  ac0dcd723121  c5c863f81833	dd8c29ab1fd2  f5433be3eb5b  fd1d9a0eca6a
```

Then under localhost I have:
```
localhost # du -h --max-depth=1
131G	./files
7.8G	./gold
139G	.
```

My questions are:
 - folders like '4f8c69d516f3' are safe to delete? Is it normal to be there? 
 - How about logs? Log rotation is good enough ? 
What is in files and what is in "gold" folders.

**Comment by GMishx** [comment]
Hello @jb68 ,

1. The folders like `4f8c69d516f3` are generated based on hostname. So I am guessing you are using docker setup. They generally hold the uploaded files before `ununpack` moves them to `localhost` (this folder is constant as per your `fossology.conf`) which are then used to load the files for scanning, browsing, etc. There might be some files left over if `ununpack` fails.
    - So yes, you can delete those folders safely.
1. The `logs` folder is use to load the logs from jobs (the ones you see in **Geeky Scan Details** page). PR #1677 will help to remove those files if the upload generated them have been deleted.
1. `files` hold all the uploaded and unpacked files for scanning, browsing, etc.
1. `gold` folder holds the actual uploaded archives for later download.

**Comment by jb68** [comment]
Thanks,
This is really helpful.
