### ISSUE TITLE
Error with the FOSSology id in the "curl" command and with connection to "SW360/Re-Check connection" of Admi/Fossology

### ISSUE THREAD

**Issue by frannicot** [fossology/fossology#1710]
### The description
I have 2 problems: on the one hand to have the FOSSology id with the "curl" command and on the other hand for the connection of SW360 with FOSSology (SW360 / Admi / Fossology).

#### How to reproduce
1. I got the id in the browser URL section to get my Fossology ID because I tried to get, without success:
`sudo curl -k -s -S -X GET "http://localhost/repo/api/v1/folders" -H "my Fossology API token"`
I also tried to replace localhost with my IP address vm = 127.0.0.1 (127.0.0.1) in the online command:
`sudo curl -k -s -S -X GET "http://127.0.0.1:80/repo/api/v1/folders" -H "my Fossology API token"`
It doesn't work either.

I also use the editor of the Swagger project at http://editor.swagger.io/ to get my API token from Fossology. It does not work :
![2020-05-06_12h48_23](https://user-images.githubusercontent.com/32058875/81168869-19ddf900-8f98-11ea-9d52-9793ae634864.png)

2. I did not manage to connect to Fossology with the first button "Re-Check connection" of SW360 / Admi / Fossology from the API token from Fossology and the id (in the browser URL section to get my Fossology ID).

In addition to this issue, please also look at another issue in SW360 to understand the problem of connecting to backend in "Re-Check connection" of Admi / Fossology: https://github.com/eclipse/sw360/issues/843.
The answer to this issue tells me to check with fossology.

#### Screenshot
See the screenshots at https://github.com/eclipse/sw360/issues/843 to explain my problem.

### Versions
Version used: fossology 3.8.0-rc1
Using latest stable release from https://github.com/fossology/fossology/releases/tag/3.8.0-rc1

Installed FOSSology without docker et Vagrant from https://github.com/fossology/fossology/wiki/Install-from-Source

* Last validation ID on the master:
Oracle VM VirtualBox 6.1 on Windows 10
Ubuntu 18.04 in Oracle VM VirtualBox

* Operating system (lsb_release -a):
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

### Newspapers

All logs (if any) generated in

#### FOSSology Logs
Logs generated under /var/log/fossology/fossology.log
[fossology.log](https://github.com/fossology/fossology/files/4586219/fossology.log)

#### Apache Logs
Logs generated under /var/log/apache2/error.log
[error.log](https://github.com/fossology/fossology/files/4586220/error.log)

**Comment by GMishx** [comment]
Hello @frannicot,

Can you please share the output of the `curl`?

**Comment by frannicot** [comment]
Here are the curl outputs with 2 commands:
![2020-05-06_12h58_37](https://user-images.githubusercontent.com/32058875/81169618-6970f480-8f99-11ea-901f-5a36ab25f211.png)

**Comment by GMishx** [comment]
Looks like the host is not available. Can you please try the curl with `--location` flag as the second curl output says it want to redirect you?

**Comment by jeremiah** [comment]
It would be good if there were an 'canonical' example of using curl to get the token. I've seen the API described differently in different places and had similar difficulties using the token fetching API as well. It would also be good if there were a working API to test against - does the demo installation provide this? Just so one knows the API works?

**Comment by dineshr93** [comment]
@GMishx I asked @frannicot to report this issue. I personally had a call & screen shared with him. It seems he has installed both Fossology & SW360 in the same Ubuntu box both were installed via source in a virtualbox in his windows PC. I am not sure if that is causing any problem.

**Comment by frannicot** [comment]
@GMishx Here are the curl output with second command and --location flag:
![image](https://user-images.githubusercontent.com/32058875/81276153-eca25100-9052-11ea-9696-be6ad96e4658.png)
I launched this command twice and I have the same error message.

@dineshr93 I installed Fossology & SW360 on the same Ubuntu VM.
He told me to try to install Fossology and SW360 on 2 separate Ubuntu machines. I do not know if that will solve the problem. I should try it.

**Comment by GMishx** [comment]
> It would be good if there were an 'canonical' example of using curl to get the token. I've seen the API described differently in different places and had similar difficulties using the token fetching API as well. It would also be good if there were a working API to test against - does the demo installation provide this? Just so one knows the API works?

Hello @jeremiah , we have an API document which you can put into swagger and get the different commands like cURL or even generate a client. You can check it out here: https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml


> @GMishx Here are the curl output with second command and --location flag:

Looks like there is some issue with your Apache routing as the error message you are getting is never generated by FOSSology. Do you have a proxy installed in between causing the issue?

**Comment by frannicot** [comment]
I saw with @GMishx who found my curl problem. I thank him very much. This is not a bug.
My apache configuration file located in /etc/apache2/sites-available/fossology.conf is incorrect. The redirect rule is missing to access the rest API.
I got the right file https://github.com/fossology/fossology/blob/master/install/src-install-apache-example.conf to replace my file in this directory / etc / apache2 / sites-available. Now it works:
![2020-05-14_14h37_10](https://user-images.githubusercontent.com/32058875/82032016-f2bfaf80-969a-11ea-831b-45d631c74164.png)
![2020-05-15_10h58_35](https://user-images.githubusercontent.com/32058875/82032405-6f528e00-969b-11ea-8b33-3d6c00c91716.png)

**Comment by frannicot** [comment]
This is not a bug. I close this issue.

**Comment by jeremiah** [comment]
@GMishx Thanks. I'm not going to use postman or swagger though, I'd like to test from the command line or use documentation similar to GitHub's API docs; https://developer.github.com/v3/ It is so much cleaner and easier to use and I don't need to sign up for some account or download some gigantic GUI built in npm. 

I know there are a couple of documents describing the API and how to call it from curl, but they conflict. Which is the "right" one?
