### ISSUE TITLE
Add unit tests for fossjobs

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#172]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2931, http://www.fossology.org/issues/2931
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
