### ISSUE TITLE
delagent does not delete rows at upload table

### ISSUE THREAD

**Issue by JustinWonjaePark** [fossology/fossology#1721]
### Description

I deleted some uploads (which was success) but upload table on my DB(fossology) has rows for the upload_pk.
But when I go to browse, the deleted uploads are gone.

#### How to reproduce

Delete uploads via Web UI or with delagent at terminal

#### Screenshots

(following is an example for upload ID 2 deleted with delagent at terminal)
![image](https://user-images.githubusercontent.com/33045921/81901442-83de4a00-95f9-11ea-8245-09ad258a4aa5.png)
---------------------------------------------------------
![image](https://user-images.githubusercontent.com/33045921/81901556-acfeda80-95f9-11ea-994b-ab18b7541523.png)
---------------------------------------------------------
![image](https://user-images.githubusercontent.com/33045921/81901633-ca33a900-95f9-11ea-98a5-55b2948f39f8.png)

### Versions

* Last commit id on master: 3.8.0 #012cd4
* Operating System (lsb_release -a): 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

### Logs

No log generated

#### FOSSology logs

No log generated

#### Apache logs

No log generated

#### Job logs

(following is an example for upload ID 61 deleted with Web UI)
2020-05-14 15:27:45 delagent [0] :: JOB[596].delagent[5293.localhost]: "NOTICE:  table "delup_61_pfile" does not exist, skipping"

**Comment by GMishx** [comment]
Hello @JustinWonjaePark ,

Deletion of `upload_pk` was causing problems with reset of sequence of `upload_pk`.
You can read more about the issue at #1684 and about the fix at #1707.

**Comment by JustinWonjaePark** [comment]
Hi @GMishx,
Thank you for the answer!

**Comment by GMishx** [comment]
Hello @JustinWonjaePark,
Would it be okay for you to close the ticket if your query has been answered?

**Comment by JustinWonjaePark** [comment]
Hi @GMishx,
Yes, I'll close it. Thanks again.
