### ISSUE TITLE
tree view and histogram view are failed to capture latest deletions

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1728]
### Description

Histogram view and license tree view are unable to capture latest decisions that are made in single file view.

#### How to reproduce

* Create a candidate license "SomeLic"
* Upload a package and add this candidate license as decision to a file.
* Remove added candidate license.
* Go to license tree view. and check see the removed candidate license in list of licenses.

#### Screenshots

![screenShot14](https://user-images.githubusercontent.com/10155976/82596696-62ff9100-9bc5-11ea-9a75-a97adfa32472.PNG)

### Versions

* Latest Master

**Comment by GMishx** [comment]
Hello @shaheemazmalmmd,

I followed the steps described by you on latest master, but couldn't see the behavior

1. Add a candidate license to a file:
![image](https://user-images.githubusercontent.com/18077542/82632470-f06ad180-9c15-11ea-8b90-186e46fccfdb.png)
1. Tree view with license decision:
![image](https://user-images.githubusercontent.com/18077542/82632491-fe205700-9c15-11ea-8fa9-7ffac5a84567.png)
1. Removed license decision:
![image](https://user-images.githubusercontent.com/18077542/82632514-109a9080-9c16-11ea-89cf-25695c5d9ddf.png)
1. Tree view without license decision:
![image](https://user-images.githubusercontent.com/18077542/82632529-1abc8f00-9c16-11ea-822d-8e8cf2970ee3.png)

Is there something I missed?

**Comment by shaheemazmalmmd** [comment]
@GMishx Instead of empty file can you please try adding it to a file which has some license findings ??

**Comment by GMishx** [comment]
Still the same result on file with license findings.

**Comment by shaheemazmalmmd** [comment]
There seems to be issue with only global decisions. and now that will get fixed with PR : https://github.com/fossology/fossology/pull/1682
