### ISSUE TITLE
Add functional tests for fossjobs

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#173]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2937, http://www.fossology.org/issues/2937
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
