### ISSUE TITLE
Add unit tests for fo_cli

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#174]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2943, http://www.fossology.org/issues/2943
Original Date: 2012/06/15
Original Assignee: Mary Laser

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/08/15 20:59:33 +0000

---

I doubt that unit tests would be of benefit for fo_cli. This is such a simple program that the functional tests should be sufficient. I'm not going to set this to resolved though as someone else should confirm that this is correct.

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
