### ISSUE TITLE
Permission issue with all server jobs

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1749]
### Description

Admin -> dashboard -> all jobs is visible without logging in.

#### How to reproduce

* Install fossology.
* Go to login page and Admin -> dashboard -> all jobs to view the jobs.

#### Screenshots

<img width="372" alt="screenShot18" src="https://user-images.githubusercontent.com/10155976/85139438-0b0a8780-b262-11ea-84e5-9919b704c63a.PNG">

**Comment by GMishx** [comment]
I don't think that's an issue. It was clearly mentioned in the pull request #1709
