### ISSUE TITLE
Add functional tests for fo_cli

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#175]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2949, http://www.fossology.org/issues/2949
Original Date: 2012/06/15
Original Assignee: Alex Norton

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/08/06 19:22:04 +0000

---

The cli is tested extensively during the scheduler's functional tests. This is because the cli is how the testing harness checks that the scheduler is in a valid state.

**Comment by mcjaeger** [comment]
closing, issues for functional tests collected here: #776
