### ISSUE TITLE
Downloading unifiedreport from API results in unusable file, downloading from browser results in OK file

### ISSUE THREAD

**Issue by l-x-u** [fossology/fossology#1767]
### Description

I am triggering a report via API. When downloading that report via API when it is done, the file I receive is not the same as the file I get if I download the report from the Web UI. The file from the API is not a valid DOCX file, and appears empty when opened despite being several kb. I have attached the obtained files for the exact same report here in case some insight can be gained from their structure. I am simply writing the bytes in the `data` field of the API response to a file.

[API.docx](https://github.com/fossology/fossology/files/4932110/API.docx)
[UI.docx](https://github.com/fossology/fossology/files/4932111/UI.docx)

#### How to reproduce

Trigger a report generation, download the report via Web UI, download the report via API.

### Versions
* Fossology: Version: [3.8.1], Branch: [heads/3.8.1], Commit: [#9103fa]
* Operating System: Ubuntu 16.04.3 LTS

**Comment by GMishx** [comment]
Hello @l-x-u , can you please provide us with the API calls?

**Comment by l-x-u** [comment]
Hello,

Here is the relevant JavaScript code performing the API calls with Axios:

```
const fossologyError = data => {
    if (data.type !== 'INFO') {
        return new Error(data.message)
    }
    return data.message
}

const wait = ms => new Promise(res => setTimeout(res, ms));

const newReport = async(upload) => {
    console.log('generating report...')
    const reportResponse = await client.get('/report', {headers: {
        reportFormat: 'unifiedreport',
        uploadId: upload
    }})
    const report = fossologyError(reportResponse.data)
    if (report instanceof Error) {
        return report
    }
    const reportIdRegex = /[0-9]*$/
    const reportId = reportIdRegex.exec(report)[0]

    while (true) {
        console.log('downloading report...')
        const reportContentsResponse = await client.get('/report/'+reportId, {headers: {
            'Accept': 'text/plain',
        }})
        if (reportContentsResponse.status === 200) {
            return reportContentsResponse.data
        } else if (reportContentsResponse.status === 503) {
            console.log('waiting for report to complete...')
            await wait(wait_interval_ms)
        } else {
            return new Error(reportContentsResponse.statusText)
        }
    }
}

    const report = await newReport(upload)
    if(report instanceof Error) {
        console.log(report)
        return -1
    }

    fs.writeFileSync('report.docx', report)

```

**Comment by GMishx** [comment]
I am not very good with JS but the code looks appropriate. However I have 2 concerns:
1. Can you try changing the `Accept` header?
1. Are you sure the `reportContentsResponse.data` does not re-encode the data?

I just tried the same API with postman and it generated a perfectly valid docx file.

**Comment by l-x-u** [comment]
Hi, thanks for the input! What should I change the `Accept` header to be?

**Comment by GMishx** [comment]
Sorry for coming to it late, your comment got lost in my emails.

There is no `Accept` header required from FOSSology side and any value should not cause any issues. But I am not sure how JS handles it. Maybe changing it to something like `application/zip` to make sure it remains binary.

If I try to do the calls on Postman or curl or using the [fossology-python](https://github.com/fossology/fossology-python) library, I am getting a valid MS Word file.

**Comment by deveaud-m** [comment]
@GMishx not really related to this issue but I can't get a zipped report even when using the header `Accept: application/zip`.

Whatever format I use, I always get the uncompressed report as output, even when setting the `Accept` header.

![fossy-zip-report](https://user-images.githubusercontent.com/11165188/96128949-42c6ca80-0ef6-11eb-8506-0a9fc03d9045.png)


I'm testing with the latest container today:  
```
Version: [3.9.0], Branch: [master], Commit: [#710b20] 2020/10/14 07:07 UTC built @ 2020/10/14 08:17 UTC
```

**Comment by GMishx** [comment]
The reports are always sent uncompressed from FOSSology API. I just suggested `application/zip` as docx file are essentially bunch of compressed files so JavaScript might treat it differently.
However, I see now the `Content-Type` header is missing in the response.

**Comment by deveaud-m** [comment]
> The reports are always sent uncompressed from FOSSology API. I just suggested `application/zip` as docx file are essentially bunch of compressed files so JavaScript might treat it differently.
> However, I see now the `Content-Type` header is missing in the response.

Thanks @GMishx for the quick response, I interpreted the [OpanAPI specification](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml#L897) as if Fossology was able to send compressed reports. `fossology-python` tests somehow used to work before, now they fail, I'll make an update.

**Comment by GMishx** [comment]
Oh, sorry for the confusion. Should we change it to something like `application/octet-stream`?

**Comment by deveaud-m** [comment]
No problem, actually I think the discussion is worth taking place :+1: 

Looking at the HTTP standard, it looks like if the `Accept` header is empty, all kind of data format is accepted: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1. 

I would propose following steps:
* for now, set the generic clients to accept all formats in the HTTP request by default (no `Accept` header)
* the server should send the correct `Content-Type` header in the HTTP response, this will be up the the clients to verify that the received data are in the correct format
* in a further step, I will integrate the `Accept` header in Python clients according to the known reports formats and corresponding mime type

@GMishx what do you think?

**Comment by GMishx** [comment]
`Accept` header will be slightly difficult to achieve but yes, I will work on `Content-Type` to send correct headers from the server.
