### ISSUE TITLE
Change fossdash code from python2 to python3

### ISSUE THREAD

**Issue by darshank15** [fossology/fossology#1771]
### Description

As of now, fossdash script  `install/fossdash/fossdash-publish.py.in` was written in python2.
Now many pyhton2-libraries and python2 itself are going to deprecate in the future.
So needs to upgrade the code to python3.

**Comment by darshank15** [comment]
Can someone assign this issue to me?

**Comment by GMishx** [comment]
Done :-)

**Comment by darshank15** [comment]
Completed. 
https://github.com/fossology/fossology/pull/1769/commits/6b0ffc947b2d7d3e1e70582c344fdd1a14f6c470

See squash git commit here. _refactor(fossdash script) : convert code from python2 to python3_

**Comment by NicolasToussaint** [comment]
All good, closing
