### ISSUE TITLE
Refactoring of fossdash_publisher script

### ISSUE THREAD

**Issue by darshank15** [fossology/fossology#1776]
### Description

Refactoring of fossdash_publisher script: Get all metric queries out of the script and put them into some configuration way.

**Comment by darshank15** [comment]
Link to commit:  https://github.com/fossology/fossology/pull/1769/commits/aed5a17b8e2a99fcf14fa2b6b8830acfc55fdaed

**Comment by NicolasToussaint** [comment]
All good, closing
