### ISSUE TITLE
Add unit tests for schema_export

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#178]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2967, http://www.fossology.org/issues/2967
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
closing issue, captured now at #777
