### ISSUE TITLE
Looking for a REST API to kill (or stop) the job

### ISSUE THREAD

**Issue by wla80** [fossology/fossology#1787]
For example, after I triggered decider & reuser job together through REST API, if the reuser agent was failed, the decider agent which depended on reuser would stay at "pending" state forever. Thus, is there an API to force the status for a specific job

**Comment by GMishx** [comment]
Currently the REST API does not have any such endpoint but definitely there can be a `DELETE` endpoint for it.

**Comment by sayantan1413** [comment]
Hello I am Sayantan Bose and I want to contribute in this project but I am unable to understand from where I should start? So can you help me how to start contribute in this project ? @GMishx  @hastagAB

**Comment by saiwali** [comment]
@GMishx I would like to work on this issue . Could u assaign it to me?? But I really dont know how to get started so I really could use some help.

**Comment by ArijeetBanerjee** [comment]
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖

**Comment by simran142002** [comment]
Is this issue still available? I want to work on this

**Comment by snehalchaudhari98** [comment]
Hi @GMishx, 
If this issue is currently open, I would love to contribute.
