### ISSUE TITLE
Add functial tests for schema_export

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#179]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2973, http://www.fossology.org/issues/2973
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

Will fill in http://www.fossology.org/projects/fossology/wiki/FOSSology_tests

**Comment by mcjaeger** [comment]
not really asked for since six years, closing
