### ISSUE TITLE
Push continuous integration information to fossology.org

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#180]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2985, http://www.fossology.org/issues/2985
Original Date: 2012/06/19
Original Assignee: Dong Ma

---

Since fonightly is within the HP firewall, many of the features of Jenkins are not available.  This will be remedied in the long run by setting up a true community integration machine, but for the short-term, this information should just be pushed.

Key info includes coverage metrics, SchemaSpy, the docs, etc.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/12/05 17:06:11 +0000

---

Updating target version to 2.2.0
Access to schemaspy was requested by Liang at UNO

**Comment by mcjaeger** [comment]
just closing because it seems like that the infrastructure is modified anyways.
