### ISSUE TITLE
REST-API: reuse component expects group id. Is there any endpoint to get group id from group name?

### ISSUE THREAD

**Issue by lakshmibhavani1** [fossology/fossology#1801]
### Description

In rest-api, the reuse component has a mandatory parameter reuse_group of type integer which expects group id. But there is no endpoint available to get a group id from the group name. 

#### How to reproduce
Most of the endpoints have group parameter that expects group name of type string. But for the reuse component which has parameter reuse_group, expects group id of type integer. Is it possible to input the group name for the same component rather than group id. Or is there any way to get group id from the group name.

### Versions
version = 3.7.0

**Comment by GMishx** [comment]
Currently there is no such endpoint. However, it would be better to replace the group id with group name in the request as it was done with #1568

**Comment by YashJipkate** [comment]
Hi, @GMishx I would like to work on this.

If I understand correctly, the int type of the `reuse_group` (and corresponding `reuseGroup`) is to be **replaced** by string type in [Reuser.php](https://github.com/fossology/fossology/blob/479322e49e87f94f41d846452d6167ec85f63ea9/src/www/ui/api/Models/Reuser.php#L39)?

**Comment by GMishx** [comment]
Hello @YashJipkate ,

Yes, the type of `reuse_group` needs to changed to string and also in the [openapi.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml). Please note that this will effect following line too.
https://github.com/fossology/fossology/blob/479322e49e87f94f41d846452d6167ec85f63ea9/src/www/ui/api/Models/ScanOptions.php#L152
The `$reuserSelector` expects a group id.

If you are okay, shall I assign the issue to you?

**Comment by YashJipkate** [comment]
Thanks @GMishx, please assign me and I'll get to working on it.
