### ISSUE TITLE
REST API: Jobs end point says job status as queued when ununpack is failed

### ISSUE THREAD

**Issue by DineshDevarajan** [fossology/fossology#1805]
### Description

Uploaded a file into fossology, the ununpack failed and the adj2nest job is still in the queued state.

```
fossology=> SELECT jq_pk,jq_job_fk,jq_starttime,jq_endtime, jq_type,jq_endtext, jq_end_bits from jobqueue WHERE jq_job_fk = 2 ;
 jq_pk | jq_job_fk |         jq_starttime          |          jq_endtime           | jq_type  | jq_endtext | jq_end_bits
-------+-----------+-------------------------------+-------------------------------+----------+------------+-------------
     6 |         2 |                               |                               | adj2nest |            |           0
     2 |         2 | 2020-09-22 09:54:38.614494+00 | 2020-09-22 09:54:38.700048+00 | ununpack | Failed     |           2
(2 rows)
```
REST API end point /jobs/id -> provides status as Queued
```
{
    "id": 2,
    "name": "****",
    "queueDate": "2020-09-22 09:54:38.546828+00",
    "uploadId": "8",
    "userId": "3",
    "groupId": "4",
    "eta": 0,
    "status": "Queued"   ------>> Expected as Failed
}
```
### Versions

* Last commit id on master: 650233
* Using docker image 

**2 issues :**
1. when ununpack fails the job adjnest should also be failed or cancelled. 
2. REST API : Job Controller -> getJobStatus is providing Failed job as queued.

https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/JobController.php#L277

$jobStatus flag : Both JOB_QUEUED and JOB_FAILED bits are set in this scenario then the following if statement should set jobStatus to Failed but if sets to Queued.

```
if ($jobStatus & self::JOB_STARTED) {
      /* If at least one job is started, set status as processing */
      $jobStatusString = "Processing";
    } else if ($jobStatus & self::JOB_QUEUED) {
      $jobStatusString = "Queued";
    } else if ($jobStatus & self::JOB_FAILED) {
      **/* If at least one job is failed, set status as failed */**
      $jobStatusString = "Failed";
    } else {
      /* If everything completed successfully, set status as completed */
      $jobStatusString = "Completed";
    } 
```

Comment in the code says "If at least one job is failed, set status as failed"   -> whether the JOB_FAILED need to be validated before JOB_QUEUED and JOB_STARTED  ?

if this is a valid case please let me know so I will create a PR to fix this ?

**Comment by GMishx** [comment]
Thanks for pointing that out. Failure should be evaluated before others.
Also, can this change fix issue pointed in #1800 ?

**Comment by DineshDevarajan** [comment]
@GMishx  Incase of Issue #1800 , can we delete a file while upload is in progress it wont appear in deletion list. Please let me know how to test issue #1800 . Tested by moving the failure check to first and this bug #1805 works as expected and gives the correct status.

**Comment by GMishx** [comment]
> @GMishx Incase of Issue #1800 , can we delete a file while upload is in progress ? will it appear in deletion list.

You can schedule the delagent while other agents are in progress but it will not be deleted immediately. Delagent is set to run in mutually exclusive mode meaning it will wait for other agents to finish first.

> Please let me know how to test issue #1800.

You can perform following operations to reproduce it:
1. Upload a package.
1. Schedule agents on the upload.
1. Kill/stop one of the agent to simulate failure (I choose softwareHeritage as it is the slowest agent, nomos is a good candidate too)
1. Delete the upload.

By performing these steps, REST API should provide 3 jobs. However the status for all the 3 jobs will be **Failed** because of 2nd job. Instead it should be **Success** for 1st and 3rd job.
