### ISSUE TITLE
Set up an integration server within community view

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#181]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2991, http://www.fossology.org/issues/2991
Original Date: 2012/06/19
Original Assignee: Dan Stangel

---

Following up on #2985, there should be an integration server accessible and viewable to the community at large.

**Comment by mcjaeger** [comment]
closed because there is travis/ci, it it setup missing is building packages and deploying.
