### ISSUE TITLE
Apache configuration

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#182]
---

Author Name: **Alex Norton** 
Original Redmine Issue: 3003, http://www.fossology.org/issues/3003
Original Date: 2012/06/20

---

The way that we instruct people to change the Apache configuration for FOSSology during a source install is very hard and prone to error. Our current method is found in install/INSTALL.

I propose changing it to adding a symlink to the fossology url configuration file in the apache2/conf.d directory. This has been a much more consistent and easier to perform method of Apache configuration that what we currently use.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:30 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
it seem t be broken some some from source installation attempts (softlinking the fo-apache.conf), sorry no more specifics, maybe "from source" would also not require to have the configuation linked to sites-enabledd

**Comment by bill-auger** [comment]
this is the behavior i observed installing from source on debian 9 - i also needed to copy /usr/local/etc/fossology/conf/src-install-apache-example.conf to /etc/apache2/sites-available/ and link o/c in /etc/apache2/sites-enabled

NOTE related to #856 which was recently opened and closed without explanation
