### ISSUE TITLE
missing *.conf migration to 2.0

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#183]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 3021, http://www.fossology.org/issues/3021
Original Date: 2012/06/21
Original Assignee: Mary Laser

---

In 2.0 the Depth.conf, Hosts.conf, Proxy.conf and RepPath.conf files were consolidated into fossology.conf.  However, the install did not migrate the contents.  A result is that if you upgrade to 2.0 your repo will no longer be available (not in fossology.conf).

Either the data needs to be migrated during install or we need to provide documentation or both.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/06/21 21:33:25 +0000

---

The release notes include this information about the new fossology.conf (http://www.fossology.org/projects/fossology/wiki/Release_Notes#Recommended-steps-for-upgrading):

FOSSology uses a new combined configuration file, called fossology.conf. Additional cleanup can be done in /etc/fossology. The following old files can be removed:

Depth.conf
Hosts.conf
Proxy.conf
RepPath.conf
Scheduler.conf
These files are no longer used by fossology and so can be safely removed. Before removing them, determine what settings in those files should be in the new configuration file fossology.conf.


Is this insufficient?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/06/21 21:39:32 +0000

---

How about something more explicit like:

FOSSology uses a new combined configuration file called fossology.conf.  Therefore the configuration data in:

Depth.conf
Hosts.conf
Proxy.conf
RepPath.conf
Scheduler.conf

must be migrated into fossology.conf.  After their data is migrated, these files can be removed.  Do not remove Db.conf.

**Comment by yaobinshi** [comment]
Updated by Bob Gobeille over 2 years ago
Ideally, this data would be migrated by the package install so that users don't have to do it manually.

#4 Updated by Mary Laser over 2 years ago
The Release Notes have been changed per Bob's suggestion.

The package install must now be changed.

#5 Updated by Mary Laser over 2 years ago
Target version deleted (2.0.1)
#6 Updated by Bob Gobeille over 2 years ago
Rank set to 99
Change unranked issues to rank 99 so they show up in a ranking report at the bottom. Otherwise, they show up on top.

**Comment by maximilianhuber** [comment]
There is still cleanup to do:

* **Depth.conf**: Still mentioned in the header of `src/lib/c/libfossrepo.h`
* **Hosts.conf**: Still mentioned in the header of `src/lib/c/libfossrepo.h`
* **Proxy.conf**: Still used in `src/testing/utils/Install.php`
* **RepPath.conf**: Still used in `src/ununpack/agent_tests/Unit/test_RunCommand.c`
* **Scheduler.conf**: no where mentioned in the code

**Comment by mcjaeger** [comment]
missing pick up here, but I guess, no one is interested in this migration step anymore
