### ISSUE TITLE
Software Heritage license information plugin: please back-off when rate-limited

### ISSUE THREAD

**Issue by olasd** [fossology/fossology#1836]
### Description

The Software Heritage license information plugin throws requests to the Software Heritage archive, even after being answered with a 429 "rate limited" error code.

The Software Heritage archive provides headers to tell you how many requests are remaining, as well as the time remaining until the rate limit counter resets.

https://archive.softwareheritage.org/api/#rate-limiting

We also provide token-based API access to lift rate limiting to specific users; The documentation for that feature (and how to get the rate limit lifted) is in the next section of the API docs.

Finally, we provide a staging instance (https://webapp.staging.swh.network/) that you can use for your testing before using the production instance.

Thanks,
Nicolas Dandrimont - Staff Engineer @ Software Heritage

#### How to reproduce

Unclear, but we see a lot of throttled requests coming from, supposedly, fossology instances.

#### Screenshots

N/A

### Versions

Unknown (see #1834)

### Logs

Any logs (if any) generated in

#### External http server

```
::1 - - [23/Nov/2020:11:49:49 +0000] "GET /api/1/content/sha256:616BD8A01B0066AA1F8883B2AB2ADC1DD930CD4403E8E6AEC748016BA2B9E441/license/ HTTP/1.1" 302 - "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"
::1 - - [23/Nov/2020:11:49:50 +0000] "GET /api/1/content/sha256:616bd8a01b0066aa1f8883b2ab2adc1dd930cd4403e8e6aec748016ba2b9e441/license/ HTTP/1.1" 429 95 "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"
::1 - - [23/Nov/2020:11:50:25 +0000] "GET /api/1/content/sha256:616BD8A01B0066AA1F8883B2AB2ADC1DD930CD4403E8E6AEC748016BA2B9E441/license/ HTTP/1.1" 302 - "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"
::1 - - [23/Nov/2020:11:50:27 +0000] "GET /api/1/content/sha256:616bd8a01b0066aa1f8883b2ab2adc1dd930cd4403e8e6aec748016ba2b9e441/license/ HTTP/1.1" 429 95 "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"
::1 - - [23/Nov/2020:11:51:01 +0000] "GET /api/1/content/sha256:616BD8A01B0066AA1F8883B2AB2ADC1DD930CD4403E8E6AEC748016BA2B9E441/license/ HTTP/1.1" 302 - "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"
::1 - - [23/Nov/2020:11:51:01 +0000] "GET /api/1/content/sha256:616bd8a01b0066aa1f8883b2ab2adc1dd930cd4403e8e6aec748016ba2b9e441/license/ HTTP/1.1" 429 95 "-" "GuzzleHttp/6.3.3 curl/7.52.1 PHP/7.0.33-0+deb9u10"

```

#### FOSSology logs

N/A

#### Apache logs

N/A

#### Job logs

N/A

**Comment by GMishx** [comment]
Hello @olasd , sometimes we received the time in `X-RateLimit-Reset` which was in past, so the mechanism to ping the server every 30 seconds or so was introduced if the response code is `429`. Do you think this 30 seconds ping time needs to be increased?
