### ISSUE TITLE
verify version in Help > About FOSSology

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#184]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 3027, http://www.fossology.org/issues/3027
Original Date: 2012/06/21
Original Assignee: Mary Laser

---

In an package upgrade from 1.4.x to 2.0, please verify that the fossology version, visible in Help > About FOSSology is correct (and not an -rc3)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:31 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
seems to work. Help -> About : displays version and git commit id
