### ISSUE TITLE
Broken Links in README.md

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/fossology#1840]
### Description

- The link of [general documentation](http://www.fossology.org/projects/fossology/wiki/User_Documentation) in Readme.md is broken
- In the about section of Readme.md the link of fossology website is given as http://fossology.org/ which should be changed to https://fossology.org/ (changing http to https )

#### How to reproduce
Visit the [general documentation](http://www.fossology.org/projects/fossology/wiki/User_Documentation) link in Readme.md

#### Screenshots

![image](https://user-images.githubusercontent.com/54680709/100540633-6fdffa00-3264-11eb-9d9d-916f18f101d8.png)

**Comment by tichnas** [comment]
@Aman-Codes  For me, changing `http` to `https` also doesn't work. Can you please try once and share the correct screenshot as well. Thanks.

**Comment by Aman-Codes** [comment]
@tichnas 
These are 2 different issues
1. The broken link http://www.fossology.org/projects/fossology/wiki/User_Documentation which neither opens on http nor on https.
2. The link of fossology website http://fossology.org/ ( which is working fine) given in readme is of http ( which redirect to https) can be changed to https in readme.
