### ISSUE TITLE
Bulk Clearing False Positive in Copyright

### ISSUE THREAD

**Issue by sameer1046** [fossology/fossology#1843]
### Description

There is no way bulk clearing of junk characters in copyright section

#### Steps followed and expected result

There should be a feature "Find and Replace" {like in excel sheet) in copyright section.

You want to replace a phrase (e.g. "\n") in copyrights, then you will be able to remove all "\n" characters in all copyrights.

**Comment by ag4ums** [comment]
Hello @sameer1046, 
PR #1822 will resolve this issue. you can test this PR and provide your feedback.

**Comment by GMishx** [comment]
Hello @sameer1046 , the PR #1822 was merged to master. Can you please check it and provide your feedback?

**Comment by sameer1046** [comment]
Its implemented
