### ISSUE TITLE
broken build directories

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#185]
---

Author Name: **Alex Norton** 
Original Redmine Issue: 3033, http://www.fossology.org/issues/3033
Original Date: 2012/06/21
Original Assignee: Mary Laser

---

From a clean svn checkout, a "make" was run in each directory for each agent.

For each agent these directories were checked:
src/<agent_name>/agent
src/<agent_name>/agent_tests/Functional
src/<agent_name>/agent_tests/Unit

The following directories did not correctly make:
src/mimetype/agent_tests/Unit
src/nomos/agent
src/pkgagent/agent_tests/Unit
src/scheduler/agent_tests/Unit
src/wget_agent/agent_tests/Unit

We should be able to do a make from any directory on clean checkout and get a clean build.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:32 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by GMishx** [comment]
Working now.
