### ISSUE TITLE
API doesn't work after PHP upgrade

### ISSUE THREAD

**Issue by mmurto** [fossology/fossology#1850]
### Description

Calls to the REST API produce internal server errors with the latest build. Works fine on the commit just before the upgrade to PHP 7.

#### How to reproduce

Docker-compose up with commit https://github.com/fossology/fossology/commit/017a3f948f78c981b908b342581012c8ce076f95. Querying `api/v1/version/` returns Internal Server Error (500). Docker logs show:

```
web_1        | 2020-12-17T10:54:01.976483032Z [Thu Dec 17 10:54:01.976230 2020] [:error] [pid 60] [client 172.18.0.1:45206] PHP Fatal error:  Interface 'Interop\\Container\\ContainerInterface' not found in /usr/local/share/fossology/vendor/flexsounds/slim-symfony-di-container/src/ContainerBuilder.php on line 21
web_1        | 2020-12-17T10:54:01.976936846Z 172.18.0.1 - - [17/Dec/2020:10:54:01 +0000] "GET /repo/api/v1/version/ HTTP/1.1" 500 185 "-" "curl/7.68.0"
```

Docker-compose up with the commit[ just before the upgrade](https://github.com/fossology/fossology/commit/b96010ea183b9bad03e2312630781deb635e744b) to PHP 7. Querying `api/v1/version/` works.

**Comment by sjha2048** [comment]
confirmed that #1830 is causing this issue, can I try to investigate what's going on?
cc: @GMishx

**Comment by GMishx** [comment]
Sure @sjha2048 , that will be great help.

I also did a quick lookup myself, seems like [container-interop](https://packagist.org/packages/container-interop/container-interop) was kicked out. But the `flexsounds/slim-symfony-di-container` still seems to refer it.
https://github.com/leroy0211/Slim-Symfony-Dependency-Injection-Bridge/blob/dd4b6ffb9b6bd739eea9e4b7c98d28957d7164a0/src/ContainerBuilder.php#L5

**Comment by sjha2048** [comment]
I'll try to test it by including [container-interop](https://packagist.org/packages/container-interop/container-interop) / [container](https://packagist.org/packages/psr/container) in dependencies itself, although updating composer.lock should work, I'll get back to you asap.

**Comment by sjha2048** [comment]
Hi @mmurto can you please checkout #1852 and test it out.
