### ISSUE TITLE
Could not connect to FOSSology database.

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#1870]
Hi, 

I have an issue with db (postgres 9.2)
I have install fossology from source, when I have finished the install, I got this message in my browser.

`Could not connect to FOSSology database.`

Could you give me a solution for this?

Thanks,

**Comment by ag4ums** [comment]
hello @C1ph3R-s , this happen when your database is down, Could you please check if your database is up 'sudo systemctl status postgresql'

**Comment by GMishx** [comment]
Please verify if `/usr/local/etc/fossology/Db.conf` contains correct information for connection.

**Comment by C1ph3R-s** [comment]
I have solved that issue, thanks!

**Comment by GMishx** [comment]
Thanks for confirming it @C1ph3R-s , can you please close the issue if it is resolved?

**Comment by C1ph3R-s** [comment]
sure
