### ISSUE TITLE
Reuse of Copyright Statements: UI label misleading

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1876]
### Description

For copyrights, the reuse is always there, it depends on the file hash. So there are two type of copyright work that is being reused:

1. edit a particular copyright statement
2.  deactivate a false positive copyright statement (usually something catched from a license text ...)

Both are automatically reuse at all uploads, thus the UI element:

<img width="440" alt="Screenshot 2021-01-21 at 12 04 00" src="https://user-images.githubusercontent.com/3418977/105342668-eeac4000-5be0-11eb-90e9-374c26283412.png">

is confusing: why there should be the checkbox if reuse happens anyway?

in fact reuse will not kick in for deactivations, if there will be a new copyright agent version.

Thus, what is proposed is to rename the label to `Reuse deactivate copyright when agent version changes` (or whatever ... just an example)

**Comment by Prodyte** [comment]
hey, I would like to do this.

**Comment by GMishx** [comment]
Hey @Prodyte , sure. I will assign this to you.
Just one addition, please check the title text for the _i_ image as well. I am not sure what it says at the moment 😅

**Comment by Prodyte** [comment]
> Just one addition, please check the title text for the _i_ image as well. I am not sure what it says at the moment
it says 'use to copy only deactived copyright decisions from the reused package'
