### ISSUE TITLE
Remove log from reuse agent

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#1884]
### Description

When i reuse a component, the agent log is getting printed which is not required. 

#### How to reproduce

* Upload component x-01,
* Do some clearing.
* Upload  component x-1.5 by reusing the x-01.
* Go to show jobs view and click on job-id of reuse.

#### Screenshots

<img width="555" alt="screenShot10" src="https://user-images.githubusercontent.com/10155976/106722757-5b392d00-662c-11eb-9720-d5d5edeb69d5.PNG">

### Versions

* Latest commit on master

**Comment by SyedAnwarHashmi** [comment]
Hello,
I'd like to get started on this issue. I am a bit unclear on the mentioned components x-01 and x-1.5. Can you elaborate on what they represent and in which package I can find them?

**Comment by GMishx** [comment]
Hello Anwar, I think what @shaheemazmalmmd meant with component x-01 is a random component X with version 01 and thus x-1.5 will be a higher version 1.5 of the same package.

You can use any popular component from github which has at least 2 releases to test out the issue.

**Comment by SyedAnwarHashmi** [comment]
Hello,

I followed the steps to reproduce the bug. I first added the twig 1.4.3 component and did some clearing after which I added the 1.4.4 component. The reuser status was complete with 26 items and 6 job-ids. However, when I checked the job-id I could not find any logs.
I have attached a screenshot of my browser.  I like to request further guidance on this.


![Screenshot 2021-02-23 at 9 10 28 PM](https://user-images.githubusercontent.com/68942638/108868356-23664980-761c-11eb-8bfc-5a949463042f.png)
![Screenshot 2021-02-23 at 9 11 05 PM](https://user-images.githubusercontent.com/68942638/108868364-26613a00-761c-11eb-8dc0-06f0ab057e7f.png)

**Comment by GMishx** [comment]
Hello, you need to check the log for **reuser** (job ID 140 from the screenshot)

**Comment by SyedAnwarHashmi** [comment]
A similar result for 140 as well.
![Screenshot 2021-02-23 at 9 45 35 PM](https://user-images.githubusercontent.com/68942638/108872797-95409200-7620-11eb-8fda-b012d2e35a57.png)

**Comment by GMishx** [comment]
Ah, maybe you need to select the "Advance reuse" option while scheduling it?
