### ISSUE TITLE
i18n in fossology does not work in trunk

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#190]
---

Author Name: **larry shi** 
Original Redmine Issue: 3105, http://www.fossology.org/issues/3105
Original Date: 2012/07/11

---

in trunk ./www/locale/  is too old.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:35 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
for users like me: i18n = internationalization

**Comment by mcjaeger** [comment]
but this is exactly the kind of issue I have problems with:
* what is expected
* what is the issue
* how to solve it
-> it seems like a do not forget this please issue to me.
