### ISSUE TITLE
Missing component Group in API documentation

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1900]
### Description

While testing a new PR, I discovered following error in Swagger Editor.

![image](https://user-images.githubusercontent.com/18077542/109458071-1c0ec800-7a82-11eb-8897-ce8fd5c18bf8.png)

Looks like the component information for `#/components/schemas/Group` was missed in #1872.

#### How to reproduce

Load the `src/www/ui/api/documentation/openapi.yaml` in Swagger editor.

### Versions

* Last commit id on master: 45e186a68fc3c3fbf42dad0a8e92dce3e39922f7

**Comment by GMishx** [comment]
Hello @piotreke12 , can you please help us?

**Comment by piotreke12** [comment]
> Hello @piotreke12 , can you please help us?

Sure @GMishx , please assign this problem to me (I missed it somehow during previous PR validation)

**Comment by GMishx** [comment]
Thank you Piotr, I will assign it to you.
