### ISSUE TITLE
update tutorials for 2.0

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#191]
---

Author Name: **Alex Norton** 
Original Redmine Issue: 3117, http://www.fossology.org/issues/3117
Original Date: 2012/07/12
Original Assignee: Mary Laser

---

The FOSSology tutorials need to be updated to work with 2.0

The tutorials are under /src/tutorials

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:36 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
removed with 3.0.0 should be on web page, there is also the training from the linux foundation.
