### ISSUE TITLE
Fix: HTML and CSS Errors

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/fossology#1911]
#### HTML Errors:

* `</br>` present in [/src/www/ui/template/admin_obligation-upload_form.html.twig](https://github.com/fossology/fossology/blob/master/src/www/ui/template/admin_obligation-upload_form.html.twig#L41-L49) in line 41 and 49
* `</hr>` in [/src/www/ui/template/ui-clearing-view_bulk.html.twig](https://github.com/fossology/fossology/blob/master/src/www/ui/template/ui-clearing-view_bulk.html.twig) in line 73
* The Html tag has no language attribute present (currently it is added in head tag instead of Html tag)
* Add a missing viewport meta tag

#### CSS Errors:

* auto is not a valid value for padding property in [Line 216](https://github.com/fossology/fossology/blob/master/src/www/ui/css/fossology.css#L216) 
* Unknown property horz-align is used in [Line 292](https://github.com/fossology/fossology/blob/master/src/www/ui/css/fossology.css#L292)
* inline-block is ignored due to the float. If 'float' has a value other than 'none', the box is floated and 'display' is treated as 'block' in [Line 164 and 200](https://github.com/fossology/fossology/blob/master/src/www/ui/css/fossology.css#L164-L200)
* empty css rulesets present in [Line 186 to 194](https://github.com/fossology/fossology/blob/master/src/www/ui/css/fossology.css#L186-L194)

#### How to reproduce

View the source code of the page

### Versions

* Last commit id on master: ae63dbd
* Operating System (lsb_release -a):
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

### Logs

None

**Comment by mukeshmjn** [comment]
Hi, please assign this to me I want to contribute

**Comment by GMishx** [comment]
Hello @mukeshmjn , thank you for your interest in contributing to the project but there is already a PR fixing it: #1912
