### ISSUE TITLE
Please modify ununpack to recognize and process tbz files (compressed bzip)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#192]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 3123, http://www.fossology.org/issues/3123
Original Date: 2012/07/17
Original Assignee: larry shi

---

This enhancement was prompted by a support request from Florence.  See email thread below.

> -----Original Message-----
> From: Perot, Florence
> Sent: Monday, July 16, 2012 4:45 PM
> To: Laser, Mary
> Subject: FW: FOSSology scan complete - problem with a *.tbz file
> 
> Mary
> It seems that Fossology did not like a *.tbz file. I can't seem to get 
> a licensing browser results Let me know Thanks Florence

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:36 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
I am not sure we are modifying ununpack since it basically uses a package (as dependency of the distro): have not seen the issue for myself, closing because of missing pick up.
