### ISSUE TITLE
Upgrade this project from PHP 7 to PHP 8

### ISSUE THREAD

**Issue by avinal** [fossology/fossology#1920]
### Description

The project currently uses PHP 7.x and is partially incompatible with PHP 8. It would be preferable to upgrade this project to PHP 8 for better compatibility with the latest technologies. 
PHP 8 changelog: https://www.php.net/manual/en/migration80.incompatible.php

#### How to reproduce

Since most of the incompatible changes are syntax changes. We can run a syntax check on our code:
- Ensure PHP version is 8.x `php -v`
- Run Syntax Checks 
- `bash src/testing/syntax/syntaxtest.sh` 
- `composer validate --no-check-all --working-dir=src --strict`

#### Screenshots

![image](https://user-images.githubusercontent.com/74113200/111267674-4780dd80-8652-11eb-9a6a-eec97b85cc59.png)

### Versions

* Last commit id on master: ae63dbd1a7e237628843c08ad57f837717d539bc
* Operating System (lsb_release -a): 
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

### Logs

https://pipelines.actions.githubusercontent.com/KPn0gHvJ2HG2MVj9fWEo5aXUaqKY85pAXvvfx2ACcvlM9dVYyY/_apis/pipelines/1/runs/26/signedlogcontent/3?urlExpires=2021-03-16T06%3A55%3A45.7724132Z&urlSigningMethod=HMACV1&urlSignature=hKpUNPpu0Q8o9Ed6rmwJjLOgkpXGNW7lJ7G7PdnCy6Y%3D

**Comment by itssingh** [comment]
@avinal @GMishx can I work on this ticket?

**Comment by GMishx** [comment]
Yes you can. No one is assigned to it.
@avinal, are you planning to work on it?

**Comment by avinal** [comment]
Yeah @itssingh, go ahead, I am working on other issues 😅.

**Comment by GMishx** [comment]
I am assigning this ticket to you then if it fine.

**Comment by vedantjangid** [comment]
Can you assign it to me i can help with it .

**Comment by GMishx** [comment]
Thank you for your interest @vedantjangid , but @itssingh has already opened a PR #1925 on it.

You can still look at some other issues from https://github.com/fossology/fossology/contribute.

**Comment by ArijeetBanerjee** [comment]
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖

**Comment by shaheemazmalmmd** [comment]
FOSSology already supports PHP 8
