### ISSUE TITLE
hey I am new to opensource and have not done this before so if any one can help me with tis then it would be so much helpful and the gesture will be much appreciate

### ISSUE THREAD

**Issue by vedantjangid** [fossology/fossology#1922]
### Description

Please describe your situation in few words here.

#### How to reproduce

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs/expected results.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by GMishx** [comment]
Hello @vedantjangid , welcome to the world of Open Source!

How can we help you with this issue? Can you please provide more information on the same?

**Comment by itssingh** [comment]
@vedantjangid could join fossology slack channel, could find link for the same here https://github.com/fossology/fossology#fossology and have some discussions:)

**Comment by vedantjangid** [comment]
So basically if any one can help me get started with open source like I don't know open source as ive mentioned it above the basic question raises in my mind and many of the new members who come here daily for such query is where do i get started and how if anyone can help me do so

**Comment by itssingh** [comment]
You could find blogs and videos online. One of such and my own favourite is (https://stackoverflow.blog/2020/08/03/getting-started-with-contributing-to-open-source/). Feel free to ask many questions but please don't ask what you could find easily online :)

**Comment by GMishx** [comment]
Hi @vedantjangid , since this is not specific to FOSSology and about Open Source community in general, I am closing the issue now.
You can still use this space for communication or open a new discussion: https://github.com/fossology/fossology/discussions
