### ISSUE TITLE
Assigned To filter on browse page

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1927]
### Description

If the uploads are filtered by "Assigned To" and person navigates away from the page or reloads the page, the filter is lost.

#### Steps followed and expected result

1. Upload some packages and assign them to individuals.
2. Filter the uploads assigned to someone.
3. Navigate back and forth from an upload.
    - The filter on "Assigned To" is lost.

#### Screenshots

![image](https://user-images.githubusercontent.com/18077542/112092007-97b0f000-8bbc-11eb-8503-00485839fea2.png)

### Versions

* Last commit id on master: eb0319dced8f0b4dd4fd7e5db5d654e0cd64bd4e

**Comment by AshuKV** [comment]
Can I work on this issue? Kindly assign it to me.

**Comment by AshuKV** [comment]
@GMishx Is it possible to add other contributors also to work on this issue?

**Comment by GMishx** [comment]
Yes, we do not have any rules against it :slightly_smiling_face: Infact Open Source spirit encourages collaboration.
