### ISSUE TITLE
Need to select multiple deactivated copyright statement and undo them once.

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1928]
### Description

There is already a feature to select multiple copyright statements and deactivate them by one click.
It will be nice to also have the same feature for already deactivated copyright statements to activate them.

#### Screenshots

![image](https://user-images.githubusercontent.com/18077542/112092297-389fab00-8bbd-11eb-929c-43397b9bb9bd.png)

**Comment by BJSwaroop** [comment]
I want to work on this issue. I know basics but I think I can do it. Please assign it to me

**Comment by GMishx** [comment]
Hi @BJSwaroop , thank you for showing interest. I have assigned the issue to you. A good start will be looking at
https://github.com/fossology/fossology/blob/aaec8d420e0d58f4e7663a9694e1fae44b42def6/src/copyright/ui/ajax-copyright-hist.php#L423

and 
https://github.com/fossology/fossology/blob/aaec8d420e0d58f4e7663a9694e1fae44b42def6/src/copyright/ui/template/histTable.js.twig#L83

**Comment by Amit-Morade** [comment]
Can I work on this issue.
If yes I would need to know what languages has been used as I can see JS and PHP. If anything else has been used please mention.
