### ISSUE TITLE
Extend the validity of the API token from one month to 3 months

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1930]
### Description

Using fossology 3.9.0 release 33f5b5a

Currently we are updating the fossology token in SW360 every month because the validity of a token in 1 month.
Can this be extended to user defined months? or atleast be extended to three months.?

**Comment by GMishx** [comment]
Hello @dineshr93 , there is already an option **Max token validity** in the Customize page under Admin menu.

**Comment by jimmyccsung** [comment]
Sorry, I can't find the option

**Comment by GMishx** [comment]
Hey @jimmyccsung just head over to Admin > Customize and search for the t "Max token validity" (CTRL + F) and you should be allowed to modify the validity dates.
