### ISSUE TITLE
Grammatical error in the documentation of About fossology

### ISSUE THREAD

**Issue by Shruti3004** [fossology/fossology#1935]
### Description

grammatical error in the documentation of about page of fossology

#### How to reproduce

src/www/ui/template/about.html.twig

#### Screenshots
![WhatsApp Image 2021-03-29 at 12 21 47](https://user-images.githubusercontent.com/56133783/112797717-6dae7080-9089-11eb-814e-a1d72cae13d7.jpeg)

**Comment by Shruti3004** [comment]
@GMishx i want to wrok on this issue

**Comment by GMishx** [comment]
Sure, assigned it to you.

**Comment by Piyussshh** [comment]
I can remove these Grammatical errors.

**Comment by GMishx** [comment]
There is already a PR #1937 for this.

**Comment by soham4abc** [comment]
@GMishx  is the issue still open. If so I can work on this!

**Comment by NicolasToussaint** [comment]
Just wondering, I do not see what is wrong which the underlined text in the screen shot
What would you like to change for ?

**Comment by GMishx** [comment]
Closing the issue as it needs changes in license text which is copyrighted by FSF which is not permitted.
```
GNU GENERAL PUBLIC LICENSE

Version 2, June 1991

Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
```

Please reopen the issue if changes are required in other sections of the page.
