### ISSUE TITLE
Improve packaging to be more robust and compliant with standards (debian)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#194]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 3249, http://www.fossology.org/issues/3249
Original Date: 2012/08/10
Original Assignee: Dan Stangel

---

This issue was created to capture irc feedback and suggestions for improvements to our debian packages.

<bobg> FOSSology postinstall complete, but sure to complete the remaining
<bobg>   steps in the INSTALL instructions.
<bobg> Setting up fossology-db (2.0.0-1) ...
<bobg> *** Setting up the FOSSology database ***
<bobg> psql: could not connect to server: No such file or directory
<bobg>  Is the server running locally and accepting
<bobg>  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
<bobg> ERROR: postgresql isn't running
<bobg> dpkg: error processing fossology-db (--configure):
<bobg>  subprocess installed post-installation script returned error exit status 1
<bobg> configured to not write apport reports
<bobg>                                       dpkg: dependency problems prevent configuration of fossology-web:
<bobg>  fossology-web depends on fossology-db; however:
<bobg>   Package fossology-db is not configured yet.
<bobg> dpkg: error processing fossology-web (--configure):
<bobg>  dependency problems - leaving unconfigured
<bobg> Setting up fossology-scheduler (2.0.0-1) ...
<bobg> configured to not write apport reports
<bobg> FOSSology postinstall complete, but sure to complete the remaining
<bobg>   steps in the INSTALL instructions.
<bobg> Setting up fossology-db (2.0.0-1) ...
<bobg> *** Setting up the FOSSology database ***
<bobg> psql: could not connect to server: No such file or directory
<bobg>  Is the server running locally and accepting
<bobg>  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
<bobg> ERROR: postgresql isn't running
<bobg> dpkg: error processing fossology-db (--configure):
<bobg>  subprocess installed post-installation script returned error exit status 1
<bobg> configured to not write apport reports
<bobg>                                       dpkg: dependency problems prevent configuration of fossology-web:
<bobg>  fossology-web depends on fossology-db; however:
<bobg>   Package fossology-db is not configured yet.
<bobg> dpkg: error processing fossology-web (--configure):
<bobg>  dependency problems - leaving unconfigured
<bobg> Setting up fossology-scheduler (2.0.0-1) ...
<bobg> configured to not write apport reports
<bobg>                                       *** Setting up scheduler ***
<bobg> FOSSology postinstall complete, but sure to complete the remaining
<bobg>   steps in the INSTALL instructions.
<bobg> Setting up fossology-ununpack (2.0.0-1) ...
<bobg> Setting up fossology-copyright (2.0.0-1) ...
<bobg> Setting up fossology-nomos (2.0.0-1) ...
<bobg> Setting up fossology-pkgagent (2.0.0-1) ...
<bobg> Setting up fossology-buckets (2.0.0-1) ...
<bobg> Setting up fossology-mimetype (2.0.0-1) ...
<bobg> Setting up fossology-delagent (2.0.0-1) ...
<bobg> Setting up fossology-wgetagent (2.0.0-1) ...
<bobg> dpkg: dependency problems prevent configuration of fossology:
<bobg>  fossology depends on fossology-web; however:
<bobg>   Package fossology-web is not configured yet.
<bobg> dpkg: error processing fossology (--configure):
<bobg>  dependency problems - leaving unconfigured
<bobg> configured to not write apport reports
<bobg>                                       Errors were encountered while processing:
<bobg>  fossology-db
<bobg>  fossology-web
<bobg>  fossology
<bobg> E: Sub-process /usr/bin/dpkg returned an error code (1)
<maryl> bobg: hm, yeah.  there needs to be something in the instructions about these errors. 
<maryl> pholland: are we having our standup on irc this morning?
<sutula> As an outsider but experienced Debian admin, I would regard those errors as fatal.  Basically, the packages aren't fully installed.
<sutula> The package system will want to remove the partially-installed packages during a future upgrade.
 sutula is warning against simply documenting the errors and leaving them alone
 bobg agrees with sutula
<maryl> sutula: thanks for your feedback on fossology's package install shortcomings. 
<sutula> maryl: You guys have complained that nobody is worrying about the Debian packaging...I guess that's a symptom
<maryl> not being a packging expert, I'm not sure how to handle dependencies like a working database
<sutula> Would it help to have a pointer to a similar package, or does nobody have time to work on it?
<maryl> sutula: an example would be good
<sutula> Try davical, which also uses postgresql
<maryl> we do create packages and are trying to automate the process
<maryl> ok
<sutula> It's in stable, testing, and unstable, so whatever he's doing is acceptable to the masses
<maryl> hm, nice
<sutula> It seems like once the package is created, you want to edit the result, and maybe that's where the effort needs to go now.  But I don't understand project builder.
<maryl> o?  I thought project builder's purpose was to create usable packages. 
<maryl> Configuring PB is tricky
<maryl> AND,...
<maryl> it helps if you know something about building packages by hand
<maryl> taggart was key in this area
<sutula> Well, the package itself is probably usable, but someone has added code to try to connect fossology to the existing database, right?  That code is failing, according to what Bob posted.  So we can't really blame project builder for that.
<maryl> ah, I c what you're getting at
<sutula> Could be that the code needs to be smarter, and test to see if fossology is already in the database, and create entries if it isn't, etc.
<maryl> yes, that would be an easy test to avoid spewing out errors
<sutula> It's not only the errors but mainly the return code of the scripts.
<sutula> Basically, if the errors are not trapped in the scripts, then the script exists with a non-zero return code.
<sutula> The return code tells the packaging system (dpkg) that the script failed, and the packaging system leaves the packages marked (in this case) as unconfigured.
<sutula> The packaging system expects that the configure step will be run again and will succeed.  Until this happens, the package is basically half-installed.
<sutula> A sysadmin in this position will need to hack the configure script, insert an "exit 0" early in the script, and tell the packaging system to reconfigure the package.
<sutula> Then, the packaging system will be satisfied that it's properly configured.
<maryl> this is good stuff ^
<sutula> It's really not the situation you want to release with, and this is certainly a valid reason for removal of fossology from Debian.
 maryl nods
<sutula> Feel free to copy this to Dan if he needs it, or point him to me.
<maryl> thanks, I will
 sutula certainly leans enough on Dan and is happy to return the favor

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:42 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by maximilianhuber** [comment]
I will close this issue since
* the problem does no longer appear and
* the packaging mechanism was also rewriten.
