### ISSUE TITLE
There are SQL errors during 'fo-postinstall -l" call during installation

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#195]
---

Author Name: **Brian Pomerantz** 
Original Redmine Issue: 3291, http://www.fossology.org/issues/3291
Original Date: 2012/08/15
Original Assignee: Dong Ma

---

There are SQL errors during 'fo-postinstall -l" call during installation, these are caused by the incorrect escaping of single quotes with a backslash \'.  The correct SQL escape for single quote is to use two single quotes: ''.  A quick sed invocation, database drop, and call of fo-postinstall fixed the issue.

sed -i "s/\\\\'/''/g" licenseref.sql

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:43 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by steffen-weber** [comment]
fixed by ce3ab9e234f4190f3a78cdf52d55e045024aa525
