### ISSUE TITLE
Broken link in Upload instructions of scheduler documentation

### ISSUE THREAD

**Issue by Shruti3004** [fossology/fossology#1950]
### Description

In Upload > Instructions the scheduler documentation is redirecting to the broken link.

#### How to reproduce

/src/www/ui/template/upload_instructions.html.twig line 82
`<a href="http://www.fossology.org/projects/fossology/wiki/Sched-20">{{ 'Scheduler documentation'| trans }}</a>.`

#### Screenshots

![Screenshot from 2021-04-05 17-10-12](https://user-images.githubusercontent.com/56133783/113570868-d8841c80-9632-11eb-92cf-5f1cb839a407.png)

**Comment by Shruti3004** [comment]
@GMishx i want to work on this issue

**Comment by GMishx** [comment]
Yes sure.
