### ISSUE TITLE
you can always create one new blank page when click on next link on [Show Jobs] page

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#196]
---

Author Name: **larry shi** 
Original Redmine Issue: 3363, http://www.fossology.org/issues/3363
Original Date: 2012/09/06
Original Assignee: larry shi

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/09/07 16:30:45 +0000

---

This has been a problem since the beginning of FOSSology and is a low priority.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4575/next_page.png

**Comment by GMishx** [comment]
Fixed by #1338
