### ISSUE TITLE
Agent version doesn't upgraded (Docker-compose version)

### ISSUE THREAD

**Issue by drej** [fossology/fossology#1963]
### Description

Agent version doesn't upgraded after FOSSology upgrade

#### How to reproduce

I setup an instance of FOSSology using docker-compose. After uploading some files (database size 3.5GB, docker volume of repository is about 40GB), I upgrade FOSSology from 3.7.0 to 3.8.1.
Everything looks fine but I found that scanner version is still 3.7.0 in the Brower - [Upload file] - Scanner details.

I checked logs and found "Error, script will take too much time. Not recoding entries. " in the scheduler output. Then I set the FOSSENCODING=1 in environment and restart FOSSology. It took some time to parse copyright record and etc. but the scanner version remain no change. (I also try to run maintenance jobs but nothing changed)

After all above I created a fresh new FOSSology 3.7.0 and then upgraded it to 3.8.1, and everything include agent version is just fine.

I wonder if I missed something or it is a bug?

#### Screenshots

![image](https://user-images.githubusercontent.com/1217733/114496315-9ffbc880-9c5a-11eb-8595-4398ca4c186b.png)

#### FOSSology logs

scheduler_1  | ********************************************************************************
scheduler_1  | *** Error, script will take too much time. Not recoding entries.             ***
scheduler_1  | *** Either rerun the fo-postinstall with "--force-encode" flag or set        ***
scheduler_1  | *** "FOSSENCODING=1" in environment or run script at                         ***
scheduler_1  | *** "/usr/local/lib/fossology/dbmigrate_change_db_encoding.php" to continue as a separate process ***
scheduler_1  | ********************************************************************************
scheduler_1  | FOSSology postinstall complete, but sure to complete the remaining
scheduler_1  |   steps in the INSTALL instructions.

**Comment by GMishx** [comment]
Hello @drej , the version you are seeing here is the agent version which last ran on that particular upload. For the new uploads you should see the 3.8.1 version.

And for the recoding step is optional at the moment but is recommended as the postgres encoding changed from `SQL_ASCII` to `UTF-8`. This will cause issues when upgrading database in future.
You can run this process in background like on weekends.

**Comment by drej** [comment]
@GMishx Hello, thank you for answering. 
Unfortunately even the new uploads are still using the 3.7.0 version.
On my second FOSSology with not so much file uploaded, it shows me here that my latest run was using an old version of agent and I can rerun the agent with newer version if I like. I cannot see the same notification on my original FOSSology.

I also checked 'agent' table in database and found that every version of agents are remain here, and all agent is set 'enabled' as 't'. I simply tried to set old version's 'enabled' to 'f', the FOSSology was just broken, won't do that again (

**Comment by GMishx** [comment]
> I also checked 'agent' table in database and found that every version of agents are remain here

Does that mean you have agents with version 3.7.0 and 3.8.1? That should be solved by a simple restart of scheduler daemon/docker container.

If that is not the case, can you please tell us the steps you followed to update the existing container?

**Comment by drej** [comment]
I mostly use the docker-compose.yml file in the source directly except that the mail program in docker-hub image didn't work for me so I build my own image on it.

```Dockerfile
FROM fossology/fossology:3.8.1

# setup proxy
ENV http_proxy "http://proxy.companyname.com:8080"
ENV https_proxy "http://proxy.companyname.com:8080"

# install heirloom-mailx
RUN DEBIAN_FRONTEND=noninteractive apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      heirloom-mailx \
      sudo \
 && rm -rf /var/lib/apt/lists/*

# replace bsd-mailx with heirloom-mailx
RUN ln -sfn /usr/bin/heirloom-mailx /etc/alternatives/mailx

# entrypoint
ENTRYPOINT ["/fossology/docker-entrypoint.sh"]
```

My upgrade steps were just like below:

```sh
docker-compose down
vi Dockerfile  <-- change version from 3.7.0 to 3.8.1
docker-compose build --no-cache
docker-compose up -d
```

**Comment by GMishx** [comment]
Interesting. I am not sure what is going wrong here. I will give it a try from my end (upgrading from 3.7.0 to 3.8.1) and get back to you.

**Comment by drej** [comment]
Thank you very much.
I remember that I did a downgrade from 3.8.1 to 3.7.0 to see what would happen then back to 3.8.1 again. I don't know if that could be the reason of all this stuck :(
and I have more than 3.7.0 and 3.8.1 in my database:
![image](https://user-images.githubusercontent.com/1217733/114833539-aa5cc480-9e0a-11eb-9a49-d293d1dd790d.png)

**Comment by GMishx** [comment]
I used the exact same Dockerfile you shared and did the test with 3.7.0 and 3.8.1.
In a step by step manner:
1. I replaced the content of `Dockerfile` with what you shared for 3.7.0
2. Did `docker-compose up` and did some uploads.
    All good, they showed 3.7.0 agent versions.
3. I edited the `Dockerfile` and replaced 3.7.0 with 3.8.1, did `docker-compose down`.
4. Built a new image with `docker-compose build --no-cache`.
5. Did `docker-compose up` and uploaded another file.
    The new upload showed 3.8.1 as last agent version.

Also, this is what my agent table holds.
![image](https://user-images.githubusercontent.com/18077542/114867605-a765d200-9e12-11eb-89cd-16d130564a8f.png)

Can you please try running `/usr/local/lib/fossology/fo-postinstall` and restart the scheduler container and see if it helps?

**Comment by drej** [comment]
I think I figured out what's happened there.
Before I upgraded my FOSSology to 3.8.1, it was 3.7.0-rc1 on my server.
I upgraded FOSSology from 3.7.0-rc1 to 3.8.1 then downgraded it to 3.7.0 (not rc1!!!). Therefore I got an agent table like below:

- 3.7.0-rc1 agents
- 3.8.1 agents
- 3.7.0 agents

When I upgrade to 3.8.1 again, no new agent records add to agent table because it was there already.
I don't read the code but I guess FOSSology just look for the end of table to decide which agent to use.

**Comment by GMishx** [comment]
Thank you for detailed analysis on the situation @drej.
So, whenever the fossology scheduler runs, it sees if the agent with current version and revision already exists in DB. If not, it creates a new entry for it. Otherwise, leave it as is.
And at other places like UI and while inserting a new entry in DB, the last created agent ID is used from the table.

The upgrade/downgrade made FOSSology think it is using 3.7.0 version as it was last inserted in the table even though the process ran by scheduler are 3.8.1 versioned.

But IMO, this is a very rare occurrence where someone downgrades FOSSology to an earlier version.
