### ISSUE TITLE
Same file upload warning in a folder

### ISSUE THREAD

**Issue by sameer1046** [fossology/fossology#1966]
While uploading a file in a folder, if the same file is already uploaded it should give a warning that the file is already uploaded.

**Comment by Amit-Morade** [comment]
Can I work on this issue? I think I can solve this.

**Comment by GMishx** [comment]
Hi @Amit-Morade , thank you for your interest. I will assign the ticket to you then :+1:

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by GMishx** [comment]
Hello @prsmahajan, thank you for your interest. You can contact @Amit-Morade as he is also interested in working on this issue.

**Comment by namangirdhar16** [comment]
Hi @GMishx , i would like to work on this issue, can you suggest me how to get started ?

**Comment by Aditi-Roy-coder** [comment]
I would like to work on this issue.
