### ISSUE TITLE
RDF/XML report has invalid uri for NOASSERTION

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1968]
### Description

The RDF/XML report generated from fossology has invalid uri for NOASSERTION

#### How to reproduce

upload any oss package in fossology & download the sample rdf/xml report from it.
Try to validate those rdf report in official spdx online validator tool https://tools.spdx.org/app/validate/

#### Screenshots
**Error screenshot**
![image](https://user-images.githubusercontent.com/4498415/115599479-f660ab00-a2db-11eb-8e07-361437f300a8.png)

#### Solution:
From the [spdx/tools-java/issues/16#issuecomment-818930555](https://github.com/spdx/tools-java/issues/16#issuecomment-818930555)
I tried to replaceAll in notepad++ the rdf/xml report noassertion uri from
http://spdx.org/licenses/NOASSERTION to
http://spdx.org/rdf/terms#noassertion

and tried to validate again.
**Valid Screenshot**

![image](https://user-images.githubusercontent.com/4498415/115598052-46d70900-a2da-11eb-8346-b751f7df51a0.png)

### Versions

* Last commit id on master: Version: [3.10.0-rc2 ], Branch: [HEAD], Commit: [#359970] 
* Operating System (lsb_release -a): Ubuntu 18.04

**Comment by dineshr93** [comment]
This also affects two places during report import I guess

[reportImport/agent/SpdxTwoImportSource.php#L252](https://github.com/fossology/fossology/blob/fb2d5e54311f084d65ec63daa9f5261cc7085b27/src/reportImport/agent/SpdxTwoImportSource.php#L252)


[reportImport/agent/SpdxTwoImportSource.php#L263](https://github.com/fossology/fossology/blob/fb2d5e54311f084d65ec63daa9f5261cc7085b27/src/reportImport/agent/SpdxTwoImportSource.php#L263)

**Comment by dineshr93** [comment]
But the existing rdf file is parsed correctly by sw360 if we make this change then we have to make sure sw360 parser does not  throw error.

**Comment by GMishx** [comment]
Seeing https://github.com/fossology/fossology/blob/3599708c68c7868141162ca7c623c13d368b365c/src/spdx2/agent/template/spdx2-file.xml.twig#L46 and https://github.com/fossology/fossology/blob/3599708c68c7868141162ca7c623c13d368b365c/src/spdx2/agent/template/spdx2-package.xml.twig#L53 seems issues not in twig files but the issue might be here: https://github.com/fossology/fossology/blob/3599708c68c7868141162ca7c623c13d368b365c/src/spdx2/agent/spdx2utils.php#L61

**Comment by dineshr93** [comment]
[SPDX2_commons-lang3-3.9-sources.jar_1619444663-spdx.rdf.txt](https://github.com/fossology/fossology/files/6377530/SPDX2_commons-lang3-3.9-sources.jar_1619444663-spdx.rdf.txt)
attaching rdf report(added .txt for github support)

One more observation that I have noticed is 
 uri for noassertion is correct in some place of the file & incorrect in few places as well
