### ISSUE TITLE
test for fossology db in dbcreate is incorrect when test databases are present

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#197]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 3381, http://www.fossology.org/issues/3381
Original Date: 2012/09/06
Original Assignee: Dan Stangel

---

Not sure who should own this... I'll take a stab at Dan ;-)

 /usr/local/lib/fossology/dbcreate:
1. then check to see if the db already exists
   su postgres -c 'psql -l' |grep -q fossology

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:44 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
review

**Comment by GMishx** [comment]
The check is there for fossology DB in [dbcreate](https://github.com/fossology/fossology/blob/master/install/db/dbcreate.in#L25).
The test DBs must not be used for production and therefore, the exact match for `fossology` is required (as done).
