### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#1970]
Hi ,

I would like to redirect httpd (8081) to nginx (443) port.

Do you have any suggested config for nginx?
Do you have any solution for change /repo uri for / ?
Thanks,

**Comment by GMishx** [comment]
I have never worked with nginx before but maybe following can help
```nginx
server {
    listen 443 default_server;
    root /usr/local/share/fossology/www/ui;
    index index.php;
    location / {
        try_files $uri $uri/ /index.php;
        rewrite ^/api/(.*)$ /api/index.php break;
    }
    location ~/\.ht {
        deny all;
    }
}
```

And you can remove the `/repo` in apache too by just removing `Alias /repo /usr/local/share/fossology/www/ui` from `/usr/local/etc/fossology/conf/src-install-apache-example.conf` and adding `DocumentRoot /usr/local/share/fossology/www/ui` in either port 80 or 443 configuration file.

Hope this information will be helpful.

**Comment by C1ph3R-s** [comment]
Thanks,

Solution:

After you remove or comment out this line  `DocumentRoot "/var/www/html"`  in /etc/httpd/conf/httpd.conf, and modify to `DocumentRoot "/usr/local/share/fossology/www/ui"`, you could create you own nginx.conf conf.
```
#DocumentRoot "/var/www/html"
DocumentRoot "/usr/local/share/fossology/www/ui"
```
