### ISSUE TITLE
Limiting job status scope to child jobs only

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#1972]
### Description

While testing PR #1955, found following thing.
For an upload, there are only 2 failed jobs (readmeoss and ojo) but the REST API says `"status": "Failed"` for every single job even when all child job has `"status": "Completed"`.

Maybe the `"status"` of a job can be limited only to its child jobs' statuses.

#### Screenshots

![image](https://user-images.githubusercontent.com/18077542/116047028-469b8c80-a691-11eb-99c6-88c900026242.png)
![image](https://user-images.githubusercontent.com/18077542/116047178-734fa400-a691-11eb-901a-93e7df10c8e0.png)

#### How to reproduce

1. In an upload, run an agent and kill it.
2. Run another agent for the same upload or download a report to create new job.
3. Check the jobs page in UI or GET data from `/jobs` endpoint.

### Versions

* Tested against #1955

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, can you suggest me to get started?

**Comment by GMishx** [comment]
Thank you for your interest @prsmahajan . I will assign the ticket to you.

And for pointers, when PR #1955 gets merged, the following functions needs to be updated:
https://github.com/fossology/fossology/blob/9053f619aaab5e59ed37bdbf86f2a2969f8c76de/src/www/ui/api/Controllers/JobController.php#L223 https://github.com/fossology/fossology/blob/9053f619aaab5e59ed37bdbf86f2a2969f8c76de/src/www/ui/api/Controllers/JobController.php#L277

Earlier, the job status was calculated based on all the jobs. Now, it needs to be limited to the jobqueue under a given job's `jobs[]` array. The logic will be same, like for the given screenshot, the job status will be "Completed" as all the jobqueue under the `jobs[]` are "Completed".

**Comment by Rahulrajak1710** [comment]
Hi,
I am rahul,a cse undergraduate.I am new to open source contributions but I am well aware of Java,C,Html,Css,JavaScript,React.js.I would love contribute in  organization  could you please tell me how to get started?
Hoping to hear from you soon.
Regards
Rahul

**Comment by rohitpandey49** [comment]
@GMishx I am not getting clearer idea on how to approach it. Can you please help me to reproduce it?

**Comment by rohitpandey49** [comment]
Steps screenshots will work.

**Comment by ArijeetBanerjee** [comment]
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖
