### ISSUE TITLE
user change do not make sense

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#198]
---

Author Name: **larry shi** 
Original Redmine Issue: 3405, http://www.fossology.org/issues/3405
Original Date: 2012/09/10
Original Assignee: larry shi

---

when you change the user fossy via other admin user (e.g. admin/admin), enable 'Blank the user's account. This will will set the password to a blank password.', then set fossy/fossy second time, find on Edit A User page, 'Blank the user's account. This will will set the password to a blank password.' is not select, it should, if you want to use password again, you have to reset the password again, do not make sense.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2013/01/08 19:53:44 +0000

---

Bob & I are not sure how to interpret this issue.  Please discuss with us or add more detail to this issue describing the problem.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/01/09 09:55:19 +0000

---

1. login with fossy/fossy
2. add a admin account as admin/admin
3. logout and login with admin/admin
4. click on [Admin]-->[Users]-->[Edit Users], 
5. edit the user fossy, get [Blank the user's account. This will will set the password to a blank password] checked. save.
6. logout, then login with admin/admin
7. click on [Admin]-->[Users]-->[Edit Users], edit the user fossy, find that [Blank the user's account. This will will set the password to a blank password] is not checked.

it is not a critical defect.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/01/18 19:59:36 +0000

---

If the user's password is already blank then the [Blank the user's account] should not be checked.  The whole question should just be greyed out and unavailable.  We don't want to check that box if the password is already blank because that means to blank it out again, which is confusing since it is already blank.

Also, the text

  Blank the user's account. This will will set the password to a blank password.

Is not very good.  How about something like:

  Require no password

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/01/18 20:01:56 +0000

---

This is not a high priority defect.  Larry, if it is easy to fix then feel free to do so.  If you don't want to bother, feel free to change it from a High to Normal priority.

I've changed the Rank to 99

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/05/28 08:31:16 +0000

---

This is not a high priority defect

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4569/change_user.png
