### ISSUE TITLE
API simultaneous scan Error: How to increase no of simultaneous scan from 10 to 20

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1980]
### Description
I have been triggering 50 fossy scan simultaneously via API. It is showing below message in api response if it simul scan reaches 10.
**Max 10 FOSSology Process can be triggered simultaneously. Please try after sometime.**

How to increase no of simultaneous scan from 10 to 20 & more

#### How to reproduce
Been using details from below api guide for triggering the fossy scan for 20 set of components

fossy_url/resource/docs/api-guide.html#resources-trigger_fossology_process-get

I am getting below log output response 

### Versions

* Last commit id on master: Version: [3.10.0], Branch: [HEAD], Commit: [#82f63a]
* Operating System (lsb_release -a): Ubuntu 18.04.5

### Logs

{
  "content" : {
    "message" : "Max 10 FOSSology Process can be triggered simultaneously. Please try after sometime."
  },
  "_links" : {
    "self" : {
      "href" : "URL/resource/api/releases/8d0af127ea21acbe08f58940b1420a76/checkFossologyProcessStatus"
    }
  }
}

**Comment by GMishx** [comment]
Hello @dineshr93 ,

I feel these endpoints and responses are not exposed by FOSSology, maybe SW360?

Any ways, you can change the number of simultaneous jobs FOSSology can run by editing `/etc/fossology/fossology.log` or `/usr/local/etc/fossology/fossology.conf` and look out for following lines:
```
[HOSTS]
localhost = localhost /usr/local/etc/fossology 10
```

The format is `{simple name} = {qualified domain name} {configuration directory} {Max simultaneous agents to run} `
Thus change the value 10 to whatever your sever can handle and restart the scheduler.

For more information, please check https://github.com/fossology/fossology/wiki/Job-Scheduler#fossologyconf

**Comment by dineshr93** [comment]
@GMishx  Thanks for the info. Yes i am triggering the scan via sw360

**Comment by dineshr93** [comment]
Hi @GMishx Two more question. 

Since I am runnng the fossy in docker container I think to increase the peformance of machine I need to install fossy from src or increase docker ram right? 
after changing the fossology.conf how to restart the scheduler? sudo service apache2 restart right? or is there any step I need to take care?

**Comment by GMishx** [comment]
Hi @dineshr93 ,

> Since I am runnng the fossy in docker container I think to increase the peformance of machine I need to install fossy from src or increase docker ram right?

I am not 100% sure but yeah that will improve nomos, copyright and monk at least. Otherwise installing on the machine allows FOSSology to use the complete resources.

> after changing the fossology.conf how to restart the scheduler? sudo service apache2 restart right? or is there any step I need to take care?

You need to restart the fossology daemon `sudo service fossology restart` (do check the docker logs, it sometimes required 2 restarts).

**Comment by dineshr93** [comment]
Hi @GMishx  One more question if I plan to migrate the docker setup to native from source setup, how to retain the existing data which is currently available in docker volumes?

**Comment by GMishx** [comment]
You need to connect to the docker container running the fossology and get a dump of fossology database.
```shell
pg_dump --create --dbname=fossology --host=<host-running-postgres> --username=fossy --file=dbdump.sql
```

Then on your other host, restore it from the `dbdump.sql` file.
```shell
psql --echo-errors --file=dbdump.sql --host=localhost --username=fossy
```

And if you are migrating from old Postgres version, you might want to [re-code DB to UTF-8](https://github.com/fossology/fossology/wiki/Migration-to-UTF-8-DB#fixing-pg_dump-fast)
