### ISSUE TITLE
Missing response , /repo/api/v1/uploads, api

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#1984]
Hi, 

I have a working solution for automate my licence check, but unfortunatelly my api does not work well.
So when I want to list my upload ids from api, it give back for me empty response.

Request
`/repo/api/v1/uploads`

Response:
`[]`

Until now, it worked well.

Do you have any idea for that?

Thanks,

**Comment by GMishx** [comment]
Can you please check the Apache error logs `/var/log/apache2/error.log`?
Or if you are running on Docker, then please check the container logs `docker logs -f <container-id>`

**Comment by C1ph3R-s** [comment]
Hi,

I use httpd with nginx, so you can check logs below (no any error):

==> access_log <==
[07/May/2021:09:50:19 +0200] "GET /repo/api/v1/uploads HTTP/1.1" 200 2 "-" "curl/7.61.1"
[07/May/2021:09:50:21 +0200] "GET /repo/api/v1/uploads HTTP/1.1" 200 2 "-" "curl/7.61.1"
 [07/May/2021:09:50:22 +0200] "GET /repo/api/v1/uploads HTTP/1.1" 200 2 "-" "curl/7.61.1"

==> nginx access.log <==
[07/May/2021:09:52:37 +0200] "GET /repo/api/v1/uploads HTTP/2.0" 200 2 "-" "curl/7.61.1"
[07/May/2021:09:52:42 +0200] "GET /repo/api/v1/uploads HTTP/2.0" 200 2 "-" "curl/7.61.1"
[07/May/2021:09:52:43 +0200] "GET /repo/api/v1/uploads HTTP/2.0" 200 2 "-" "curl/7.61.1"

I have restarted all services but nothing changed, any idea?

**Comment by GMishx** [comment]
Anything on the error logs?

Can you please try `/repo/api/v1/uploads/<upload-id>` and see if it works?

**Comment by C1ph3R-s** [comment]
Sure, where can i check upload id in gui? Unfortunately, I always check these with api calls.

**Comment by C1ph3R-s** [comment]
Meanwhile I have found, it

<img width="581" alt="Screenshot 2021-05-07 at 10 04 49" src="https://user-images.githubusercontent.com/12477373/117418482-c3452b00-af1b-11eb-94ba-6d32af99211d.png">

so the response:

```
/repo/api/v1/uploads/952

{"code":403,"message":"Upload is not accessible","type":"ERROR"}
```

**Comment by GMishx** [comment]
> In any other scenarios work well, for example when I request folder list it give back well.

Oh, in that case, there can only be something in the codebase being wrong which should be noted in the error log.

> Sure, where can i check upload id in gui? Unfortunately, I always check these with api calls.

In the GUI, if you open any of the upload, you get this URL> `http://localhost/repo/?mod=license&upload=44&folder=1&item=60301&show=quick` and there is the upload id, 44.

**Comment by GMishx** [comment]
> {"code":403,"message":"Upload is not accessible","type":"ERROR"}

So maybe you are in wrong group? Do check header `groupName: <your-group>`

**Comment by C1ph3R-s** [comment]
That's could be an options, how can I check that?

**Comment by GMishx** [comment]
You can do that in two ways:

1. From GUI, check the group from the drop-down in the top right corner.
2. From REST, send the required group name via `groupName` header.

**Comment by C1ph3R-s** [comment]
I have a user for uploads (username:asdf), so currently i'm use `asdf`  user in `asdf` group.

**Comment by C1ph3R-s** [comment]
> Oh, in that case, there can only be something in the codebase being wrong which should be noted in the error log.

Where can I find this error log?

**Comment by C1ph3R-s** [comment]
I have generated a new token, and it gave back this, now:

```
/repo/api/v1/uploads


<script>(function (c) {if (c && c.groupCollapsed) {
c.log("%c%cdefault%c %cDEBUG%c DI container setup (cached: yes) (1.040ms)", "font-weight: normal", "background-color: blue; color: white; border-radius: 3px; padding: 0 2px 0 2px", "font-weight: normal", "font-weight: bold", "font-weight: normal");
c.log("%c%cdefault%c %cDEBUG%c bootstrap (2.012ms)", "font-weight: normal", "background-color: blue; color: white; border-radius: 3px; padding: 0 2px 0 2px", "font-weight: normal", "font-weight: bold", "font-weight: normal");
c.log("%c%cdefault%c %cDEBUG%c setup init (115.160ms)", "font-weight: normal", "background-color: blue; color: white; border-radius: 3px; padding: 0 2px 0 2px", "font-weight: normal", "font-weight: bold", "font-weight: normal");
c.log("%c%cdefault%c %cDEBUG%c prepare 'Fossology\\UI\\Api\\Helper\\DbHelper::getTokenKey.getTokenSecret' took 0.448ms", "font-weight: normal", "background-color: blue; color: white; border-radius: 3px; padding: 0 2px 0 2px", "font-weight: normal", "font-weight: bold", "font-weight: normal");
```

**Comment by GMishx** [comment]
I am not sure what is going on there. But your last message definitely means something went wrong.

You need to check your error logs. It should be marked with `error_log` directive in your nginx config (see [this](https://linuxize.com/post/nginx-log-files/)).

**Comment by C1ph3R-s** [comment]
I pasted logs here: https://github.com/fossology/fossology/issues/1984#issuecomment-834148484 , but unfortuantelly not any error in these.

Do you have another idea?

**Comment by C1ph3R-s** [comment]
Probably It will be a permission issue.

**Comment by GMishx** [comment]
https://github.com/fossology/fossology/issues/1984#issuecomment-834148484 only contains access logs. Please check for error logs configured for nginx.

Also, not getting the uploads in `/api/v1/uploads` can be a permission issue, but getting `<script>(function (c) {if (c && c.groupCollapsed) {` in response means a 500 error on server.

**Comment by C1ph3R-s** [comment]
Thanks, I have solved the issue. 
I have another question, Do you have an idea to kill all jobs in queue?

**Comment by GMishx** [comment]
Nice that the issue was resolved.

And the jobs can be killed only from the GUI at the moment. You need to goto Jobs > My Recent jobs.

**Comment by msalvinik** [comment]
@C1ph3R-s how do you solved the issue? thanks

**Comment by ChenZhaobin** [comment]
@C1ph3R-s how did you solve the issue? thanks
