### ISSUE TITLE
dpkg-scansources not included in new versions of 'dpkg-dev' - breaks project builder

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#199]
---

Author Name: **Dan Stangel** 
Original Redmine Issue: 3489, http://www.fossology.org/issues/3489
Original Date: 2012/09/18
Original Assignee: Dong Ma

---

According to defect #3453, the latest versions of dpkg-dev do not include the dpkg-scansources utility.  This prevents project builder from building package repositories for debian and ubuntu packages, which breaks the nightly package build.

The workaround for #3453 was to downgrade the version of dpkg-dev to an earlier version that still includes dpkg-scansources.  However this does not seem to be a good long-term solution since we will need to continue building packages on many future versions of Debian and Ubuntu that will not support older versions of the Debian dpkg tool chain.

So we need to figure out how to fix this for future package builds.

Dan sent an email to Bruno and Vincent on 2012-09-18 to start the conversation and see if this is something that might need to be addressed "Upstream" in the project builder project, or if FOSSology needs to address it.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:45 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
did not see this in recent attempts to build with project builder.
