### ISSUE TITLE
Is there a way to check upload already exists & Avoid double upload for fossy clearing

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#1990]
### Description
Is there a way to check a file to be upload, already exists & Avoid double upload for fossy clearing or in other words is there a way to find & reuse existing spdx results via sw360

    Last commit id on master: Version: [3.10.0], Branch: [HEAD], Commit: [#82f63a]
    Operating System (lsb_release -a):

**Comment by GMishx** [comment]
Hello @dineshr93 , there is an endpoint called `/filesearch` build for this. Please check if this will solve your purpose:
https://github.com/fossology/fossology/blob/e779fb062e5b4a5f91da2a19e86150b7c0442835/src/www/ui/api/documentation/openapi.yaml#L1030-L1061

**Comment by dineshr93** [comment]
Thanks.. When working with sw360 it automatically uploads to fossy from sw360 without checking if already exists in a given folder id.

**Comment by GMishx** [comment]
@dineshr93 Then SW360 can use this endpoint and provide the feature to prevent duplicate uploads.
