### ISSUE TITLE
question/save results of analysis without source code

### ISSUE THREAD

**Issue by alexeyhohlov** [fossology/fossology#1999]
Dear all,
Is it possible to remove all sources after the scanning on copyrights/licenses, but save information about the found licenses and don't store scanned code?

**Comment by GMishx** [comment]
Hello @alexeyhohlov , you can export the license/copyright scan results in forms of various reports. Most popular being Unified report and SPDX RDF.

The SPDX and DEP5 reports are machine readable and can be translated with help of tools.

Do checkout our video: https://youtu.be/TZqU5ZALI7U?t=3570

There is also an option to export the results in form of CSVs. While in an upload, look for **"Export list"** in the yellow bar and you will have various options.

**Comment by GMishx** [comment]
Closing the issue for now, please reopen @alexeyhohlov if required.
