### ISSUE TITLE
Migrate releases to GitHub

### ISSUE THREAD

**Issue by xizhao** [fossology/fossology#20]
It may be a good idea to put releases on github, or even fully migrate it.

**Comment by mcjaeger** [comment]
I would say, it would be good to have releases available. github or new webpage.

**Comment by mcjaeger** [comment]
(this is ongoing with fobuild.int.fossology.org)

**Comment by mcjaeger** [comment]
actually, releases are there, question is how to deal with new releases and automate this, but this is issue is here is maybe too general for this.
