### ISSUE TITLE
Info, data store, git, on-premise

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#2002]
Hi,

I have some questions about the workflow in fossology.

So first of all, where store datas when it clone a repo from git?
How can I check, fossy will not upload my datas to cloud or anywhere?
Fossology it an on-premise solution right?

Sorry but I didn't find any info about these on the website (or I have missed something)

Thanks.

**Comment by GMishx** [comment]
Hello @C1ph3R-s ,

When you upload a file from GIT, it is cloned in `/srv/fossology/repository/$(hostname -f)`. Once cloning is complete, the contents are them moved inside `/srv/fossology/repository/localhost/` based on file hash. The cloned folder is then removed from disc.

To check the location where your files are stored, please check the `path` variable in `/usr/local/etc/fossology/fossology.conf` or `etc/fossology/fossology.conf` (depending on your installation), [refer this for more](https://github.com/fossology/fossology/wiki/Job-Scheduler#fossologyconf).

And yes, FOSSology is completely on-premise.

I hope I have answered your query.

**Comment by C1ph3R-s** [comment]
Thanks, That is what I have searched. :)
