### ISSUE TITLE
Fossology Api, uploads, folder contents

### ISSUE THREAD

**Issue by C1ph3R-s** [fossology/fossology#2003]
Hi,

I have a problem with API. 

So when I want to list my uploads, with this command:

`curl -k -s -S -X GET -H "Authorization: Bearer $fossy_api" $Fossology_API/uploads?limit=1000 | jq -r '.[]`

It gives me back only the first folder content. Do you have any idea for that?

**Comment by deveaud-m** [comment]
According to the OpenAPI specification, the `limit` option must be in the header: https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml#L271

Your cURL command should be build like this:
```
curl -k -s -S -X GET -H "Authorization: Bearer $fossy_api" -H "limit: 1000" $Fossology_API/uploads
```

Could you give it a try?

You can also use the OpenAPI editor to better visualize and understand how to use parameters for your rest calls: https://editor.swagger.io/, use the [raw OpenAPI spec](https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml) from this repository as `File->Import URL->https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml`.

@GMishx maybe it would make sense to integrate a Swagger UI with the last OpenAPI spec as Github Pages, WDYT?

**Comment by GMishx** [comment]
Adding to reply of @deveaud-m , the endpoint also has `recursive` header. You can set it to `true` or `false` to include child folders or not.

**Comment by Aman-Codes** [comment]
Also there are some GitHub actions available like [this](https://github.com/peter-evans/swagger-github-pages) to automate the deployment to GitHub pages.
I have even deployed it on https://aman-codes.github.io/SwaggerApiDoc/ long time back

**Comment by C1ph3R-s** [comment]
> According to the OpenAPI specification, the `limit` option must be in the header: https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml#L271
> 
> Your cURL command should be build like this:
> 
> ```
> curl -k -s -S -X GET -H "Authorization: Bearer $fossy_api" -H "limit: 1000" $Fossology_API/uploads
> ```
> 
> Could you give it a try?
> 
> You can also use the OpenAPI editor to better visualize and understand how to use parameters for your rest calls: https://editor.swagger.io/, use the [raw OpenAPI spec](https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml) from this repository as `File->Import URL->https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml`.
> 
> @GMishx maybe it would make sense to integrate a Swagger UI with the last OpenAPI spec as Github Pages, WDYT?

@deveaud-m Thanks, This setup has been solved my issue
