### ISSUE TITLE
REST API: filter criteria for list of uploads

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology#2007]
### Description

In our continuous effort to automate Fossology workflows, we regularly check all uploads available on a given instance.

When the instance is under heavy utilization, listing all available uploads can consume lots of resources.  
 
Having the possibility to filter the list uploads according to different criteria would help us a lot, e.g.:

* all uploads with clearing status `closed`
* new uploads since xx.xx.xx
* upload with given strings in the description
* ...

**Comment by prsmahajan** [comment]
Hi, I want to contribute to this issue, Can anyone suggest ways to get started?

**Comment by deveaud-m** [comment]
> Hi, I want to contribute to this issue, Can anyone suggest ways to get started?

I suppose you'd need to understand how uploads are retrieved from the Fossology DB and which SQL parameters can be added to filter those.

Afterwards, that's just a matter of providing the corresponding options via the REST /uploads endpoint.

But I think @GMishx can provide more details on the way to go.

**Comment by GMishx** [comment]
Here is the Upload Controller which handles the calls to `/uploads` endpoint: https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/UploadController.php#L97

It uses Db Helper functions where you'll find the SQL queries: https://github.com/fossology/fossology/blob/master/src/www/ui/api/Helper/DbHelper.php#L98

The relevant information should be contained as columns of `upload` and `upload_clearing` tables.
