### ISSUE TITLE
contain [Admin] menu on the welcome page 1st time

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#201]
---

Author Name: **larry shi** 
Original Redmine Issue: 3561, http://www.fossology.org/issues/3561
Original Date: 2012/09/27
Original Assignee: larry shi

---

in 2.1.0, after you install fossology successfully, visit http://hostname/repo/ 1st time, will see [Admin] menu, then fresh the current page, this menu disappear.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/09/27 18:40:40 +0000

---

adding to iteration 10 (include in 2.1.0-RC2)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/02 19:08:39 +0000

---

Larry, I can't reproduce this behavior.  Perhaps while you are in Fort Collins you can show me.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/02 22:13:16 +0000

---

Removing IterNum and Target version and reducing priority to Normal because this is a harmless error probably the result of a cached page.  But it represents no escalation of privileges so is harmless.

**Comment by mcjaeger** [comment]
today it is home and help.
