### ISSUE TITLE
verify install locations

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#202]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 3621, http://www.fossology.org/issues/3621
Original Date: 2012/10/05
Original Assignee: Bob Gobeille

---

After a source and binary install, verify that the installed files get installed in the correct locations.
Also verify that make, apt-get and rpm remove removes all the files.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:50 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
super old ticket - still relevant?

**Comment by bobgob** [comment]
This is just basic install testing which all needs to be redone outside of the HP infrastructure anyway.  Closing.
