### ISSUE TITLE
Create a single document manual

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#203]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 3645, http://www.fossology.org/issues/3645
Original Date: 2012/10/12

---

As suggested by Michael Silberman, we could really use a manual that is a single document that could be downloaded.

**Comment by mcjaeger** [comment]
could.

**Comment by mcjaeger** [comment]
there is a single page manual https://www.fossology.org/get-started/basic-workflow
