### ISSUE TITLE
REST API: Pagination feature in the Search request

### ISSUE THREAD

**Issue by Shruti3004** [fossology/fossology#2031]
### Description

Pagination feature for the `/search` request, on the UI we are seeing the files at different pages in the current implementation, but on making the request it is giving all the files at once and we have to apply filter on our UI but that will anyhow create the load on server.

#### Screenshots

![Screenshot from 2021-06-24 21-34-04](https://user-images.githubusercontent.com/56133783/123296061-efe8ec80-d533-11eb-9b59-d5a4c7858a4d.png)

**Comment by Shruti3004** [comment]
@GMishx while making the search page i get to know actually it is giving 100 responses only but thre is no pagination thing mentioned in the swagger, and how we will get the further files.

**Comment by GMishx** [comment]
> @GMishx while making the search page i get to know actually it is giving 100 responses only but there is no pagination thing mentioned in the swagger, and how we will get the further files.

Apparently, there is already a limit and pagination in the library. Just need to expose it from API.

https://github.com/fossology/fossology/blob/6fcd4005a4b5783e67377231fdca11e5d5dc7c4a/src/www/ui/search-helper.php#L42

**Comment by coder-whale** [comment]
I can take up this feature request if the enhancement is still required. Please revert if that is indeed the case.
