### ISSUE TITLE
upload from server fails when the file path contain special character

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#204]
---

Author Name: **larry shi** 
Original Redmine Issue: 3807, http://www.fossology.org/issues/3807
Original Date: 2012/12/11
Original Assignee: larry shi

---

when path contain space character
Upload failed for /home/bobg/json statement.txt: '/home/bobg/json\ statement.txt' does not exist.

The file really does exist. It has world read access.

also, should confirm if other special characters work or not.

**Comment by mcjaeger** [comment]
space, paragraph sign, percent sign works, dollar sign not, but ...
