### ISSUE TITLE
apt-get purge fossology does not delete repository directory

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#205]
---

Author Name: **larry shi** 
Original Redmine Issue: 3813, http://www.fossology.org/issues/3813
Original Date: 2012/12/12
Original Assignee: Dong Ma

---

 after I run apt-get purge fossology* -y, find that all the fossology related files are deleted except /srv/fossology/

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/12/12 22:32:40 +0000

---

I don't think we want apt-get purge to remove the repository.  Removing the repository should be a manual step, so it doesn't get removed accidentally.

Other opinions?

**Comment by maximilianhuber** [comment]
I will close this issue, since there was no feedback new and the mentioned opinion by Mary Laser sounds good.

Please reopen if someone is of an other opinion.
