### ISSUE TITLE
REST API: default group on login

### ISSUE THREAD

**Issue by Aman-Codes** [fossology/fossology#2054]
### Description

What default group should be displayed on the header when a user with multiple accessible groups logs in.
Currently, get request to `/groups` only returns the list of all the accessible groups.

#### Steps followed and expected result

API to return the default group of the user. 

#### Screenshots

![image](https://user-images.githubusercontent.com/54680709/125727193-49aaa126-6a2a-4432-97bb-d7eb4db732e5.png)

**Comment by teekhandekar** [comment]
Can I  work on this ? please

**Comment by GMishx** [comment]
Sure @teekhandekar but note the fix has to be applied to https://github.com/fossology/fossology repository as data is required from REST API.

You can look at https://github.com/Shruti3004/FOSSology-REST-API/pull/8 for sample implementation.
