### ISSUE TITLE
Wrong description in tooltips

### ISSUE THREAD

**Issue by eschenbachertq** [fossology/fossology#2061]
### Description

The descriptions for two tooltips when determining the clearing decision type are incorrect:

- "Do not use"
![image](https://user-images.githubusercontent.com/7579200/126286424-8d2166d5-0e36-4f33-8818-7d454e7facb5.png)

- "Identified"
![image](https://user-images.githubusercontent.com/7579200/126286443-a2a9c39f-780a-4ccf-94d9-5c065292fd07.png)

### Versions

* Release 3.10.0 (commit 07f8e50592add625560b9a5c146ba59cbfc426da)

**Comment by DawnArchi01** [comment]
Can you assign me for this task ? I would be glad to work on it

**Comment by Aditi-Roy-coder** [comment]
I want to work on this issue.

**Comment by sameer786m** [comment]
i would like to work on this. please assign me this task

**Comment by DawnArchi01** [comment]
@eschenbachertq @GMishx I've made a PR #2142 on this particular issue . Please review and let me know if some changes are to be done .

**Comment by Rahulrajak1710** [comment]
i would like to work on this. please assign me this task
