### ISSUE TITLE
Clearing status remains unchanged

### ISSUE THREAD

**Issue by eschenbachertq** [fossology/fossology#2078]
### Description

The starting point is a file for which the scanners have not found any license-relevant information, the scanner result is "No_license_found". 
![image](https://user-images.githubusercontent.com/7579200/128699738-208fffec-1f60-4879-9b2d-ec066485808e.png)

If you now set the Clearing Decision Type manually to "No license known" 
![image](https://user-images.githubusercontent.com/7579200/128699835-f90f8f4b-23d2-47e1-a106-a19f87ed74ef.png)
the cleared counter is set to 1, but the clearing status remains unchanged (gray instead of red)
![image](https://user-images.githubusercontent.com/7579200/128699934-7202cc31-1674-4609-acae-02958784d03e.png)

### Question

**Is this behavior wanted or shouldn't the clearing status be set to green?**

### Versions

* Release 3.10.0 (commit 07f8e50)

**Comment by GMishx** [comment]
If the file does not contain any license, the status remains grey. It will turn to green or red iff it contains any license.

Hope it answers your question. Please reopen the issue if needed.
