### ISSUE TITLE
Create an API end-point for copyright 

### ISSUE THREAD

**Issue by itssingh** [fossology/fossology#2081]
### Description

Add a new API end-point for showing detected copyright similar to license `uploads/{id}/licenses`.  

#### Expected result
```json
[
  {
    "filePath": "path/to/LICENSE",
    "findings": {
      "scanner": [
        "MIT",
        "BSD-3-Clause"
      ],
      "conclusion": [
        "MIT",
        "GPL-2.0"
      ],
      "copyright": [
        "Copyright (C) 2017-2020 Free Software Foundation, Inc.",
        "Copyright (C) 1991-2020 Free Software Foundation, Inc."
      ]
    }
  }
]
```

#### Screenshots current status

![image](https://user-images.githubusercontent.com/43489890/129477797-12a51e0e-e8e5-4d46-988f-b742d6a8b0b7.png)

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by SidharajYadav** [comment]
I would like to work on this issue.
please guide me

**Comment by Rahulrajak1710** [comment]
Hi,
I am rahul,a cseundergraduate.I am new to open source contributions but I am well aware of Java,C,Html,Css,JavaScript,React.js.I would love contribute in  organization  could you please tell me how to get started?
Hoping to hear from you soon.
Regards
Rahul

**Comment by JOY2OP** [comment]
I would like to work on this issue
