### ISSUE TITLE
Documentation of precise steps to install FOSSOLOGY in WSL2 along with steps to overcome issues associated with it.

### ISSUE THREAD

**Issue by reachaadrika** [fossology/fossology#2097]
### Description
1 . Steps to install the FOSSOLOGY  repository in WSL2.
2.  Steps of how to  overcome some issues that are associated with installation in WSL2  . (One of them is the "postgresql error")

Addition of these steps would make it easier for new contributors who are using WSL2 to install Fossology.

**Comment by reachaadrika** [comment]
If this is a valid issue , Can I work on this ?

**Comment by GMishx** [comment]
Using Virtual Box or Vagrant will be much more preferred instead of WSL. The architecture of WSL is slightly different than of native Linux.

**Comment by reachaadrika** [comment]
@GMishx Should I close this issue ?

**Comment by GMishx** [comment]
You can submit documentation if you prefer. We can put it on wiki.
But we would not like to publish anything resembling "FOSSology officially supports WSL".
As long as it's an experimental step, it should be fine.

**Comment by reachaadrika** [comment]
@GMishx Should I share the changes made in documentation here ?

**Comment by GMishx** [comment]
Hey, that's great. Yeah you can drop the patch file here for review or over Slack and we can put them on Wiki.

**Comment by reachaadrika** [comment]
Done .!

**Comment by reachaadrika** [comment]
Done with the changes in wiki .
