### ISSUE TITLE
investigate separating functional tests 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#210]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 3981, http://www.fossology.org/issues/3981
Original Date: 2013/03/12
Original Assignee: Dong Ma

---

investigate separating functional tests so that we can run them with package installs.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2013/08/06 01:17:22 +0000

---

defer to next release as not high priority

**Comment by mcjaeger** [comment]
not picked up since August 2013. Maybe testing will change in future.
