### ISSUE TITLE
Selected files in a folder should be editable in one step

### ISSUE THREAD

**Issue by rahulmohang** [fossology/fossology#2104]
#### Steps followed and expected result
1. Select an upload. 
2. Browse to any folder. 
3. In the files view table, go to 'Actions' column. 
4. Select some files to mark a decision. 
5. Only the action, 'MarkAsIrrelevant' is possible on multiple files selection. 
6. Request is to provide similar functionality to edit license decisions on selected multiple files in a folder. Now, edit applies only to individual files. 

#### Screenshots
![image](https://user-images.githubusercontent.com/54024745/135594101-730d986e-d78e-421c-9f8e-f1be9860c60a.png)

**Comment by GMishx** [comment]
A suggestion: We can remove the `Download` and `Edit` from each row. Add a drop down in the header of the table and Download/Edit selected files.

**Comment by rahulmohang** [comment]
Yes, that is a good suggestion.

**Comment by rahulmohang** [comment]
@GMishx , is there any update on this?

**Comment by GMishx** [comment]
I think yes, it has been implemented. Let me find the corresponding PR

**Comment by GMishx** [comment]
I guess it was #1774

Can you please check and close the issue if fixed?

**Comment by rahulmohang** [comment]
Sorry @GMishx, just saw this message. I have been using the feature for some time. Thank you.
