### ISSUE TITLE
Add a 'Clean Text' button to the 'License Text' field

### ISSUE THREAD

**Issue by rahulmohang** [fossology/fossology#2108]
### Description

It would be good if  a 'Clean Text' button is added to the 'License Text' field. 

#### Steps followed and expected result

1. Copy text of a license from the file browser window. 
2. Click on the 'License Text' field to paste the text in to the field. 
3. If the text has delimiters, it has to be manually removed now. 
4. It would be helpful if the delimiters could be removed with a button.

**Comment by rahulchandra17** [comment]
Hey I want to work on this issue please assign

**Comment by thegeekymuggle** [comment]
Hi, I would love to work on this issue

**Comment by Rahulrajak1710** [comment]
Hi, I would love to work on this issue

**Comment by rohitpandey49** [comment]
Raised PR #2157

**Comment by 19shivii** [comment]
I am interested in working on this. Please assign me.
