### ISSUE TITLE
delete folder is too slow

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#211]
---

Author Name: **larry shi** 
Original Redmine Issue: 3999, http://www.fossology.org/issues/3999
Original Date: 2013/03/13
Original Assignee: Dong Ma

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/01 01:42:52 +0000

---

This is a difficult problem because of the way the repository is structured.  Each file is an individual inode.  So if you delete an upload with 3 million files, it's going to take a while.  We also need to profile where the time is being spent - deleting db records or deleting files.  If it is from deleting files we might want to consider a different repository structure.

**Comment by mcjaeger** [comment]
how slow is too slow? From the current ops, we did not encounter any issue, maybe SSD or high IOPS filesystems have compensated this.
