### ISSUE TITLE
Display 'All' option in license browser table

### ISSUE THREAD

**Issue by rahulmohang** [fossology/fossology#2110]
### Description

There are use cases where a display all files inside a folder in the 'License Browser' view could be helpful. e.g.. When we do an edit function for multiple files, it would be nice to display all files in a single window, with a scroll bar, so that all the files of a folder could be brought under the scope of the edit operation. Please see the screenshot.

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

#### Screenshots

![image](https://user-images.githubusercontent.com/54024745/136794984-9da09079-f0eb-4ad1-8112-a76eee524d0f.png)

**Comment by DawnArchi01** [comment]
Hey ! I want to contribute . How can I help ? 
@GMishx @rahulmohang

**Comment by rahulmohang** [comment]
@DawnArchi01, thank you. Please see the drop down pointed to in the attached picture. Now, there is no option to display all files in a single widow. There is a limit of 100 files. It would be better to display all files in a window.

**Comment by DawnArchi01** [comment]
Ok. Please assign me the task

**Comment by rohitpandey49** [comment]
Raised PR #2155

**Comment by GMishx** [comment]
Closed by #2155
