### ISSUE TITLE
Identification of licenses by Fossology scanners may be based on latest SPDX identifiers

### ISSUE THREAD

**Issue by rahulmohang** [fossology/fossology#2111]
### Description

As per https://spdx.org/licenses/, the SPDX identifiers used for 'or later' licenses have changed from the '+' sign to 'or later'. Fossology scan still identifies the identifiers that are deprecated.  

#### How to reproduce

1. Please scan a source package. 
2. Go to a file with any license that allows it to be licensed under a later version. 
3. Fossology scanner identifies the identifiers with the '+'.
4. All such licenses should be identified by the Fossology scanner using the latest SPDX identifiers. 

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by tngraf** [comment]
I totally agree

**Comment by rahulmohang** [comment]
@GMishx @shaheemazmalmmd

**Comment by GMishx** [comment]
PR #2363 इस working on it.

**Comment by rahulmohang** [comment]
Thank you.

**Comment by GMishx** [comment]
PR #2363 is merged. Closing the issue. Please reopen if needed.
