### ISSUE TITLE
move folder fails

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#212]
---

Author Name: **larry shi** 
Original Redmine Issue: 4029, http://www.fossology.org/issues/4029
Original Date: 2013/03/13
Original Assignee: larry shi

---

have a folder structure
test1
test1/test2
test1/test2/test3

try to move test1 to test3, then will get error msg below, I know this move is incorrect, but we should avoid this move, also this failure happened in a previous testing( I forgot the test method). 

Fatal error: Maximum function nesting level of '100' reached, aborting! in /usr/local/share/fossology/lib/php/common-plugin.php on line 187 Call Stack: 0.0003 655608 1. {main}() /usr/local/share/fossology/www/ui/index.php:0 0.1787 13468456 2. ui_browse->Output() /usr/local/share/fossology/www/ui/index.php:51 0.1792 13469176 3. ui_browse->ShowFolder() /usr/local/share/fossology/www/ui/ui-browse.php:486 0.1830 13472656 4. FolderListDiv() /usr/local/share/fossology/www/ui/ui-browse.php:285 0.1848 13477864 5. FolderListDiv() /usr/local/share/fossology/lib/php/common-folders.php:508 0.1862 13483056 6. FolderListDiv() /usr/local/share/fossology/lib/php/common-folders.php:508 0.1875 13488320 7. FolderListDiv() /usr/local/share/fossology/lib/php/common-folders.php:508 0.1889 13493624 8. FolderListDiv() /usr/local/share/fossology/lib/php/common-folders.php:508 0.1903 13499032 9. FolderListDiv() /usr/local/share/fossology/lib/php/common-

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2013/07/30 01:07:37 +0000

---

Talk with team, this bug is not high priority.

**Comment by steffen-weber** [comment]
Since d0a899f841f03ea79269bfbe490c50dc1b1cdff8 the cycle is the detected and the action denied.
