### ISSUE TITLE
copyright - missed after long year string

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#213]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 4203, http://www.fossology.org/issues/4203
Original Date: 2013/03/26
Original Assignee: Dong Ma

---

From Oliver Fendt email to fossology@fossology.org  Mar 26, 2013

The copyright strings are somehow extracted in the current version in a way I wouldn't expect. For example:
the package libxml2 version 2.7.7 contains a file: libxml2-2.7.7/config.sub
the copyright string in the file is:
 
Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation, Inc.
 
the copyright information extracted by the current version of FOSSology is:
 
```
28	Show	copyright (c)

```
 
Note missing "Free Software Foundation, Inc.".  This may be because the year substring is so long.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2013/07/15 07:33:23 +0000

---

This issue caused by the statement in the file in different line:

1. Copyright (C) 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
1. 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009
1. Free Software Foundation, Inc. 

The copyright agent can only identify the first line, also in the copyrightview page, the copyright statement have been cleaned up, so all the 'Copyright (C)' follow with the year will group by 'Copyright (C)'.

Bob, I need to discuss with you how to handle this issue.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/08/01 21:37:43 +0000

---

What do you recommend?

**Comment by yaobinshi** [comment]
Updated by Dong Ma over 1 year ago
Status changed from In Progress to Feedback
Assignee changed from Dong Ma to Bob Gobeille
I discussed with Larry, we consider this is the right behaviour for copyright agent, i recommend do not change this behaviour.

#5 Updated by Bob Gobeille over 1 year ago
Status changed from Feedback to In Progress
Assignee changed from Bob Gobeille to Dong Ma
I don't agree that this is the right behavior because the result is incorrect. The real problem seems to be that it is very difficult to identify the end of the copyright line. Because of this we require the entire copyright to be on a single line and use the line to terminate the copyright.

If this is too difficult to fix, just close the issue. If this is an isolated case it won't hurt us. If it is a common case we will have to address it eventually.

**Comment by mcjaeger** [comment]
sees to be resolved

![copy floppy 2015-08-28 21_31_18-copyright_email_url_author browser](https://cloud.githubusercontent.com/assets/3418977/9555255/31183940-4dcc-11e5-829a-f8a20129f4ee.png)
