### ISSUE TITLE
create survey & solicit fossology users to respond to questions about fossology usage

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#214]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 4605, http://www.fossology.org/issues/4605
Original Date: 2013/04/09
Original Assignee: Mary Laser

---

# On what distro do you run fossology?
1. which fossology feature do you like/use the most?
1. which fossology feature do you dislike or rarely use?
1. what kind of improvements would you like to see with fossology?
1. other questions...

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2013/04/09 14:21:59 +0000

---

reworded subject

**Comment by mcjaeger** [comment]
we did that with? http://www.fossology.org/projects/fossology/wiki/WhoUsesFOSSology

**Comment by bobgob** [comment]
When I created Who Uses FOSSology, I didn't survey the users about what they use/don't use.  So those are two different things.

**Comment by mcjaeger** [comment]
I understood it was already some effort to find out more about who uses fossology, which is a kind of very basic one-question variant of the four, five questions given above. No problem with this, just wondered how likely it is that users would answer it.
