### ISSUE TITLE
Docker container Fossology won't upload a file greater than 1MB, even when the size set is 700MB

### ISSUE THREAD

**Issue by jmhartle** [fossology/fossology#2146]
### Description
The company I work for has an IT team which created a Fossology Docker container for our internal use as CaaS.  But when I try to upload any zip file that is greater than 1MB, it reports that the entity is too large.  I have uploaded these same files on the server "https://fossology.osuosl.org/repo/" and they uploaded just fine.  I searched your database before and saw the article on changing the size of the upload to 700MB and gave the instructions to IT.  They said that this server is already set at 700MB.  As it is, this Fossology is not completely usable to us.  Is there anything we can do to improve the upload size?

#### How to reproduce
I would assume that you could create a Docker container for Fossology and it would have the same issue unless there is something that IT is missing.

#### Screenshots
![Edk2 properties](https://user-images.githubusercontent.com/95775766/151210369-727760ea-4065-44ae-afbe-526fb7d80d20.png)

![Too Large Entity](https://user-images.githubusercontent.com/95775766/151210395-350f9c25-2904-4822-b521-87adea5a3736.png)

### Versions
FOSSology version 3.11.0.6-rc2 (code revision 907b08) with 600 known licenses in database

### Logs

Will ask IT for the logs.

**Comment by GMishx** [comment]
Hello @jmhartle , from the screenshot I see the response if coming from nginx server. However, the default Docker container runs apache2 server instead.

I am assuming there is a a reverse proxy between you and the container or the container is modified.
You'll need to add `client_max_body_size 700M;` to appropriate context in nginx.

**Comment by jmhartle** [comment]
Hi Mishra, 
Thanks for your suggestions.  It took a while for IT to get this fixed, but you were correct on your thinking.  Thanks to you, our instance is now working very well.

Regards,
Judy

**Comment by GMishx** [comment]
Thanks for the confirmation. :-)

I think we can close the issue now. Please reopen if needed.
