### ISSUE TITLE
Flag license as possibly proprietary

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#215]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 4821, http://www.fossology.org/issues/4821
Original Date: 2013/04/16
Original Assignee: Bob Gobeille

---

This license is identified by Nomos as Apache 2.0 which is accurate.
Can we also flag it as possible proprietary?
Review this with Nissa for accuracy.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/04/16 21:52:28 +0000

---

Wouldn't it be reasonable to label it with "Android-SDK"?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2013/04/18 17:04:16 +0000

---

Yes, I would agree with your assessment.  However, this request came directly from Nissa.  Please direct any questions you might have regarding this issue to Nissa.
Thanks.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/04/18 17:06:08 +0000

---

I'll contact Nissa.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/04/18 20:34:20 +0000

---

From Nissa:
@The problem is that the Android SDK is something of a hybrid.  There are open source elements, but it's my understanding that to get to these, you need to agree to a click-to-accept proprietary agreement that contains "no forking" restrictions, etc.  Review of this proprietary agreement should be done by the commercial attorneys, not the open source review attorneys.  Basically, we want to flag this license early on as something that should be taken to the commercial attorneys to review; whichever mechanism works best for that is fine, but tagging something as proprietary makes it more obvious to the reviewers to take it to the appropriate reviewer rather than relying on reviewers to remember that the Android SDK has some "unique" properties.@

We need further discussion.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4563/Android_SDK_license.txt

**Comment by yaobinshi** [comment]
any new update, will return as: Apache-2.0-Property

**Comment by yaobinshi** [comment]
sorry, it is Apache-2.0-Proprietary

**Comment by pguttmann** [comment]
It may be more informative to return "Android Software Development Kit License"
This appears to be the "title" as per line 7 of the attached file.

**Comment by bobgob** [comment]
There are two licenses in the file, not one.  The Android SDK license is followed by the Apache-2.0.  Previous comment expressed concern that it may not be obvious that the SDK license contains some non open parts.  So I recommend that we return:  Apache-2.0, AndroidSDK-Commercial.  

It would probably be better if licenses had properties like "commercial", or used buckets, rather than putting that in the license name, but we are already inconsistent in that regard.

**Comment by pguttmann** [comment]
Yes. Great point! That was my intention, *both* licenses should be reported. As mentioned "highlighting" the commercial aspect of the SDK license is beneficial.

**Comment by yaobinshi** [comment]
ok, will return AndroidSDK-Commercial, Apache-2.0
