### ISSUE TITLE
html entitiles are not stripped when processing a group name

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#216]
---

Author Name: **Mark Donohoe** 
Original Redmine Issue: 4869, http://www.fossology.org/issues/4869
Original Date: 2013/04/19

---

add a new group page allows html and php to pass through....  below is a dump of the groups table:

fossology=> select * from groups;
 group_pk |           group_name           
----------+--------------------------------
        1 | Default User
        2 | fossy
        3 | perm1
        4 | perm11
        5 | myPerm1
        6 | --perm1--
        7 | <h2>Does this work?<h3>
        8 | <?php print "hello World!"; ?>
(8 rows)

even with my typos! (e.g. h3 instead of /h2 or />).

**Comment by steffen-weber** [comment]
fixed by ef7b2749228091aa5dfdad20c55422d1510ff02
