### ISSUE TITLE
Author Table Duplicates issue (3.11)

### ISSUE THREAD

**Issue by kannan-seenivasan** [fossology/fossology#2162]
### Description

We found duplicates records inserted in the author table. 

### Example ###

For the Same agent_fk = XXX and  pfile_fk=<pfile_fk>, the author information inserted multiple times for same copy_startbyte and copy_endbyte.

Example: 
`select agent_fk, pfile_fk,copy_startbyte, copy_endbyte from author where pfile_fk=<pfile_fk>
and hash='<hash value>' 
and copy_startbyte=<copy_startbyte> 
and copy_endbyte=<copy_endbyte>
and agent_fk = <agent_fk>
and type='author'
and "content" = '<text>'
order by author_pk`

Result: 

| agent_fk | pfile_fk | copy_startbyte | copy_endbyte |
| -- | -- | -- | -- |
| 106 | 2279834 | 220 | 248 |
| 106 | 2279834 | 220 | 248 |
| 106 | 2279834 | 220 | 248 |
| 106 | 2279834 | 220 | 248 |
...
...
..
72 times...

We can see 72 records duplicated with unique author_pk.

**Note**: Not all rows are duplicated

### Versions

we are currently using the 3.11.0 version 
Last commit id: "c9392107af9" from community

Question:

Is this an expected result or do we need to restrict such duplicates?

**Comment by shaheemazmalmmd** [comment]
@kannan-seenivasan : The issue with author table is not reproducible from our end. Can you please share more info about  your environment ? is the process automated ?

**Is this an expected result or do we need to restrict such duplicates?**
we need to restrict the duplicates. it is not a expected behavior.

**Comment by GMishx** [comment]
Closing the issue for now. Please reopen if issue persists.
