### ISSUE TITLE
Edit users forgets users agent selections

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#218]
---

Author Name: **Mark Donohoe** 
Original Redmine Issue: 4911, http://www.fossology.org/issues/4911
Original Date: 2013/04/25

---

When a User is created or edited, the user preferences are remembered.  For some reason, the agents selected are not remembered. They used to be.
See the attached screen shots.  To reproduce:
1. Create a user (as fossy), select some agents to always use.  Select the default bucket pool.  Note what agents were selected.
2. Do something else, create another user, browse, etc...
3. Edit users (as fossy), select the user created in step 1 above.  Note that the agent boxes are all blank.  Also note that the default bucket pool was remembered.

I don't consider this a serious defect.  It can be delayed to 2.3.0, I'm filing it against 2.2.0 because that is where I found it.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4557/ForgotAgents.png

**Comment by mcjaeger** [comment]
just tested, fixed.
