### ISSUE TITLE
No file selected 

### ISSUE THREAD

**Issue by Raghavendrakamatagi-eng** [fossology/fossology#2180]
Hello Team,

We have installed fossology-version: [3.11.0] from the deb packages in central Ubuntu Server 18.04 and accessing through the IP address and we can able to upload the smaller packages but its showing upload error as No file selected for packages greater than 50 KB.

Kindly help us to resolve **No file selected issue** 

PS: This is working fine for Fossology Admin and not for other team members 

Regards
Raghavendra

**Comment by Raghavendrakamatagi-eng** [comment]
Hello Team,

Any update on the above issue?

Regards
Raghavendra

**Comment by Raghavendrakamatagi-eng** [comment]
Hello Team,

Can you please help us to resolve the above issue?

**Comment by GMishx** [comment]
Hello @Raghavendrakamatagi-eng , can you please check for following values in `/etc/php/<version>/apache2/php.ini`?
- `post_max_size`
- `upload_max_filesize`
- `memory_limit`

Are you using any other server in between? Like a LoadBalancer or Nginx reverse proxy?

**Comment by Raghavendrakamatagi-eng** [comment]
Hello @GMishx ,

After configuring the php upload size, issue is resolved.

Thanks a lot for your help.
