### ISSUE TITLE
REST API: OpenAPI Description: Fix typo in HeathInfo

### ISSUE THREAD

**Issue by tngraf** [fossology/fossology#2185]
### Description

There is a typo in the OpenAPI Description
* HeathInfo => HealthInfo

#### How to reproduce

See OpenAPI file, version 1.4.3,
line 155,
line 166,
line 2066

### Versions

OpenAPI file, version 1.4.3

**Comment by krishna9304** [comment]
Can i work on this?

**Comment by teekhandekar** [comment]
Can I work on this please
