### ISSUE TITLE
REST API: endpoint /filesearch: data type description inaccurate

### ISSUE THREAD

**Issue by tngraf** [fossology/fossology#2186]
### Description

The OpenAPI description, version 1.4.3, says that the input for the /filesearch endpoint
is an array of `Hash` objects.

This is not totally correct:
* As soon as the property `size` is available in the JSON data, the call to /filesearch does not return results,
  but says `Invalid keys`.
* The example data provided, 
```
[
  {
    "sha1": "81fe8bfe87576c3ecb22426f8e57847382917acf",
    "md5": "e2fc714c4727ee9395f324cd2e7f331f",
    "sha256": "88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589",
    "size": 0
  }
]
```
will result in such an `Invalid keys` message.
* As soon as the `file` property is omitted, i.e.
```
[
  {
    "sha1": "81fe8bfe87576c3ecb22426f8e57847382917acf",
    "md5": "e2fc714c4727ee9395f324cd2e7f331f",
    "sha256": "88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589",
  }
]
```
a correct result will be returned.

### Versions

* Commit: [#fcf1de] 2022/03/09 08:26 +00:00 built @ 2022/03/09 08:32 +00:00
* Latest version of the containerized version of FOSSology

**Comment by Vaibhav992** [comment]
I want to work on this issue. Can you tell me how can I solve
