### ISSUE TITLE
new regex scanner module

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#219]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 4983, http://www.fossology.org/issues/4983
Original Date: 2013/05/22
Original Assignee: Paul Guttmann

---

http://www.fossology.org/boards/9/topics/63?r=69

Create a new module that scans text for regex's.  We can implement a crypto reference scanner this way.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/02/27 23:55:10 +0000

---

From Paul G.:
The regexscan is waiting on getting this file scan SQL request recoded/corrected. Then it needs the database work completed to both record activity into an ARS table and also capture the "hit" information. Finally the whole UI stuff needs thinking about and implementation. I see 3 major UI areas required:
1. Regex "maintenance" to add/edit/delete assorted regex strings available for scanning operations
2. RegexScan "operations" to schedule scanning a selected uplaod for a selected regex string (from 1. above)
3. RegexScan "reporting" to view and investigate "hits" for a previously run scan (from 2. above)

From Bob G.:
Besides deleting the regex strings, we probably also need a way to delete specific regex results.  For example, say we define regex “A”, then run a scan of “A” on upload “X”.  Now we learn our regex was incorrect.  So it would be good to delete those old results.

**Comment by mcjaeger** [comment]
we have this with the copyright / ECC? there is also the ticket from Paul with the enhancement to put the regex in files:  #460
