### ISSUE TITLE
Unexpected token error on login attempt in FossologyUI

### ISSUE THREAD

**Issue by coder-whale** [fossology/fossology#2198]
### Description

On attempting to login through FossologyUI with default credentials ('fossy', 'fossy'), an unxpected token error is thrown.

#### How to reproduce

1. Install Fossology from source and start the service.
2. Start FossologyUI app.
3. Attempt to login.

#### Screenshots

![Screenshot from 2022-03-30 20-13-55](https://user-images.githubusercontent.com/69923950/160895804-0f75877e-bd61-48d0-a7f9-a898650c3104.png)

### Versions

* Last commit id on master: https://github.com/fossology/fossology/commit/77a85ca0396a7545939656a8f9b8bf9b2620cc39
* Operating System: Ubuntu 20.04.4 LTS

#### Apache logs

PHP Notice:  Trying to access array offset on value of type bool in /usr/local/share/fossology/pkgagent/ui/agent-pkgagent.php on line 57, referer: http://localhost:3000/

**Comment by GMishx** [comment]
Hello @coder-whale , I don't think the error you are receiving is due to the php notice you've mentioned.

Can you check the network log when you try to login? I think it is due to errors mentioned in https://github.com/fossology/FOSSologyUI/issues/181
