### ISSUE TITLE
CONTRIBUTING.md within root folder

### ISSUE THREAD

**Issue by bufferoverflow** [fossology/fossology#22]
We really need a CONTRIBUTING.md file within root folder to guide people how to contribute to FOSSology.
A very nice side effect is this: https://github.com/blog/1184-contributing-guidelines

best!
-roger

**Comment by mcjaeger** [comment]
we have had a similar discussion with code style updates and DoD as well as default licensing headers.Should be done once these three are updated int he wiki ...

**Comment by maximilianhuber** [comment]
@bufferoverflow: There is a new feature in github: [ISSUE_TEMPLATE](https://github.com/blog/2111-issue-and-pull-request-templates). This could be used to remember people to add meta-information like the commit hash.
