### ISSUE TITLE
Make client id as configurable claim for REST auth

### ISSUE THREAD

**Issue by GMishx** [fossology/fossology#2204]
### Description

While using client credentials flow for REST API authentication, the client id claim used to authorize request is implementation dependent. Thus it should be configurable by admins.

The `client_id` claim is currently hard coded and should be configurable.

https://github.com/fossology/fossology/blob/ec36f4ed00649437bbde143cf3a78c4bdabe4591/src/www/ui/api/Helper/AuthHelper.php#L318

**Comment by GMishx** [comment]
Also update the wiki while closing the ticket

https://github.com/fossology/fossology/wiki/OpenID-Connect-authentication-configuration#verify-client-id-claim

**Comment by coder-whale** [comment]
@GMishx Do note that "Application Login URI" in Auth0 only accepts `https` so the picture in the wiki is misleading

**Comment by GMishx** [comment]
Nice catch. Will fix it.
