### ISSUE TITLE
`fossology.version` returns `unknown` in `/info` endpoint in Docker

### ISSUE THREAD

**Issue by soham4abc** [fossology/fossology#2206]
### Description

The `/info` API returns the fossslogy version as `unknown` when the sever is running from docker.

![image](https://user-images.githubusercontent.com/63705023/161546092-5aa2294d-5389-4086-a690-343c316e12d7.png)

UI output:
![image](https://user-images.githubusercontent.com/63705023/161545690-42be418d-c2b6-4a4c-b9d6-ca81ab92cb64.png)

#### How to reproduce

Run the Fossology from Docker.

#### Probable Reason
The docker image does not have the `.git` folder with complete latest tag information which causes it to be missing.

**Comment by omkarg01** [comment]
I would like to work on this issue, may I know
where to look for the following versions details?
![161546092-5aa2294d-5389-4086-a690-343c316e12d7](https://user-images.githubusercontent.com/67428719/161978118-0607cfad-cd3d-47b0-b351-54bfb97970ea.png)

**Comment by Pranjal7852** [comment]
Is this still an issue to work on?

**Comment by ArijeetBanerjee** [comment]
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖
