### ISSUE TITLE
Eliminate the 10-net on the fo.usa agents

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#222]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 5013, http://www.fossology.org/issues/5013
Original Date: 2013/05/30
Original Assignee: Bob Gobeille

---

Determine what config changes need to be made to eliminate the 10-net on foagent1-foagent6.
1) changes in the fossology.conf files
2) insure NFS mount points are using the .osttprivate 192.168.x network
3) what else?

**Comment by mcjaeger** [comment]
that is probably obsolete?

**Comment by bobgob** [comment]
Old and HP internal to boot.  Closing.
