### ISSUE TITLE
LGPL 2.1 not detected

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#223]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 5217, http://www.fossology.org/issues/5217
Original Date: 2013/06/06

---

$ ./nomos /tmp/bla/gdk-pixbuf-0.2/src/io-jpeg.c
File io-jpeg.c contains license(s) No_license_found

/*
  io-jpeg.c: GdkPixBuf loader for jpeg files.

  Based on io-jpeg from gdk_imlib, but not much.

  This code is licensed under the Lesser GNU
  General Public License, version 2.1.

  Author:
    Michael Zucchi <zucchi@zedzone.mmc.com.au>
*/

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4551/io-jpeg.c

**Comment by yaobinshi** [comment]
have been fixed in one previous fix.

**Comment by bobgob** [comment]
tested.  Closing.
