### ISSUE TITLE
Getting error while building 

### ISSUE THREAD

**Issue by ChandanHJ** [fossology/fossology#2236]
### Description

Getting error while building fossology   

#### How to reproduce

Using build command to build it 

#### Screenshots

![image](https://user-images.githubusercontent.com/42247568/174469393-48c9140d-05ad-4197-9439-b9dc07b820a7.png)

Help me to solve this and to install fossology

**Comment by GMishx** [comment]
Did you run the [utils/fo-installdeps](https://github.com/fossology/fossology/blob/master/utils/fo-installdeps) to install the dependencies?

**Comment by GMishx** [comment]
Closing the issue. Please reopen is issue persists.
