### ISSUE TITLE
copyright - add text filter

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#224]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 5265, http://www.fossology.org/issues/5265
Original Date: 2013/06/13
Original Assignee: Bob Gobeille

---

Add a text filter to copyright.  For example, you can limit the results by just searching for copyrights that contain "liferay".  In this case, the max returned rows ($MaxTreeRecs) does not apply.  Or $MaxTreeRecs is applied to the result of the query instead of before the query like it does now.

**Comment by steffen-weber** [comment]
Since b7fad9fb7f6b246c1be3ff7512d438cbdc1cb7f8 copyright-hist uses jQuery datatable with search fields.
