### ISSUE TITLE
Check if user has a deletable group via REST API 

### ISSUE THREAD

**Issue by dushimsam** [fossology/fossology#2246]
### Description
There's a need for the API to check if a particular user has any group that can be deleted.

#### Steps to be followed

1. Create new route in the main page (index.php) as a part of Group routes.
2. Add a new function in GroupController to check for the group's existence.
3. Test the API.
4. Add the new API's documentation  in [https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml](url)
5. Open a pull request.

#### Expected Results

1.  An endpoint to be accessed at ''/groups/has-deletable-group".
2. The API should return the object with the property **available** marked as 
   **true** if the API exists else as **false**.

cc: @shaheemazmalmmd @GMishx

**Comment by GMishx** [comment]
I would recommend the endpoint to be renamed as `/groups/deletable` to check a bunch of groups the current user can delete.

What do you think?

**Comment by dushimsam** [comment]
Yeap, that's awesome.
I'm going to update it.
