### ISSUE TITLE
Folder selection fails in Edit Uploaded File Properties

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#225]
---

Author Name: **Raino Lintulampi** 
Original Redmine Issue: 5355, http://www.fossology.org/issues/5355
Original Date: 2013/06/26
Original Assignee: Bob Gobeille

---

One cannot change folder when trying to edit upload properties.
Sequence:
Organize->Uploads->Edit properties
1. Select the folder that contains the upload

Selected folder is flashed but after that Software Repository is shown again.

FOSSology version trunk (code revision 6775M).

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/09/23 22:41:15 +0000

---

Wasn't this fixed in 2.3?

**Comment by mcjaeger** [comment]
tested today, works.
