### ISSUE TITLE
beerware license not recognized

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#226]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 5403, http://www.fossology.org/issues/5403
Original Date: 2013/07/01

---

The attached two files from BusyBox contain two licenses: RSA and Beerware. The RSA part is recognized, but the beerware license is not.

**Comment by pguttmann** [comment]
Attachments - 1) http://www.fossology.org/attachments/4539/hash_md5prime.c
2) http://www.fossology.org/attachments/4545/pw_encrypt_md5.c

**Comment by yaobinshi** [comment]
will return as: Beerware,RSA-Security

**Comment by bobgob** [comment]
Test cases are missing from nomos/agent_tests/testdata
