### ISSUE TITLE
standalone copyright agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#227]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 5427, http://www.fossology.org/issues/5427
Original Date: 2013/07/02
Original Assignee: Bob Gobeille

---

hi!

in the Binary Analysis Tool I currently extract (but not yet use) copyright information using the copyright agent. It would be nice to able to use it without the database layer, as a standalone program.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/04/18 02:52:27 +0000

---

standalone copyright agent will be very useful, so improve the priority.

**Comment by mcjaeger** [comment]
copyright agent has been rewritten at some point, requires review what is the status today

**Comment by GMishx** [comment]
Copyright agent still require the database layer. Needs rework.

**Comment by GMishx** [comment]
Done in #1155
