### ISSUE TITLE
Modify the `/uploads/:id/licenses` endpoint in order to ommit repeated Copyright Information.

### ISSUE THREAD

**Issue by soham4abc** [fossology/fossology#2272]
### Description

Currently when we use the `uploads/:id/licenses` endpoint with the headers:

```
license: true
copyright: true
agent: nomos,monk,ojo

```

The response returns all the repeating copyright information which is undesirable.
The response should not have any repeating occurrences of copyright information. 

#### How to reproduce

send a GET request to this particular URL: `localhost/repo/api/v1/uploads/<Insert_upload_id_here>/licenses?license=false&copyright=true&agent=nomos,monk,ojo` and examine the output. There is a chance that you will find that there are repeating occurences of copyright information.

#### Screenshots

Response of the endpoint from my side: https://fossology.slack.com/files/U02PWEEG40H/F03Q1AE0SRL/response.json?origin_team=T6P6QSFSN&origin_channel=C022EV42030

### Versions

* Last commit id on master:[8eab614]
* Operating System (lsb_release -a): Ubuntu 20.04

PS: I would like to work on this issue

@shaheemazmalmmd @GMishx @Shruti3004

**Comment by GMishx** [comment]
@soham4abc , instead of modifying the current endpoint, I will recommend to create a new endpoint for copyrights alone which can provide the information in required format.

```json
[
    {
        "copyright": "Copyright 1",
        "filePaths": [
            "path/to/file/1"
        ]
    },
    {
        "copyright": "Copyright 2",
        "filePaths": [
            "path/to/file/2",
            "path/to/file/3",
        ]
    },
    {
        "copyright": "Copyright 3",
        "filePaths": [
            "path/to/file/1",
            "path/to/file/3",
        ]
    },
    {
        "copyright": "Copyright 4",
        "filePaths": [
            "path/to/file/3",
            "path/to/file/4",
        ]
    }
]
```

**Comment by soham4abc** [comment]
Can we have a prescribed endpoint URL format for this new functionality ?
