### ISSUE TITLE
Scancode error while scanning boost package FATAL scancode_wrapper.cc.196: JSON parsing failed * Line 15, Column 23"

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2277]
### Description

ScanCode error failed

#### How to reproduce

Tried to scan [boost_1_64_0.tar.bz2](http://downloads.sourceforge.net/project/boost/boost/1.64.0/boost_1_64_0.tar.bz2) and got an error from ScanCode, see attached screenshot. I have also attached the error log from FOSSology, see 001070.txt.

#### Screenshots
![image](https://user-images.githubusercontent.com/4498415/181445597-0b862c53-a1e9-4403-8fe4-95b4172a2cde.png)

### Versions

* Last commit id on master: Version: [4.1.0.0], Branch: [HEAD], Commit: [#76450a]
* Operating System (lsb_release -a): Ubuntu 18.0

#### Job logs
[001070.txt](https://github.com/fossology/fossology/files/9206620/001070.txt)

[001095.txt](https://github.com/fossology/fossology/files/9206618/001095.txt)

**Comment by alpianon** [comment]
maybe related to #2329 ?
