### ISSUE TITLE
Delete license Candidate

### ISSUE THREAD

**Issue by dushimsam** [fossology/fossology#2297]
### Description
There's a need of the API to delete  a certain license candidate.

#### Steps to be followed

1. Create a new route on the main page (index.php) as a part of the License routes.
2. Add a new function in LicenseController to handle the functionality.
3. Test the API.
4. Add the new API's documentation  in [https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml](url)
5. Open a pull request.

#### Expected Results

1.  A DELETE endpoint to be accessed at ` ''/license/candidates" `.
2. The API should return a success message if the delete operation was successful with the respective status code.

cc: @shaheemazmalmmd @GMishx

**Comment by legendarykamal** [comment]
Hi @dushimsam can i get started with this 🙂

**Comment by dushimsam** [comment]
Hey, @legendarykamal I have completed it already locally, just going to make a pull request in time.😂

**Comment by dushimsam** [comment]
But we still have a lot of to do's on the license module we can appreciate your contribution,
you can refer to other issues or pick some of these

Example:

1. Rest-API to  Selecting license.
2. Rest-API to add the admin-standard-license comment.
etc.

**Comment by legendarykamal** [comment]
no problem @dushimsam can you guide me how to contribute to the examples listed? 
PS;- I am new out here.

**Comment by dushimsam** [comment]
The project is all about writing REST API's in Slim PHP framework. 
So i would recommend you to be comfortable in that framework for now.
Then you can refer to the previous REST API's to develop those as well.
