### ISSUE TITLE
UPX license exception

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#230]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 5451, http://www.fossology.org/issues/5451
Original Date: 2013/07/08

---

a tricky one and only for one software package, so perhaps treat it as a curiosity: the UPX license exception described in the attached file.

This license is a funny one: it is GPL licensed and it rewrites binaries, but it is OK to use by commercial programs as long as they use unmodified UPX stubs.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4527/LICENSE

**Comment by yaobinshi** [comment]
will return as GPL-2.0+-with-UPX-exception

**Comment by bobgob** [comment]
I don't see a test case in nomos/agent_tests/testdata
