### ISSUE TITLE
Creation of a POST route to import a report

### ISSUE THREAD

**Issue by krishna9304** [fossology/fossology#2308]
There is a requirement of a POST route that will import a report to an existing upload. I'd like to work on this.

Steps to be followed ---
- Create a new POST route in the `index.php` file inside `www/ui/api `directory for initiating a report import job.
- Add new method `importReport` in the `ReportController` class.
- Try to re-use the methods that are already used in the backend from the `ReportImportPlugin` and `ReportImportAgentPlugin` plugins for the functionalities.

@GMishx @shaheemazmalmmd @Shruti3004 Please assign me this.

**Comment by jatinmark** [comment]
I want to work on this issue can you assign it to me please
