### ISSUE TITLE
Admin -> Dashboard fails

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#232]
---

Author Name: **Paul Guttmann** 
Original Redmine Issue: 5511, http://www.fossology.org/issues/5511
Original Date: 2013/07/17

---

On a clean 2.2.0 install I am seeing Fossology "hang" when accessing Admin->Dashboard from the Menu System.

The issue would appear to lie in admin-dashboard.php line 36

This module refers to RepPath.conf which appears to have been removed from V2.2

I managed to "workaround" this issue by editing the php file and "hard coding" the repository URL instead.

**Comment by bobgob** [comment]
old issue.  dashboard was rewritten after this issue was filed.   Closing
