### ISSUE TITLE
Errors while file uploading the tar.gz packages

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2321]
### Description
File Uploading Some tar.gz packages (for example 
https://files.pythonhosted.org/packages/c8/18/631398e45c109987f2d8e57f3adda161cc5ff2bd8738ca830c3a2dd41a85/gevent-21.12.0.tar.gz ) are not working

#### How to reproduce

Download the above mentioned file
upload manually 
Triggers "This site can't be reached" browser error page

#### Screenshots

![brave_fqiaaWPfid](https://user-images.githubusercontent.com/4498415/190994936-760bd734-ad2b-46d3-ad9f-c7a99cfeb0e6.gif)

### Versions

* Last commit id on master: Version: [4.1.0.0], Branch: [HEAD], Commit: [#76450a] 2022/05/20 09:19 +00:00 built @ 2022/09/16 15:50 +00:00
* Operating System (lsb_release -a): Ubuntu 18.04.5 LTS

### Logs

```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/www/ui/page/UploadFilePage.php on line 85, referer: http://fossology.ebgroup.com:8081/repo/?mod=upload_file
 PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/www/ui/page/UploadFilePage.php on line 85, referer: http://fossology.ebgroup.com:8081/repo/?mod=upload_file
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/share/fossology/www/ui/page/UploadFilePage.php on line 85, referer: http://fossology.ebgroup.com:8081/repo/?mod=upload_file
```

https://github.com/fossology/fossology/blob/76450a21575d2a9ad3e5873b2f758fe408caf7a5/src/www/ui/page/UploadFilePage.php#L85

**Comment by jatinmark** [comment]
I want to on this issue can you assign it to me please

**Comment by GMishx** [comment]
Closing the issue for now. Please reopen if needed.
