### ISSUE TITLE
Update bucket definitions page

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#233]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 5607, http://www.fossology.org/issues/5607
Original Date: 2013/08/22
Original Assignee: Bob Gobeille

---

From email:

```
Are there documented instructions for modifying bucket definitions?  
Maybe that's in the wiki already(?), but it has a very old date with references to 1.3 & 1.4.  I expect it needs updating.  Can you please check it for accuracy
https://www.fossology.org/projects/fossology/wiki/Creating_and_Using_Bucketpools

Thanks.
Mary

```

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/09/24 01:00:40 +0000

---

Also, add examples for more examples of creating buckets.

**Comment by mcjaeger** [comment]
is that Ok to close? maybe clarification is required to have one of the latter pages below unified
http://www.fossology.org/projects/fossology/wiki/UsingBuckets
http://www.fossology.org/projects/fossology/wiki/Buckets
http://www.fossology.org/projects/fossology/wiki/Creating_and_Using_Bucketpools

**Comment by mcjaeger** [comment]
OK to close maybe now.
