### ISSUE TITLE
About section UI breaks at several screen size

### ISSUE THREAD

**Issue by sarthakastic** [fossology/fossology#2338]
### Description

For the screen width 1080px to 1000px the About description overlap with the floating navigation modal.

#### Screenshots

<img width="1710" alt="Screenshot 2022-10-26 at 9 45 47 AM" src="https://user-images.githubusercontent.com/72138026/197933702-f1bca162-a923-4ca8-88cd-a677734a851b.png">

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by Laraibnehal** [comment]
@sarthakastic is this issue assigned or can I take this issue ?

**Comment by tiwarishankar** [comment]
@sarthakastic can i take this issue?

**Comment by Cvanshulll** [comment]
@sarthakastic  I want to work on this issue. Can you please assign this to me?

**Comment by GMishx** [comment]
Thank you for opening the issue but the website is created using wordpress. The website serves documents and contact details about the project not the project itself. I would call the issue minor and in my opinion it is not worth investing time on it to make it responsive.

Please feel free to reopen the issue if needed.
