### ISSUE TITLE
Missing header on running `make`

### ISSUE THREAD

**Issue by danger-ahead** [fossology/fossology#2344]
### Description

The header sstream is possibly missing in `OjoAgent.cc`. While running `make`, this is the error I encountered:
```bash
OjoAgent.cc: In member function ‘std::vector<ojomatch> OjoAgent::processFile(const std::string&, OjosDatabaseHandler&, int, int)’:
OjoAgent.cc:43:21: error: aggregate ‘std::stringstream sstr’ has incomplete type and cannot be defined
   43 |   std::stringstream sstr;
      |                     ^~~~
OjoAgent.cc: In member function ‘std::vector<ojomatch> OjoAgent::processFile(const std::string&)’:
OjoAgent.cc:77:21: error: aggregate ‘std::stringstream sstr’ has incomplete type and cannot be defined
   77 |   std::stringstream sstr;
      |                     ^~~~
make[3]: *** [Makefile:49: OjoAgent.o] Error 1
```

#### How to reproduce

After completing the previous steps, running `make` gives this error.

### Versions

* Last commit id on master: [9a0a6eb](https://github.com/fossology/fossology/commit/9a0a6ebbbee23c2adc794151015be425ac1c91cd)
* Operating System (lsb_release -a): Ubuntu

#### Fix

Adding the appropriate header fixes the problem.

**Do I want to work on this issue?:** Yes

**Comment by withmohit** [comment]
Hey, I want to work on this issue.

**Comment by GMishx** [comment]
Since we have moved to CMake from #2075, the issue is no longer relevant.
