### ISSUE TITLE
Regression tests for buckets

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#235]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 5841, http://www.fossology.org/issues/5841
Original Date: 2013/09/25
Original Assignee: Bob Gobeille

---

We have had a request by HP to develop regression tests for their proprietary bucket definitions.  I think we should try to convince them to make some of these public so we can put the tests in our test suite.

**Comment by mcjaeger** [comment]
not picked up since September 2013
