### ISSUE TITLE
Update Ubuntu package at packages.ubuntu.com

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#237]
---

Author Name: **Paul Guttmann** 
Original Redmine Issue: 5865, http://www.fossology.org/issues/5865
Original Date: 2013/09/25
Original Assignee: Paul Guttmann

---

The provided Fossology package at http://packages.ubuntu.com/precise/utils/fossology is a little dated ;)
Perhaps we could arrange for a more recent 2.0+ version to be made available ?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2013/09/26 14:00:03 +0000

---

Entered a question at ubuntu's launchpad site to determine procedure required to resolve this.
https://answers.launchpad.net/ubuntu/+question/236407

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2013/09/26 15:15:31 +0000

---

Converted to a bug - https://bugs.launchpad.net/ubuntu/+source/fossology/+bug/1231486

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2014/03/11 13:23:19 +0000

---

It looks as if this package was removed from Debian back in June 2012.
https://ftp-master.debian.org/removals-2012.txt due to it being unmaintained.
This appears to be the result/resolution of Bug 656591 ;)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=656591

This seems to be the genesis for the question asked in my Ubuntu request at
https://bugs.launchpad.net/ubuntu/+source/fossology/+bug/1231486

How should I respond? Is there any interest in reviving the Debian release/version or should I respond that Ubuntu is an *active* release platform for us and mention we both test and use Fossology under Ubuntu these days ?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/11 17:05:31 +0000

---

It sounds like we need a Debian maintainer.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2014/03/11 17:31:26 +0000

---

Do we actually have test machines for Debian 6.0 and 7.0 ?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/11 17:57:40 +0000

---

Yes, but unfortunately, like our other testing machines, they are inside the HP firewall.

http://www.fossology.org/projects/fossology/wiki/Testing-vm_machine_list

**Comment by mcjaeger** [comment]
it is an HP ticket I am not sure if anyone is going to pick this up. also four years w/o update
