### ISSUE TITLE
macOS case issues due to file system

### ISSUE THREAD

**Issue by jimjag** [fossology/fossology#2379]
### Description

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/decisionimporter/agent/DecisionImporter.php'
  'src/decisionimporter/agent/decisionimporter.php'

#### How to reproduce

'src/decisionimporter/agent' contains 2 filenames which differ only in case, which mangles things on case-insentive FS

#### Screenshots

n/a

### Versions

HEAD

**Comment by GMishx** [comment]
Solved with #2383
