### ISSUE TITLE
browser tab interference

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#238]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 5871, http://www.fossology.org/issues/5871
Original Date: 2013/09/25
Original Assignee: Dong Ma

---

For years now I've noticed that fossology processing in one tab interferes with the processing in another tab.  But I never spent the time to look into it.    This would result in a bad situation when a page in one tab takes a really long time so you start a new tab and find that the new tab just spins too, no matter what you are trying to bring up.  My solution has always been to start a new browser instead of a tab.  But I think we really need to fix this.

To see this for yourself:
1) start 1 browser (I tried both firefox and chrome)
2) In one tab click on the license browser on a big upload (should take several seconds)
3) In another tab click on the new dashboard.  The new dashboard in top of tree renders almost instantly.

What happens is the dashboard won't render until the license browser finishes.

I'm guessing that this has something to do with sharing the same session.  To test this I did the following:

1) start a browser (e.g. firefox)
2) click on that big upload license browse (you may have to update the cache)
3) start a second browser (e.g. chrome)
4) while the license browser is spinning on browser 1, click on Dashboard in browser 2.  The Dashboard will render immediately, even though the license page in the first browser hasn't finished.

So why is this happening?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2014/02/28 06:46:40 +0000

---

From my tests, this is because sharing the login session. For my tests:

1) start 1 browser
2) In one tab click on the license browser on a big upload (should take several seconds)
3) Clear the login Cookies of this site use browser tools
4) In another tab click on the new dashboard. it will request new login immediately and after login the new dashboard will render immediately.

So from my thought the same login session use the same db connection.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/02/28 15:43:10 +0000

---

Yes, but the question is WHY does this happen?  Is this from the same session or same db connection?  And what do we do about it?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2014/03/03 02:27:07 +0000

---

There are 3 issue here:
1. The common-db.php DBconnect() function only call one time at the index.php, no other place call DBconnect() function, so no new connection created in different page.
2. The $PG_CONN set as global, in the common-db.php, line47, if (!empty($PG_CONN)) return $PG_CONN; so if $PG_CONN not empty, even call DBconnect(), will not create new connection.
3. If a second call is made to pg_connect() with the same connection_string as an existing connection, the existing connection will be returned unless you pass PGSQL_CONNECT_FORCE_NEW as connect_type.

I didn't have a good way to fix this, as I cannot set different $PG_CONN for each instances, need to discuss with you.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/04 18:37:26 +0000

---

Like we talked about yesterday:
1) all fossology pages start with index.php.  That's why this is where the db connection is done.
2) There is only one $PG_CONN per fossology instance, by design.
3) So did you try PGSQL_CONNECT_FORCE_NEW to force each instance to have a new connection?
You can turn on connection logging to see all the connections.

**Comment by mcjaeger** [comment]
closing it because it does not seem to be an issue anymore. I work with Fossology and multiple tabs all the time could not imagine how without.
