### ISSUE TITLE
Excluding unnecessary files

### ISSUE THREAD

**Issue by Mohnaa** [fossology/fossology#2384]
## Short Description
Excluding duplicate/ unnecessary files
## Possible Labels

- new feature

## Select Category

-  [ ] Enhancement
-  [ ] Add License/Copyright
-  [x] Scan Feature
-  [ ] Packaging
-  [ ] Documentation
-  [ ] Expand Support
-  [ ] Other

## **Describe the Update**
Analyzing and excluding unnecessary files/docs wich are not needed in the project.

## **How This Feature will help you/your organization**
We can speed up the analysis by excluding the build output directory.

**Comment by GMishx** [comment]
Hello @Mohnaa , can you please explain more about the issue? It is very unclear what is need to be done.

**Comment by GMishx** [comment]
Can I say the request is what described in #703 ?

**Comment by GMishx** [comment]
Duplicate #703
