### ISSUE TITLE
Adding a user requires an email, help is contradictory

### ISSUE THREAD

**Issue by duhow** [fossology/fossology#2391]
### Description

When creating a new user, `Email address. This may be blank` description is shown.
But apparently this field is **required**.

#### How to reproduce

- Add a new user
- Do not provide email

#### Screenshots

![2023-03-15_10-06](https://user-images.githubusercontent.com/1145001/225260508-edc8f8b0-4999-495e-9e16-f2c23d7422a3.png)

### Versions

* Last commit id on master: Docker [4.2.1](https://github.com/fossology/fossology/tree/4.2.1)

**Comment by Hero2323** [comment]
I'd like to work on this issue. I'll be working based on the assumption that not not specifying an email is the intended functionality and will thus be working on making that work.
