### ISSUE TITLE
Eye button to see the password in login Page

### ISSUE THREAD

**Issue by simran142002** [fossology/fossology#2392]
### Description

Password in Login page does not have an eye button 
To see the password

#### How to reproduce

For an enhancement or new feature:
So there should be an eye button beside password which can enable us to see the password before login If we want to

#### Screenshots

[Screencast from 16-03-23 10:32:40 AM IST.webm](https://user-images.githubusercontent.com/95395832/225520061-abdfe0e9-1495-4c30-ae0a-b58bb0806c6a.webm)

Here I have added a toggle eye button which currently does not exist

**Comment by snehalchaudhari98** [comment]
Hi, I would love to work on this issue if given a chance.

**Comment by simran142002** [comment]
> Hi, I would love to work on this issue if given a chance.

The PR for this issue has been raised
