### ISSUE TITLE
license_file_audit can not find rf_fk because license_ref has a different rf_pk after migration

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#24]
license_ref has a different rf_pk after migration, that is a problem.

**Comment by mcjaeger** [comment]
I think it worked at one user, requires more investigation

**Comment by shaheemazmalmmd** [comment]
As history is not stored in license_file_audit table now .. this issue could be closed.

**Comment by maximilianhuber** [comment]
In fact there is no license_file_audit table any more. Closing this issue
