### ISSUE TITLE
nomos crash

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#240]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6021, http://www.fossology.org/issues/6021
Original Date: 2013/11/01
Original Assignee: Bob Gobeille

---

Nomos crash on 2.3.0:
http://fossology.usa.hp.com/?mod=showjobs&upload=2253
Same upload on top of tree:
http://bobg.fc.hp.com/trunk/?mod=showjobs&upload=153&show=job&job=1041

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/11/01 08:29:50 +0000

---

this file result in nomos crash.

http://bobg.fc.hp.com/trunk/?mod=view&upload=153&show=detail&item=10820053

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/11/01 09:08:47 +0000

---

licenses.c：711 fails, have not found the root cause on that file.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/11/14 08:45:07 +0000

---

can not find the root cause till now.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/18 08:48:56 +0000

---

right now, I can not reproduce the crash on 9cf7d8fb5646972c7fc7670f277a28e545aa65, it is weird.
also http://osrb.usa.hp.com/incoming/OSRB_15283_Fir_1.tgz is moved away, anyone can tell me where it is? thanks.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bryan Sutula** 
Original Date: 2014/02/18 23:55:51 +0000

---

Please check with Bob G regarding access to the upload.  It is no longer available in the OSRB approval process.  We can't keep in-flight data available for long periods of time.  (Note that this request is almost 4 months old.)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/19 03:02:20 +0000

---

hi bob, 

right now, I can not reproduce the crash on 9cf7d8fb5646972c7fc7670f277a28e545aa65, it is weird.
also http://osrb.usa.hp.com/incoming/OSRB_15283_Fir_1.tgz is moved away.
and I can not access 
http://bobg.fc.hp.com/trunk/?mod=view&upload=153&show=detail&item=10820053

on you bobg,fc.hp.com server, still store that tar ball?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/02/26 17:08:24 +0000

---

I still have OSRB_15283_Fir_1.tgz on my server but because of the change to git, it has a different url:

http://bobg.fc.hp.com/fossology/?mod=browse&show=detail&folder=9

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/07 08:07:40 +0000

---

can not reproduce always, right now, have not found the root cause.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/07 16:26:37 +0000

---

You're saying that starting with a system in the same state that sometimes nomos crashes and sometimes it does not??

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/10 09:35:46 +0000

---

larry@bl460c-10:~/fossology/src/nomos/agent$ ./nomos 9cf7d8fb5646972c7fc7670f277a28e545aa65
Segmentation fault
larry@bl460c-10:~/fossology/src/nomos/agent$ cp 9cf7d8fb5646972c7fc7670f277a28e545aa65 seg_tests
larry@bl460c-10:~/fossology/src/nomos/agent$ ./nomos seg_tests
File seg_tests contains license(s) No_license_found


yes, it is weird.


then

in ./src/nomos/agent/parse.c

966   if ((INFILE(_CR_EASYSW) || INFILE(_TITLE_CUPS)) && INFILE(_LT_CUPS)) {

INFILE(_CR_EASYSW) direct this error, not found the detailed reason.

one workaround is 
if (INFILE(_TITLE_CUPS) && INFILE(_LT_CUPS)) {

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/10 14:32:00 +0000

---

a workaround in git 8b9143d..465f6da, this workaround will not impact the existing nomos tests

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/10 21:37:14 +0000

---

I just tested this with your update and the nomos log file has a backtrace showing an attempted free of an invalid pointer.  
```
2014-03-10 15:32:28 nomos [0] :: JOB[1373].nomos[27153.localhost]: "*** glibc detected *** 
/usr/local/etc/fossology/mods-enabled/nomos/agent/nomos: free(): invalid pointer: 0x00000000014e87c0 ***"

2014-03-10 15:32:28 nomos [0] :: JOB[1373].nomos[27153.localhost]: "======= Backtrace: ========="
2014-03-10 15:32:28 nomos [0] :: JOB[1373].nomos[27153.localhost]: "/lib/libc.so.6(+0x71e16)[0x7fba9ad2ae16]"
...

```

Is this your fix?  What results should I expect?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/11 08:40:25 +0000

---

with  http://sourceforge.net/p/fossology/fossology.git/ci/0d29826d77836abf014933b3ba0256210f81701c/

bobg@bobg:~/fossology/src/nomos/agent$ ./nomos 9cf7d8fb5646972c7fc7670f277a28e545aa65
File 9cf7d8fb5646972c7fc7670f277a28e545aa65 contains license(s) No_license_found
bobg@bobg:~/fossology/src/nomos/agent$ cp 9cf7d8fb5646972c7fc7670f277a28e545aa65 seg
bobg@bobg:~/fossology/src/nomos/agent$ ./nomos seg
FATAL parse.c.7239: File-offset list, nMatch(hO▒R): bad entry


larry@bl460c-10:~/fossology/src/nomos/agent$ ./nomos 9cf7d8fb5646972c7fc7670f277a28e545aa65
Segmentation fault
larry@bl460c-10:~/fossology/src/nomos/agent$ cp 9cf7d8fb5646972c7fc7670f277a28e545aa65 seg
larry@bl460c-10:~/fossology/src/nomos/agent$ ./nomos seg
File seg contains license(s) No_license_found



both tests in Debian GNU/Linux 6.0 

do not know why.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/11 21:56:14 +0000

---

Looking at the segfault traceback and the code I get the "feeling" that the problem could be due to using a char *buffer instead of an unsigned char *buffer.  So to experiment I changed it.  You can see what I changed on bobg.fc.hp.com /home/bobg/fossology/src/nomos/agent.  I didn't check it in because I don't feel great about it, plus I did not change all the variable types of the variables that use the buffer.  So make generates quite a few warnings about types that differ in signedness.  That said, my experiment did fix the 9c... test case.  Since your previous fix worked on your machine but not mine, perhaps you want to try my changes on your machine, and if they work, perhaps finish the job by getting rid of all the signedness warnings.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/12 06:23:23 +0000

---

yes, on my dev machine instead with unsigned char also can fix this issue, but lots of code change is needed, and why this change can fix this issue, have to change so much?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/12 21:24:03 +0000

---

I made this change because when you are working with unsigned bytes, it is usually best to declare them that way (unsigned char or uint8).  In this case I do not know exactly why this fixes the problem or if there is some sign propagation issue.  It just seemed faster to me to change what looks like an erroneous declaration than to try to debug what seems to be a very peculiar and machine specific error.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/13 16:14:04 +0000

---

Assigned to bobg to make the code changes to an unsigned char.  I'm still unhappy with this fix since there is no root cause analysis.  However, this does appear to fix the problem.  It was tested on two machines by Larry and me.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/18 17:26:47 +0000

---

Changing from char * to unsigned char * caused several regressions in nomos.  We are after code complete so deferring this to 2.6

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/18 23:11:25 +0000

---

This problem (memory corruption) appears to be in regcomp().  With the given test file, doing a regcomp() on %STR%  "[a-z]- [ ]*[a-z]" (_UTIL_HYPHEN in STRINGS.in), then doing a regfree() results in a segv right away.  The regcomp() did not throw an error.

Compiling nomos with the glibc memory checker:

make CFLAGS="-g -Wall -lmcheck"

lets the program throw the error:

```
== idxGrep(2059, 0x111cb00, 0x2)
... regex "[a-z]- [ ]*[a-z]"
*** glibc detected *** fossology/src/nomos/agent/nomos: free(): invalid pointer: 0x000000000111cf70 ***

```

Simplifying that regex and rerunning, the problem moves to a new regex (_CR_EASYSW).  Simplifying that the problem moves to a new regex (_URL_ORACLE_BERKELEY_DB) and simplifying that the problem moves back to the original _UTIL_HYPHEN.

Since this is 6 months old and we have not seen the problem again, I'm moving this to Target Version "New License Scanner" so that it becomes a test case for any new scanner.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/04/21 03:34:24 +0000

---

Bob Gobeille wrote:
> This problem (memory corruption) appears to be in regcomp().  With the given test file, doing a regcomp() on %STR%  "[a-z]- [ ]*[a-z]" (_UTIL_HYPHEN in STRINGS.in), then doing a regfree() results in a segv right away.  The regcomp() did not throw an error.
> 
> Compiling nomos with the glibc memory checker:
> 
> make CFLAGS="-g -Wall -lmcheck"
> 
> lets the program throw the error:
> 
> [...]
> 
> Simplifying that regex and rerunning, the problem moves to a new regex (_CR_EASYSW).  Simplifying that the problem moves to a new regex (_URL_ORACLE_BERKELEY_DB) and simplifying that the problem moves back to the original _UTIL_HYPHEN.
> 
> Since this is 6 months old and we have not seen the problem again, I'm moving this to Target Version "New License Scanner" so that it becomes a test case for any new scanner.
I can  not capture what you mean, we can have a talk in the meeting tomorrow.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4515/9cf7d8fb5646972c7fc7670f277a28e545aa65

**Comment by mcjaeger** [comment]
I have had no crashes of nomos since a year or so and also the instance with us is not crashing nomos. I tend to close it. I will try to retest the cases mentioned in the conversion for the 3.0.1 milestone.

**Comment by mcjaeger** [comment]
well the file does not crash on nomos in 3.0.0 anymore. closing.
