### ISSUE TITLE
SPDX Meta Tags

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#241]
---

Author Name: **larry shi** 
Original Redmine Issue: 6051, http://www.fossology.org/issues/6051
Original Date: 2013/11/12
Original Assignee: larry shi

---

Hi Bob,

I understand that here tag is the same with our license (short) name from nomos.
Also nomos has already has GPL-2.0+ license.

For “GPL-2.0 or MIT”, right now, nomos can report as “GPL-2.0, MIT, Dual-license”, certainly, if you still think “GPL-2.0 or MIT” is better, I can do it.

-Larry
From: Gobeille, Robert 
Sent: Tuesday, November 12, 2013 12:27 AM
To: Shi, Yao-Bin (Larry, GBU-HPSW, Cloud and OS)
Cc: fossology-devel@lists.fossology.org
Subject: Re: [FOSSology-devel] Fwd: SPDX Meta Tags

Hi Larry,
1. The word “tags” is overused but that is the term SPDX used for the text “SPDX-License-Identifier:”.  They are proposing that people “tag” their files with:

  SPDX-License-Identifier: {license name}

To make it easier to scan for licenses.

2.  see 1.

3. “GPL-2.0 or MIT” is much better information than what we provide (“GPL-2.0, MIT”).  “GPL-2.0 or MIT” is a dual license.  Meaning that one can choose either license.  Whereas, “GPL-2.0, MIT” doesn’t tell you if there are two separate licenses or if it is a dual license.

Thanks,
Bob Gobeille

On Nov 11, 2013, at 12:27 AM, Shi, Yao-Bin (Larry, GBU-HPSW, Cloud and OS) <yao-bin.shi@hp.com> wrote:

Hi Bob,
 
1.	What do you mean ‘’add more tags”? license (short) name?
2.	If yes, we already have GPL-2.0+ license (short) name. 
3.	For ‘GPL-2.0 or MIT’, I am not sure report ‘GPL-2.0 or MIT’ is better.
Right now, for one file, if nomos finds signatures of GPL-2.0 and MIT, will report both, likes like: GPL-.20, MIT.
 
 
From: fossology-devel-bounces@lists.fossology.org [mailto:fossology-devel-bounces@lists.fossology.org] On Behalf Of Shi, Yao-Bin (Larry, GBU-HPSW, Cloud and OS)
Sent: Monday, November 11, 2013 1:03 PM
To: Gobeille, Robert; fossology-devel@lists.fossology.org
Subject: Re: [FOSSology-devel] Fwd: SPDX Meta Tags
 
Hi bob,
Can you file a issue for this mail? Thanks 
-Larry
 
From: fossology-devel-bounces@lists.fossology.org [mailto:fossology-devel-bounces@lists.fossology.org] On Behalf Of Gobeille, Robert
Sent: Friday, November 08, 2013 10:47 PM
To: fossology-devel@lists.fossology.org
Subject: [FOSSology-devel] Fwd: SPDX Meta Tags
 
This is just a heads up about an SPDX proposal that is currently in DRAFT mode.  They are suggesting to add tags like:
SPDX-License-Identifier:        GPL-2.0+
SPDX-License-Identifier: (GPL-2.0 or MIT)
etc.
 
Bob Gobeille
 
 
Begin forwarded message:
 
From: "Lamons, Scott (Open Source Program Office)" <scott.lamons@hp.com>
Subject: SPDX Meta Tags
Date: November 7, 2013 at 5:10:03 PM MST
To: "Gobeille, Robert" <bob.gobeille@hp.com>
 
Bob,
 
Here’s the page that describes the proposed tagging standard:
http://wiki.spdx.org/view/Technical_Team/SPDX_Meta_Tags
 
U-boot would be a good test case if you decide to put this into the next release.
 
-Scott

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/13 09:32:10 +0000

---

1, how to Represent Multiple Licenses, we should pay more attention.

2. for your license is not on the SPDX license list, I will collect them in months. 


So, this issue here more looks like a placeholder, does not mean have to finish all the related jobs in one specific release.

**Comment by mcjaeger** [comment]
1. I propose to please do not copy mails with all header information straight in.
2. closed because of #478 https://github.com/fossology/fossology/pull/478
