### ISSUE TITLE
Broken Travis-CLI badge in README

### ISSUE THREAD

**Issue by mayank-pathakk** [fossology/fossology#2432]
### Description

The Travis svg in the readme does not render and instead a hyperlink is displayed 

#### How to reproduce

Visible on the home page of repository in the README.
I looked up and found that `travis.org` was been ceased and now it uses `travis.com`, but still I could not find fossology in travis.com.

Possible fix : Designing a svg from `image shield` just like the other svgs, and using the correct link to travis.

#### Screenshots
![travis-badge-bug](https://user-images.githubusercontent.com/97532378/231659063-7411f985-a2bc-4a09-b176-d30e8c7eed43.jpeg)

**Comment by mayank-pathakk** [comment]
I would like to work on this issue, can someone provide the correct link

**Comment by GMishx** [comment]
Solved by #2433
