### ISSUE TITLE
Copyright agent display limit 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#246]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6159, http://www.fossology.org/issues/6159
Original Date: 2013/12/03

---

copyright (hist.php) limits the number of rows that can be displayed.  The user will see
```
Too many rows to display

```
This limit is set by $MaxTreeRecs in hist.php.  A better solution would be to page the output.

**Comment by mcjaeger** [comment]
tested with actual version
with boost 1.55: "Showing 1 to 50 of 5,496 entries"
with linux kernel 3.12: "Showing 1 to 50 of 15,117 entries"
with linux kernel master from a couple of days: showing 16747 entries ...
and it did not seem to have particular problems ... what is the desired limit? 
I think that this is an issue of the old copyright UI, so closing.
Please reopen in case.
