### ISSUE TITLE
maintagent - add feature to remove failed uploads

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#247]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6165, http://www.fossology.org/issues/6165
Original Date: 2013/12/03
Original Assignee: Bob Gobeille

---

The following is from Larry on #4953:

how to test maintagent on failed uploads.
1. upload a file
2. during this upload's ununpack job has not completed, stop the scheduler.
3. then will find this upload is failed
4. run maintagent should delete that failed upload.

**Comment by mcjaeger** [comment]
closing it because the user might actually see that an upload failed and then delete manually.
