### ISSUE TITLE
enhancement suggestions from gerv 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#248]
---

Author Name: **larry shi** 
Original Redmine Issue: 6177, http://www.fossology.org/issues/6177
Original Date: 2013/12/04
Original Assignee: larry shi

---

gerv contacted me on IRC.  He works on a pretty big project (Firefox OS) and is inquiring about the feasibility of a license inference agent.

gerv would write this agent with our help.  It is an agent that infers a license based on file proximity..  For example, let’s say there are 10 files in a directory, 9 are MIT, and the last one is No_license_found.  Based on the proximity to the MIT files, gerv wants to label the No_license_found as MIT with a 90% probability.

Another situation where a license may be inferred is when a new version of a project is uploaded.  The license can be inferred based on the previous version of the file.  In this case the file has to have the same path, but its contents may have changed.  For example, /a/b.c is assigned a license either by nomos, the inference agent, or manually.  Then when a new version of /a/b.c is uploaded, it’s license can be inferred from the previous version, even though /a/b.c was modified.  Note, that if nomos picked up a different license in the new version, the inference agent would probably skip it (not override a nomos license unless the previous version had the same nomos license manually overridden).

The license_file table already has a field “rf_match_pct” that we have never used.  I put it in there in anticipation of future license scanners like this that could produce a match probability.  However, the field has never been implemented in the UI.

There are a lot of fine details that need to be worked out with the user interface, but it seems to me that gerv has a good idea here.

FYI, gerv’s FOSSology investigation page is:  https://wiki.mozilla.org/Fossology  but the main issue is stated above.

Comments?

Thanks,
Bob Gobeille

**Comment by steffen-weber** [comment]
The table license_file refer to pfile. Hence, all files with same hash would be shown as related to the inferred license. The license of a file may depend on the context. Moreover, should simple file that are only placeholders really be labeled? For huge and valuable files, these arguments might be wrong

**Comment by yaobinshi** [comment]
I agree, the same file in the different context may be inferred to different license, how about select the timestramp(or and the user) as the identifier?

**Comment by mcjaeger** [comment]
first example: inference for licenses if there are 9 of 10 files licensed, why not licensing also the tenth: because that is act of relicensing -> not recommended practise according to what I have heard from a couple of lawyers -> would be OK for closing then.
second example: reuser agent does that togther with decider agent, existing uploads of a prvious version can be selected for that at upload. -> close also
