### ISSUE TITLE
scheduler does not allow priority change

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#250]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6207, http://www.fossology.org/issues/6207
Original Date: 2013/12/10
Original Assignee: Dong Ma

---

It looks like the scheduler only uses the job priority when the job is initially queued.  We need to allow priority to change while the job is waiting in the queue.

To test:
1) queue up a job that runs long enough to perform the remainder of these steps.
2) queue up delagent
3) queue up another upload

In this case the job in step 3 will not run because the scheduler is waiting to run delagent, which can't be run in tandem with any other job.  So while the queue has these three jobs, raise the priority of the job in step 3 so that it runs before delagent.

**Comment by mcjaeger** [comment]
would be good, but not picked up so far.  I think a more basic problem about the scheduler is that people complain about performance / scheduling single user usage on a machine with a high number of cores
