### ISSUE TITLE
on Maintenance page, be able to check all checkboxs one time

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#251]
---

Author Name: **larry shi** 
Original Redmine Issue: 6231, http://www.fossology.org/issues/6231
Original Date: 2013/12/12
Original Assignee: Bob Gobeille

---

at least for -D, it runs 2 times. 

when runing maintagent from command line, has the same problem.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/12/12 15:26:48 +0000

---

This is what -a and -A are for.

Usage: ./maintagent [options]
  -a   :: Run all non slow maintenance operations.
  -A   :: Run all maintenance operations.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/12/13 02:48:13 +0000

---

on GUI or CLI, I mean when you check all the operations, 
e.g. ./maintagent -A -D, Vacuum Analyze run 2 times.

it is not critical for me, we can put it in 2.5.0.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/12/13 15:11:56 +0000

---

Yes, that is true.

**Comment by steffen-weber** [comment]
fixed by commit 528f310d3d681f55b4874547dce71097f04ec858
