### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by soham4abc** [fossology/fossology#2514]
Modify my recent and all recent jobs to get all the required data for UI.

**Comment by soham4abc** [comment]
Can I work on this issue?

**Comment by soham4abc** [comment]
Would also like to know the requirements or the additional data that is required for the UI for `jobs` endpoints

**Comment by GMishx** [comment]
Please have a look at following issues. We can have followup discussions during the GSoC calls:
* https://github.com/fossology/fossology/issues/1972
* https://github.com/fossology/fossology/issues/1301
