### ISSUE TITLE
bug: ambiguous value of rf_detector_type in licenseRef.json

### ISSUE THREAD

**Issue by avinal** [fossology/fossology#2522]
### Description

licenseRef.json has int and string values for `rf_detector_type`, it must be of one type, or it may create problem when parsing the json.

#### How to reproduce

- Open licenseRef.json
- Search for `rf_detector_type: "1"` and `rf_detector_type: 1`

#### Screenshots

1. 
![image](https://github.com/fossology/fossology/assets/74113200/844878c2-0485-4162-9eb2-7345e7f55226)

2. 
![image](https://github.com/fossology/fossology/assets/74113200/43ac9fc1-1c54-494b-b0b5-0a8e38107255)

### Versions

* Last commit id on master: 3a8b583f6acc271567a5e72b0728b35660887c42
* Operating System (lsb_release -a): N/A

**Comment by lata-11** [comment]
Hi! If this issue is still open, I would like to work. Can I go ahead?

**Comment by lata-11** [comment]
Hi @GMishx, I intend to solve this issue. By looking at the issue, I am able to figure out that both the rf_detector_type values could be changed to string "1" to solve this issue. Can I go ahead with this?

**Comment by GMishx** [comment]
Oops, I missed to update the issue. It was solved in #2646
