### ISSUE TITLE
How to get folderId by folder name?

### ISSUE THREAD

**Issue by leimaohui** [fossology/fossology#2527]
### Description

I tried to get folderId by folder name according to https://github.com/fossology/fossology/wiki/FOSSology-REST-API. But failed.

#### How to reproduce

```shell
curl -L -X POST \
  "https://fossology-server.com/repo/api/v1/uploads" \
  -H  "Authorization: Bearer xxx"
```

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

```
curl -L -X POST "http://192.168.70.199:8083/repo/api/v1/uploads"  -H "Authorization: Bearer xxx"
{"code":400,"message":"Require location object if uploadType != file.","type":"ERROR"}
```

**Comment by GMishx** [comment]
Thanks for creating the issue @leimaohui . The document needs to be updated. In the mentioned endpoint, the header `uploadType` is now marked as required. The value for the same should be `file` if you are uploading a file.

https://github.com/fossology/fossology/blob/4c9a370db9996260882e5ae7e55972c064daed84/src/www/ui/api/documentation/openapi.yaml#L539-L551

**Comment by GMishx** [comment]
Also, I noticed just now, the OpenAPI description also needs to be updated with the same on line https://github.com/fossology/fossology/blob/4c9a370db9996260882e5ae7e55972c064daed84/src/www/ui/api/documentation/openapi.yaml#L541

**Comment by leimaohui** [comment]
@GMishx 
Thank you for your reply. I got the issue of openAPI description.  
But I want to get the folderId by folder name. Can you tell me how I can do? Still by "POST  /uploads" ?

**Comment by GMishx** [comment]
I am sorry @leimaohui , the documentation was wrong for all these years and no one actually found it :-)

I have fixed the request. It should actually be a `GET` request to `/api/v1/folders` endpoint.

https://github.com/fossology/fossology/wiki/FOSSology-REST-API#1-query-folders

**Comment by leimaohui** [comment]
> I am sorry @leimaohui , the documentation was wrong for all these years and no one actually found it :-)
> 
> I have fixed the request. It should actually be a `GET` request to `/api/v1/folders` endpoint.
> 
> https://github.com/fossology/fossology/wiki/FOSSology-REST-API#1-query-folders

OK. Than you very much.
