### ISSUE TITLE
Source install testing need to use the tar ball instead of checking out source code

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#254]
---

Author Name: **Dong Ma** 
Original Redmine Issue: 6255, http://www.fossology.org/issues/6255
Original Date: 2013/12/13
Original Assignee: Dong Ma

---

None

**Comment by mcjaeger** [comment]
At least I am testing on build packages on our jenkins. can we close this?

**Comment by bobgob** [comment]
Install testing needs to be moved off HP infrastructure.  I think the question of whether we should be using a git checkout vs the tarball can be answered then.
