### ISSUE TITLE
scheduler functional test cannot stop 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#255]
---

Author Name: **larry shi** 
Original Redmine Issue: 6297, http://www.fossology.org/issues/6297
Original Date: 2014/01/06
Original Assignee: larry shi

---

the scheduler functional test cannot stop.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/01/06 10:10:25 +0000

---

it works, sometimes takes long time. rejecting.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/01/08 09:44:01 +0000

---

re-open this issue, on fotest server, hang at times.

**Comment by mcjaeger** [comment]
it would be good to have a test execution command for the "fucntional test of the scheduler"

**Comment by mcjaeger** [comment]
the ticket requires more help here:
a) how to test it?
b) what shall we do with "sometimes" errors?
is there more information available for tracking down this issue?

**Comment by mcjaeger** [comment]
after asking for more information more than a year ago -> no info, closing
