### ISSUE TITLE
add migration testing into CI system 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#256]
---

Author Name: **larry shi** 
Original Redmine Issue: 6303, http://www.fossology.org/issues/6303
Original Date: 2014/01/07
Original Assignee: larry shi

---

form me, one Debian-like and one RHEL-like distribution are enough.

**Comment by mcjaeger** [comment]
can we close it?

**Comment by bobgob** [comment]
we only have manual migration testing.  The issue is to put this into the CI system but I think that is going to be difficult with travis and we will have to use the LF infrastructure.

**Comment by mcjaeger** [comment]
again, we need the package build anyways before.

**Comment by mcjaeger** [comment]
there is not official CI
