### ISSUE TITLE
nomos: LGPL 2.1 header not recognized properly

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#257]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 6375, http://www.fossology.org/issues/6375
Original Date: 2014/01/12

---

Nomos 2.3 does not recognize the header of a file inside Vala properly, or actually it gets confused by some of the _content_ of the file:

This is the header:

/\* valaprojectgenerator.vala
 *
- Copyright (C) 2007-2008  Jürg Billeter
  *
- This library is free software; you can redistribute it and/or
- modify it under the terms of the GNU Lesser General Public
- License as published by the Free Software Foundation; either
- version 2.1 of the License, or (at your option) any later version.
- This library is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty of
- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
- Lesser General Public License for more details.
- You should have received a copy of the GNU Lesser General Public
- License along with this library; if not, write to the Free Software
- Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
  *
- Author:
-      Jürg Billeter j@bitron.ch
  */

As you can see it is very clearly LGPL 2.1

Later in the file in the _code_ there are some references to LGPL 3, which confuses Nomos:

typedef enum  {
        VALA_PROJECT_LICENSE_GPL2,
        VALA_PROJECT_LICENSE_GPL3,
        VALA_PROJECT_LICENSE_LGPL2,
        VALA_PROJECT_LICENSE_LGPL3
} ValaProjectLicense;

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/01/14 05:34:15 +0000

---

the reason is because the code below in test file:
    gtk_combo_box_append_text (self->priv->license_combobox, "GNU General Public License, version 3 or later");
    gtk_combo_box_append_text (self->priv->license_combobox, "GNU Lesser General Public License, version 2.1 or later");
    gtk_combo_box_append_text (self->priv->license_combobox, "GNU Lesser General Public License, version 3 or later");


no solution till now. thinking.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/19 07:35:13 +0000

---

this case is so special. 
no solution till now.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/19 08:23:13 +0000

---

a fix in git fbb80c, return GPL-3.0+,LGPL-2.1+, and added tests accordingly.

till now, has not found a method to just return LGPL-2.1+

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/06 10:47:43 +0000

---

GPL-3.0+ and LGPL-2.1+ are not exclusive, so I think return GPL-3.0+,LGPL-2.1+ is correct, not a defect. what do you think?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **armijn hemel** 
Original Date: 2014/03/06 10:59:42 +0000

---

This does not make any sense to me at all. *this* file is very clearly licensed under LGPL 2.1+. It has only some references to GPL 3 somewhere in the code, but it is not a license statement about *this* file, just a few C constants and strings that set up some infrastructure for *other* files/projects. That does not change the license of *this* file :-)

If the question that Nomos tries to answer is "which license is this file under?" then what Nomos is currently saying is clearly wrong.

If the question that Nomos tries to answer "which license identifiers were found" then the results are still wrong and you need to add many many more, see lines 52-55 and 1146-1150 of the file.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/01 21:09:36 +0000

---

Certainly, the correct question is "which license is this file under", and the correct answer is LGPL-2.1+.   

But this is a tough case for nomos.  I don't think lines 52-55 are relevant, but lines 1146-1150 are a problem, like Larry pointed out.   We pick up license identifiers because they are sometimes used as a license reference.  So one thing we can do is have nomos learn the context for picking up a license identifier, much like it does to ignore lines 52-55.  But this may not be practical.  Ideally, it would be good if nomos gave us a confidence level in the license ID.  For example, if it found the complete text of a common license reference, or the complete text of a license, it would report a 100% confidence.  If it only found an identifier, it would report a much lower confidence, or perhaps a different license name.  We actually have a field to report this in the database license_file table but it is unimplemented because nomos does not support it.  If we had this we could study the cases where only an identifier is found and see what rules we can come up with.  But because we don't currently have this capability we have made a decision to error on the side of false positives.  We would rather say this file has a GPL-3.0+ and be wrong than to miss a license.

Personally, I'd like to write a new scanner that combines the best of Ninka and Nomos and has the ability to determine a confidence level.  But we haven't made the decision to invest the time in this yet.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/04/18 08:42:37 +0000

---

this issue is critical, however change nomos to fix this issue is not a good idea, we have to find another solution, like bob said, possible, we should write a new scanner.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/18 14:54:57 +0000

---

I created a new Target Version called "New License Scanner".  I'd like to use this to keep track of features and bugs that are deemed too difficult to implement in Nomos.

This issue was initially a defect that the LGPL-2.1+ was not being reported.  That has been fixed.  However, Nomos generates a false positive when it sees  the lines like:
```
gtk_combo_box_append_text (self->priv->license_combobox, "GNU General Public License, version 3 or later");

```
This is in keeping with our philosophy that a false positive is better than not reporting a possible license.   A future license scanner should resolve this either by better false positive rejection or by assigning a confidence level to the results, or some other method.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4503/valaprojectgenerator.c

**Comment by mcjaeger** [comment]
I am not sure that a new license scanner target is helpful now. I am going to test this for 3.0.1 milestone and then retarget possibly.

**Comment by mcjaeger** [comment]
let's do some machine learning approach in future. Up to then, having the rule-based approach, it is right to report on the other licensing references.
