### ISSUE TITLE
Dark mode feature request

### ISSUE THREAD

**Issue by warriorBunny013** [fossology/fossology#2573]
### Description

I would like to request the implementation of a dark mode feature for the FOSSology web interface. Dark mode has become a popular and user-friendly feature in many software applications and websites. It not only enhances the user experience by reducing eye strain in low-light environments but also provides a modern and visually appealing design option.

#### How to Reproduce

This is an enhancement request, so there's no specific reproduction step. However, I can provide some insights on the expected behavior of the dark mode:

When a user toggles the dark mode option in the FOSSology web interface settings, the interface should switch to a dark color scheme. This would involve changing the background colors to darker shades, adjusting the text and UI element colors for better contrast, and ensuring that the overall design remains coherent and functional.

#### Screenshots

N/A

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Additional Information

Dark mode is a feature that many users appreciate, and its implementation would add value to the FOSSology web interface. It's important to consider accessibility and usability when designing the dark mode to ensure that the interface remains easy to navigate and read.

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by Pawank06** [comment]
Hey, I want to work on this issue. Is there anyone else who is working on this issue?

**Comment by attharva15** [comment]
Hey, i would i like to work on this issue.

**Comment by shaheemazmalmmd** [comment]
Currently we are trying to adopt the dark mode in new UI of FOSSology. you can find it here https://github.com/fossology/FOSSologyUI
