### ISSUE TITLE
DB column agent/agent_rev is too short

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#2579]
### Description
In table `agent`, column `agent_rev` is too short

With latest master branch, some my build (on local GitLab instance) produce very long Fossology Version, that are longer than 32 chars.

When starting Fossology, I get this error when it tries to register the agents in the table (for each agent)
```
ERROR:  value too long for type character varying(32)
STATEMENT:    INSERT INTO agent (agent_name, agent_rev, agent_desc)     VALUES ('adj2nest', '"tag_test_07-884-gbdbce4d4a".bdbce4', '(null)')
(...)
```

I got it fixed by growing the column length to 64 chars here:
https://github.com/fossology/fossology/blob/fca6abe95930b8becb08902461f05a6659542957/src/www/ui/core-schema.dat#L19

I suppose that could happen to anyone, depending how the build was made.

I can happily provide a PR for that change, except if anyone can think of a more subtle fix ?

**Comment by GMishx** [comment]
Hey @NicolasToussaint , in such case, I will recommend to use `text` as the field type instead as someone might exceed `64` char limit too. This datatype does not have any limit.

**Comment by lata-11** [comment]
Hi! I would like to work on this issue. Can I work if it is not done yet?

**Comment by NicolasToussaint** [comment]
> Hi! I would like to work on this issue. Can I work if it is not done yet?

Hi @lata-11 ,

I fixed it the dirty way on my own instance but I don't think I ever finalised anything to push upstream, unfortunately 
You're very welcome to fix this cleanly, thanks :-)

**Comment by lata-11** [comment]
Great. I'm on it.

**Comment by lata-11** [comment]
Hi @NicolasToussaint ,

I have raised the PR. Could you please review it?
