### ISSUE TITLE
User Cannot Change Password [4.3.0] [Bug]

### ISSUE THREAD

**Issue by wang-fut** [fossology/fossology#2587]
### Description

Modify an user's password and press 'Update Account' button got an "Email address already exists." error.

#### How to reproduce

Admin - Users - Edit User Account

Enter new password into "Passoword" & "Re-enter password" and click "Update Account" below

#### Screenshots

![image](https://github.com/fossology/fossology/assets/95271446/1b2a9901-f4bf-464b-a3d1-30c13d91847a)

### Versions

* 4.3.0 on Docker
* The Docker Image on Docker Hub has no Version info so I build image directly on source code

### Logs
nothing on logs

web:
"POST /repo/?mod=user_edit&newuser=14 HTTP/1.1" 200 6925 "http://domain.name:port/repo/?mod=user_edit&newuser=14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42"

db & scheduler:
[nothing]

**Comment by wang-fut** [comment]
I just tried same operations on https://fossology.osuosl.org/repo and got the same result.
The bug is still exist in latest build.

**Comment by vishisht-dubey** [comment]
Hiii @wang-fut i would like to solve this issue kindly assign me with this

**Comment by GMishx** [comment]
Hey @wang-fut , we have fixed the issue with #2620. You can test it on the latest Docker image in some time available with `docker pull fossology/fossology:latest`.
