### ISSUE TITLE
doc fix for copyright agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#259]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 6417, http://www.fossology.org/issues/6417
Original Date: 2014/01/17
Original Assignee: Bob Gobeille

---

attached patch fixes a bug in the copyright agent documentation. That section might need a good look anyway since other flags are mentioned that don't seem to exist (like -d )

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4491/copyright-2.4.0-doc.patch

**Comment by steffen-weber** [comment]
This patch was already applied in 213e76ee0ad31f409b08567eb9501417332b8ba9. Close this ticket?
