### ISSUE TITLE
[BUG]: Error during setup: php-sqlite3 does not install as a dependency

### ISSUE THREAD

**Issue by Akashsah2003** [fossology/fossology#2596]
### Description

When the steps for install as a dependency are followed during setup the build command gives error as php-sqlite3 extension is not installed and is a dependency.

#### How to reproduce

Follow the steps for installing from source given here: https://github.com/fossology/fossology/wiki/Install-from-Source
When `cmake --build ./build --parallel` command is run it gives the error attached as a screenshot below.

#### Screenshots

![error](https://github.com/fossology/fossology/assets/73382164/e6bfd8e7-04c5-4182-86b7-ac546fddbac3)

### Versions

* Operating System (lsb_release -a): Ubuntu 22.04.3

**Comment by shaheemazmalmmd** [comment]
@Akashsah2003 Install sqlite3 manually and try again it should work.

**Comment by Akashsah2003** [comment]
> @Akashsah2003 Install sqlite3 manually and try again it should work.

I have installed sqlite3 manually and setup is done. To make the setup process easier I was thinking that we could add this dependency in the utils/fo-dep script or we can add this step in the install from source guide. I would like to work on this issue.

**Comment by GMishx** [comment]
@Akashsah2003 , please go ahead. You can modify following lines and add `php-sqlite3` and `php<version>-sqlite3` at the end of each package list.

https://github.com/fossology/fossology/blob/e38c748b732b475b5ecc1fccba6dbafb2dfed69d/utils/fo-installdeps#L100-L111
