### ISSUE TITLE
‘(c)' is recognized as a copyright signature wrongly

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#261]
---

Author Name: **larry shi** 
Original Redmine Issue: 6597, http://www.fossology.org/issues/6597
Original Date: 2014/02/27
Original Assignee: larry shi

---

Hi Kotrappa,

It is very common for people to use ‘(c)’ in a copyright statement, so that’s why fossology flags this as a possible copyright.  Of course, in this case it is a false positive.  Fossology tends to error on the side of reporting possible copyrights (and licenses) rather than risk missing them.

This is a fossology issue, not spdx.

Thanks,
Bob Gobeille

On Feb 26, 2014, at 2:16 AM, <kotrappa.devershetty@wipro.com> <kotrappa.devershetty@wipro.com> wrote:

Hi Bob, Matt
 
We have installed Fossology 2.4.0 + SPDX 1.0 module. We scanned some of internal source code and tried to get .sdpx results by following command
 
wget -qO - --no-check-certificate --post-file=./imp_onoff.zip --timeout=0 "http://localhost/repo/?mod=spdx_license_once&noCopyright=false&jsonOutput=false&fullSPDXFlag=true&packageNameInLog=imp_onoff.zip" > imp_onoff.spdx
 
 
We found part of source code where switch(c) is available Fossology+SPDX module reported this part of source code as Copyright Info.
 
Please find results of scan as below.
 
FileName: setVariant.cpp
FileType: SOURCE
FileChecksum: SHA1: 5fbc973c8761ebd6b923010284408be700d6499d
LicenseConcluded: NOASSERTION
LicenseInfoInFile: LicenseRef-1
FileCopyrightText: <text>(c) copyright 2011
*  company      harman/becker automotive systems gmbh
author  simon ziehme
*
* @brief   to set varints to starter
(c)
      {
      case 'm' :
         para_m = 1;
         strcpy(cdefaultmarketcode, optarg);
http://en.wikipedia.org/wiki/power_of_two#fast_algorithm_to_check_if_a_positive_number_is_a_power_of_two</text>

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/02/27 09:35:16 +0000

---

fixed in git bee078 , will update tests later if this fix is make sense

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/04 01:43:13 +0000

---

have revert git (bee078 )

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/04 02:21:24 +0000

---

To be clear, we are pushing this to low priority until people report this as a common problem.  If we do have to fix this we might want to implement a dictionary of exceptions.

**Comment by mcjaeger** [comment]
first: it is ultra important to have an clear file to demonstrate the error / failure / whatever. 

I do not see a problem here anymore -please reopen if you think differently, see attached screenshot.

![2015-08-28 20_44_27-view copyright_email_url analysis](https://cloud.githubusercontent.com/assets/3418977/9554376/a9cdf2f0-4dc5-11e5-981a-5f30207791a5.png)
