### ISSUE TITLE
"Show Jobs" page displays *blank* nomos file count.

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#263]
---

Author Name: **Paul Guttmann** 
Original Redmine Issue: 6609, http://www.fossology.org/issues/6609
Original Date: 2014/02/28

---

Using Fossology 2.4 to process the attached files causes the "Show Jobs" page to show *blank* entries for the Nomos job row, even after completion. Using "License Browser" after completion does display the correct/expected file counts though.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2014/02/28 14:44:00 +0000

---

After a little more "investigation" - Looking at jobqueue table and jq_itemsprocessed column with phpPgAdmin, I notice that count(s) for 629 and 1321 are both 1. This would seem to imply that it may actually be the nomos agent that is failing to update the jobqueue table correctly as it processes files. Accordingly, I'll change the ticket category to Nomos from UI as it appears that the UI is displaying the information "available" which may be incorrect.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/04 16:06:48 +0000

---

I cannot reproduce this with our top of tree code Mar. 4, 2014

See attached file (mahout.gif)

**Comment by pguttmann** [comment]
Attachments: 1) http://www.fossology.org/attachments/4467/mahout-core-0.6-cdh4.0.0-job-org-apache-commons-math.zip
2) http://www.fossology.org/attachments/4473/mahout-core-0.6-cdh4.0.0-job-org-apache-mahout-math.zip
3) http://www.fossology.org/attachments/4479/mahout.gif

**Comment by steffen-weber** [comment]
cannot be reproduced with recent code (5bfa5c4f65b6aa51f1c6a4fbad311b88109451b1)
