### ISSUE TITLE
nomos missing unidentified license

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#264]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6627, http://www.fossology.org/issues/6627
Original Date: 2014/02/28
Original Assignee: larry shi

---

https://dashboard.tapjoy.com/dashboard/sdk/license

With nomos not knowing about the tapjoy license, it reports: GPL-2.0,MIT

It should report GPL-2.0,MIT, UnclassifiedLicense

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/04 02:15:42 +0000

---

Using tapjoy isn't a good test because once nomos learns tapjoy, that's how this license will be reported.

To test this issue, make a new test file composed of an unclassified license, a gpl reference, and an mit reference.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/07 07:34:20 +0000

---

have to talk with bob soon.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/11 01:03:30 +0000

---

This is a difficult fix due to the way nomos works.  If nomos finds a "popular" license it ignores lesser licenses like "Unknown".  This is a serious bug.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Silvano Cirujano Cuesta** 
Original Date: 2014/03/17 16:57:46 +0000

---

I agree in the seriousness of the bug. At least for us this is a critical issue.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/04/18 08:17:18 +0000

---

 due to the way nomos works, I have no solution for this issue.

any suggestions?

**Comment by yaobinshi** [comment]
will return Tapjoy, make sense?

**Comment by bobgob** [comment]
Yes, that makes sense to me (return "Tapjoy".  Has this been added to nomos/agent_tests/testdata/NomosTestfiles?

However, this issue isn't about Tapjoy.  The issue is to be able to find lesser licenses like "unknown" even when other license are present.

**Comment by yaobinshi** [comment]
>Yes, that makes sense to me (return "Tapjoy". Has this been added to >nomos/agent_tests/testdata/NomosTestfiles?
will add soon after getting some answers.

>However, this issue isn't about Tapjoy. The issue is to be able to find lesser licenses like "unknown" >even when other license are present.
I know that, report common and uncommon licenses together is not a easy job, according to the current logic of nomos, report both them will result in lots false positives, we can file another issue to trace.
I mean for this case, just return Tapjoy, make sense?

**Comment by bobgob** [comment]
This issue is about returning all licenses, not Tapjoy.  So why not just leave the issue open after adding Tapjoy.

**Comment by yaobinshi** [comment]
ok, let us  leave it.

**Comment by yaobinshi** [comment]
Tapjoy test is added days ago.

**Comment by mcjaeger** [comment]
tested now, see tapjoy. great.
