### ISSUE TITLE
[BUG] AS GITHUB->Actions does not work correctly

### ISSUE THREAD

**Issue by tdrozdovsky** [fossology/fossology#2641]
### Description

I use the product as github->action. But for the last few months it hasn't been working. Previously it worked great. Please tell me maybe I'm doing something wrong.

#### How to reproduce

I am using this file as github->actions:

```
name: Check diff for license with Fossology

on: [pull_request]

jobs:
  check-license:
    name: Check license
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_ACTIONS=true \
            fossology/fossology:scanner "/bin/fossologyscanner" nomos ojo

  check-copyright:
    name: Check copyright
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run --rm --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e GITHUB_PULL_REQUEST=${{ github.event.number }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_API=${{ github.api_url }} \
            -e GITHUB_REPO_URL=${{ github.repositoryUrl }} \
            -e GITHUB_REPO_OWNER=${{ github.repository_owner }} \
            -e GITHUB_ACTIONS \
            fossology/fossology:scanner "/bin/fossologyscanner" copyright keyword
```
But every time I get an error:
```
Status: Downloaded newer image for fossology/fossology:scanner
Traceback (most recent call last):
  File "/bin/fossologyscanner", line 273, in <module>
    sys.exit(main(args))
  File "/bin/fossologyscanner", line 233, in main
    cli_options.update_args(parsed_args)
  File "/bin/FoScanner/CliOptions.py", line 71, in update_args
    self.report_format = ReportFormat[args.report]
  File "/usr/lib/python3.9/enum.py", line 408, in __getitem__
    return cls._member_map_[name]
KeyError: <ReportFormat.TEXT: 0>
Error: Process completed with exit code 1.
```

**Comment by pranjul1203** [comment]
By adding -e GITHUB_ACTIONS=true in the check-copyright job, you ensure that the GITHUB_ACTIONS environment variable is correctly set

**Comment by tdrozdovsky** [comment]
> By adding -e GI

Thanks for the suggestion. I tried this before and it doesn't work

**Comment by tdrozdovsky** [comment]
> By adding -e GITHUB_ACTIONS=true in the check-copyright job, you ensure that the GITHUB_ACTIONS environment variable is correctly set

Thanks for the suggestion. I tried this before and it doesn't work

**Comment by GMishx** [comment]
There is a new parameter now `--report` to accept different report formats (`TEXT`, `SPDX_JSON`, `SPDX_RDF`, `SPDX_TAG_VALUE`, `SPDX_YAML`). The default value for it is `TEXT`. However, there is some programming issue in [fossologyscanner.py](https://github.com/fossology/fossology/blob/7ba0bc4800808ba6510c8defd3e828e51e833d8c/utils/automation/fossologyscanner.py#L268-L271).

Till it is fixed in code, as a hotfix/workaround, you can add the parameter `--report TEXT` (or any other format) like `fossology/fossology:scanner "/bin/fossologyscanner" --report TEXT copyright keyword` in the GitHub workflow file.

**Comment by dvjsharma** [comment]
> There is a new parameter now `--report` to accept different report formats (`TEXT`, `SPDX_JSON`, `SPDX_RDF`, `SPDX_TAG_VALUE`, `SPDX_YAML`). The default value for it is `TEXT`. However, there is some programming issue bellow
> 
> https://github.com/fossology/fossology/blob/7ba0bc4800808ba6510c8defd3e828e51e833d8c/utils/automation/fossologyscanner.py#L268-L271
> 
> Till it is fixed in code, as a hotfix/workaround, you can add the parameter `--report TEXT` (or any other format) like `fossology/fossology:scanner "/bin/fossologyscanner" --report TEXT copyright keyword` in the GitHub workflow file.

Hi @GMishx, I believe this can be improved. The default parameter sets the default value for the `--report` argument and it uses `ReportFormat.TEXT`, which is an enum member. However, when the user provides a value, it might be a string, not an enum member. Using `ReportFormat.TEXT.name` as the default value explicitly sets the default value as string "TEXT". This might fix the programming error you quoted. If you are good with the solution i'll open up a pull request. Please take a look.
