### ISSUE TITLE
getAllLicenseDataForUpload() SQL Syntax icorrect, export fails

### ISSUE THREAD

**Issue by uholeschak** [fossology/fossology#2648]
In AllDecisionsDao.php the SQL Syntax is incorrect, a space is missing, so export is not possible:
`"PHP Warning: pg_prepare(): Query failed: FEHLER: Müll folgt auf Parameter bei »$1U«"`
` " INNER JOIN uploadtree ut ON ce.uploadtree_fk=ut.uploadtree_pk WHERE ut.upload_fk=$1" .`
` "UNION DISTINCT " .`
To fix this add a space before UNION:
` " INNER JOIN uploadtree ut ON ce.uploadtree_fk=ut.uploadtree_pk WHERE ut.upload_fk=$1" .`
` " UNION DISTINCT " .`

**Comment by GMishx** [comment]
Can you please open a PR with the fix @uholeschak ?

**Comment by uholeschak** [comment]
Can't you simply add this space and done? Creating a pull request consumes to much time ...

**Comment by Hemant2335** [comment]
Can I work on this isuue
