### ISSUE TITLE
Better output from fo-postinstall

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#266]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6675, http://www.fossology.org/issues/6675
Original Date: 2014/03/13
Original Assignee: Dong Ma

---

Currently fo-postinstall emits a lot of output.  Martin Hamant has suggested that we log the output to a file to insure it doesn't get lost by forgetting to redirect upgrade output to a file.  Also, the output needs to be evaluated so that the user only sees what is relevant.  For example, perhaps verbose output could go the a log file but that is filtered for the important bits to be displayed to the user.

**Comment by mcjaeger** [comment]
could be done, but no movement for a long time.
