### ISSUE TITLE
REST API: Scancode Job does not run if the upload has already been scanned

### ISSUE THREAD

**Issue by chacabuco** [fossology/fossology#2666]
### Description

When calling up the Scancode Job through the REST API(POST /jobs) on an Upload that has already been scanned by Scancode, the Job does not get triggered.

#### How to reproduce
Pre-requisites:
The account that calls up the job has been assigned an access token.

Steps:
1.- Run Scancode on an Upload through the REST API
2.- Run Scancode on the same Upload again through the REST API, after having waited for the former analysis to be done.

Expected Result:
1.- The server gets the request, and responds with 201. It then proceeds to run the Job, and it can be seen on the GUI in Jobs->My recent Jobs
2.- The server gets the request, and responds with 201. It then proceeds to run the Job, and it can be seen on the GUI in Jobs->My recent Jobs

Actual Result:
1.- The server gets the request, and responds with 201. It then proceeds to run the Job, and it can be seen on the GUI in Jobs->My recent Jobs
2.- The server gets the request, and responds with 201. It does not run the job, and can NOT be seen on the GUI under Jobs-> My Recent Jobs **-> NOK**

### Versions

FOSSology version 4.3.0 (code revision 8b76e7)

### Code used to generate the REST API Request.

```
from __future__ import print_function
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint

# Configure OAuth2 access token for authorization: oauth
configuration = swagger_client.Configuration()
configuration.access_token = 'xxx'

# create an instance of the API class
api_instance = swagger_client.JobApi(swagger_client.ApiClient(configuration))
body = swagger_client.ScanOptions() # ScanOptions | Agents to be scheduled with the job
scancode = swagger_client.Scancode(True, True, True, True)
body.scancode = scancode
folder_id = y # int |
upload_id = z #  int |

try:
    # Schedule an Analysis
    api_response = api_instance.start_jobs(body, folder_id, upload_id)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling JobApi->start_jobs: %s\n" % e)

```

**Comment by GMishx** [comment]
Can you please share the screenshot/job logs from the UI?

Also, you can use the [fossology-python](https://github.com/fossology/fossology-python/) library as well to communicate with the REST API.

**Comment by chacabuco** [comment]
Hello,
There are no job logs since the second job does not get scheduled. Or do you want a screenshot of Jobs->"All Recent Jobs"?

**Comment by chacabuco** [comment]
Discussed on FOSSology Community Meeting. This is NOT a bug, it is a feature! I am trying to re-run the agent on an upload which has already been analyzed; therefore, it is my understanding it will not run again.
