### ISSUE TITLE
Issue with detection of BSD

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#267]
---

Author Name: **Silvano Cirujano Cuesta** 
Original Redmine Issue: 6693, http://www.fossology.org/issues/6693
Original Date: 2014/03/14
Original Assignee: larry shi

---

Nomos appears to have problems with the detection of BSD in some cases.

The scan of the attached archive COPYING_tests.7z illustrates this issue. This archive contains 10 files:
- COPYING: a file containing 9 different licenses (BSD-family)
- COPYING_1 to COPYING_9: each one of the single licenses

In following screenshot it can be observed that the individual licenses are detected as "BSD-3-Clause", "Sun(tm)", "BSD", "BSD-2-Clause" and "CMU". But the scan of the file grouping them all reports only "CMU" and "Sun(tm)"!

!Screenshot_COPYING_bug.png!

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Silvano Cirujano Cuesta** 
Original Date: 2014/03/14 16:09:51 +0000

---

The file COPYING contained inside of the archive COPYING_tests.7z should be added to the Nomos tests.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/14 16:31:46 +0000

---

This might be the same issue as #6627 where if nomos finds some licenses it ignores others as being unimportant.  We are past our code complete date for 2.5 so I'm putting the target version as 2.6.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Silvano Cirujano Cuesta** 
Original Date: 2014/03/17 07:52:00 +0000

---

Bob Gobeille wrote:
> This might be the same issue as #6627 where if nomos finds some licenses it ignores others as being unimportant.  We are past our code complete date for 2.5 so I'm putting the target version as 2.6.

What does it mean "ignores others as being unimportant"? Does it mean that Nomos doesn't report all found licenses? Which is the criteria to decide which licenses are unimportant?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/17 16:14:55 +0000

---

Yes, this means that in some cases, nomos does not report all licenses (see #6627).  For example, if it finds a GPL then I don't think it will keep looking for a Beerware license.  This is a serious problem that we need to address.

As far as the criteria goes for which licenses nomos thinks is important, I THINK the lesser important ones are given by LOWINTEREST() and MEDINTEREST() macros in parse.c.  Larry has been doing our Nomos maintenance so he should be able to give you a more authoritative answer.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/07/18 08:44:55 +0000

---

hi silvano,
this issue is different with #6627.

right now: there are couple of reasons why nomos can not report multiple licenses in a scanning file.
1) the 'if else logic', nomos detect license with lots of 'if else' clauses, when there are multiple licenses in one scanning file, these 'if else clauses' may restrict each other, can not be detected together. in our issue list, there are couple of related issues. such as #6069.
someone may say, why not use 'switch clause' to report all the licenses, because the performance will be very bad, so in the beginning, we did not do that way.
2) for UnclassifiedLicense, fossology only report when no license found or LOWER_INTERESTING license found. that is #6627.


so till now, for these similar issues, no solutions for me. we should find a innovative method to fix them.

**Comment by pguttmann** [comment]
Attachments - 1) http://www.fossology.org/attachments/4455/COPYING_tests.7z
2) http://www.fossology.org/attachments/4461/Screenshot_COPYING_bug.png

**Comment by mcjaeger** [comment]
note that most of the attachments are here:

http://archive15.fossology.org/projects/fossology/wiki/Github_attachments_

**Comment by mcjaeger** [comment]
Nomos output:

```
COPYING_tests.7z/COPYING_9: BSD-3-Clause
COPYING_tests.7z/COPYING_8: BSD-3-Clause
COPYING_tests.7z/COPYING_7: BSD-3-Clause
COPYING_tests.7z/COPYING_6: BSD-3-Clause
COPYING_tests.7z/COPYING_5: BSD-3-Clause
COPYING_tests.7z/COPYING_4: BSD-3-Clause
COPYING_tests.7z/COPYING_3: BSD-3-Clause
COPYING_tests.7z/COPYING_2: BSD-3-Clause
COPYING_tests.7z/COPYING_1: MIT-CMU
COPYING_tests.7z/COPYING: BSD-3-Clause
```
note that CMU-MIT in Copying_1 is the following license:

```
       Copyright 1989, 1991, 1992 by Carnegie Mellon University

		  Derivative Work - 1996, 1998-2000
Copyright 1996, 1998-2000 The Regents of the University of California

			 All Rights Reserved

Permission to use, copy, modify and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appears in all copies and
that both that copyright notice and this permission notice appear in
supporting documentation, and that the name of CMU and The Regents of
the University of California not be used in advertising or publicity
pertaining to distribution of the software without specific written
permission.

CMU AND THE REGENTS OF THE UNIVERSITY OF CALIFORNIA DISCLAIM ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS.  IN NO EVENT SHALL CMU OR
THE REGENTS OF THE UNIVERSITY OF CALIFORNIA BE LIABLE FOR ANY SPECIAL,
INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
FROM THE LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

```

-> looks good to me

(tested on: 3.4.0)
