### ISSUE TITLE
api token creation is not working in version 4.4.0.0 (7ba0bc)

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2682]
### Description

Please describe your situation in few words here.

#### How to reproduce

Go to admin > users > edit users account > Create a new token

Once we create the page refreshes but no token is visible

screenshot:
![chrome_UsoCM6NJQ0](https://github.com/fossology/fossology/assets/4498415/2c7fad1b-b3bf-49ce-8cb0-d18836960f5c)

### Versions

* Last commit id on master: Version: [4.4.0.0], Branch: [HEAD], Commit: [#7ba0bc] 2023/11/22 09:23 
* Operating System (lsb_release -a):  Ubuntu 20.04.2 LTS

#### FOSSology logs

No error log generated

**Comment by GMishx** [comment]
Hey @dineshr93 , 4.4.0 was tagged on 2024/01/15, the version string you pasted is from 2023/11/22
The issue was fixed in https://github.com/fossology/fossology/pull/2649 and merged before tagging 4.4.0
Please install the correct package/commit and try again.

**Comment by dineshr93** [comment]
> Hey @dineshr93 , 4.4.0 was tagged on 2024/01/15, the version string you pasted is from 2023/11/22 The issue was fixed in #2649 and merged before tagging 4.4.0 Please install the correct package/commit and try again.

Its working now Thanks @GMishx
