### ISSUE TITLE
"Require uploadType" error

### ISSUE THREAD

**Issue by seaykut** [fossology/fossology#2694]
### Description

I'm trying to upload a test file (*.tar.gz or license.txt) to Fossology server via Rest api, regarding to instructions here; https://www.fossology.org/get-started/basic-rest-api-calls/

But it gives "{"code":400,"message":"Require uploadType","type":"ERROR"}" error.

#### How to reproduce

Command :
url -k -s -S -X POST http://10.10.10.10:8081/repo/api/v1/uploads   
-H "folderId: 4"    
-H 'uploadDescription: created by REST'    
-H 'public: public' 
-H 'Content-Type: multipart/form-data'  
 -F 'fileInput=@"test.tar.gz";type=application/octet-stream'     
-H "Authorization: Bearer eyXttKYmPn13v5P0..."

### Versions

* Fossology ver : 4.4.0.11
* Ubuntu 20.4

**Comment by alpianon** [comment]
@seaykut those instructions are outdated. 

To get full documentation, I usually go to https://editor-next.swagger.io/ and then load the most recent openapi.yaml file into it (https://raw.githubusercontent.com/fossology/fossology/master/src/www/ui/api/documentation/openapi.yaml). You will see that a lot more parameters and data are required now to upload anything to fossology.

I guess that the issue title should be changed to "basic REST API calls instructions in Fossology website are outdated" or something like that :slightly_smiling_face:

**Comment by dvjsharma** [comment]
I agree with @alpianon. Perhaps the documentation will be included in #2695. In the meantime, Swagger Editor can be used for API information. Also, there is [openapi2.yml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapiv2.yaml) which contains details for V2 REST API calls.

**Comment by seaykut** [comment]
Thanks @alpianon @dvjsharma
