### ISSUE TITLE
Which is the most recent version of Postgres available for use (14/15/16...)?

### ISSUE THREAD

**Issue by MsPs2014** [fossology/fossology#2699]
Hello there, I'm currently working on a Fossology migration project. I wanted to know if anyone has worked on the latest version of fossology with a recent version of postgres? If yes, which one? Thanks :)

**Comment by GMishx** [comment]
Hey @MsPs2014 , I have tested it with 15 and it works without any change.

**Comment by MsPs2014** [comment]
> Hey @MsPs2014 , I have tested it with 15 and it works without any change.

I got this error
database files are incompatible with server
db-1         | 2024-03-12 10:33:30.807 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 15.6 (Debian 15.6-1.pgdg120+2).

**Comment by GMishx** [comment]
I guess you are using containers here. You need to migrate the data before changing the engine version. You can use [pg_upgrade](https://www.postgresql.org/docs/current/pgupgrade.html) or [pg_upgradecluser](https://medium.com/@gembit.soultan/how-to-upgrade-postgresql-15-to-postgresql-16-using-pg-upgradeclusters-in-ubuntu-22-04-c9f279c5d3ab) if you are looking for in-place upgrades.

Or, you can use [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html) to dump the data, drop the DB container, spin a new one for PG 15 and use [pg_restore](https://www.postgresql.org/docs/current/app-pgrestore.html) or `psql` to restore the data.

**Comment by MsPs2014** [comment]
it works :) thanks for your reply
