### ISSUE TITLE
License Browser Scanner Count is off

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#27]
It looks like the License Browser "Scanner Count" is summing the results from multiple versions of the license scanner.  For example, if both version 1 and 2 of nomos produced 1 Public-domain each, then the Scanner Count would show 2 instead of 1 for the last scan.  I'm only speculating here.

Sorry for the HP internal URL:
http://bobg.fc.hp.com/fossology/?mod=license&upload=257&item=21270940
I've attached a screenshot in case this helps:

![screen shot 2014-12-04 at 10 51 51 am](https://cloud.githubusercontent.com/assets/8060442/5303103/b8d63b08-7ba3-11e4-8540-6c4ec414a59e.jpg)

**Comment by mcjaeger** [comment]
Andreas' (wuan) sounds reasonable now, and since there has not been an update since 12 months, I am closing
