### ISSUE TITLE
Reimport of an exported SPDX RDF report is not working (since version 4.2.1.45)

### ISSUE THREAD

**Issue by JanAltenberg** [fossology/fossology#2701]
### Description

Starting from 4.2.1.45 (7bd7ecba621d25741c6b08e53f6dd9a8328be173) reimporting an exported RDF report does not work properly. The reportImport job returns success, but nothing is being imported. A `git bisect` returns the following as the offending commit:

```
commit 7bd7ecba621d25741c6b08e53f6dd9a8328be173
Author: Gaurav Mishra <mishra.gaurav@siemens.com>
Date:   Mon Jan 23 22:39:12 2023 +0530

    fix(spdx): add license text for valid RDF
    
    Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>

 src/spdx2/agent/spdx2.php                          | 101 +++++++++++++++++++--
 .../agent/template/dep5-copyright-document.twig    |  12 +--
 src/spdx2/agent/template/spdx2-document.xml.twig   |  33 +++++--
 src/spdx2/agent/template/spdx2-file.xml.twig       |  55 ++++++++++-
 src/spdx2/agent/template/spdx2tv-document.twig     |  12 +--
 5 files changed, 182 insertions(+), 31 deletions(-)
 ```
 
This commit introduces `<spdx:ListedLicense>`, which is not being parsed when importing an RDF report.

#### How to reproduce

1. Take any FOSSology version >= 4.2.1.45
2. Upload and scan a package
3. Put your license decisions
4. Generate an SPDX RDF report
5. Upload the same package without any action
6. Do "Import Report" for the new upload and use the previously exported RDF report

### Versions

* Any version starting with commit 7bd7ecba621d25741c6b08e53f6dd9a8328be173

#### Job logs

The logs of the reportImport job show the following entries:

```
[...]
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
reportImport [0] :: JOB[96].reportImport[2613423.localhost]: "ERROR: can not handle license=[Array] of type=[array]"
[...]
```

### Further analysis

The above mentioned commit introduces `<spdx:ListedLicense>`, which is not taken into account in `parseLicense()` (`src/reportImport/agent/SpdxTwoImportSource.php`)

I have verified this finding by adding the following patch for testing purposes:

```
diff --git a/src/reportImport/agent/SpdxTwoImportSource.php b/src/reportImport/agent/SpdxTwoImportSource.php
index 455991c01..c80719fd8 100644
--- a/src/reportImport/agent/SpdxTwoImportSource.php
+++ b/src/reportImport/agent/SpdxTwoImportSource.php
@@ -302,7 +302,8 @@ class SpdxTwoImportSource implements ImportSource
         return array($item);
       }
     }
-    elseif ($this->isPropertyOfType($license, 'License'))
+    elseif ($this->isPropertyOfType($license, 'License') ||
+            $this->isPropertyOfType($license, 'ListedLicense'))
     {
       $licenseId = $this->stripLicenseRefPrefix($this->getValue($license,'licenseId'));
       $item = new ReportImportDataItem($licenseId);
```

With the above mentioned change the RDF import worked for me.

Let me know, if I can support with any further information.

Many thanks
Jan

**Comment by JanAltenberg** [comment]
Thanks @OliverFendt for your feedback.
@GMishx @shaheemazmalmmd I would be glad to support in resolving this issue. Just let me know, if the proposed change is okay, or if you see anything else to be done and I will create a pull request (same applies for #2703)

**Comment by GMishx** [comment]
Hey @JanAltenberg ,thanks for investigating into the issues. The solution you posted seems good. Please go ahead and create a PR for the same.

In the meantime, I am working on rewriting the agent to read RDF files directly and not as PHP arrays. This will help in extending the agent for new spdx versions like 3.x

**Comment by JanAltenberg** [comment]
Thanks @GMishx, I've just created a pull request :)
