### ISSUE TITLE
Importing an RDF report can fail with "shortname already in use" when matching with SPDX ID

### ISSUE THREAD

**Issue by JanAltenberg** [fossology/fossology#2703]
### Description
Commit d1e1b6e0dde4e37aa62e63b3246fd6b313e3d4d4 introduced an option to select the method for matching licenses when importing an RDF report (either by "SPDX ID" or by "Shortname").

```
commit d1e1b6e0dde4e37aa62e63b3246fd6b313e3d4d4
Merge: c669ce4f7 c173a05ce
Author: Shaheem Azmal M MD <shaheem.azmal@gmail.com>
Date:   Thu Jan 19 14:33:20 2023 +0530

    Merge pull request #2363 from siemens/feat/spdx/spdx-2-id
    
    feat(license): use spdx identifiers for reporting licenses
    
    Reviewed-by: shaheem.azmal@siemens.com
    Tested-by: shaheem.azmal@siemens.com
```

When selecting "SPDX ID", import of an RDF report can fail completely, if the report contains at least one license statement without an SPDX ID, that can be matched.

#### How to reproduce

1. Take any FOSSology version starting from commit d1e1b6e0dde4e37aa62e63b3246fd6b313e3d4d4
2. Choose a package for which you have an existing report
   * To reproduce the problem, the report has to contain at least one license statement that cannot be matched by SPDX ID (examples, that failed in my tests are: Public-domain, Dual-license, ...)
   * I tested with busybox-1.36.1 and took an existing report from the OSSelot project (https://www.osselot.org)
3. Upload the same package without any action
4. Do "Import Report" with the existing SPDX RDF report (and select "SPDX ID" under "Match license using")

The import will fail at the point, where the license statement can not be matched with an SPDX ID.

### Versions

Any version starting with commit d1e1b6e0dde4e37aa62e63b3246fd6b313e3d4d4

#### Job logs
```
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "Caught exception while processing uploadId=14: shortname already in use#0 /usr/local/share/fossology/reportImport/agent/ReportImportSink.php(105): Fossology\ReportImport\ReportImportSink->getIdForDataItemOrCreateLicense()"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#1 /usr/local/share/fossology/reportImport/agent/ReportImportAgent.php(291): Fossology\ReportImport\ReportImportSink->handleData()"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#2 /usr/local/share/fossology/reportImport/agent/ReportImportAgent.php(131): Fossology\ReportImport\ReportImportAgent->walkAllFiles()"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#3 /usr/local/share/fossology/lib/php/Agent/Agent.php(328): Fossology\ReportImport\ReportImportAgent->processUploadId()"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#4 /usr/local/share/fossology/reportImport/agent/reportImport.php(13): Fossology\Lib\Agent\Agent->run_scheduler_event_loop()"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#5 /usr/local/lib/fossology/fo_wrapper(65): require('/usr/local/shar...')"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#6 {main}agent failed on uploadId=14#0  Fossology\Lib\Agent\Agent->bail() called at [/usr/local/share/fossology/lib/php/Agent/Agent.php:339]"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#1  Fossology\Lib\Agent\Agent->run_scheduler_event_loop() called at [/usr/local/share/fossology/reportImport/agent/reportImport.php:13]"
reportImport [0] :: JOB[81].reportImport[2377839.localhost]: "#2  require(/usr/local/share/fossology/reportImport/agent/reportImport.php) called at [/usr/local/lib/fossology/fo_wrapper:65]"
```

### Further analysis
In `getIdForDataItemOrCreateLicense` (`src/reportImport/agent/ReportImportSink.php`) the license is matched (depending on the selected option):
 ```
     $licenseShortName = $dataItem->getLicenseId();
     if ($this->configuration->shouldMatchLicenseNameWithSPDX()) {
       $license = $this->licenseDao->getLicenseBySpdxId($licenseShortName, $groupId);
     } else {
       $license = $this->licenseDao->getLicenseByShortName($licenseShortName, $groupId);
     }
 ```
 
Whenever `getLicenseBySpdxId` returns null, we run into the following exception and the import fails at that point:
 

 ```
     elseif (! $this->licenseDao->isNewLicense($licenseShortName, $groupId))
    {
      throw new \Exception('shortname already in use');
    }
```

I've checked this finding by adding a fallback to `getLicenseByShortName()` when `getLicenseBySpdxId()` fails.

```
diff --git a/src/reportImport/agent/ReportImportSink.php b/src/reportImport/agent/ReportImportSink.php
index 6b444e55f..57e2f79f1 100644
--- a/src/reportImport/agent/ReportImportSink.php
+++ b/src/reportImport/agent/ReportImportSink.php
@@ -139,6 +139,10 @@ class ReportImportSink
     $licenseShortName = $dataItem->getLicenseId();
     if ($this->configuration->shouldMatchLicenseNameWithSPDX()) {
       $license = $this->licenseDao->getLicenseBySpdxId($licenseShortName, $groupId);
+      if ($license == null) {
+             echo "WARNING: Could not match Shortname=\"$licenseShortName\" with SPDX ... trying ShortName ...\n";
+             $license = $this->licenseDao->getLicenseByShortName($licenseShortName, $groupId);
+      }
     } else {
       $license = $this->licenseDao->getLicenseByShortName($licenseShortName, $groupId);
     }
```

Let me know, if I can support with any further information.

Many thanks
Jan

**Comment by OliverFendt** [comment]
@JanAltenberg and @shaheemazmalmmd this relates to import report, thus my comment on #2701 applies here to.
@shaheemazmalmmd can you please look into it and fix it?
Thank you very much

**Comment by JanAltenberg** [comment]
@GMishx @shaheemazmalmmd thank you so much for your feedback on #2701. If you're fine with the proposed change here (or you have any additional comments / proposals), please let me know and I can prepare a pull request for a fix for this issue as well.

Thanks again

**Comment by GMishx** [comment]
@JanAltenberg the proposed changes looks good to me. As commented on #2701, please go ahead and open a PR :-)

**Comment by JanAltenberg** [comment]
Thanks again @GMishx for the feedback. If just opened a PR.
