### ISSUE TITLE
"Require uploadType" error with API v1

### ISSUE THREAD

**Issue by seaykut** [fossology/fossology#2708]
### Description

I'm trying to upload a file to another Fossology server with API v1 but it gives "Require uploadType" error.

#### How to reproduce

```
 curl -X POST "http://10.10.10.10:8081/repo/api/v1/uploads" \
     -H "Authorization: Bearer xxxxxxxxxxxxxxx" \
     -F "fileInput=@/home/repos.tar.gz;type=application/gzip" \
     -F "folderId=1" \
     -F "uploadDescription=License" \
     -F "public=public" \
     -F "uploadType=file"
```

```
curl -X POST "http://10.10.10.10:8081/repo/api/v1/uploads"     
-H "Authorization: Bearer xxxxxxxxxxxxxxx"      
-F "fileInput=@/home/repos.tar.gz;type=application/gzip"      
-F "folderId=1"      
-F "uploadDescription=license"      
-F "public=public"     
-F "groups=groupName"      
-F "uploadType=file"
```

### Versions

Version: [4.4.0.11], Branch: [master], Commit: [#2ce7d2] 2024/03/06 07:12 +00:00 built @ 2024/03/06 10:01 +00:00

### Error

{"code":400,"message":"Require uploadType","type":"ERROR"}

**Comment by dvjsharma** [comment]
Hello @seaykut, in v1 API requests, these parameters are expected to be found in headers rather than the request body as detailed in [opanapi.yaml](https://github.com/fossology/fossology/blob/67e5a73b3856d08df872ae10ca45c59544ecd4bf/src/www/ui/api/documentation/openapi.yaml#L747-L798). So a request with below format should work fine for v1:
```
curl -X 'POST' \
  'http://localhost/repo/api/v1/uploads' \
  -H 'accept: application/json' \
  -H 'folderId: 1' \
  -H 'public: public' \
  -H 'applyGlobal: false' \
  -H 'ignoreScm: false' \
  -H 'uploadType: file' \
  -H 'Authorization: Bearer xxxxxxxxxxxxxxx' \
  -H 'Content-Type: multipart/form-data' \
  -F 'fileInput=@platform-client-mzima-2024.10.0.tar.gz;type=application/gzip'
 ```
Output- `{"code":201,"message":8,"type":"INFO"}`

Please update the command and try again.

**Comment by seaykut** [comment]
Thanks @dvjsharma , that command worked.

Are the instructions on this page up to date? -> https://github.com/fossology/fossology/wiki/FOSSology-REST-API#a-check-if-upload-is-finished

If not, is there any other up to date instructions that I can follow?

**Comment by dvjsharma** [comment]
Hey @seaykut, you can check out the v1 API documentation in [openapi.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml) and the v2 API documentation in [openapiv2.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapiv2.yaml). These files contain the latest documentation, including any updates to the API code. They can also be imported into [Swagger Editor](http://editor.swagger.io/) for a user-friendly interface. The editor provides CURL commands for reference. Simply send a request to view the command.

![image](https://github.com/fossology/fossology/assets/119073504/ed0f7aeb-6bb8-4f98-9b3e-0f1fd2ab88b0)
_a `GET` request to `/uploads` endpoint_

**Comment by GMishx** [comment]
> Thanks @dvjsharma , that command worked.
> 
> Are the instructions on this page up to date? -> https://github.com/fossology/fossology/wiki/FOSSology-REST-API
> 
> If not, is there any other up to date instructions that I can follow?

Hey @seaykut , https://github.com/fossology/fossology/wiki/FOSSology-REST-API is the updated REST API guide. But the most updated doc, as @dvjsharma said, is [openapi.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml) which you can load in swagger editor and play with it.
