### ISSUE TITLE
Upgrade the User & Group APIs to Version 2

### ISSUE THREAD

**Issue by dushimsam** [fossology/fossology#2709]
# Upgrade the /users & /groups APIs to Version 2

**In accordance with our new policy documented [here](https://github.com/fossology/fossology/issues/2404#issuecomment-1671046653), we want to enhance our REST APIs to Version 2 migrating all `/users` APIs. The setup for the Version 2 is already in place.**

#### 1.  **/users**,  POST
<img width="926" alt="Screenshot 2024-04-03 at 05 43 58" src="https://github.com/fossology/fossology/assets/66276301/ecd29585-9848-41a1-b42a-5e289625e2b2">

- Change these fields to camelCase: `copyright_email_author`, `user_pass`

#### 2.  **/users** & **/users/{id}**,  GET

<img width="654" alt="Screenshot 2024-04-03 at 05 46 23" src="https://github.com/fossology/fossology/assets/66276301/3fbfa693-b0d8-472c-ba59-36aa332f4780">

- Change these fields to camelCase: `copyright_email_author`

#### 3.  **/users/{id}**,  PUT
<img width="926" alt="Screenshot 2024-04-03 at 05 43 58" src="https://github.com/fossology/fossology/assets/66276301/75eedf74-689c-42b5-a496-49be0f510af7">

- Change these fields to camelCase: `copyright_email_author`, `user_pass`

####  4. **/users/self**, GET
<img width="799" alt="Screenshot 2024-04-03 at 05 51 49" src="https://github.com/fossology/fossology/assets/66276301/7a317d74-0c1f-438f-a3fc-d2a3ea407e5a">

- Change these fields to camelCase: `copyright_email_author`, `default_group`

#### 5. **/users/tokens**, POST

<img width="946" alt="Screenshot 2024-04-03 at 05 57 04" src="https://github.com/fossology/fossology/assets/66276301/10c7eb0e-44f1-4060-95cf-18ef4221b409">

- Change these fields in requestBody to camelCase: `token_name`, `token_scope`, `token_expire`

#### 6. **/users/tokens/{type}**, GET

<img width="782" alt="Screenshot 2024-04-03 at 05 58 58" src="https://github.com/fossology/fossology/assets/66276301/73326cac-e2f4-415c-873d-aafa2c3c38cb">

- Change these fields to camelCase: `active_tokens`, `token_name`, `token_expire`

#### 7.  **/groups**,  POST

<img width="782" alt="Screenshot 2024-04-03 at 06 22 02" src="https://github.com/fossology/fossology/assets/66276301/4c071335-68f4-45c8-8959-59aed9906c8c">

- Move `name` from the headers to query parameters.

#### 8.  **/groups/{id}/members**,  GET

<img width="778" alt="Screenshot 2024-04-03 at 06 26 13" src="https://github.com/fossology/fossology/assets/66276301/34fe4f52-6d6d-4d14-ba65-d4d83dd6eb13">

- Change these fields to camelCase: `copyright_email_author`, `group_perm`

Cc: @GMishx @shaheemazmalmmd

**Comment by dvjsharma** [comment]
I'll look into this

**Comment by shaheemazmalmmd** [comment]
Can be closed as this work is already done as part of GSOC-2024
