### ISSUE TITLE
a none permission user can get an upload list via /delagent  -f

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#271]
---

Author Name: **larry shi** 
Original Redmine Issue: 6729, http://www.fossology.org/issues/6729
Original Date: 2014/03/18
Original Assignee: Dong Ma

---

larry@bl460c-10:~/fossology/src/delagent/agent$ ./delagent  --user t2 --password '' -f
1. Folders
   1 :: Software Repository
     -- :: Contains: fossology_2.4.0-1.tar.gz
     -- :: Contains: fossology_2.4.0-1.tar.gz
     -- :: Contains: fossology-buckets-2.4.0-1.el6.x86_64.rpm
     -- :: Contains: fossology.git
     -- :: Contains: grit.git
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.php
     -- :: Contains: *.rpm
     -- :: Contains: schema-export.php
     -- :: Contains: schema-export.php
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
     -- :: Contains: test
      3 :: tests250
         4 :: command
           -- :: Contains: *.deb
        -- :: Contains: fossology-buckets-2.4.0-1.el6.x86_64.rpm

**Comment by mcjaeger** [comment]
I am snot sure I understood the issue right, does it mean that a user can get permissing while she is logged into the machine where fossology is running.

**Comment by bobgob** [comment]
It just means that delagent isn't respecting the permission scheme.

**Comment by mcjaeger** [comment]
seems to be releated with #272 and #273 BTW

**Comment by maximilianhuber** [comment]
maybe related to #368

**Comment by maximilianhuber** [comment]
Solved by #573
