### ISSUE TITLE
Upgrade the Folder & License APIs to Version 2

### ISSUE THREAD

**Issue by dushimsam** [fossology/fossology#2710]
# Upgrade the /folders , /obligations & /license APIs to Version 2

**In accordance with our new policy documented [here](https://github.com/fossology/fossology/issues/2404#issuecomment-1671046653), we want to enhance our REST APIs to Version 2 migrating all `/folders` & `/license` APIs. The setup for the Version 2 is already in place.**

#### 1.  **/folders**,  POST
<img width="743" alt="Screenshot 2024-04-03 at 06 35 29" src="https://github.com/fossology/fossology/assets/66276301/64d7cce4-f7a1-4944-933d-01db4de5a262">

- Move `parentFolder`, `folderName`, `folderDescription`, `groupName` from the headers to query parameters.

#### 2.  **/folders/{id}**,  DELETE
<img width="738" alt="Screenshot 2024-04-03 at 06 37 29" src="https://github.com/fossology/fossology/assets/66276301/ab0eb68c-03ca-4442-bb61-3cf72fd51f19">

- Move `groupName` from the headers to query parameters.

#### 3.  **/folders/{id}**,  PATCH
<img width="787" alt="Screenshot 2024-04-03 at 06 38 33" src="https://github.com/fossology/fossology/assets/66276301/ab30fe30-956c-461a-b9ee-ba930747ad6d">

- Move `name`, `description`, `groupName` from the headers to query parameters.

#### 4.  **/folders/{id}**,  PUT
<img width="780" alt="Screenshot 2024-04-03 at 06 40 40" src="https://github.com/fossology/fossology/assets/66276301/db8442b9-e85a-4719-9a35-78b8806e2922">

- Move `parent`, `action`, `groupName` from the headers to query parameters.

#### 5.  **/folders**,  GET
<img width="494" alt="Screenshot 2024-04-03 at 06 42 13" src="https://github.com/fossology/fossology/assets/66276301/5cdff416-2325-4d9c-8f3d-381e66c89acb">

- Move `groupName` from the headers to query parameters.

#### 6. **/folders/{id}**, GET
<img width="774" alt="Screenshot 2024-04-03 at 06 43 43" src="https://github.com/fossology/fossology/assets/66276301/31d70216-1e0b-4287-a11d-371ce92fb72f">

- Move `groupName` from the headers to query parameters.

#### 6. **/license**, GET

<img width="605" alt="Screenshot 2024-04-03 at 06 59 08" src="https://github.com/fossology/fossology/assets/66276301/9154f2c0-11ac-475e-9029-9ebe99030936">

- Move `page`, `limit`, `active`, `groupName` from the headers to query parameters.

#### 6. **/license**, POST

![image](https://github.com/fossology/fossology/assets/66276301/658dbe04-1e32-4237-9fdc-103e39a22130)

- Move `groupName` from the headers to query parameters.

#### 7. **/license/import-csv**, POST

<img width="564" alt="Screenshot 2024-04-03 at 07 02 35" src="https://github.com/fossology/fossology/assets/66276301/8192e3d1-8af2-44dc-81ec-127d14556ac7">

- Change `file_input` to camelCase (`fileInput`)

#### 8. **/license/{shortname}**, GET
<img width="600" alt="Screenshot 2024-04-03 at 07 04 04" src="https://github.com/fossology/fossology/assets/66276301/35b79712-f615-4d47-b3df-abbcb23c4a7e">

- Move `groupName` from the headers to query parameters.

#### 9. **/license/{shortname}**, PATCH
<img width="600" alt="Screenshot 2024-04-03 at 07 04 04" src="https://github.com/fossology/fossology/assets/66276301/35b79712-f615-4d47-b3df-abbcb23c4a7e">

- Move `groupName` from the headers to query parameters.

#### 10. **/license/admincandidates**, GET

<img width="733" alt="Screenshot 2024-04-03 at 07 06 03" src="https://github.com/fossology/fossology/assets/66276301/e7f6a195-591c-47b5-b2f7-09a3faa849b3">

- Change `group_id`, `group_name` to camelCase.

#### 11. **/license/adminacknowledgements**, GET

<img width="737" alt="Screenshot 2024-04-03 at 07 08 03" src="https://github.com/fossology/fossology/assets/66276301/cf5bca34-476b-45ae-ab80-a08d1cadb94f">

- Change `is_enabled` to camelCase.

#### 12. **/license/stdcomments**, GET

<img width="737" alt="Screenshot 2024-04-03 at 07 09 34" src="https://github.com/fossology/fossology/assets/66276301/c3e731f0-a02a-47a6-8573-ed546120c257">

- Change `is_enabled` to camelCase.

#### 13. **/obligations/list**, GET

<img width="810" alt="Screenshot 2024-04-28 at 13 06 02" src="https://github.com/fossology/fossology/assets/66276301/1e537b0e-6973-49fb-8063-68e80b2bbf97">

- Change `obligation_topic` to camelCase.

#### 14. **/obligations/import-csv**, POST

<img width="991" alt="Screenshot 2024-04-28 at 13 12 15" src="https://github.com/fossology/fossology/assets/66276301/5a7575e5-4827-4dee-86f3-1b26750f8f04">

- Change `file_input` to camelCase.

#### 15. **/filesearch**, POST

![image](https://github.com/fossology/fossology/assets/66276301/d0ced7e0-0815-4c7d-a705-4ba35ee2c30d)

- Move `groupName` from headers to query parameters.

#### 16. **/tokens**, POST

<img width="640" alt="Screenshot 2024-04-28 at 13 54 58" src="https://github.com/fossology/fossology/assets/66276301/3f586079-0694-461f-9853-124036fc4404">

- Move change to camelCase: `token_name`, `token_scope`, `token_expire`

Cc: @GMishx @shaheemazmalmmd

**Comment by dvjsharma** [comment]
I'll look into this

**Comment by dushimsam** [comment]
Have added more APIs to improve (`/obligations`)

**Comment by shaheemazmalmmd** [comment]
Can be closed as this work is already done as part of GSOC-2024
