### ISSUE TITLE
Alert mechanism via API

### ISSUE THREAD

**Issue by seaykut** [fossology/fossology#2713]
### Description

I'm trying to create alert or some kind of notification, if I found a specific type of licences on SPDX or Cyclonedx reports. 

For example if my repo has GPL3 license, somehow I want to be informed about it.

I checked API and other documentations but couldn't find anything. 

Is that possible in Fossology?

Or should I just basically grep the report file?

### Versions

Version: [4.4.0.11], Branch: [master], Commit: [#2ce7d2]

**Comment by shaheemazmalmmd** [comment]
@seaykut : there is no such type of alert functionality in fossology(may use grep). but you may take a look onto compatibility agent which was merged recently.
