### ISSUE TITLE
As a User I would like to filter out files by extension on the search box.

### ISSUE THREAD

**Issue by chacabuco** [fossology/fossology#2718]
### Description
In the upload view, I would like to filter out all of the files that end with a certain extension, maybe adding regex support would be the cleanest solution, so that one can extend the search functionality.  I don't know what the backend on the search functionality might be, but I guess using the backend's regex expressions would be advisable. 

#### Screenshots
![Bildschirmfoto vom 2024-04-18 11-52-09](https://github.com/fossology/fossology/assets/63021395/dacd385b-695d-4b83-938f-12bc79a22a4b)

**Comment by Akashsah2003** [comment]
I'll look into this.

**Comment by Akashsah2003** [comment]
> ### Description
> In the upload view, I would like to filter out all of the files that end with a certain extension, maybe adding regex support would be the cleanest solution, so that one can extend the search functionality. I don't know what the backend on the search functionality might be, but I guess using the backend's regex expressions would be advisable.
> 
> #### Screenshots
> ![Bildschirmfoto vom 2024-04-18 11-52-09](https://private-user-images.githubusercontent.com/63021395/323556960-dacd385b-695d-4b83-938f-12bc79a22a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDg5NDIsIm5iZiI6MTcxMzUwODY0MiwicGF0aCI6Ii82MzAyMTM5NS8zMjM1NTY5NjAtZGFjZDM4NWItNjk1ZC00YjgzLTkzOGYtMTJiYzc5YTIyYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA2MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYmEzYWY5M2ZhOGJlOTBhZGY2ZmMzODQwYjQ1Y2MxM2VmZDY0ZDE1MjEwOWVkNTYwMjRiZGNiYmM2NTVmYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.McbgOZ0Ip__fAPls_cIRkwU2qrxmidyBfekm-gpPfWw)

Hey @chacabuco, I looked through the server side code for table in the license browser page and found that this functionality is already existing. You can use it by entering `ext:` followed by the file extension name in the search box. For instance to search for text files you can type `ext:txt` in the search box. 


![Screenshot from 2024-04-19 12-12-05](https://github.com/fossology/fossology/assets/73382164/5b0b6edd-e15d-4649-b67b-a05e89390e81)

**Comment by shaheemazmalmmd** [comment]
@chacabuco :  the functionality already exists.
