### ISSUE TITLE
any user who is not the owner can delete any upload via /delagent -U

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#272]
---

Author Name: **larry shi** 
Original Redmine Issue: 6735, http://www.fossology.org/issues/6735
Original Date: 2014/03/18
Original Assignee: Dong Ma

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/03/18 17:42:20 +0000

---

We are past the 2.5 code complete date, so moving to 2.6.

**Comment by bobgob** [comment]
Yes, these tickets could have been combined if the issue title wasn't specific to the delagent swtich.  If you want to combine them, please list both switches (-F and -U) and close the other issue.

**Comment by maximilianhuber** [comment]
maybe related to #368

**Comment by maximilianhuber** [comment]
Solved by #573
