### ISSUE TITLE
Upgrade the Jobs & Report based APIs to Version 2

### ISSUE THREAD

**Issue by dushimsam** [fossology/fossology#2724]
# Upgrade the /jobs & /report APIs to Version 2

**In accordance with our new policy documented [here](https://github.com/fossology/fossology/issues/2404#issuecomment-1671046653), we want to enhance our REST APIs to 
Version 2 migrating all `/jobs` APIs. The setup for the Version 2 is already in place.**

#### 1.  **/jobs**,  GET

- Move `limit`, `page`, `groupName` from the headers to query parameters.

<img width="747" alt="Screenshot 2024-04-28 at 13 22 17" src="https://github.com/fossology/fossology/assets/66276301/9e8a65f9-2e37-4c25-908c-df76a00d21d9">

#### 2.  **/jobs**,  POST
<img width="759" alt="Screenshot 2024-04-28 at 13 25 47" src="https://github.com/fossology/fossology/assets/66276301/a099cb87-7d5a-4879-ab30-231c7673ab0a">

<img width="779" alt="Screenshot 2024-04-28 at 13 28 17" src="https://github.com/fossology/fossology/assets/66276301/9e4b7b2f-4e36-461a-8285-ecf778291003">
<img width="769" alt="Screenshot 2024-04-28 at 13 29 47" src="https://github.com/fossology/fossology/assets/66276301/6f334d93-ce61-44be-9916-198756324c9a">

- Move `folderId`, `groupId`, `groupName` from the headers to query parameters.
- Change these fields request body to camelCase: `copyright_email_author`, `nomos_monk`, `bulk_reused`, `new_scanner`, `ojo_decider`, `reuse_upload`, `reuse_group`, `reuse_main`, `reuse_enhanced`, `reuse_report`, `reuse_copyright`.

#### 3.  **/jobs/all**,  GET

<img width="759" alt="Screenshot 2024-04-28 at 13 24 02" src="https://github.com/fossology/fossology/assets/66276301/4be6744c-7fa1-4afa-96a6-27fd6e393b78">

- Move `limit`, `page` from the headers to query parameters.

#### 4.  **/jobs/report**,  GET

<img width="761" alt="Screenshot 2024-04-28 at 13 36 28" src="https://github.com/fossology/fossology/assets/66276301/b7e44b77-537f-411b-8c83-672248d47141">

- Move `uploadId`, `reportFormat`, `groupName` from the headers to query parameters.

#### 5.  **/jobs/report/{id}**,  GET

<img width="763" alt="Screenshot 2024-04-28 at 13 39 41" src="https://github.com/fossology/fossology/assets/66276301/569fa8c0-7414-427a-aa3c-0958cc196c66">

- Move `groupName` from the headers to query parameters.

#### 6.  **/report**,  GET

<img width="763" alt="Screenshot 2024-04-28 at 13 43 39" src="https://github.com/fossology/fossology/assets/66276301/05797ca2-618c-4c38-8748-d6807549cabc">

- Move `uploadId`, `reportFormat`, `groupName` from the headers to query parameters.

#### 7.  **/report/{id}**,  GET

<img width="763" alt="Screenshot 2024-04-28 at 13 39 41" src="https://github.com/fossology/fossology/assets/66276301/569fa8c0-7414-427a-aa3c-0958cc196c66">

- Move `groupName` from the headers to query parameters.

#### 8.  **/report/import**,  POST

<img width="715" alt="Screenshot 2024-04-28 at 13 46 12" src="https://github.com/fossology/fossology/assets/66276301/71a019e4-75b6-46a4-8579-8bbee8929676">

- Move `groupName` from the headers to query parameters.

Cc: @GMishx @shaheemazmalmmd

**Comment by valens200** [comment]
Hey @dushimsam Allow me to draft a PR for this.

**Comment by dvjsharma** [comment]
I'll look into this

**Comment by shaheemazmalmmd** [comment]
Can be closed as this work is already done as part of GSOC-2024
