### ISSUE TITLE
[API ERROR] calling Upload api throws 405 NOT ALLOWED

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2727]
### Description

The upload api throws error in the latest [4.4.0], Branch: [HEAD], Commit: [#903df0]  but works previously in previous version

#### How to reproduce

Just call the api

#### Screenshots
Fossology instance [4.4.0], Branch: [HEAD], Commit: [#903df0] upload api is Not working
![image](https://github.com/fossology/fossology/assets/4498415/0f98789d-2786-4fd2-b3dd-1d051e919dd8)
but folder api is working
![image](https://github.com/fossology/fossology/assets/4498415/391bf76e-0b50-4605-afe2-428e2134a775)

But In fossology instance [4.2.1.0], Branch: [HEAD], Commit: [#9a0a6e] it works
![image](https://github.com/fossology/fossology/assets/4498415/f6c7090a-0f89-4f0e-b0a6-f04dbe62a9f2)

### Versions

* Last commit id on master: Version: [4.4.0], Branch: [HEAD], Commit: [#903df0] 2024/01/15 09:27

**Comment by dvjsharma** [comment]
Hey @dineshr93. In the first screenshot, I see the request URL is `/api/v1//uploads`, which will lead to a 405 Method Not Allowed error. Please correct this and attempt again.

**Comment by dineshr93** [comment]
Thanks @dvjsharma  my mistake.
