### ISSUE TITLE
fo_copyright_list - bad error message

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#276]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6783, http://www.fossology.org/issues/6783
Original Date: 2014/03/20
Original Assignee: larry shi

---

```
$ fo_copyright_list --user fossy --password fossy -u 71 -type
Upload ID or Uploadtree ID is not digital number

```

Note incorrect error message.  The error messages should be as specific as possible

**Comment by maximilianhuber** [comment]
closed by #564
