### ISSUE TITLE
Failed to build Fossology docker image

### ISSUE THREAD

**Issue by nhtrung289** [fossology/fossology#2765]
### Description

After Numpy update from 1.x to 2.0.0 version on Jun 16 2024, we cannot build Fossology anymore.

#### How to reproduce

Step 1: Clone Fossology source code

Step 2: Execute docker compose up command: docker-compose up

### Versions

* Last commit id on master: https://github.com/fossology/fossology/commit/4e8e8716820390f2b95176023a1e8cba9a11ac80

### Docker build  Logs
```
Successfully installed Beautifulsoup4-4.12.3 MarkupSafe-2.1.5 annotated-types-0.7.0 attrs-23.2.0 banal-1.0.6 binaryornot-0.4.4 blis-0.7.11 boolean.py-4.0 catalogue-2.0.10 certifi-2024.6.2 cffi-1.16.0 chardet-5.2.0 charset-normalizer-3.3.2 click-8.1.7 cloudpathlib-0.18.1 colorama-0.4.6 commoncode-31.2.1 confection-0.1.5 container-inspector-33.0.0 crc32c-2.4 cryptography-42.0.8 cymem-2.0.8 debian-inspector-31.1.0 dockerfile-parse-2.0.1 dparse2-0.7.0 dukpy-0.4.0 extractcode-31.0.0 extractcode-7z-16.5.210531 extractcode-libarchive-3.5.1.210531 fasteners-0.19 filelock-3.15.1 fingerprints-1.2.3 ftfy-6.2.0 gemfileparser2-0.9.3 grpcio-1.64.1 html5lib-1.1 idna-3.7 importlib-metadata-7.1.0 intbitset-3.1.0 isodate-0.6.1 jaraco.functools-4.0.1 javaproperties-0.8.1 jinja2-3.1.4 joblib-1.4.2 jsonstreams-0.6.0 langcodes-3.4.0 language-data-1.2.0 license-expression-30.3.0 lxml-5.2.2 marisa-trie-1.2.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.3.0 murmurhash-1.0.10 mutf8-1.0.6 normality-2.5.0 numpy-2.0.0 packageurl-python-0.15.1 packaging-24.1 packvers-21.5 pandas-2.2.2 parameter-expansion-patched-0.3.1 pdfminer.six-20231228 pefile-2023.2.7 pip-requirements-parser-32.0.1 pkginfo2-30.0.0 pluggy-1.5.0 plugincode-32.0.0 ply-3.11 preshed-3.0.9 progress-1.6 protobuf-5.27.1 publicsuffix2-2.20191221 pyOpenSSL-24.1.0 pyahocorasick-2.1.0 pycparser-2.22 pydantic-2.7.4 pydantic-core-2.18.4 pygmars-0.8.0 pygments-2.18.0 pymaven-patch-0.3.2 pypac-0.16.4 pyparsing-3.1.2 python-dateutil-2.9.0.post0 pytz-2024.1 pyyaml-6.0.1 rdflib-7.0.0 requests-2.32.3 requests-file-2.1.0 rich-13.7.1 safaa-0.0.1 saneyaml-0.6.0 scancode-toolkit-31.2.4 scanoss-1.5.1 scikit-learn-1.3.0 scipy-1.13.1 setuptools-70.0.0 shellingham-1.5.4 six-1.16.0 smart-open-7.0.4 soupsieve-2.5 spacy-3.7.5 spacy-legacy-3.0.12 spacy-loggers-1.0.5 spdx-tools-0.7.0a3 srsly-2.4.8 text-unidecode-1.3 thinc-8.2.4 threadpoolctl-3.5.0 tldextract-5.1.2 toml-0.10.2 tqdm-4.66.4 typecode-30.0.1 typecode-libmagic-5.39.210531 typer-0.12.3 typing-extensions-4.12.2 tzdata-2024.1 urllib3-2.2.1 urlpy-0.5 wasabi-1.1.3 wcwidth-0.2.13 weasel-0.4.1 webencodings-0.5.1 wrapt-1.16.0 xmltodict-0.13.0 zipp-3.19.2
WARNING: You are using pip version 21.2.2; however, version 24.0 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/fossy/pythondeps/spacy/__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "/home/fossy/pythondeps/spacy/errors.py", line 3, in <module>
    from .compat import Literal
  File "/home/fossy/pythondeps/spacy/compat.py", line 39, in <module>
    from thinc.api import Optimizer  # noqa: F401
  File "/home/fossy/pythondeps/thinc/api.py", line 1, in <module>
    from .backends import (
  File "/home/fossy/pythondeps/thinc/backends/__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "/home/fossy/pythondeps/thinc/backends/cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
The command '/bin/sh -c /usr/local/lib/fossology/fo-postinstall --agent --common --scheduler-only      --web-only --no-running-database --python-experimental  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
ERROR: Service 'scheduler' failed to build : Build failed
```

**Comment by nhtrung289** [comment]
To workaround we can force to use the old numpy version.

**Comment by dineshr93** [comment]
I too got the same error when building docker from latest master commit [4e8e871](https://github.com/fossology/fossology/commit/4e8e8716820390f2b95176023a1e8cba9a11ac80)

**Comment by lmarie23** [comment]
> To workaround we can force to use the old numpy version.

Hi, 
How can we do that ?

**Comment by GMishx** [comment]
Can you please describe the changes done on commit 4e8e8716820390f2b95176023a1e8cba9a11ac80 as the build for the same finished without any issue on [GitHub Action](https://github.com/fossology/fossology/actions/runs/9480690172/job/26121913064#step:7:7933)

**Comment by nhtrung289** [comment]
@GMishx , The issue didn't happen on GitHub Action because it built before Jun 16 2024 so it used numpy-1.26.4
```
  #39 17.84 Collecting numpy>=1.17.3
#39 17.85   Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
```

The issue happens after Numpy update from 1.x to 2.0.0 version on Jun 16 2024.

So if you rebuild it now, I believe that  you can re-procedure the issue.

**Comment by nhtrung289** [comment]
@lmarie23 , You can update file fossology/install/fo-install-pythondeps to remove the new numpy and install the old numpy version.

**Comment by dineshr93** [comment]
@nhtrung289  do we have to manually insert the commands to remove and install numpy in file https://github.com/fossology/fossology/blob/master/install/fo-install-pythondeps ?

**Comment by dineshr93** [comment]
> Hi @nhtrung289. I tried to reproduce the issue, but I successfully built and ran FOSSology on the latest master. A recent [docker action](https://github.com/fossology/fossology/actions/runs/9599287474/job/26472661555?pr=2766) also executed without encountering any errors. Please pull the latest master and try again.
> 
> CC @dineshr93 

Have you tried to wipe out the entire old images and rebuild the docker? I am using Ubuntu 18.04 so far.

**Comment by dvjsharma** [comment]
Yes @dineshr93, I used a fresh Ubuntu 22.04 instance for testing with no old images. Though I did observe failed docker tests yesterday, which are passing today. I might be wrong but it's possible that there have been changes in the dependencies code.

**Comment by nhtrung289** [comment]
> @nhtrung289 do we have to manually insert the commands to remove and install numpy in file https://github.com/fossology/fossology/blob/master/install/fo-install-pythondeps ?
> 
> `The issue didn't happen on GitHub Action because it built before Jun 16 2024 so it used numpy-1.26.4`
> 
> Also are you able to build using freshly pulled image by deleting the old images in the machine ?

Yes. I manual insert commands to remove and install old numpy.
Yes.

**Comment by nhtrung289** [comment]
> Yes @dineshr93, I used a fresh Ubuntu 22.04 instance for testing with no old images. Though I did observe failed docker tests yesterday, which are passing today. I might be wrong but it's possible that there have been changes in the dependencies code.

Can you show to the numpy version in the log build?
For instance:
`  #39 17.84 Collecting numpy>=1.17.3
#39 17.85   Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)`

**Comment by dvjsharma** [comment]
> > Yes @dineshr93, I used a fresh Ubuntu 22.04 instance for testing with no old images. Though I did observe failed docker tests yesterday, which are passing today. I might be wrong but it's possible that there have been changes in the dependencies code.
> 
> Can you show to the numpy version in the log build? For instance: ` #39 17.84 Collecting numpy>=1.17.3 #39 17.85 Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)`
```
#38 20.05 Collecting numpy>=1.17.3
#38 20.07   Downloading numpy-2.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
```

**Comment by lmarie23** [comment]
I am based on 4.4.0 release. Can someone provide a patch (4.4.1) to solve this issue ? 
I do not manage to fix numpy version.

**Comment by GMishx** [comment]
Dear all, we just merged few PRs to `main` branch and the Docker image build in GitHub Action is working without any issues. Please check https://github.com/fossology/fossology/actions/runs/9663071133/job/26654372585

You can pull the latest image from [docker.io/fossology/fossology:latest](https://hub.docker.com/r/fossology/fossology/tags)

**Comment by dineshr93** [comment]
Hi All, I tried to rebuild and was able to build successfully build the docker image from the latest main branch as well. Thanks @GMishx

**Comment by lmarie23** [comment]
Release 4.4.0 also build

**Comment by GMishx** [comment]
Thanks for confirmation. Closing the PR for now. Please reopen if needed.
