### ISSUE TITLE
Add public upload flag to user profiles

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#279]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6807, http://www.fossology.org/issues/6807
Original Date: 2014/03/21

---

Currently the user profiles (account settings) allow one to specify their default agents.  There also needs to be an option to set the public flag.

**Comment by mcjaeger** [comment]
nice idea, have a preset for these:
![image](https://user-images.githubusercontent.com/3418977/40611717-cea28612-6277-11e8-9c99-f2d348c013c4.png)

**Comment by bighnesh0404** [comment]
I would like to work on this issue

**Comment by NicolasToussaint** [comment]
A system-wide preference would make sense too.
I actually had to patch the upload pages to force the private option by default for all uploads

**Comment by GMishx** [comment]
Hello @bighnesh0404, mind if I assign it to you?

**Comment by GMishx** [comment]
> A system-wide preference would make sense too.
> I actually had to patch the upload pages to force the private option by default for all uploads

So there will be a system-wide preference which can be changed by admin and this will be the default value for each user until they change it?

**Comment by NicolasToussaint** [comment]
> So there will be a system-wide preference which can be changed by admin and this will be the default value for each user until they change it?

Indeed, that sounds good to me:
- the system setting would propose 3 existing possibilities
    - _only for active group_
    - _all groups_
    - _public_
- the user setting would have the 3 above, plus _use system default_ 

So the default would be used for already existing and newly created users
