### ISSUE TITLE
Readmeoss report doesnt contain copyright and licenses for larger package

### ISSUE THREAD

**Issue by dineshr93** [fossology/fossology#2797]
### Description

Readmeoss report doesnt contain copyright and licenses for larger package
[ReadMe_OSS_OSRBSD-821-sqlite-version-3.41.2.zip_1721901007.txt](https://github.com/user-attachments/files/16374208/ReadMe_OSS_OSRBSD-821-sqlite-version-3.41.2.zip_1721901007.txt)

we tried restarting the server and generated the report. its still produces empty report as attached above

package: https://github.com/sqlite/sqlite/archive/refs/tags/version-3.41.2.zip
#### How to reproduce

upload the packge 
perform the clearance
genreate the readme oss report

#### Screenshots

![image](https://github.com/user-attachments/assets/2d1d0057-388c-4b28-9199-4c951b299f79)

### Versions

* Last commit id on master: Version: [4.4.0.63], Branch: [master], Commit: [#4e8e87] 2024/06/12 10:07 +00:00 built @ 2024/06/24 17:25 +00:00
* Operating System (lsb_release -a): Ubuntu 20.04

#### Apache logs

```
10.10.186.138 - - [25/Jul/2024:10:29:19 +0000] "POST /repo/?mod=jobstatus HTTP/1.1" 200 314 "http://fossology.com:8081/repo/?mod=ui_readmeoss&upload=4792&show=quick&item=19680466" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
10.10.186.138 - - [25/Jul/2024:10:29:19 +0000] "POST /repo/?mod=ajaxShowJobs&do=showjb HTTP/1.1" 200 10685 "http://fossology.com:8081/repo/?mod=ui_readmeoss&upload=4792&show=quick&item=19680466" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
10.10.185.19 - - [25/Jul/2024:10:29:22 +0000] "POST /repo/?mod=jobstatus HTTP/1.1" 200 314 "http://fossology.com:8081/repo/?mod=showjobs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
10.10.185.19 - - [25/Jul/2024:10:29:23 +0000] "POST /repo/?mod=ajaxShowJobs&do=showjb HTTP/1.1" 200 10685 "http://fossology.com:8081/repo/?mod=showjobs" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
127.0.0.1 - - [25/Jul/2024:10:29:23 +0000] "GET /repo/api/v1/health HTTP/1.1" 200 1014 "-" "curl/7.74.0"
127.0.0.1 - - [25/Jul/2024:10:29:28 +0000] "GET /repo/api/v1/health HTTP/1.1" 200 1014 "-" "curl/7.74.0"
10.10.186.138 - - [25/Jul/2024:10:29:29 +0000] "POST /repo/?mod=jobstatus HTTP/1.1" 200 314 "http://fossology.com:8081/repo/?mod=ui_readmeoss&upload=4792&show=quick&item=19680466" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
```
#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)
logs are empty
![image](https://github.com/user-attachments/assets/31b808c8-5f03-44c4-9d18-446e7db668ac)

**Comment by dineshr93** [comment]
Hi @shaheemazmalmmd  I did  `docker logs fossology_web_1` and have produced the output in the ablve apache logs section. I still see the rest call it makes.  

and below is output for `docker logs fossology_scheduler_1`

```
2024-07-31 09:53:26 scheduler [1] :: NOTE: Unable to send email. SMTP host or port not found in the configuration.
2024-07-31 09:53:26 scheduler [1] :: Please check Configuration Variables.
2024-07-31 09:55:16 scheduler [1] :: WARNING ../src/scheduler/agent/agent.c.986: JOB[92451].unifiedreport[511370.localhost]: agent closed unexpectedly, agent status was AGENT_FAILED
```

**Comment by dineshr93** [comment]
Hi @shaheemazmalmmd  I played around the groups a bit. changing the group it produced just the copyright atleast. but not the license. 
My question is should one be in the same group as when uploaded for generating the readme_oss file ?

[ReadMe_OSS_OSRBSD-821-sqlite-version-3.41.2.zip_1723405588.txt](https://github.com/user-attachments/files/16575955/ReadMe_OSS_OSRBSD-821-sqlite-version-3.41.2.zip_1723405588.txt)

**Comment by shaheemazmalmmd** [comment]
@dineshr93 : upload, clearing and report generation should be done from the same group to get desired output. groups restrict users to access clearings/uploads of other groups. 

one can also use admin > upload permissions page to give the owner rights to different groups if needed.
