### ISSUE TITLE
Export all the entries of the license list from the Fossology UI or Command line.

### ISSUE THREAD

**Issue by sanket-kalpande** [fossology/fossology#2798]
### Description

Export all the entries of the license list from the Fossology UI or Command line. 

#### How to reproduce

For a bug: In the fossology UI the export list entries can be viewd at max available total 2200, But we want to export all the entries. is there any option to export all from UI or from any other way. 

Kindly suggest how we can achieve the above scenario. below is the screenshot provided for the same.

#### Screenshots

<img width="779" alt="image" src="https://github.com/user-attachments/assets/74f168bc-f452-4162-85c3-ba80b1d9fc6c">

### Versions

Version: [4.3.0.2]

**Comment by shaheemazmalmmd** [comment]
@sanket-kalpande if you want to change the number you can do it via Admin > Customize > Maximum licenses to List , If you want fill list for individual agents you can go to cli folder and execute ./fo_nomos_license_list it will list different options it will perform, and you can choose from that.

**Comment by sanket-kalpande** [comment]
> @sanket-kalpande if you want to change the number you can do it via Admin > Customize > Maximum licenses to List , If you want fill list for individual agents you can go to cli folder and execute ./fo_nomos_license_list it will list different options it will perform, and you can choose from that.

Thank you so much @shaheemazmalmmd  for your help. it works for me.
