### ISSUE TITLE
PHP Fatal error:  Call to a member function CheckStatus() on a non-object

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#280]
---

Author Name: **Martin Hamant** 
Original Redmine Issue: 6813, http://www.fossology.org/issues/6813
Original Date: 2014/03/24
Original Assignee: Bob Gobeille

---

Hi !

I got the following error when accessing for example : http://fossology.ow2.org/?mod=view&upload=30&item=236864

```
PHP Fatal error:  Call to a member function CheckStatus() on a non-object in /usr/share/fossology/www/ui/ui-view.php on line 747

```

**Comment by mcjaeger** [comment]
propose to close it because it seems not really easy to catch up here:
1. version there is FOSSology version 2.5.0 (code revision 559eac)
2. the error does not appear when I am calling it (also not on ff console)

**Comment by bobgob** [comment]
closing per @mcjaeger
