### ISSUE TITLE
Need License Admin Documentation

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#282]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6837, http://www.fossology.org/issues/6837
Original Date: 2014/03/27
Original Assignee: Bob Gobeille

---

On the FOSSology admin documentation page, 

http://www.fossology.org/projects/fossology/wiki/FOAdmin

there is a link to License Admin, but it has never been written.

We need to explain the License Admin to our users.

**Comment by mcjaeger** [comment]
seems to be there. I am taking the opportunity to close it:

http://www.fossology.org/projects/fossology/wiki/LicenseAdmin
