### ISSUE TITLE
Database error : Could not receive data from client: Connection reset by peer

### ISSUE THREAD

**Issue by rahulkumartandf** [fossology/fossology#2835]
### Description

Hi , we are getting exceptions at fossology apps due to database error : Could not receive data from client: Connection reset by peer. 

in the PostgreSQL log means that the client end of the connection has vanished without properly closing the database session.

can someone please suggest.

#### How to reproduce

For a bug: Describe the bug and list the steps you used when the issue occurred.

For an enhancement or new feature: Describe your needs/expected results.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### FOSSology logs

Logs generated under /var/log/fossology/fossology.log

#### Apache logs

Logs generated under /var/log/apache2/error.log

#### Job logs

Logs generated under Geeky Scan Details (Job history => click on agent's job id)

**Comment by shaheemazmalmmd** [comment]
@rahulkumartandf Usually this type of issue will happen because if network issues or running Max Connections or because of the server load.

**Comment by shaheemazmalmmd** [comment]
Closing as there is no response from user since last 3 months.
