### ISSUE TITLE
Creation of rule form moves to page 2 if exceeds 1-

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#2841]
### Description

if the rule count exceeds, the creation form moves to new page which is, confusing.

known issue from : https://github.com/fossology/fossology/pull/2782

#### How to reproduce

* Create over 10 rules for compatibility agent.

**Comment by Vaibhavsahu2810** [comment]
@shaheemazmalmmd By modifying the pagination settings, I’ve ensured that the creation form remains on the same page even when more rules are added, providing a smoother and less confusing user experience. Please let me know if further adjustments are needed.
Thank you!
