### ISSUE TITLE
add more tests for package install testing in CI

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#285]
---

Author Name: **larry shi** 
Original Redmine Issue: 6861, http://www.fossology.org/issues/6861
Original Date: 2014/04/03
Original Assignee: larry shi

---

such as: confirm if install successfully/complete, etc

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/03 15:46:49 +0000

---

"Successful" and "complete" are two very different things.  Could you add more specifics?  For example, you created this defect because the license_admin table wasn't being populated in a new install.  So you should mention that.  Are there any other tests you have in mind or is this meant to be open ended to look at all the package install testing?

**Comment by mcjaeger** [comment]
is this maybe close-able already?

**Comment by bobgob** [comment]
Package and install testing need to be moved off the HP infrastructure.  So this is part of a much larger problem.  I'm going to close this because it just sounds like basic install testing.
