### ISSUE TITLE
New License Added to licenseRef.json Not Detected During File Scanning

### ISSUE THREAD

**Issue by YovM** [fossology/fossology#2861]
Description
I added new license information to licenseRef.json following the existing format and restarted the Fossology repository. In the Admin section under License Admin, the newly added license is visible and selectable. However, when scanning code files that include this new license information, the scanner fails to detect the license.

How to reproduce
Open licenseRef.json and add a new license entry following the existing format.
Restart the Fossology repository to apply the changes.
Navigate to Admin > License Admin and verify that the new license appears in the selection list.
Perform a scan on code files that contain the new license information.
Observe that the scanner does not detect the newly added license.

**Comment by ritankarsaha** [comment]
@YovM I guess  double-checking the newly added license entry and ensuring  the format matches the existing licenses.
Also Checking  the regex or match field and Ensuring it correctly captures the license text in scanned files can be a possible solution to this problem.
