### ISSUE TITLE
Reduce UI top

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#287]
---

Author Name: **Silvano Cirujano Cuesta** 
Original Redmine Issue: 6873, http://www.fossology.org/issues/6873
Original Date: 2014/04/07

---

A more compact presentation in the top of the UI (see attached screenshot) would be desirable.

!UI_top_page.png!

Changing the logo doesn't change anything.

The space between the menu and the view name ("Welcome to FOSSology" in the screenshot) and between the view name and the separator (line) should be reduced.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/04/08 15:50:32 +0000

---

I tried this on three different browsers (firefox, chrome, safari) and the header all looks the same (see attached).  I tried changing my browser width.  I could never get it to change and look like your screenshot.  What browser are you using?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Silvano Cirujano Cuesta** 
Original Date: 2014/04/09 07:23:05 +0000

---

Sorry, you are right. My screenshot is showing even more empty space because of a feature we implemented. Your screenshot shows the right layout, I will update the shown picture to show your screenshot.

Anyway, an even more compact view than that shown in your screenshot would be desirable for us.

**Comment by pguttmann** [comment]
Attachments - 1) http://www.fossology.org/attachments/4437/UI_top_page.png
2) http://www.fossology.org/attachments/4443/header.png

**Comment by mcjaeger** [comment]
I think the dual menu sections could be also reworked when touching it.

**Comment by mcjaeger** [comment]
dupßlicate of https://github.com/fossology/fossology/issues/286 closing ...
