### ISSUE TITLE
agent_desc not being initialized in install

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#290]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6891, http://www.fossology.org/issues/6891
Original Date: 2014/04/09
Original Assignee: Dong Ma

---

I just noticed that the agent.agent_desc field is not being initialized during an install.  I traced this error all the way back to the 2.0.0 release.

**Comment by mcjaeger** [comment]
I think it was corrected at some time, but requires retest.

**Comment by mcjaeger** [comment]
seems to be still an issue, however some agents do seem to work. see screenshot in next commont :D

**Comment by maximilianhuber** [comment]
![tmp](https://cloud.githubusercontent.com/assets/1187050/11275456/f0942458-8edd-11e5-819f-24a9a08c49ba.png)
