### ISSUE TITLE
Delagent not deleting log files

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#291]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6897, http://www.fossology.org/issues/6897
Original Date: 2014/04/14
Original Assignee: Dong Ma

---

By code inspection, I cannot see where delagent is deleting jobqueue log files (jq_log).

**Comment by mcjaeger** [comment]
could we have a clarification on this? point is that there is the question that 

a) it should be deleted but the place in the code is not found

or

b) shall a delagent delete log file entries as well - just asking if that makes sense or if it more useful to keep track of what was uploaded once to the server and processed?

**Comment by GMishx** [comment]
Can this issue be closed by PR #1677 ?

**Comment by shaheemazmalmmd** [comment]
Resolved by PR https://github.com/fossology/fossology/pull/1677
