### ISSUE TITLE
Continuous Integration Source and Package install testing failure

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#293]
---

Author Name: **Dong Ma** 
Original Redmine Issue: 6909, http://www.fossology.org/issues/6909
Original Date: 2014/04/15
Original Assignee: Dong Ma

---

List the Source and Package install testing failure:
*1.* Err http://ftp.us.debian.org wheezy Release.gpg
  Could not connect to web-proxy.fc.hp.com:8088 (16.85.175.150). - connect (111: Connection refused)
Err http://ftp.us.debian.org wheezy-updates Release.gpg
  Unable to connect to web-proxy.fc.hp.com:8088:

*2.* Package(s) data still to download: 144 M
http://mirror.centos.org/centos/6/updates/x86_64/Packages/pixman-0.26.2-5.1.el6_5.x86_64.rpm: [Errno 12] Timeout on http://mirror.centos.org/centos/6/updates/x86_64/Packages/pixman-0.26.2-5.1.el6_5.x86_64.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
Error Downloading Packages:
  pixman-0.26.2-5.1.el6_5.x86_64: failure: Packages/pixman-0.26.2-5.1.el6_5.x86_64.rpm from updates: [Errno 256] No more mirrors to try.

*3.* Cloning into 'fossology'...
remote: error: unable to open object pack directory: ./objects/pack: Transport endpoint is not connected        
remote: fatal: unable to read 6591219548e51b8f796c36defea8a80bc77f1c9b        
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed

*4.* Cloning into 'fossology'...
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: index-pack failed

*5.* There was 1 error:
1) test_cp2foss::test_upload_from_server
pg_query(): Query failed: ERROR:  relation "ununpack_ars" does not exist
LINE 1: SELECT count(*) FROM ununpack_ars where upload_fk = 1 and ar...
/srv/fossology/test4packageinstall/test_common.php:109
/srv/fossology/test4packageinstall/test_cp2foss.php:137
FAILURES!

*6.*There was 1 error:
1) test_cp2foss::test_upload_from_server
pg_query(): Query failed: ERROR:  relation "copyright_ars" does not exist
LINE 1: SELECT count(*) FROM copyright_ars where upload_fk = 3 and a...
/srv/fossology/test4packageinstall/test_common.php:109
/srv/fossology/test4packageinstall/test_cp2foss.php:205
FAILURES!

*7.*Package(s) data still to download: 144 M
http://mirror.centos.org/centos/6/os/i386/Packages/perl-CGI-3.51-136.el6.i686.rpm: [Errno 12] Timeout on http://mirror.centos.org/centos/6/os/i386/Packages/perl-CGI-3.51-136.el6.i686.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
http://mirror.centos.org/centos/6/os/i386/Packages/perl-Git-1.7.1-3.el6_4.1.noarch.rpm: [Errno 12] Timeout on http://mirror.centos.org/centos/6/os/i386/Packages/perl-Git-1.7.1-3.el6_4.1.noarch.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
http://mirror.centos.org/centos/6/os/i386/Packages/perl-Pod-Simple-3.13-136.el6.i686.rpm: [Errno 12] Timeout on http://mirror.centos.org/centos/6/os/i386/Packages/perl-Pod-Simple-3.13-136.el6.i686.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
http://mirror.centos.org/centos/6/os/i386/Packages/perl-libs-5.10.1-136.el6.i686.rpm: [Errno 12] Timeout on http://mirror.centos.org/centos/6/os/i386/Packages/perl-libs-5.10.1-136.el6.i686.rpm: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 30 seconds')
Trying other mirror.
Error Downloading Packages:
  1:perl-Pod-Simple-3.13-136.el6.i686: failure: Packages/perl-Pod-Simple-3.13-136.el6.i686.rpm from base: [Errno 256] No more mirrors to try.
  perl-CGI-3.51-136.el6.i686: failure: Packages/perl-CGI-3.51-136.el6.i686.rpm from base: [Errno 256] No more mirrors to try.
  perl-Git-1.7.1-3.el6_4.1.noarch: failure: Packages/perl-Git-1.7.1-3.el6_4.1.noarch.rpm from base: [Errno 256] No more mirrors to try.
  4:perl-libs-5.10.1-136.el6.i686: failure: Packages/perl-libs-5.10.1-136.el6.i686.rpm from base: [Errno 256] No more mirrors to try.

*8.*The following packages have unmet dependencies:
 cron : Depends: adduser but it is not going to be installed
 fossology:i386 : Depends: fossology-web:i386 but it is not going to be installed
                  Depends: fossology-scheduler:i386 but it is not going to be installed
                  Depends: fossology-ununpack:i386 but it is not going to be installed
                  Depends: fossology-copyright:i386 but it is not going to be installed
                  Depends: fossology-buckets:i386 but it is not going to be installed
                  Depends: fossology-mimetype:i386 but it is not going to be installed
                  Depends: fossology-delagent:i386 but it is not going to be installed
                  Depends: fossology-wgetagent:i386 but it is not going to be installed
 upstart : Depends: initscripts
           Depends: mountall
           Depends: ifupdown (>= 0.6.10ubuntu5)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
FATAL! Could not install fossology on Ubuntu version 13.10

**Comment by mcjaeger** [comment]
still open?

**Comment by bobgob** [comment]
Most of this looks like proxy failures and not a FOSSology problem.  Closing.
