### ISSUE TITLE
upgrade redmine

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#294]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 6915, http://www.fossology.org/issues/6915
Original Date: 2014/04/15
Original Assignee: Bob Gobeille

---

we are currently running redmine 1.2.1.  It's three years old and many rev's back from the current 2.5.1.  We should probably upgrade.

**Comment by mcjaeger** [comment]
redmine is archived, update not needed anymore.
