### ISSUE TITLE
Scheduler not stable when more than one schedulers running at the same time

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#300]
---

Author Name: **Dong Ma** 
Original Redmine Issue: 6981, http://www.fossology.org/issues/6981
Original Date: 2014/05/07
Original Assignee: larry shi

---

The root cause of bug#5601 is scheduler not stable when more than one schedulers running at the same time, create a new bug related scheduler issue.

**Comment by mcjaeger** [comment]
could someone please make more description what the scenario for this - I assume it is not about starting two scheduler executables on the same user space.

**Comment by pguttmann** [comment]
G'day Michael,
   I'd suggest closing this - It would appear that the underlying Redmine issue 5601 was closed before we migrated issues to github.
   Presumably it *should* have been between current issues 232(5511) and 233(5607) ;)

Paul...

reply@reply.github.com At: Nov 19 2015 10:30:49" data-digest="From: reply@reply.github.com At: Nov 19 2015 10:30:49" style="">

**Comment by mcjaeger** [comment]
following Paul's suggestion (took a long time, sorry)
