### ISSUE TITLE
software license agreement data

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#304]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7011, http://www.fossology.org/issues/7011
Original Date: 2014/05/12

---

We need to supply data for Software License Agreements.  For example, see http://docs.hpcloud.com/cloudos/os-3rd-party-license-agreements

This includes a list of licenses, license text, and all packages under those licenses.  Packages may be debian or rpm packages OR archives (e.g. tar files).

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/05/15 07:34:20 +0000

---

Would you like adding one functionality to fossology or one page to provide software license agreement data?

I prefer add one functionality to fossology. 
please refer to attached file list_software_license.png.

my solution is:
1) using the current license admin page, just add another item to list related packages
2) take GPL-2.0 as an example, when click list icon will list all the pacakges which are license under GPL-2.0
3) package list for one license is editable(add/modify), even some packages  are not existing in your server, for me, upload those package will be best.

possible problems:
1) performance, in one big repo/db server(e.g. OSPO product server), will take a long time to collect packages when click on list icon. have to consider it, find a better solution.
2) which packages should will be listed? one package is different with an individual file
a) for one file, you can say this file are licensed under multiple licenses, all the licenses are equal.
b) for one package, usually nomos report lots of licenses for this package, usually lawyers just pay attention to the licenses which are found most times.
take fossology_2.5.0-1.tar as an example, part licenses, please refer part_fossology_2.5.0_license.png, 
will see there are lots of license nomos report, I do not think you want more than 10 licenses in license admin page list fossology_2.5.0-1.tar.

so we have to make a decision, just list how much popular license, possible default as top 3 popular licenses, and is customizable, what do you think?


If you want to create a page to list licenses/licenses text/packages, you may want to use repo/DB  from one big server(e.g. OSPO product server).

-Larry

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/05/15 07:41:31 +0000

---

If you want to create a wiki page to list licenses/licenses text/packages, you may want to use repo/DB  from one big server(e.g. OSPO product server).
Right now: fossology DB has licenses data.
 what we should do is collecting which packages are licensed under which licenses, then store these information into DB, then show them on a wiki page.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/05/15 18:32:11 +0000

---

I forwarding this discussion to fossology-devel

**Comment by pguttmann** [comment]
Attachments - 1) http://www.fossology.org/attachments/4401/list_software_license.png
2) http://www.fossology.org/attachments/4407/part_fossology_2.5.0_license.png

**Comment by mcjaeger** [comment]
not really asked for in the past. please reopen if demand persists
