### ISSUE TITLE
auto archive or delete feature

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#305]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7017, http://www.fossology.org/issues/7017
Original Date: 2014/05/13

---

Add a feature that allows an upload to be auto archived (reduced to it's gold file in the repo) or auto deleted.

1) Should the expiration date be based on the date the upload was last accessed (browsed), or based on the upload date?

2) Should we allow the fossology admin to set a default expiration time (e.g. 1 yr, 1 month, 234 days, …)?  The advantage of a default expiration date is that the field on the upload form would then come populated.  This may be good because if it comes up blank, the user may not bother filling it in.  However, they can easily override it if they wish.

3) Should the expiration be expressed as a date (1/1/2014) or an interval (365 days)? 
- probably both

**Comment by GMishx** [comment]
Fix with a different approach in https://github.com/fossology/fossology/pull/2093 using maintenance agent to remove files older than a given date.

**Comment by shaheemazmalmmd** [comment]
Already satisfies the issue with different approach. Please  reopen if something is missing.
