### ISSUE TITLE
Update and consolidate wiki pages for Buckets

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#310]
---

Author Name: **Paul Guttmann** 
Original Redmine Issue: 7119, http://www.fossology.org/issues/7119
Original Date: 2014/06/17
Original Assignee: Paul Guttmann

---

There are two separate wiki pages for "Buckets":
Jan 3rd 2012 - Jaime Phillips : http://www.fossology.org/projects/fossology/wiki/Buckets/history
Jan 9th 2012 - Dan Stangel : http://www.fossology.org/projects/fossology/wiki/Creating_and_Using_Bucketpools/history

Update and consolidate the Buckets documentation into the "Creating and Using Bucketbools" wiki page

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2014/06/17 16:33:14 +0000

---

After a little further investigation I discovered that the Wiki page -
http://www.fossology.org/projects/fossology/wiki/Buckets
is actually linked to from the Admin -> Buckets -> Duplicate Bucketpool page :P
That page also appears to require some editing/updates since it appears to refer to no longer present Admin -> Buckets options - see steps 8 and 9 on that Duplicate Bucketpool page.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2014/06/17 16:39:19 +0000

---

Item 3 of the "help text" in Admin -> Buckets -> Duplicate Bucketpool needs a little "tweaking" also ;)
3. Duplicate any bucket scripts that you defined in /var/lib/fossology.
 The actual scripts seem to need to reside in /var/lib/fossology/bucketpools/(bucketpool_pk)/ where (bucketpool_pk) is the value stored in the bucketpool table.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/06/17 16:42:34 +0000

---

I wouldn't worry about Admin > Buckets > Duplicate Bucketpool.  It is being replaced in 2.6 with an entire bucket UI.

**Comment by mcjaeger** [comment]
keeping it for 3.0.0 because of the intended work on buckets, which maybe goes inline with the documentation part

**Comment by bobgob** [comment]
Given my change in status along with the UI changes, I've not implemented the new bucket UI.  Sorry.  Somebody should really pick this up because buckets are a very powerful feature.

**Comment by mcjaeger** [comment]
connected with #306

**Comment by mcjaeger** [comment]
let's close this because it passed 2 yrs w/o update
