### ISSUE TITLE
foss discovery

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#311]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7125, http://www.fossology.org/issues/7125
Original Date: 2014/06/18

---

We already have the antelink solution for discovering foss projects, but that requires an antepedia license.  So let's implement a manual solution that integrates with the SPDX module.  For example, let the user pick directories that contain projects.  Like a distro src/ directory which typically contains many projects.  The software could even learn common directories to search in.

This needs quite a bit more research to determine if this is a viable approach.

**Comment by mcjaeger** [comment]
despite the issues is about three years old and does not have a conversation. I have trouble understanding what the use case is actually. @yaobinshi, @bobgob in case you can shed some light here, please reopen the ticket in case
