### ISSUE TITLE
Agent-Race condition

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#312]
---

Author Name: **Johannes Najjar** 
Original Redmine Issue: 7143, http://www.fossology.org/issues/7143
Original Date: 2014/06/26
Original Assignee: Johannes Najjar

---

If the scheduler is not running, an agent can be scheduled multiple times on the same file.
This yields that, e.g., nomos can run twice on the same files and duplicate each database entry.

To reproduce:
1. Upload file (from UI)
2. sudo service fossology stop   (on the host)
3. UI: Jobs -> Schedule agents ; then select an agent, Analize!
4. Repeat 3.
5. sudo service fossology restart   (on the host)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/06/26 14:53:26 +0000

---

This is unfortunate.  There is a test in each agent against its ars table to prevent duplicate submissions.  For example:

```
/* Is this a duplicate request (same upload_pk, sameagent_fk)?
             If so, there is no point in repeating it.
       */
      snprintf(sqlbuf, sizeof(sqlbuf),
          "select ars_pk from nomos_ars,agent \
                  where agent_pk=agent_fk and ars_success=true \
                    and upload_fk='%d' and agent_fk='%d'",
                    upload_pk, gl.agentPk);
      result = PQexec(gl.pgConn, sqlbuf);
      if (fo_checkPQresult(gl.pgConn, result, sqlbuf, __FILE__, __LINE__)) Bail(-__LINE__);
      if (PQntuples(result) != 0)
      {
        LOG_NOTICE("Ignoring requested nomos analysis of upload %d - Results are already in database.",
            upload_pk);
        PQclear(result);
        continue;
      }

```
However, I think the better solution would be to create a unique index.  For example, for nomos the unique index on nomos_ars table would be "agent_fk, upload_fk, ars_success"

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Johannes Najjar** 
Original Date: 2014/06/30 16:25:32 +0000

---

It now also prevents duplicated jobs on the same file, when hitting [F5] to refresh page and thus resending the job schedule. This was a problem if the scheduler was not running.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/08/04 07:48:03 +0000

---

0) this issue not be fixed
1) I can not re0analyze one job(e.g. nomos) 2 times even the scheduler stop
2) certainly, If i analyze nomos, then analyze bucket, there will be 2 nomos.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/08/05 10:35:09 +0000

---

> 2) certainly, If i analyze nomos, then analyze bucket, there will be 2 nomos.
1) upload one package - pkg1(do not select any agents) from file, the scheduler is running
2) stop the scheduler
3) [Jobs]-->[Schedule agents] to Analyze 'nomos' on pkg1
4) [Jobs]-->[Schedule agents] to Analyze 'bucket' on pkg1
5) go to Show Jobs page, will see there are 2 nomos jobs

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/08/05 10:37:21 +0000

---

hi Johannes, 

you checked in a fix for this issue, right? could you provide commit number?  thanks

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Johannes Najjar** 
Original Date: 2014/08/05 17:03:01 +0000

---

Here are the relevant commits from the log

Merge into master
commit f98cd431db4ce94c3d4b1bd7b1755b002d8822b6
Merge: 8cba1f1 fe79fb3
Author: Johannes Najjar <johannes.najjar@tngtech.com>
Date:   Mon Jun 30 18:23:01 2014 +0200

    Merge branch 'master' of ssh://git.code.sf.net/p/fossology/fossology into upstream_write/master


2nd fix
commit 8cba1f101bc197160bdfb5b174a543d323d49748
Author: Johannes Najjar <johannes.najjar@tngtech.com>
Date:   Mon Jun 30 09:27:09 2014 +0200

    #7143: Added function discription, also prevented rescheduling during stopped service by refreshing the page

1st fix
commit 72ccb011ed6f407bbebc58e6e15227f6bb43bbc3
Author: Johannes Najjar <johannes.najjar@tngtech.com>
Date:   Thu Jun 26 17:29:19 2014 +0200

    #7143: Fixed race condition


The problem seems to be that the fix in this commits does nothing to address jobs which are scheduled as dependencies of other jobs.
At the top of my head I would think that a fix would have to deal with those on a more fundamental level and not on the submit a job page. 
It would have to be in the function that actually creates the database entry for a scheduled job. 
But I have not thought about this in detail.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/08/12 09:44:46 +0000

---

do you think we should file another issue or keep this issue open(then we can fix it in 2.7.0)?

**Comment by mcjaeger** [comment]
retest appears necessary, seems to be fixed.

**Comment by max-wittig** [comment]
seems to be fixed. Can't reproduce it. Schedule agents are automatically removed from `additional analysis`
