### ISSUE TITLE
get  nomos/bucket comparison report from cli

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#315]
---

Author Name: **larry shi** 
Original Redmine Issue: 7215, http://www.fossology.org/issues/7215
Original Date: 2014/07/10
Original Assignee: larry shi

---

None

**Comment by mcjaeger** [comment]
I am sorry, this is not really much information to follow what is meant here. Anyone who could shed more light on this?

**Comment by bobgob** [comment]
Insufficient information.  Closing.
