### ISSUE TITLE
scaling performance issues

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#318]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7275, http://www.fossology.org/issues/7275
Original Date: 2014/07/15
Original Assignee: larry shi

---

On our internal production server we have almost 340 million files loaded into a fossology server and performance is getting sluggish.  We need to profile the code, see where we are running into problems and come up with some solutions.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/10/14 09:14:09 +0000

---

it is critical, if we can fix it in 2.6.2, that will be great.

**Comment by mcjaeger** [comment]
is it fixed?

**Comment by bobgob** [comment]
I wouldn't call it fixed.  The system can still be slow.  But this is a general problem whose solution (other than the report cache) could be a major update.  I'm going to close this since we don't have a specific user complaint, but I suspect it will come up again at some time.
