### ISSUE TITLE
Fossology without "make install"?

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#320]
---

Author Name: **larry shi** 
Original Redmine Issue: 7293, http://www.fossology.org/issues/7293
Original Date: 2014/07/16

---

Hi Gerv,

We don’t really handle this very well, but here is what I do.  In /usr/local/etc/fossology/mods-enabled, I have all the modules point to my development tree.  That way I can change a UI file and immediately hit reload without a make install.  Other times I have multiple git repos.  To handle this I have multiple versions of mods-enabled and I just rename or link the one I want to mods-enabled.  There are a couple of pain points.  1) switching mods-enabled works best if you are running the same scheduler since /etc/init.d/fossology has the scheduler path hardcoded.  2) if I change something in src/lib/php I have to do a make install on that one directory. 

Yours isn’t an unreasonable request, but with the work around above it hasn’t been a big enough pain for anyone to work on.

Thanks,
Bob Gobeille

On Jul 9, 2014, at 4:20 AM, Gervase Markham gerv@mozilla.org wrote:

> I apologise if this is obvious, but I can't work out how to do it.
> 
> Basically, I'd like to run fossology without 'make install' - that is 
> to say, I'd like to download the codebase, compile it as necessary, 
> point my webserver at it and have it run, without it needing to be 
> installed into special locations on my computer.
> 
> This is for a couple of reasons. Firstly, because I'd like to be 
> running multiple copies at once, for development purposes - perhaps on 
> different ports or at different URLs. Also secondly, because I'd like 
> to edit a web UI file within my checkout, hit "Reload" in my browser, 
> and see the change. At the moment, it seems like I have to edit the 
> file, run "sudo make install" and then hit Reload, which is a pain.
> 
> This doesn't sound like an unreasonable request - most apps with a web 
> UI can be made to work this way, i.e. run directly from a code checkout.
> 
> The Developer Documentation:
> http://www.fossology.org/projects/fossology/wiki/Developer_Documentati
> on doesn't seem to have anything about setting up a development 
> environment.
> 
> Can someone enlighten me?
> 
> Thanks,
> 
> Gerv
> ---

**Comment by GMishx** [comment]
You can install individual components either by going to their directory and calling `make install` or call `make install-<component-name>` from the root directory itself.

E.g.: If I changed something in `nomos`, I can navigate to `src/nomos` and call `make install` or call `make install-nomos` from root itself.

Supported tags:
```
install                install-copyright      install-delagent       install-mimetype       install_offline        install-reuser         install-unifiedreport  
install-adj2nest       install-debug          install-install        install-monk           install-pkgagent       install-scheduler      install-ununpack       
install-buckets        install-decider        install-lib            install-ninka          install-readmeoss      install-spdx2          install-wget_agent     
install-cli            install-deciderjob     install-maintagent     install-nomos          install-reportImport   install-src            install-www
```
