### ISSUE TITLE
nomos - false positive in PNG files, for example

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#322]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7311, http://www.fossology.org/issues/7311
Original Date: 2014/07/17
Original Assignee: larry shi

---

attached image file says LGPL in 2.5.0.  It should be No License Found.

There is "lgpl" in the text representation of this file but there is no context around it to suggest that it is a license.

According to http://en.wikipedia.org/wiki/Portable_Network_Graphics it is possible for a png to contain a tEXT chunk that could potentially have license or copyright information.  So we can't just throw away (not scan) png files.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4377/SunE450.png

**Comment by mcjaeger** [comment]
nice picture. :)

**Comment by mcjaeger** [comment]
tested with current master, still there:
![2015-11-19 10_32_27-change concluded license](https://cloud.githubusercontent.com/assets/3418977/11266980/e0735826-8ea8-11e5-9096-c8de85f1a014.png)

question is what to do here, because false positives are inherently present.

My question would be if we shall look for LGPL or GPL with spaces before it only? A space after is uncertain, because a version number would follow.

votes?

**Comment by mcjaeger** [comment]
Maximilan says: looking at the string around the match and check if there will be spaces to distinguish between text and binary data. In the shown case it is not likely a license info that is placed in the png file as metadata.

**Comment by steffen-weber** [comment]
Another idea would be to use an initial (heuristic) test for each file if it looks like binary data.
But this could be to restrictive -- the exif could contain license information.

**Comment by mcjaeger** [comment]
requires retest because copyright agent has changed

**Comment by mcjaeger** [comment]
I think need to open an issue where the user can select to ignore binary files at upload to speed up the work on fossology. False positve is generally better than false negative, so I guess letting the user decide to switch off scanning binaries would be better than changing nomos.
