### ISSUE TITLE
wget_agent uses -v switch to tar (twice) and then throws all the output away

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#324]
---

Author Name: **Gervase Markham** 
Original Redmine Issue: 7335, http://www.fossology.org/issues/7335
Original Date: 2014/07/23

---

gerv@hare:/usr/src/fossology$ ack "cvvf"
src/wget_agent/agent/wget_agent.c
404:        snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ >/dev/null 2>&1", TempFile, TempFilePath);
505:  snprintf(command,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ >/dev/null 2>&1", GlobalTempFile, TempFileDirectory);
669:    snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ %s >/dev/null 2>&1", TempFile, Path, GlobalParam);
689:    snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C %s/temp ./  > /dev/null 2>&1 && rm -rf %s/temp  > /dev/null 2>&1", TempFile, TempFileDir, TempFileDir);

It seems pointless to ask for verbose output and then redirect it all to /dev/null.

Gerv

**Comment by maximilianhuber** [comment]
Was fixed with #532.
