### ISSUE TITLE
wget_agent redirects STDERR to /dev/null and so user doesn't see errors

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#325]
---

Author Name: **Gervase Markham** 
Original Redmine Issue: 7341, http://www.fossology.org/issues/7341
Original Date: 2014/07/23
Original Assignee: Dong Ma

---

wget_agent just failed on me. It turned out that this was because I was using Upload from Server and tar couldn't read one of the files in the target directory. However, the UI didn't tell me that. All I got was:

2014-07-23 14:23:38 wget_agent [0] :: JOB[40].wget_agent[4386.localhost]: "FATAL wget_agent.c.673: rc_system is:512, CMD is:tar -cvvf  '/srv/fossology/repository/hare/wget/wget.4386' -C '/usr/src/b2g-fossology' ./  >/dev/null 2>&1"
2014-07-23 14:23:38 wget_agent [0] :: JOB[40].wget_agent[4386.localhost]: "FATAL main.c.247: Failed to archieve. GlobalURL, GlobalTempFile, TempFileDir are: /usr/src/b2g-fossology, /srv/fossology/repository/hare/wget/wget.4386, /srv/fossology/repository/hare/wget, Mode is: 40755 (octal)"
2014-07-23 14:23:38 wget_agent [0] :: JOB[40].wget_agent[4386.localhost]: agent failed with error code 50
2014-07-23 14:23:38 wget_agent [0] :: JOB[40].wget_agent[4386.localhost]: agent failed, code: 50

(Also, we need to fix the spelling of "archive" in that error.) 

We should log all output that goes to STDERR instead of throwing it away. That would have shown me:

tar: ./external/aac/documentation/.aacDecoder.pdf.sUQw6j: Cannot open: Permission denied

which explains the problem well.

Here are the sites to change:

src/wget_agent/agent/wget_agent.c
404:        snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ >/dev/null 2>&1", TempFile, TempFilePath);
505:  snprintf(command,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ >/dev/null 2>&1", GlobalTempFile, TempFileDirectory);
669:    snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C '%s' ./ %s >/dev/null 2>&1", TempFile, Path, GlobalParam);
689:    snprintf(CMD,MAXCMD-1, "tar -cvvf  '%s' -C %s/temp ./  > /dev/null 2>&1 && rm -rf %s/temp  > /dev/null 2>&1", TempFile, TempFileDir, TempFileDir);

Gerv

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/10/30 21:50:09 +0000

---

A related support problem just came in.  The user ran out of disk space but got this unhelpful error message:

```
2014-10-30 15:24:07 scheduler [17896] :: ERROR job.c.636: JOB[25]: job unable to create log file: 
/srv/fossology/repository/logs/00/00/25/000025

Upload failed for file PocketAgent.zip: FATAL wget_agent.c.137: upload 3 Failed to import 
/tmp/phpTShTAU-uploaded from /tmp/phpTShTAU-uploaded into repository gold DEC3B102A0F0E9351767DE1AFB5CE2925F303D94.FDDDE4E12AA5D58C860E7E186B7CD9A2.62216821

```

**Comment by mcjaeger** [comment]
tempted to reschedule this for 3.0.1, but it appears actually as kind of smaller modification to me.

**Comment by pguttmann** [comment]
I believe that wget_agent probably needs a good code "clean up".

**Comment by mcjaeger** [comment]
hm, I was only referring to the pieces of proposed code. I am not much into the wget_agent, if you feel it is a larger issue, shall we rather have this for 3.1?

**Comment by pguttmann** [comment]
I guess it might be good to incorporate Gerv's suggested fix for error reporting from here into 3.0.0 and propose the cleanup for 3.1 then ?

**Comment by steffen-weber** [comment]
pull https://github.com/fossology/fossology/pull/531 did not change the "out of disk space unhelpful error message"
```
2014-10-30 15:24:07 scheduler [17896] :: ERROR job.c.636: JOB[25]: job unable to create log file: 
/srv/fossology/repository/logs/00/00/25/000025

Upload failed for file PocketAgent.zip: FATAL wget_agent.c.137: upload 3 Failed to import 
/tmp/phpTShTAU-uploaded from /tmp/phpTShTAU-uploaded into repository gold DEC3B102A0F0E9351767DE1AFB5CE2925F303D94.FDDDE4E12AA5D58C860E7E186B7CD9A2.62216821

```

**Comment by mcjaeger** [comment]
OK, so far for my idea that this appears a smaller issue for me. I am not sure how this is the same issue as reported as this seems to another issues at the same agent. Again, the wget agent reworking is maybe sort of larger effort. Having the display of the std err in the Agent Geeky Scan details page appears to be good improvement.

**Comment by steffen-weber** [comment]
Just realized that there is already a ticket https://github.com/fossology/fossology/issues/325 for the "out of disk space unhelpful error message" sub-issue. Therefore pull https://github.com/fossology/fossology/pull/531 is sufficient to close this one.
