### ISSUE TITLE
nomos's performance decline from 2.1.0 significantly 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#326]
---

Author Name: **larry shi** 
Original Redmine Issue: 7353, http://www.fossology.org/issues/7353
Original Date: 2014/08/05
Original Assignee: larry shi

---

this issue is from #6399
If the nomos performance is just due to adding licenses, then why no change from 2.2 - 2.4? It doesn't seem this is the only cause. If it is then we could speed up nomos a lot by getting rid of the obscure licenses that nomos reports that we have no license reference for.
I will follow up this issue, so the 1st thing is file a new defect for it.

**Comment by mcjaeger** [comment]
the nomos performance story seems to be a more complex topic. It seems also to depend on what  users are used to (BSAM?). I propose to move it to move to 3.1 - @others please reschedule if you feel this rescheduling is inappropriate.

**Comment by mcjaeger** [comment]
closing here because we have a similar ticket already #343 and adding the remark form here to the #343
