### ISSUE TITLE
#include <sys/stat.h> forgotten?

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#329]
---

Author Name: **Johannes Najjar** 
Original Redmine Issue: 7383, http://www.fossology.org/issues/7383
Original Date: 2014/08/11
Original Assignee: Dong Ma

---

Vincent wrote:

"In our CI testing system, capture some Unit and Functional test failure related new changes, question is if the test cases finished?
   lib/c:
   Error: there were make errors for lib/c
   gcc -c   -g -O2 -Wall -D_FILE_OFFSET_BITS=64 -lfossology -I`pg_config --includedir` `pkg-config glib-2.0 --cflags --libs` -I../../../../src/lib/c -L../../../../src/lib/c -lpq L../../../../src/testing/lib/c -l focunit -I ../../../../src/testing/lib/c -I.. -I../ -lcunit test_libfossdbmanager.c
   test_libfossdbmanager.c: In function '_setLogFileForTest':
   test_libfossdbmanager.c:95: error: 'S_IRUSR' undeclared (first use in this function)
   test_libfossdbmanager.c:95: error: (Each undeclared identifier is reported only once
   test_libfossdbmanager.c:95: error: for each function it appears in.)
   test_libfossdbmanager.c:95: error: 'S_IWUSR' undeclared (first use in this function)
        make: *** [test_libfossdbmanager.o] Error 1
   Error: 'make coverage' of lib/c did not succeed, return code:2"

On our system we did not run into this, but maybe #include <sys/stat.h> fixes this.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Johannes Najjar** 
Original Date: 2014/08/11 11:15:08 +0000

---

commit f83c3a63b4e0e764559adb8ed01ee74709382441
Author: Johannes Najjar <johannes.najjar@tngtech.com>
Date:   Mon Aug 11 13:14:21 2014 +0200

    #7383 include stat.h

**Comment by maximilianhuber** [comment]
Jahannes has solved that issue a long time ago.
