### ISSUE TITLE
Catching ununpack errors

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#330]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7443, http://www.fossology.org/issues/7443
Original Date: 2014/08/15

---

We just had an incident where ununpack reported SUCCESS and no errors, yet nothing was unpacked and no error log was created.

Ununpack needs to redirect stderr to the log.  Had that happened we would have immediately seen that the tar file was corrupt.

I have a testfile /home/bobg/OSRB-16405-csbu-ubuntu-src.tar but it is too large (3.6 GB) to attach here.

**Comment by mcjaeger** [comment]
maybe we could have some feedback: how many times did it happen in the past year? I think, despite working with all kinds of archives even corrupted ones on purpose I have not seen it.

**Comment by bobgob** [comment]
not enough information.  Closing.
