### ISSUE TITLE
conf files still say SVN_REV

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#331]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7449, http://www.fossology.org/issues/7449
Original Date: 2014/08/15
Original Assignee: Dong Ma

---

Our conf files (e.g. src/nomos/VERSION) still says SVN_REV and VERSION says "trunk" even though we have moved to git.
SVN_REV should probably be called COMMIT
and build versions should probably be the branch name.
Or perhaps we use something like:
VERSION=2.5.0+
BRANCH=master
COMMIT=abcdef

**Comment by mcjaeger** [comment]
related to #550 but not covered entirely by #550

**Comment by maximilianhuber** [comment]
closed by #581
