### ISSUE TITLE
Scanner dependency

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#335]
---

Author Name: **Steffen Weber** 
Original Redmine Issue: 7491, http://www.fossology.org/issues/7491
Original Date: 2014/08/21

---

As mentioned in http://www.fossology.org/issues/7467#note-4, the monk license scanner depends on the license_ref table. Hence, the same revision could yield different results. 
Since re-running an agent requires a newer revision of this agent, I was going to generate a new agent ID whenever license_ref was updated by the user.

Moreover, scanner highlighting or even the finding links might be seem strange if existing reference license has been updated. I suggest to deny updating license_ref to avoid confusing output. Mabe, one could use the rf_active column to hide "wrong licenses" and insert the edited license as a new one.

**Comment by steffen-weber** [comment]
Since 24c79da453220b04538d81e71e2fb4bc7ede2a5a, there is a renew-monk-revision in menu Admin::Agent
