### ISSUE TITLE
fo_copyright_list cli options not available in UI

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#336]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7497, http://www.fossology.org/issues/7497
Original Date: 2014/08/21
Original Assignee: larry shi

---

The -x and -X options were added to fo_copyright_list cli in 2.6.0.  That functionality also needs to be in the UI.

(mcj adding fro clarification:)
  -x copyright        :: to match all that does not contain my copyright, (default): show all files
  -X copyright        :: to match my copyright, (default): show all files

**Comment by shaheemazmalmmd** [comment]
Already available with this commit https://github.com/fossology/fossology/commit/462591e8cec17c5f660892d49bba6a77e1dcfee8
