### ISSUE TITLE
jobs for monk

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#337]
---

Author Name: **larry shi** 
Original Redmine Issue: 7509, http://www.fossology.org/issues/7509
Original Date: 2014/08/22
Original Assignee: larry shi

---

from issue #7467,
Johannes Najjar wrote:

> Hi Larry,

> the threshold of .66 was a first guess, I believe based on what we found in BSAM or Ninka, I do not remember now. I think this value must be determined empirically. So to do that it would be a good idea to make it a bit easier to change. For the UI however I think this would be a bad idea to provide this option, as different thresholds find different licenses and thus the mapping monk-version <-> licenses would not be unique if there was no recompilation.

> This triggers the next question: What if the license reference table changes, but the version of monk does not? Then monk might find different licenses, even if it is the same version. How do we encode that dependence? I think of the recent case with the wrong license text in the database, if this gets fixed by a user without recompiling, can he re-scan packages, that were already scanned before the fix?

I agree with you, so let us keep it .66. I will fix that license text soon.

Can you please explain the two further points you mentioned?

1) license download for monk
on ui, there are 2 menues, | License List | License List Download |, right now, just support for nomos.
2) cli command to get monk license
there is one command - fo_nomos_license_list, through this command the users can get nomos license data from the command line.

couple of users want to get the license report from the command line, so if we can support for monk in the future, that will be great.

**Comment by mcjaeger** [comment]
clean way would be to move the respective logic from the SPDX agent (where this is already in) to a more general place, the lib/php area and then use the output of that function for the generation of the "license list" view and the "license list download" file.

**Comment by maximilianhuber** [comment]
Maybe the logic from the SPDX tools are not the corerct starting point, since
* they use the clearing information and add the scanner results to them with `addScannerResults(...)`
