### ISSUE TITLE
License browser regression - schedule link

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#338]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7539, http://www.fossology.org/issues/7539
Original Date: 2014/08/26
Original Assignee: larry shi

---

If you pull up the license browser and there is no license scan data, you used to get a message "No data available" and a link to schedule a scan.  Look at the bucket and copyright browsers for examples.  Now we only get a text message.  The idea behind giving the user a link is to make this task much simpler for the user.  The current text "There is no successful scan for this upload, please schedule one license scanner on this upload" doesn't even tell a user how to do this.  And if they know how to do it, it takes several clicks.

**Comment by mcjaeger** [comment]
Hm, the hint could be given like go to menu. So would be a notification below the yellow link area at the top of the main content area a solution?

**Comment by mcjaeger** [comment]
tested with current master: copyright has "schedule agent" button now, EC as well. Buckets as well.
