### ISSUE TITLE
incorrect behavior on nomos -l ./testfile

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#340]
---

Author Name: **larry shi** 
Original Redmine Issue: 7599, http://www.fossology.org/issues/7599
Original Date: 2014/08/29
Original Assignee: larry shi

---

./nomos /usr/local/share/fossology/www/ui/ui-browse-license.php -l
File /usr/local/share/fossology/www/ui/ui-browse-license.php contains license(s) GPL-2.0

./nomos /usr/local/share/fossology/www/ui/ui-browse-license.php
File ui-browse-license.php contains license(s) GPL-2.0

incorrect result below:
./nomos ./nomos.c -l
File ./nomos.c contains license(s) GPL-2.0

**Comment by yaobinshi** [comment]
why need this functionality?

**Comment by bobgob** [comment]
The -l switch is used to print the full path of the file being scanned.  This is to facilitate further processing of the output.  For example, when you have a script (or use -d) to create a master list of file paths and their licenses and then you want to feed that into another program.  The full paths can be very useful.
