### ISSUE TITLE
Add commit to performance graph label

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#341]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7605, http://www.fossology.org/issues/7605
Original Date: 2014/08/29
Original Assignee: Dong Ma

---

The current regression tests do not label the points with the last commit included in the build being tested.  This would be very helpful information to know what is being tested.

**Comment by mcjaeger** [comment]
seems to be outdated with current project infrastructure
