### ISSUE TITLE
Show Jobs - add estimated completion date/time

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#342]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7617, http://www.fossology.org/issues/7617
Original Date: 2014/09/02
Original Assignee: Bob Gobeille

---

Add an estimated completion date and time.  This will be very handy for long running jobs.

**Comment by steffen-weber** [comment]
done via 674710e5d92556b86ace9bfc572c98b15caf988e
