### ISSUE TITLE
copyright agent 2.5.0: non-ASCII symbols

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#345]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 7653, http://www.fossology.org/issues/7653
Original Date: 2014/09/07
Original Assignee: larry shi

---

hi,

something that will make your life a lot more complex: supporting non-ASCII characters. The attached file is from U-Boot. As you can see the name of the author in the file contains a non-ASCII character. The copyright agent currently strips the non-ASCII character out and replaces it with a space. It would be nice to have it in the copyright statement.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4359/sed13806.c

**Comment by steffen-weber** [comment]
Tested with recent copyright agent (1248f41) and got also the non-ASCII characters.
