### ISSUE TITLE
copyright agent 2.5.0: too much reported

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#346]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 7659, http://www.fossology.org/issues/7659
Original Date: 2014/09/08
Original Assignee: larry shi

---

When running the copyright scanner on the attached file from the Linux kernel too much is reported:

/tmp/pnode.c ::
        [29:90:statement] '(c) copyright ibm corporation 2005.
-      released under gpl v2.'
      [94:172:statement] 'author : ram pai (linuxram@us.ibm.com)
  *
  */
  #include <linux/mnt_namespace.h>'
      [113:132:email] 'linuxram@us.ibm.com'

The reason is of course the include statement directly after the end of the header. Since most copyright statements will be in the header right before any include statements this will likely happen quite often. It might also be useful to add some more language specific knowledge to finding out what are comments and what are preprocessor instructions (although this will get funky when dealing with language embeddings).

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/09/08 14:56:17 +0000

---

This is a duplicate of #7533 but since this contains more information I'm closing #7533
From #7533:
> One thing that makes copyright results difficult to use is the large number of false positives. 
> We need to work on this.
> Armijn has given us a heads up about the importance of copyright scanning.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4353/pnode.c

**Comment by mcjaeger** [comment]
what is the observed behavior with the file
 http://www.fossology.org/attachments/4353/pnode.c
and what is the desired?

**Comment by mcjaeger** [comment]
will do a retest with the copyright agent anyways, because we found another issue when generating the readme file. Will update then.

**Comment by mcjaeger** [comment]
new link to the file:
http://archive15.fossology.org/attachments/download/4353/pnode.c

retest shows it has well improved:

<img width="960" alt="screen shot 2018-07-11 at 15 58 31" src="https://user-images.githubusercontent.com/3418977/42576736-600ffc06-8523-11e8-96a9-e034ce020a6b.png">

(see matched at the left and extracted at the right)
