### ISSUE TITLE
cp2foss fails to upload a directory using '*' option

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#349]
---

Author Name: **Paul Guttmann** 
Original Redmine Issue: 7677, http://www.fossology.org/issues/7677
Original Date: 2014/09/09
Original Assignee: larry shi

---

This is to correct the 2nd defect reported in Backlog - 7083
http://www.fossology.org/issues/7083

I cloned https://github.com/spdx-tools/fossology-spdx into a test directory, changed to that directory and then attempted -
cp2foss --username fossy --password fossy -f cp2fosstest '*'

This appears to fail in a similar way to Bob's reported errors.
Interestingly, when I replaced '*' with 'fossology-spdx' everything was fine...

**Comment by mcjaeger** [comment]
I think that is also the error we have seen when taking files from another application.

**Comment by mcjaeger** [comment]
seems to be related with #512
