### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#350]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 7701, http://www.fossology.org/issues/7701
Original Date: 2014/09/09
Original Assignee: larry shi

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2014/09/09 23:09:46 +0000

---

License text: "Available via the MIT or new BSD license.", http://fossology.usa.hp.com/?mod=view-license&napk=161&upload=3181&item=798062823

License text: "/* Modernizr 2.6.2 (Custom Build) | MIT & BSD", http://fossology.usa.hp.com/?mod=view-license&napk=161&upload=3181&item=798062818

License text: "/*! jQuery v1.8.3 jquery.com | jquery.org/license */", http://fossology.usa.hp.com/?mod=view-license&napk=161&upload=3181&item=798062815

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4329/BSM_Help.zip

**Comment by yaobinshi** [comment]
for these 3 cases,will return:
MIT&BSD
MIT/BSD
See-URL

**Comment by bobgob** [comment]
Please add the test cases to nomos/agent_tests/testdata/NomosTestfiles

**Comment by bobgob** [comment]
It would be really helpful if you put the names of the test files in the issue.  As near as I can tell they are 

MIT/bsdormit.txt
MIT/bsdandmit.txt
See-file/seeurl.txt

closing
