### ISSUE TITLE
copyright using uploadtree

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#352]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7827, http://www.fossology.org/issues/7827
Original Date: 2014/10/07
Original Assignee: Daniele Fognini

---

From the copyright code:

2014-10-07 13:26:34 MDT:192.168.8.30 LOG:  duration: 15767.094 ms  statement: SELECT pfile_pk, pfile_sha1 || '.' || pfile_md5 || '.' || pfile_size AS pfilename   FROM (     SELECT distinct(pfile_fk) AS PF       FROM uploadtree       WHERE upload_fk = 3317 and (ufile_mode&x'3C000000'::int)=0   ) AS SS     left outer join copyright on (PF = pfile_fk and agent_fk = 180)     inner join pfile on (PF = pfile_pk)   WHERE ct_pk IS null or agent_fk <> 180

Note that in this case the uploadtree table should have been uploadtree_3317, and the "upload_fk=3317" in the where clause should have been omitted since uploadtree_nnnn only contains records for that upload and the extra parameter slows down this query.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Johannes Najjar** 
Original Date: 2014/10/08 15:37:15 +0000

---

Hi,

Daniele and me have refactored/rewritten the copyright agent in C++, including all sql queries. Is is now based on regular expressions and not on a dictionary.
What is still missing in our implementation is the name-scanner, which was present in the "old" copyright scanner. We could re-use the name-scanner part and put it in a separate scanner and then we could contribute our code. What do you think of that?

Best regards,
Johannes

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/10/08 15:56:26 +0000

---

Hi Johannes and Daniele,
I remember us talking about this rewrite but I don't recall the advantages.  How do the results compare? Do you get better results now?  Is it faster?  Easier to maintain?  I think you were going to keep the email and URL scanning since those were already regex based.  Is that right?   Did we talk about making this more generic so people could define and choose their own set of regex's?  For example, that would allow them to create crypto string regex's.

I think making the name scanner separate would be a good thing since people use that for different purposes.

Thanks!

**Comment by mcjaeger** [comment]
IIRC, one of the advantages was to use c++ and the regex involved with that. However, I am not getting from the discussion how the SQL issue mentioned above is covered?

**Comment by bobgob** [comment]
1) The original issue was about the copyright code using the correct uploadtree table.  I don't know if the current copyright agent uses the correct table or not since there is no reference to "uploadtree" in any of the code in copyright/agent/master.  That code must have been move to a library but I don't know where that is now to check it.

2) The next issue was about the name scanner.  I don't think that was ever replaced.

3) There was never an answer about if the new copyright scans are faster or have higher/lower quality.

**Comment by mcjaeger** [comment]
I did some some testing comparing the copyrights statements found with one version before we worked on this (1,5 years ago...) and one version after to time last year autumn. I plan to do this test again for 3.0.0. with current master. The approach was to:

* remove irrelevant statements (hits from license texts for example)
* export this to a spreadsheet app
* sort them alphabetically
* aggregate doubles
* then have list of the copyright statements

Do this again fro another version of fossology with the same upload.

**Comment by mcjaeger** [comment]
I did a sort of qualitative check with one of the OpenSSL 1.0.2 versions on my hard disk, comparing:
* Fossology 2.6.1 (latest release with name scanner)
* current master
From this check, the following observations can be made:
* For copyrights, the new implementation and the previos one find the same names / companies
* The new implementation has more results w.r.t. years and, more interesting, has years.
* It looks like there are slight advantages with URLs and E-Mails in OpenSSL

As there is in addition:
* names list does not find companies
* Copyright regex can be put into files, much better handling
* C++ written agent.

I am closing this ticket then.
[Fossology Copyright Listings 02.xlsx](https://github.com/fossology/fossology/files/13603/Fossology.Copyright.Listings.02.xlsx)
