### ISSUE TITLE
Password in DBConnection string is printed to Fossology log when connection attempt fails.  

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#355]
---

Author Name: **Valerie Duncan** 
Original Redmine Issue: 7887, http://www.fossology.org/issues/7887
Original Date: 2014/10/22
Original Assignee: larry shi

---

Fossology attempts a connection to the database which fails.  The entire Dbconnection string (including the password being used, in clear text)is printed in the fossology log.  See below.

2014-10-20 14:30:16 scheduler [5472] :: FATAL database.c.643: Unable to connect to the database: "ERROR: Unable to connect to the database
2014-10-20 14:30:16 scheduler [5472] ::    Connection string: 'dbname=fossology host=localhost user=fossy password=xxxxx'
2014-10-20 14:30:16 scheduler [5472] ::    Connection status: '1'

Suggested change:  Do not print the password.  Add a second message telling where to find the password being used.  For example, “see /etc/fossology/db.conf”.

**Comment by mcjaeger** [comment]
there is a similar thing that, if the upload from git repo fails, the git password, as part of the URL string is also printed in clear in the console output. just had this error recently in a telco sharing my screen discussing the 300-testing, ... , but let's correct this one first.
