### ISSUE TITLE
enhanced browse option (root folder) for admins

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#356]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7923, http://www.fossology.org/issues/7923
Original Date: 2014/11/05

---

It is typical for fossology admins to have their root folder set to Software Repository.  On systems with a lot of users, an admin does a lot of scrolling to find their own folder (especially if they have a user name late in the alphabet).  This is a proposal to let admins view all users  even if their root folder is set to their own.

For example,  user zephod is an admin on a system with 300 fossology users.  zephod's root folder is set to "zephod" so by default those are the only files they see.  However, since they are an admin, they can click a link (next to Expand|Collapse|Refresh) to show all folders or collapse back down to their root folder.

**Comment by mcjaeger** [comment]
not touched for a long time. Also the per user view does not support reuse of uploads ... maybe reopen if found still useful.

Nevertheless, the scrolling option on the left side of the folder view could be improved.
