### ISSUE TITLE
hardcoded path in wget_agent

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#359]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7965, http://www.fossology.org/issues/7965
Original Date: 2014/11/11
Original Assignee: larry shi

---

In wget_agent.c  GetVersionControl():

1) what is the dependency on the HOME environment variable?  This needs to be documented in the header.
2) We shouldn't have hardcoded paths (/srv/fossology).  This is what fossology.conf is for.

**Comment by bobgob** [comment]
Fixed in 75d0d5e
