### ISSUE TITLE
Upload from file failed with unhelpful error

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#36]
Upload from File just failed with the error below.  It is very frustrating to users to get errors that don't tell them what is wrong.  We need to improve the error message.

`Upload failed for file Fedora-12-source-DVD.iso: FATAL wget_agent.c.137: upload 2240 Failed to import /tmp/phpliy0fR-uploaded from /tmp/phpliy0fR-uploaded into repository gold 3135D6F013A19D0BF460C558A9E865796282BE9C.FF494BED045C64861B807A56F301897A.4544911360`

**Comment by max-wittig** [comment]
based on issue #325
