### ISSUE TITLE
MIT and University of Illinois Open Source licenses not detected

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#360]
---

Author Name: **Raino Lintulampi** 
Original Redmine Issue: 7971, http://www.fossology.org/issues/7971
Original Date: 2014/11/12
Original Assignee: larry shi

---

nomos in 2.6.1 version does not detect MIT and University of Illinois Open Source License
in the enclosed file. Following patches correct the issue:

--- a/src/nomos/agent/STRINGS.in
+++ b/src/nomos/agent/STRINGS.in
@@ -3369,6 +3369,10 @@ e /* (INFILE(j)) */
 %ENTRY%        _LT_MITref2
 %KEY%  "licen[cs]"
 %STR%  "licen[cs]e is the MIT licen[cs]e"
+#
+%ENTRY%        _LT_MITref3
+%KEY%  "licen[cs]"
+%STR%  "licen[cs]ed under =FEW= MIT"
 #####
 # DELETED: ... =SOME= accompanied by this header"
 #####
@@ -7376,7 +7380,7 @@ k
 #
 %ENTRY%        _TITLE_NCSA
 %KEY%  "licen[cs]"
-%STR%  "university of illinois/ncsa open source licen[cs]e"
+%STR%  "university of illinois(|/ncsa) open source licen[cs]e"
 #
 %ENTRY%        _TITLE_NCSA_EXHIBIT
 %KEY%  "licen[cs]"

--- a/src/nomos/agent/parse.c
+++ b/src/nomos/agent/parse.c
@@ -1945,7 +1945,7 @@ char *parseLicenses(char *filetext, int size, scanres_t *scp,
       lmem[_mMIT] = 1;
     }
   }
-  else if (INFILE(_LT_MITref2)) {
+  else if (INFILE(_LT_MITref2) || INFILE(_LT_MITref3)) {
     INTERESTING(lDebug ? "MIT(ref2)" : "MIT");
     lmem[_mMIT] = 1;
   }

In LICENSE.TXT file University of Illinois Open Source License is in the form
University of Illinois/NCSA
Open Source License

so the license reference in the file has typing error. However, the wrong form is
in all code files in the library so this is worth of correcting. 

Br
Raino

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4323/bind.cpp

**Comment by yaobinshi** [comment]
will return Dual-license,MIT-style,NCSA

**Comment by bobgob** [comment]
Please add bind.cpp to NomosTestfiles/
