### ISSUE TITLE
Allow install to skip version

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#362]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 7989, http://www.fossology.org/issues/7989
Original Date: 2014/11/13
Original Assignee: Dong Ma

---

We need to make it so that you can upgrade from one version to another without having to do sequential upgrades.

**Comment by steffen-weber** [comment]
The recent version of fossinit.php uses the variable named 'Release' in DB table sysconfig to detect Releases >= 2.6.3 and skips sequential upgrades if possible.
