### ISSUE TITLE
error when run ./delagent  -T

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#368]
---

Author Name: **larry shi** 
Original Redmine Issue: 8061, http://www.fossology.org/issues/8061
Original Date: 2014/11/21
Original Assignee: Dong Ma

---

e.g.

./delagent  --user fossy --password fossy  -u 10 -T

ERROR: util.c:473, ERROR:  table "delup_10_pfile" does not exist
On: DROP TABLE DelUp_10_pfile;

**Comment by shaheemazmalmmd** [comment]
May Be this Issue is fixed with merge of https://github.com/fossology/fossology/pull/646 (Refactor delagent)

**Comment by maximilianhuber** [comment]
@shaheemazmalmmd: can you retest it?

**Comment by shaheemazmalmmd** [comment]
Tested : 368b3cb

unfortunately this issue still exists. to reproduce this.

./delagent --user uname --password pass -U uploadId -T
