### ISSUE TITLE
parse.c: curly brackets missing in else  branch 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#369]
---

Author Name: **Raino Lintulampi** 
Original Redmine Issue: 8073, http://www.fossology.org/issues/8073
Original Date: 2014/11/27

---

In file parse.c line 1608 else branch does not use opening / closing
brackets. There are 18 if/else if structures under that else branch.
I do not know what compiler does in this situation but at least for 
clarity reason brackets should be added.

**Comment by yaobinshi** [comment]
fixed in git 77c51d

**Comment by steffen-weber** [comment]
Also the indent from line 1604 to 1724 was to much, fixed with commit  c126c10d8c1d09e35f8f9f0572521a54a2b25401
