### ISSUE TITLE
nomos 2.6.1: missed Trolltech GPL exception

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#370]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 8079, http://www.fossology.org/issues/8079
Original Date: 2014/11/28

---

The attached file from Qt 4.3.1 has an addition exception to the GPL (Trolltech GPL exception). Nomos currently does not recognize it.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4311/abstractwidgetfactory.cpp

**Comment by yaobinshi** [comment]
bob, please help to verify this issue, thanks.

**Comment by bobgob** [comment]
tested on master 8bba20c 
closing
