### ISSUE TITLE
nomos 2.6.1: LGPLv3 recognized as LGPLv2

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#372]
---

Author Name: **armijn hemel** 
Original Redmine Issue: 8091, http://www.fossology.org/issues/8091
Original Date: 2014/11/28

---

The attached file from Libreoffice is LGPLv3 but is recognized as LGPLv2. I suppose that the following part of the header is what causes it:

#ifndef LUIDL_PARSENV2_HXX
#define LUIDL_PARSENV2_HXX

because it contains the substring "v2"

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4299/parsenv2.hxx

**Comment by yaobinshi** [comment]
have been fixed in one previous commit.

**Comment by bobgob** [comment]
Please use commit hash in future comments.  In this case it was 3483f13
Tested.  Closing.
