### ISSUE TITLE
Paged file viewer (new in 2.6.1) makes file browsing and license investigation unworkable

### ISSUE THREAD

**Issue by sutula** [fossology/fossology#377]
Prior to 2.6.1, clicking on a file displayed the entire file.  This allowed quick scrolling of the entire file and use of the browser's search facility if specific words are sought.  2.6.1 added a paged file viewer, the use of which apparently can't be avoided.  It is basically unusable compared to prior versions of Fossology.  For large files, there is no real way to look for specific contents within the whole file, except page by page, which can easily be tens or hundreds of pages for large files.

**Comment by yaobinshi** [comment]
it is critical defect, debugging.

**Comment by wuan** [comment]
The page size was reduced by a factor of 10 during development. It should be restored to the original setting. This could as well be a configurable parameter.

**Comment by yaobinshi** [comment]
a configurable parameter(on Admin-->Customize page) in  is better for me, do you want to fix it?

**Comment by wuan** [comment]
We are currently busy preparing the following contributions. In the new clearing view the value of the page size is restored to the original value (current value * 10).
We could leave this issue open to create the configuration later.

**Comment by bobgob** [comment]
I think the simplest solution is to add new values for the drop down page length.  One of the values should be the entire file (no limit).
