### ISSUE TITLE
Put all Jenkins configuration files to github

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#38]
Putting all the Jenkins configuration files to github, use for others, back up and track changes.

**Comment by mcjaeger** [comment]
Steffen and I once have written:
https://github.com/fossology/fossology/wiki/Install-Fossology-on-a-Jenkins-Server

Would that solve this issue? Or is it for your Jenkins installation, because it is kind of special in doing extra things (package building?)?

**Comment by max-wittig** [comment]
too long open
