### ISSUE TITLE
Current MozillaFirefox license file generates AGPL false positive

### ISSUE THREAD

**Issue by sutula** [fossology/fossology#380]
Within HP, an example file can be found:

  http://fossology.usa.hp.com/?mod=view-license&bapk=179&napk=184&upload=3501&item=845048126

The Nomos license scanner generates a number of license indications:

  AGPL-3.0+, Apache-2.0, ATT-style, Google-BSD, JPNIC, LGPL-2.1+, MIT-style, MPL-2.0-no-copyleft-exception, NotreDame-style, Princeton

I think a number of these are false positives, but the AGPL-3.0 is the most annoying in our use.

**Comment by yaobinshi** [comment]
in 2.6.2, from my testing, return as: Apache-2.0,LGPL-3.0,MPL-2.0 for this file.

**Comment by maximilianhuber** [comment]
Seems to be solved in the current master (7d6de33) and current license file:
![screenshot](https://cloud.githubusercontent.com/assets/1187050/11976179/e5281e1e-a975-11e5-8fe3-876d2f8fc23c.png)

**Comment by mcjaeger** [comment]
OK, missed that, but if it solved ....
