### ISSUE TITLE
missed file reference for CUPS files

### ISSUE THREAD

**Issue by armijnhemel** [fossology/fossology#382]
the file tbcp.c in CUPS 1.7.4 is not recognized as a file reference (sorry, I haven't figured attachments out on GitHub yet):

 *   These coded instructions, statements, and computer programs are the
 *   property of Apple Inc. and are protected by Federal copyright
 *   law.  Distribution and use rights are outlined in the file "LICENSE.txt"
 *   which should have been included with this file.  If this file is
 *   file is missing or damaged, see the license at "http://www.cups.org/".
 *
 *   This file is subject to the Apple OS-Developed Software exception.

**Comment by mcjaeger** [comment]
seems to work now (file in 1.7.4. looks pretty much the same)

![2015-12-23 14_27_13-change concluded license](https://cloud.githubusercontent.com/assets/3418977/11977248/4f896e42-a981-11e5-865a-8924743979df.png)
