### ISSUE TITLE
Dashboard failure in 2.6.2

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#384]
File: /usr/share/fossology/www/ui/admin-dashboard.php, Line number: 232
ERROR: column "procpid" does not exist LINE 1: SELECT procpid, state, query_start, now()-query_start AS ela... ^
SELECT procpid, state, query_start, now()-query_start AS elapsed FROM pg_stat_activity WHERE state != '' AND datname = 'fossology' ORDER BY procpid;

#0  debugbacktrace() called at [/usr/share/fossology/lib/php/common-db.php:172]
#1  DBCheckResult(, SELECT procpid, state, query_start, now()-query_start AS elapsed FROM pg_stat_activity WHERE state != '' AND datname = 'fossology' ORDER BY procpid;, /usr/share/fossology/www/ui/admin-dashboard.php, 232) called at [/usr/share/fossology/www/ui/admin-dashboard.php:232]
#2  dashboard->DatabaseQueries() called at [/usr/share/fossology/www/ui/admin-dashboard.php:371]
#3  dashboard->Output() called at [/usr/share/fossology/www/ui/index.php:48]

**Comment by yaobinshi** [comment]
1. please confirm you have get rid of the old file ui-about.php after doing the source install
2. please make sure delete the cached files in /var/local/cache/fossology/
through running /usr/local/lib/fossology/fo-postinstall or get rid of cashed files manually. 

then try again.

**Comment by steffen-weber** [comment]
the column procpid was renamed in Postgres 9.2
http://www.postgresql.org/docs/9.2/static/release-9-2.html

**Comment by steffen-weber** [comment]
Successfully tested with Postgresql version	9.3.6 after path cb426f969fdea8c8cdc75c6cb213e84d305aaaef.
