### ISSUE TITLE
Upload from Server: remove or disable by default

### ISSUE THREAD

**Issue by fogninid** [fossology/fossology#386]
cp2foss already allows to upload files directly from the server and does not expose the server to users who only have http access.
I would remove the plugin completely or disable it on a default installation.
Or does anybody see a use case which is not covered by cp2foss?

**Comment by yaobinshi** [comment]
usually, cp2foss is used by other script or tool, cp2foss cover the jobs upload from server, upload from url, and upload from version control system do.

cp2foss can not do the job upload from file(you are  accessing fossology  from  another machine).
certainly if you are doing http access fossology from the fossology server, upload from server is able to do the jobs what upload from file does.

sure, you can run sudo mv /usr/{local}/share/fossology/www/ui/upload-*  ./temp_folder

**Comment by fogninid** [comment]
How do you put the file on server if you do not have enough access to run cp2foss?

As it is now, every user can 'upload' a file from the server, you just need that the scheduler has the permission to read it (=everything readable by fossy:fossy).
This has obvious privacy/security implications. For example try uploading /srv/fossology/repository/localhost/files/

I would at least make the installation optional: e.g. `sudo make -C src/www/ui install-fileupload`

**Comment by bobgob** [comment]
@fogninid I agree.  We hadn't considered the security implications before.  Removing it will force people who have this usage model to either use cp2foss, or keep their files in a place where they can be reached with Upload from URL.  That seems reasonable to me.   Making the install optional, would give the user a choice.  But I agree, it should definitely not be installed by default.

**Comment by steffen-weber** [comment]
only files in white-listed directories can be uploaded from server with 382d4f4c2230b6ae6566c829ec179618ab5bc59b
