### ISSUE TITLE
Both Monk and Nomos appear to miss PostgreSQL License

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#387]
When scanning https://github.com/ZhengYang/odbc_fdw both Monk and Nomos license scanners fail to report the postgreSQL license found in files such as: odbc_fdw--1.0.sql, odbc_fdw.c and odbc_fdw.control

**Comment by bobgob** [comment]
A temporary workaround for monk is to add the license with the license admin tool.
Admin > License Admin

**Comment by pguttmann** [comment]
This still seems broken for both scanners on - 9)  https://github.com/atris/JDBC_FDW/archive/master.zip
After I add the license for Monk, how do I "rescan" the file. I can't see/find an easy way to reschedule either agent :P
I used license info at - https://spdx.org/licenses/PostgreSQL.html

**Comment by bobgob** [comment]
A scanned file won't be rescanned until the scanner is updated.  When you working from the master branch and installing from source, we aren't updating the agent table so fossology doesn't know the scanner has been updated.  A simple work around is to modify your test file.  Just add a space or something at the end so the hash changes.

**Comment by yaobinshi** [comment]
test again with the latest code from master branch on nomos, works

**Comment by bobgob** [comment]
@pguttmann please close this if your retest passes.
