### ISSUE TITLE
support running cli commands from GUI

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#389]
not all the users have the permission to run from the server

**Comment by mcjaeger** [comment]
resetting this for 3.1 because it appears as new feature to me and we are not going to make it until the next few weeks.

**Comment by mcjaeger** [comment]
It is about the CLI tools provided by fossology, right? Actually, I am still tending to close it, because it is maybe a use case that you could do (more) from commend line as from the web interface.

**Comment by pguttmann** [comment]
I think the issue was "not all the users have the permission to run from the server" presumably meaning they may not have shell/cli access to the server and the suggestion was to use the web GUI as a "proxy" of sorts to bypass that access requirement ;)

**Comment by mcjaeger** [comment]
OK, but are you sure about just allowing a Web user to have general access to the shell of the server where is Fossology is running? Usually this is something that someone would like to avoid with Web applications. (again asking if it is about the CLI tools of Fossology or general access)

**Comment by pguttmann** [comment]
I'm pretty ambivalent actually. I make sure I've got shell access ;)
I didn't open the case either - Perhaps it can be closed/withdrawn, since pretty much all the CLI functionality is available from the web GUI isn't it ?

**Comment by mcjaeger** [comment]
Well I did not systematically check it, but my impression is the same.

it would man to see all CLI things with Fossology and then check.

But restarting the scheduler for example 8which is not covred IMHO) would be handy maybe (asked sometimes actually) to have this from Web UI. However, it sounds weird from my side, to put a sudo command access onto a Web page...

**Comment by pguttmann** [comment]
Yeah - Restarting the scheduler seems to be a "Feature" that was omitted in:
Admin=>Scheduler=>"Select an Operation" drop down list ;)

**Comment by mcjaeger** [comment]
and I am not sure, if that is useful to have. Useful as developer yes, but in production maybe also too much of control from the Web UI.

**Comment by pguttmann** [comment]
I believe it's an Admin only function. Perhaps we could investigate a separate DevOps or similar role ?

**Comment by max-wittig** [comment]
you shouldn't be able to run commands from the web-interface
