### ISSUE TITLE
UI improvement to concluded license handling

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#39]
I propose following changes for handling concluded license in
different views.
1. Adding new user permission level ("Audit"). The user has to
   have this permission level in order to change/review licenses.
2. Removing the 'Edit concluded license' button from View License
   view if concluded license has already been set. In that case
   additional change has to be done via Audit menu.
3. Adding possibility to set concluded license directly from
   List Files for License in case concluded license has not been
   set. Also it could be useful to set concluded license for
   multiple files at the same time.
4. Concluded license is shown in addition to scanner result in
   List Files for License view.
5. Restoring the capability to change nomos scanner result.

All these changes except setting concluded license for multiple
files are demonstrated in the patch which can be found in 
http://www.fossology.org/issues/8103.

**Comment by yaobinshi** [comment]
for item 1:
admin should have the audit permission, still have to add this specific permission(user)?
for item 3:
set concluded license on files, not  understand very well.
files here means files with same licenses or one directory or any selected files on an upload, others?
for item 4: 
still show concluded licenses even has audit licenses? 
for item 5:
have to define Change license for license scanner/Concluded license/Audit license more clearly, possible will confuse users if not.

**Comment by rlintu** [comment]
Item 1:
Currently if a user who has upload right he automatically has also right to edit (concluded) license. 
From governance point of view it is ok that designers may have right to upload and scan packages but
license review is done by other people (license reviewers). I think Admin right should be reserved
for tool administrators. Therefore I propose a new permission level.

Item 3:
Hopefully attached picture clarifies this. In many case it is clear what the concluded license
on file level is, for example in case when only one license is detected by a scanner. In these
cases the concluded license could be selected directly from the 'List Files for License' view.
![list-files-for-license](https://cloud.githubusercontent.com/assets/9692647/5644529/1da5b7fa-966d-11e4-9657-8a652ebc1134.png)

Item 4:
Selecting 'Edit concluded license' and 'Audit' open the same view. Maybe the names should be identical?

Item 5:
I agree. The naming could be different. Also adding this new permission level helps this
because then the ordinary user does not see these options (buttons) at all, only the reviewers who
should know the tool features better.

**Comment by yaobinshi** [comment]
rlintu, thanks for your explanation.

I talked with bob on Tuesday on this issue.
from bob's  perspective, audit is just a permission role, this role has the permission to change the license scanner report and edit conclude license, do not have to add audit functionality.

ideas?

**Comment by rlintu** [comment]
Yes, audit is a permission role. 
I didn't quite follow your comment about adding audit functionality. I added possibility to
change nomos scanner report result but 'Audit/Edit concluded license' are as they
exist in 2.6.x versions.
I just tried to make access to that functionality more user friendly.
This picture illustrate 'View License' when concluded license is not set.
![view-license-1](https://cloud.githubusercontent.com/assets/9692647/5659956/ee90d1fa-9722-11e4-9102-ca732ba19290.png)

Buttons are visible which indicates that this file has not been reviewed. Concluded license
can be set either selecting 'Edit concluded license' button or selecting 'Audit' from micromenu.
When the concluded license is set then buttons are not any more visible in 'View License'
view as shown in the picture below. However, the concluded license can be changed still
by selecting 'Audit' from micromenu.
![view-license-2](https://cloud.githubusercontent.com/assets/9692647/5660011/872fb8fe-9723-11e4-9c58-417c3436f0a5.png)

By the way 'One-shot copyright/emailURL' option in micromenu is not logical. I think it
should be removed and if needed it can be selected from 'Upload' menu.

Br, 
Raino

**Comment by yaobinshi** [comment]
from my previous point:
no audit features, just have audit roles (this role is able to do all the license review jobs), Audit micro-menu is not necessary because it is same as 'Edit concluded license'.

however, after I reading your comment above, your idea is more make sense to me, need talk with others. from bob's perspective, we need more more discussions from the whole team, it seems that the guys from siemens also have ideas on Audit.

-Larry

**Comment by mcjaeger** [comment]
a lot has changed then, I am inclined towards closing the ticket, because while there is not a spcieal audit role, the edit and review support in the UI has much improved. Pushing back therefore and candidate for closing. Please speak up if parts of it should be still in or differently scheduled.

**Comment by rlintu** [comment]
Lot of changes indeed. It is quite difficult to follow what is happening. About the original idea to separate rights to upload and schedule agents and right to set concluded license. How is that done now? Using group rights?

**Comment by mcjaeger** [comment]
Now, it is like there is a read-access role and there is a read-write-access role (in addition to the admin role). Accordingly, there is is distinction between tasks. I think what is needed here is to have a comprehensive view, if we want to have something like more process oriented roles (Uploader / Customer, Clearing Expert, ...) which sounds good in general. 

More feedback?

**Comment by rlintu** [comment]
For 3.0 current permission setup is manageable, I mean give read-write permissions only few people and make clear instructions what to do and what you cannot do even you have rights to do. 

For later releases I support your comment on process oriented roles. However, for 3.0 I would like to see this bug corrected
https://github.com/fossology/fossology/issues/524

**Comment by steffen-weber** [comment]
Well, the global permissions like read-write do only affect the upload itself (e.g., the description), but not the decisions.
There are three permission levels within a group: User, Advisor and Admin. A [group] User can conclude license, but not change the assignee for an upload. An Advisor can also change the assignee or reject the clearing. A [group] Admin can additionally manage the permissions within the group.
A fourth group role, e.g. Observer, for those how cannot change the concluded license, might be good.

**Comment by mcjaeger** [comment]
observer roles makes sense. I am not seeing this super urgent (hence 3.2.0 milestone) because in most cases, people should have an understanding about OSS licensing before using fossology. Please object if you do not agree.

**Comment by mcjaeger** [comment]
actually catching up with this issue is difficult, so the only open point was opened here:
https://github.com/fossology/fossology/issues/1091
