### ISSUE TITLE
license browser URL ambiguity conflict with report_cache

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#393]
A license browser url has the form:
http://myfossology.com/?mod=license&upload=2667&item=736883824
and displays the latest scanner results (when there have been multiple scans from different license scanner agents).  Note that the license scanner agent_pk's are missing from the url.  This means:

1) a bookmarked url will return different results at different times.  This is not good when people are expecting the same results.

2) the report_cache key is the url.  So after a new scan the license browser will return whatever is cached, which may not be the latest results

**Comment by steffen-weber** [comment]
(1) A bookmark of latest results returns latest results. 
(2) Obsolete since commit 7b49ddd176dd73da6752cc1bb9af62fb4171a080
