### ISSUE TITLE
cp2foss failed to load files from filesystem

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#397]
I tried to load archive file using cp2foss. Loading failed because scheduler started
wget_agent which obviously failed because there was no valid URL. I tried lot of different
options but in all cases wget_agent was started and upload failed.
I finally managed to load the archive by copying it to localhost/www tree and hence using
valid http URL with cp2foss. I tried this with 2.6.2 and 2.5.0 versions with the same results.
This is strange because 'man cp2foss' describes several examples how to load files.
Is this a bug or is  'man cp2foss' page outdated? 

Br,
Raino

**Comment by bobgob** [comment]
It should work with a local regular file name.  But it has to be run from your fossology server (unless you use the -c option).

**Comment by anthonyharrison** [comment]
I had the same problem and tried the -c option (using /etc/fossology as the directory assuming that is what is meant by the directory for system configuration) but still got wget_agent starting. Even tried explicitly listing all of the agents (except wget_agent) and it still starts. All I am trying to do is replicate in a script what can be achieved interactively at the Upload new File page. Help!

**Comment by yaobinshi** [comment]
wget_agent will be scheduled always.
how I do as below:
1. upload from one url: 
cp2foss --username fossy --password fossy  -q all http://www.fossology.org/releases/2.6.2/Ubuntu/14.04/fossology-buckets_2.6.2-1_amd64.deb -v

2. upload from local server（make sure the fossy account has the execute permission)
cp2foss --username fossy --password fossy  -q all ./ -v 

anything please let us know.

**Comment by bobgob** [comment]
I'm using the master branch but I don't see a problem.   To test, I'm in my home directory, which is not accessible via a url.
```
$ cp2foss --username fossy --password fossy readmetest.tar
```
This worked.  Yes it does start wget_agent which takes care of copying the file for us.  Make sure that user fossy has read access to the file.  If user fossy can't read the file, you will get one of our not very helpful, cryptic but verbose error messages like this:

```
2015-05-26 14:04:00 wget_agent [0] :: JOB[2620].wget_agent[25211.localhost]: "FATAL wget_agent.c.737: [wget_agent.c:737] Error exit: 1, CMD:cp '/home/bobg/readmetest.tar' '/srv/fossology/repository/bobg.fc.hp.com/wget/wget.25211' >/dev/null 2>&1"
2015-05-26 14:04:00 wget_agent [0] :: JOB[2620].wget_agent[25211.localhost]: "FATAL main.c.252: Failed to archieve. GlobalURL, GlobalTempFile, TempFileDir are: /home/bobg/readmetest.tar, /srv/fossology/repository/bobg.fc.hp.com/wget/wget.25211, /srv/fossology/repository/bobg.fc.hp.com/wget, Mode is: 100640 (octal)"
2015-05-26 14:04:00 wget_agent [0] :: JOB[2620].wget_agent[25211.localhost]: agent failed, code: 50
```

**Comment by rlintu** [comment]
User `fossy` needs to have read access to the root folder where the packages are uploaded with `cp2foss`.
