### ISSUE TITLE
Wildcard Tagging

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#40]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 393, http://www.fossology.org/issues/393
Original Date: 2012/01/11

---

Request from Scott Lamons.
A new feature to tag based on wildcards.  For example, tag all the .h's or .cpp's.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/01/12 22:07:09 +0000

---

adding Scott Lamons to watcher list

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:34:59 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
since this ticket is also kind of "old" please update in case. Sounds reasonable to me in general.

**Comment by mcjaeger** [comment]
(asked for update but did not get)
