### ISSUE TITLE
Upload from File page cannot select folder

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#400]
![image](https://cloud.githubusercontent.com/assets/5294029/6633563/7a902c0c-c985-11e4-8b6e-28a609bd8fa5.png)

**Comment by yaobinshi** [comment]
I did the testing with lasted code, works fine.

**Comment by bobgob** [comment]
I just closed #443 as a duplicate of this issue that I filed.   I could reproduce the same issue as @larainema 
From #443 :
> Testing current master 420e4c9
>Upload from File "Select the folder for storing the uploaded file:" pulldown only shows my root folder. It should show my subfolders as well.

**Comment by bobgob** [comment]
I just applied d81792 and now I see that Upload from URL has the same bug.

**Comment by steffen-weber** [comment]
This was probably caused by using the old FolderDao without migration of column folder.parent_fk for 2.4 data. The newer FolderDao from https://github.com/fossology/fossology/pull/462 shouldn't have this migration issue. Can you re-test it @larainema?

**Comment by bobgob** [comment]
Tested on #abb949f
Closing.
