### ISSUE TITLE
Create a new "universal" license report cli utility based upon  fo_nomos_license_list.php

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#402]
As the number of license scanning agents increases it may be worthwhile creating a more "universal" license report cli utility based upon  fo_nomos_license_list.php

I'd suggest we rename this to  fo_license_list and incorporate a switch/argument to specify which agent's report(s) to return.

**Comment by bobgob** [comment]
I agree.  Also, look into a combined report for a set of agents.

**Comment by yaobinshi** [comment]
should the new fo_license/copyright list cli support running from command line and scheduler, right?

**Comment by bobgob** [comment]
I don't think it needs to support running from the scheduler.  A user can already background the process.

**Comment by mcjaeger** [comment]
and I think that many persons seem to use the Fossology CLI ...

**Comment by mcjaeger** [comment]
(from discussion) it has been improved with scanner findings conclusions and so on and can be exported as CSV
