### ISSUE TITLE
Fatal error when load the license browse page

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#404]
![image](https://cloud.githubusercontent.com/assets/5294029/6775724/4aff3da0-d170-11e4-9107-b5ca928f1eed.png)

**Comment by steffen-weber** [comment]
You should define your timezone in the php.ini as
``date.timezone = Asia/Chongqing``

**Comment by larainema** [comment]
After change the timezone in php.ini fix this issue, but found another issue:
![image](https://cloud.githubusercontent.com/assets/5294029/6780607/bc2bcdfa-d1a1-11e4-9ea2-2f2167284f33.png)

**Comment by pguttmann** [comment]
I have a similar issue after "upgrading" 2.6 install to latest (as of Friday Mar-20th-2015) :
#1  Fossology\Lib\Db\SolidDbManager->execute(Fossology\Lib\Dao\ClearingDao::getFileClearingsFolderuploadtree, Array ([0] => 812,[1] => 1,[2] => 276)) called at [/usr/share/fossology/lib/php/Dao/ClearingDao.php:133]
#2  Fossology\Lib\Dao\ClearingDao->getFileClearingsFolder(Fossology\Lib\Data\FileTreeBounds Object ([] => uploadtree_a,[] => 812,[] => 1,[] => 276,[] => 5511815)) called at [/usr/share/fossology/www/ui/ui-browse-license.php:191]
#3  ui_browse_license->ShowUploadHist(5511815, /repo/?mod=license&upload=812, ) called at [/usr/share/fossology/www/ui/ui-browse-license.php:282]
#4  ui_browse_license->Output() called at [/usr/share/fossology/lib/php/Plugin/FO_Plugin.php:387]
#5  FO_Plugin->renderOutput() called at [/usr/share/fossology/lib/php/Plugin/FO_Plugin.php:449]
#6  FO_Plugin->execute() called at [/usr/share/fossology/www/ui/index.php:56]

ERROR:  column cd.scope_fk does not exist
LINE 24: ...  LEFT JOIN clearing_decision_scopes CD_scopes ON CD.scope_f...

**Comment by pguttmann** [comment]
One thing I did notice when running fo-postinstall after installing/upgrading to latest 2.6.2 source install was -
"Missing column clearing_decision.clearing_pk, you should update to version 2.6.2 before migration"

I'm not really sure how to interpret or process that one ;)

**Comment by steffen-weber** [comment]
The migration script from pull request #399 didn't work correctly and left the clearing decision table in an unexpected state. Updating from the tagged version 2.6.2 to the latest source works. However, commit 4c147855f37a8ba18c81c5a0159fc8c00c55b3f4 allows to continue ignoring state.

**Comment by larainema** [comment]
Commit 4c14785 will need user input when the fresh install, it will hang here when run fo-postinstall if user didn't input, i don't think it's a good behavior, especially for the automated testing.

**Comment by pguttmann** [comment]
Perhaps this could be modified to included a "timeout" of some sort, say 20 seconds, after which it will perform a default action ?

**Comment by steffen-weber** [comment]
This would be possible.
```
diff --git a/install/fossinit.php b/install/fossinit.php
index fa59e75..bdab739 100755
--- a/install/fossinit.php
+++ b/install/fossinit.php
@@ -214,11 +214,19 @@ if(!array_key_exists('Release', $sysconfig)){
   }
   if(!array_key_exists('clearing_pk', $currSchema['TABLE']['clearing_decision']))
   {
+    $timeoutSec = 20;
     echo "Missing column clearing_decision.clearing_pk, you should update to version 2.6.2 before migration\n";
-    echo "Type 'i' to ignore this warning and run the risk of losing clearing decisions: ";
+    echo "Enter 'i' within $timeoutSec seconds to ignore this warning and run the risk of losing clearing decisions: ";
     $handle = fopen ("php://stdin","r");
-    $line = fgets($handle);
-    if(trim($line) != 'i'){
+    stream_set_blocking($handle,0);
+    for($s=0;$s<$timeoutSec;$s++)
+    {
+      sleep(1);
+      $line = fread($handle,1);
+      if($line) break;
+    }
+    if(trim($line) != 'i')
+    {
      echo "ABORTING!\n";
      exit(26);
     }
```

**Comment by pguttmann** [comment]
Excellent. That appears to solve the automated testing aspect. Thanks :)
Now there only remains the "mysterious" - "you should update to version 2.6.2 before migration" message.
Isn't this installation part of the "update to version 2.6.2" ?

**Comment by larainema** [comment]
Cool, the default action is best solution.
