### ISSUE TITLE
the scanner count is inconsistent on license browser and bucket browser

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#405]
right now, bucket browser is using unique file count, nomos is not.

**Comment by yaobinshi** [comment]
my fix is below, will check in after more tests are done.

diff --git a/src/lib/php/Dao/LicenseDao.php b/src/lib/php/Dao/LicenseDao.php
index c7acc20..548c175 100644
--- a/src/lib/php/Dao/LicenseDao.php
+++ b/src/lib/php/Dao/LicenseDao.php
@@ -304,7 +304,7 @@ class LicenseDao extends Object
     $agentText = $agentId ? (is_array($agentId) ? implode(',', $agentId) : $agentId) : '-';
     $statementName = __METHOD__ . '.' . $uploadTreeTableName . ".$orderStatement.$agentText";
     $param = array($itemTreeBounds->getUploadId(), $itemTreeBounds->getLeft(), $itemTreeBounds->getRight());
-    $sql = "SELECT rf_shortname AS license_shortname, count(*) AS count, count(distinct pfile_ref.rf_pk) as unique
+    $sql = "SELECT rf_shortname AS license_shortname, count(*) AS count, count(distinct pfile_ref.pfile_fk) as unique
          FROM ( SELECT license_ref.rf_shortname, license_ref.rf_pk, license_file.fl_pk, license_file.agent_fk, license_f
              FROM license_file
              JOIN license_ref ON license_file.rf_fk = license_ref.rf_pk) AS pfile_ref
@@ -484,4 +484,4 @@ class LicenseDao extends Object
     return $this->getLicenseByCondition(" rf_pk=(SELECT rf_parent FROM license_map WHERE usage=$1 AND rf_fk=$2 AND rf_fk
             array(LicenseMap::CONCLUSION,$licenseId), $groupId);
   }
-}
\ No newline at end of file
+}
diff --git a/src/www/ui/ui-browse-license.php b/src/www/ui/ui-browse-license.php
index 612b344..8779121 100644
--- a/src/www/ui/ui-browse-license.php
+++ b/src/www/ui/ui-browse-license.php
@@ -643,7 +643,7 @@ class ui_browse_license extends FO_Plugin
       $count = 0;
       if (array_key_exists($licenseShortName, $scannerLics))
       {
-        $count = $scannerLics[$licenseShortName]['count'];
+        $count = $scannerLics[$licenseShortName]['unique'];
       }
       $editedCount = 0;
       if (array_key_exists($licenseShortName, $editedLics))

**Comment by yaobinshi** [comment]
--- a/src/buckets/ui/ui-list-bucket-files.php
+++ b/src/buckets/ui/ui-list-bucket-files.php
@@ -195,6 +195,7 @@ class list_bucket_files extends FO_Plugin
                  and bucket_fk=$bucket_pk
                  and bucketpool_fk=$bucketpool_pk
                  and bucket_pk=bucket_fk
+                 and nomosagent_fk=$nomosagent_pk
                  order by uploadtree.ufile_name
                  limit $limit offset $Offset";
           $fileresult = pg_query($PG_CONN, $sql);

**Comment by joshovi** [comment]
Hi Larry,
could you apply your changes to a branch and push it to the repo? Then we could see the changes in the pull request view, with context and syntax highlighting.
