### ISSUE TITLE
cp2foss is unable to create folders using -f switch

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#410]
Attempting to use cp2foss -f now throws some sort of sql query error.
This was working fine previously.

**Comment by pguttmann** [comment]
cp2foss -P 1 --username fossy --password fossy -f '/Software Repository/Sublime Text Editor' -q agent_nomos,agent_monk sublime-text_build-3059_amd64.deb

Fails with message ==>
Loading '/home/ubuntu/sublime-text_build-3059_amd64.deb'
<hr>File: /usr/local/lib/fossology/cp2foss.php, Line number: 184<br>ERROR:  column reference "parent_fk" is ambiguous
LINE 4:   WHERE parent_fk = '1' AND folder_name='Sublime Text Editor...
                ^<br> SELECT * FROM folder
  INNER JOIN foldercontents ON child_id = folder_pk
  AND foldercontents_mode = '1'
  WHERE parent_fk = '1' AND folder_name='Sublime Text Editor';<pre>#0  debugbacktrace() called at [/usr/local/share/fossology/lib/php/common-db.php:172]
#1  DBCheckResult(, SELECT * FROM folder
  INNER JOIN foldercontents ON child_id = folder_pk
  AND foldercontents_mode = '1'
  WHERE parent_fk = '1' AND folder_name='Sublime Text Editor';, /usr/local/lib/fossology/cp2foss.php, 184) called at [/usr/local/lib/fossology/cp2foss.php:184]
#2  GetFolder(Sublime Text Editor, 1) called at [/usr/local/lib/fossology/cp2foss.php:172]
#3  GetFolder(/Sublime Text Editor, 1) called at [/usr/local/lib/fossology/cp2foss.php:172]
#4  GetFolder(//Sublime Text Editor, 1) called at [/usr/local/lib/fossology/cp2foss.php:258]
#5  UploadOne(//Sublime Text Editor, /home/ubuntu/sublime-text_build-3059_amd64.deb, sublime-text_build-3059_amd64.deb, ) called at [/usr/local/lib/fossology/cp2foss.php:583]
#6  require(/usr/local/lib/fossology/cp2foss.php) called at [/usr/local/lib/fossology/fo_wrapper:71]
</pre><hr>

**Comment by pguttmann** [comment]
Using -v option the offending SQL appears to be -
SELECT * FROM folder
  INNER JOIN foldercontents ON child_id = folder_pk
  AND foldercontents_mode = '1'
  WHERE parent_fk = '1' AND folder_name='Sublime Text Editor';

**Comment by pguttmann** [comment]
OK - I fixed the SQL issue by changing the query to -
SELECT * FROM folder
INNER JOIN foldercontents ON child_id = folder_pk
AND foldercontents_mode = '1'
WHERE foldercontents.parent_fk = '1' AND folder_name='Sublime Text Editor';

This locks the parent_fk field to the foldercontents table and appears to avoid the ambiguity possible with the same named field in the folder table.

There is another issue though that I may need some help from Steffen with ;)
He added an extra argument - $groupId - into common-job.php functions :
1. Line  62 - JobAddUpload()
2. Line 106 - JobAddJob()

This breaks the two calls to those functions from cp2foss.php in lines 281 and 290

Presumably $groupId can be determined from $userId somehow ?

**Comment by pguttmann** [comment]
Steffen, please explain how I might workaround this $groupId issue and I'll take this back to resolve. Thanks in advance,
Paul...

**Comment by joshovi** [comment]
This should be fixed by the pull request [https://github.com/fossology/fossology/pull/407]. I have just merged it.

**Comment by pguttmann** [comment]
Thanks Johannes! This does appear to fix the folder creation issue. After extending my test to use -q and nomos and monk agents I see another/separate issue with fossjobs though. I'll open a separate ticket for that issue and see if I'm able to isolate the cause ;)
