### ISSUE TITLE
A fresh install requires decision for alter DB (clearing_decision.clearing_pk)

### ISSUE THREAD

**Issue by bufferoverflow** [fossology/fossology#415]
I'm playing around with Docker and faced the following issue:
```
*** update the database and license_ref table ***
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
fresh install, import licenseref.sql 
Migrate data from 2.1 to 2.2 in /usr/local/lib/fossology
Missing column clearing_decision.clearing_pk, you should update to version 2.6.2 before migration
Enter 'i' within 20 seconds to ignore this warning and run the risk of losing clearing decisions: i
```
I think, as long as it is a fresh install, no user interaction shall be required.

here is my installation procedure:
https://github.com/bufferoverflow/fossology/blob/docker/Dockerfile

cheers
-roger

**Comment by abirw** [comment]
Hi! I am currently trying to integrate fossology with out gitlab ci pipeline..

I have a fossology database recreated from a schema (that was created as described here: http://archive15.fossology.org/projects/fossology/wiki/Database) being hosted in a docker container. I then run the fossology image in another docker container using environment variables as described in the wiki. It connects to the database and then I get the exact issue above. If I enter 'i' I get these errors:
`Adding link to real parent in uploadtree table
Rename license (using /usr/local/lib/fossology) for SPDX validity
Transform bulk licenses into bulk license sets...PHP Warning:  pg_query(): Query failed: ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 79
[2019-07-16 13:35:49] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  column "rf_fk" does not exist LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...                                 ^ HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. [] []
PHP Fatal error:  Uncaught Fossology\Lib\Exception: error executing: 
  INSERT INTO license_set_bulk (lrb_fk, rf_fk, removing)
  SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bulk

ERROR:  column "rf_fk" does not exist
LINE 3:   SELECT lrb_pk lrb_fk, rf_fk, removing FROM license_ref_bul...
                                ^
HINT:  There is a column named "rf_fk" in table "license_set_bulk", but it cannot be referenced from this part of the query. in /usr/local/share/fossology/lib/php/Db/DbManager.php:144
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(203): Fossology\Lib\Db\DbManager->checkResult(false, '\n  INSERT INTO ...')
#1 /usr/local/lib/fossology/dbmigrate_bulk_license.php(29): Fossology\Lib\Db\DbManager->queryOnce('\n  INSERT INTO ...')
#2 /usr/local/lib/fossology/fossinit.php(318): require_once('/usr/local/lib/...')
#3 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 144`

Do you have any suggestions as to what I can do about this?
