### ISSUE TITLE
Missing commercial licenses found in open source

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#416]
These 3 commercial licenses should be added to nomos:

/*
* Broadcom USB remote download definitions
*
* Copyright (C) 2014, Broadcom Corporation
* All Rights Reserved.
*
* This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
* the contents of this file may not be disclosed to third parties, copied
* or duplicated in any form, in whole or in part, without the prior
* written permission of Broadcom Corporation.
*
* $Id: usbrdl.h 412875 2013-07-16 23:54:25Z $
*/

**Internal to HP, the above can be found in file: https://fossology.usa.hp.com/?mod=view-license&pfile=39535130&upload=3683&item=866210840**

/*
* INTEL CONFIDENTIAL
*
* Copyright (C) 2010 - 2013 Intel Corporation.
* All Rights Reserved.
*
* The source code contained or described herein and all documents
* related to the source code ("Material") are owned by Intel Corporation
* or licensors. Title to the Material remains with Intel
* Corporation or its licensors. The Material contains trade
* secrets and proprietary and confidential information of Intel or its
* licensors. The Material is protected by worldwide copyright
* and trade secret laws and treaty provisions. No part of the Material may
* be used, copied, reproduced, modified, published, uploaded, posted,
* transmitted, distributed, or disclosed in any way without Intel's prior
* express written permission.
*
* No License under any patent, copyright, trade secret or other intellectual
* property right is granted to or conferred upon you by disclosure or
* delivery of the Materials, either expressly, by implication, inducement,
* estoppel or otherwise. Any license under such intellectual property rights
* must be express and approved by Intel in writing.
*/

**Internal to HP you can find many examples of this at: https://fossology.usa.hp.com/?mod=license_list_files&napk=198&item=866197683&lic=UnclassifiedLicense**

/* -----------------------------------------------------------------------------------------------------------
Software License for The Fraunhofer FDK AAC Codec Library for Android

© Copyright 1995 - 2013 Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.
All rights reserved.

1. INTRODUCTION
The Fraunhofer FDK AAC Codec Library for Android ("FDK AAC Codec") is software that implements
the MPEG Advanced Audio Coding ("AAC") encoding and decoding scheme for digital audio.
This FDK AAC Codec software is intended to be used on a wide variety of Android devices.

**Many examples of the above, including the complete license can be found internal to HP at: https://fossology.usa.hp.com/?mod=list_bucket_files&bapk=196&item=866176218&bpk=147&bp=14&napk=198**

**Comment by bobgob** [comment]
The Clover license also needs to be added  http://www.fossology.org/attachments/4599/clover.license

**Comment by yaobinshi** [comment]
for this 3 cases, will return COMMERCIAL,UnclassifiedLicense
not get rid of UnclassifiedLicense, make sense?

**Comment by bobgob** [comment]
Commit 3483f13 generates a compile warning that should be fixed:
```
parse.c: In function ‘parseLicenses’:
parse.c:6276:3: warning: "/*" within comment [-Wcomment]
```

I like keeping these as COMMERCIAL since that makes it easy to find commercial licenses (without buckets) but why not also use the license name instead of "UnclassifiedLicense"?

**Comment by yaobinshi** [comment]
>I like keeping these as COMMERCIAL since that makes it easy to find commercial licenses (without buckets) but why not also use the license name instead of "UnclassifiedLicense"?
in the old logic, COMMERCIAL license has a lower interest than UnclassifiedLicense

**Comment by yaobinshi** [comment]
>parse.c: In function ‘parseLicenses’:
parse.c:6276:3: warning: "/*" within comment [-Wcomment]
will fix soon

**Comment by bobgob** [comment]
Rereading I see that I wasn't very clear about the license name.  What I meant was why not return the license name followed by COMMERCIAL.  For example, Broadcom-COMMERCIAL.  This gives the user a little more information.

Also, commercial2.txt contains the following line which looks like a mistake:
```
%STR% "source code =ANY= of =FEW= (files?|materials?) =ANY= disclosed? =ANY= without =FEW= prior =FEW= written permission"
```

**Comment by yaobinshi** [comment]
our rules always is general, not for special cases, so do not think adding Broadcom prefix is a good idea, for me, just know it is a commercial license is enough, if that license is really common, will not just return COMMERCIAL

**Comment by bobgob** [comment]
I think we should continue with our current model rather than start something new (at least without a good reason).  Today we have:

```
SCO(commercial)
QT(Commercial)
Genivia(Commercial)
IoSoft(COMMERCIAL)
AndroidSDK-Commercial
```
So for the sake of consistency I think we should do them all the same way.  So I propose:

```
SCO(Commercial)
QT(Commercial)
Genivia(Commercial)
IoSoft(Commercial)
AndroidSDK-Commercial
Broadcom(Commercial)
Intel(Commercial)
AndroidFraunhofer(Commercial)
```
