### ISSUE TITLE
license and bucket filters in search

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#42]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 483, http://www.fossology.org/issues/483
Original Date: 2012/01/20
Original Assignee: Bob Gobeille

---

add license and bucket filters in search.   This allows the user to get a linear list of all the files in a tree with a certain license (or bucket).  Then they can click through to view each one.  Combined with tags, for example a tag that says what files need review, this becomes a very powerful feature.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/01/20 23:14:38 +0000

---

Will try to fit this in to 2.0.1, if time allows.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:01 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
last update "Original Date: 2012/10/08 18:35:01 +0000", closing because of missing pickup
