### ISSUE TITLE
fo-postinstall errors on missing PROJECTGROUP

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#421]
The bulk decider commit ( 8e0cb87)  requires PROJECTGROUP to be defined under DIRECTORIES in fossology.conf.  I just did a source update and fo-postinstall gives me an error:

```
PHP Notice:  Undefined index: PROJECTGROUP in /usr/local/lib/fossology/fossinit.php on line 106
PHP Stack trace:
PHP   1. {main}() /usr/local/lib/fossology/fossinit.php:0
```

Adding PROJECT=fossology to fossology.conf fixes the problem but fo-postinstall shouldn't error out.  We need to update fossology.conf or apply a default to PROJECTGROUP

**Comment by steffen-weber** [comment]
With commit 686e474f7426e55a8e4e19568c935da2ab3287b1, fo-postinstall set a default value to PROJECTGROUP.

**Comment by bobgob** [comment]
a lot of users use lts distros and may not support the local -n switch which was only introduced in bash 4.3.  I think you should remove the -n switch. 

```
./fo-postinstall: line 84: local: -n: invalid option
local: usage: local [option] name[=value] ...
```

**Comment by steffen-weber** [comment]
Commit 3de17a38dba9c5dce2347fcd8a6dd6e0566a1ca5 removed the -n switch.
