### ISSUE TITLE
copyright scanner cannot extract email addresses from domains using new TLDs

### ISSUE THREAD

**Issue by armijnhemel** [fossology/fossology#422]
The regular expression for extracting e-mail addresses is too limited as it restricts the last part of a domain name to a maximum of 4 characters:

[a-z]{1,4}

There are new TLDs that have more characters and that currently are truncated.

**Comment by pguttmann** [comment]
There is some discussion and useful (links) resources on this topic at - http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

**Comment by maximilianhuber** [comment]
One maybe has to test, wether a simple increasing the maximum length to something around `12` leads to false-positives. I would support this, since this would cover nearly all new TLD's, see [list of all TLD's as TXT](https://data.iana.org/TLD/tlds-alpha-by-domain.txt).

**Comment by maximilianhuber** [comment]
There are only 46 TLD's which are longer then 12 chars:
```
13 CONSTRUCTION
13 SCHOLARSHIPS
13 VERSICHERUNG
13 XN--3E0B707E
13 XN--80ADXHKS
13 XN--80ASEHDB
13 XN--MGB9AWBF
13 XN--MGBAB2BD
13 XN--MGBPL2FH
13 XN--MGBT3DHD
13 XN--MK1BU44C
13 XN--NGBC5AZD
13 XN--NGBE9E0A
13 XN--OGBPF8FL
13 XN--QCKA1PMC
14 INTERNATIONAL
14 SPREADBETTING
14 XN--ECKVDTC9D
14 XN--FPCRJ9C3D
14 XN--FZC2C9E2C
14 XN--YFRO4I67O
14 XN--YGBI2AMMX
15 CANCERRESEARCH
15 XN--6QQ986B3XL
15 XN--B4W605FERD
15 XN--FIQ228C5HS
15 XN--JLQ61U9W7B
15 XN--MGBA3A3EJT
15 XN--MGBAAM7A8H
15 XN--MGBAYH7GPA
15 XN--MGBBH1A71E
15 XN--MGBX4CD0AB
16 SANDVIKCOROMANT
16 XN--I1B6B1A6A2E
16 XN--KCRX77D1X4A
16 XN--LGBBAT1AD8J
16 XN--MGBA3A4F16A
16 XN--MGBC0A9AZCG
16 XN--NQV7FS00EMA
17 XN--XKC2AL3HYE2A
18 XN--MGBERP4A5D4AR
18 XN--XKC2DL3A5EE0H
19 TRAVELERSINSURANCE
23 XN--CLCHC0EA0B2G2A9GCD
24 XN--VERMGENSBERATER-CTB
25 XN--VERMGENSBERATUNG-PWB
```
#### count of TLD's by lengths
length | occurrences
------ | -----------
3      | 247        
4      | 165        
5      | 160        
6      | 128        
7      | 115        
8      | 103        
9      |  63        
10     |  43        
11     |  49        
12     |  51        
13     |  15        
14     |   7        
15     |  10        
16     |   7        
17     |   1        
18     |   2        
19     |   1        
23     |   1        
24     |   1        
25     |   1
