### ISSUE TITLE
cp2foss create two adj2nest jobs on showjob page

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#424]
When you run cp2foss like this:
cp2foss --username fossy --password fossy -q all debian-7.5.0-i386-CD-1.iso
Then go to the showjob page, you will find two adj2nest jobs created:
![image](https://cloud.githubusercontent.com/assets/5294029/7465930/951bf7e4-f30c-11e4-870e-d3d0ba04290f.png)

**Comment by yaobinshi** [comment]
have fixed in days ago, please help to verify it. thanks.

**Comment by steffen-weber** [comment]
ran cp2foss command like the one above and got only one adj2nest job
