### ISSUE TITLE
Compile error on Rhel 6 system

### ISSUE THREAD

**Issue by larainema** [fossology/fossology#429]
I catch one issue when compile latest code on rhel6, if i missing some dependencies? I have install boost-devel package.

g++ -c libfossAgentDatabaseHandler.cc -DFOSSDB_CONF='"/usr/local/etc/fossology/Db.conf"' -DFOSSGROUP='"fossy"' -DDEFAULT_SETUP='"/usr/local/etc/fossology"' -fPIC -std=c++0x -I../../../src/lib/cpp -I../../../src/lib/c -I/usr/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -I../../../src/lib/c -Wextra -Weffc++ -o libfossAgentDatabaseHandler.o
In file included from libfossdbmanagerclass.hpp:31,
                 from libfossAgentDatabaseHandler.cc:18:
libfossdbQueryResult.hpp:47: error: â€˜fo::QueryResult::QueryResult(fo::QueryResult&&)â€™ cannot be defaulted
make: *** [libfossAgentDatabaseHandler.o] Error 1

**Comment by fogninid** [comment]
I tested commit d995f67 on debian6. You should have the same package versions on rhel6.
