### ISSUE TITLE
scheduler unable to kill a job that hasn't started

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#43]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 543, http://www.fossology.org/issues/543
Original Date: 2012/01/25
Original Assignee: Alex Norton

---

In fo_cli:

kill 831 this job is no longer needed
Command received
Invalid kill command: job 0 does not exist
status
scheduler:11981 revision:(null) daemon:0 jobs:1 log:/var/log/fossology/fossology.log port:5555 verbose:1

There needs to be a way to cancel a job that hasn't started.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/01/26 23:27:00 +0000

---

re-prioritizing

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/06/07 20:53:59 +0000

---

Fixed with svn 5913.

Users can kill jobs that have not been scheduled yet.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/08/23 20:10:38 +0000

---

this should be included in 2.1.0 after it is verified.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:05 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
works actually on current master (48b72a4 )
