### ISSUE TITLE
Add text or comment to license in "Change concluded License" fails.

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#431]
Tested on 2748f3b
On the Change concluded License page, when I "click to edit" the Text field, I get a popup with lots of html.  In this case I entered "hello" in the text field.  See attached screen shot.

![textfield](https://cloud.githubusercontent.com/assets/8060442/7599513/e2e99888-f8bf-11e4-86ee-ab4cd5cb028b.jpg)
The same thing happens when I enter text into the Comment field.

**Comment by steffen-weber** [comment]
Please re-test if error still exists after @fogninid 's commit.

**Comment by maximilianhuber** [comment]
This seems to be fixed. Closing it now.
