### ISSUE TITLE
star main license toggle fail

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#436]
Tested with 0e562cf (master on May 19,2015) using Chrome 42.0.2311 and Firefox 38.0.1 on OSX

On "Change concluded License" the star toggle, to indicate the main license doesn't toggle. Clicking on the star the first time will set it, but clicking on it again does not turn it off.

**Comment by yaobinshi** [comment]
both on and off always work when summit that page.

**Comment by bobgob** [comment]
Not for me.

**Comment by yaobinshi** [comment]
bob, 
both on and off always work when summit that page.
I mean on 'Change concluded License ' page,
for one file, has license GPL-2.0,
1. add another license, e.g. AFL-1.2 through 'user decision'
2. 'Clearing decision type' choose 'Identified'
3. click on 'submit'
4. back to 'License Browser ' page, for this file, 'Edited Results' is 'AFL-3.0, GPL-2.0'

no matter if star's action of the entries(AFL-3.0, GPL-2.0) is on or off of

**Comment by steffen-weber** [comment]
The star indicates that the license is a main license of the upload.
If you found some files with a license, you might want to declare it as main license.
On the other hand, one cannot conclude from a single file that one license is no main license for the upload. Hence, removing a main license is only provide at the Browse page.
Therefore, these stars are not intended to be a two-way toggle. If deleting from main license list also on View page is desired, we should not forget a confirm box before removing.
Anyway, a documentation for the usage of main licenses is required.
