### ISSUE TITLE
Agents need to give more informative error messages in the logs

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#44]
---

Author Name: **Mark Donohoe** 
Original Redmine Issue: 549, http://www.fossology.org/issues/549
Original Date: 2012/01/25
Original Assignee: Mary Laser

---

The agent logs do not contain enough information to determine what went wrong.  Using an error code like 3 or agent code 12 does not indicate what the real error was.  Saying only in the log that the agent failed is also not helpful when trying to figure out what the problem is or how it might be fixed.

The agents should give informative messages like 'file xxx not found', no permission to write to xxxx, can't schedule scheduler, go db error xxxx, etc...

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/02/03 16:34:55 +0000

---

Agreed.  Especially useful when trying to determine failures.  Bob has been preaching this every chance he gets.  Since this enhancement affects all agents, we'll define/create an all-inclusive task to improve error reporting post-2.0.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:02 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
(closing because of no updates, also tickets is not specific enough)
