### ISSUE TITLE
Ubuntu 14.10 init sequence order bug

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#441]
From Roger at: http://www.fossology.org/boards/3/topics/603

Install fossology On Ubuntu 14.10, It does not auto create init link at rcX.d.
(Example : S20fossology -> ../init.d/fossology on Ubuntu 12.04)
So I create it manual, but use same sequence with postgresql.
After change the init sequence later than postgresql, fossology will auto execute at system boot time.

**Comment by mcjaeger** [comment]
Vincent, please update the Assignment if necessary.

**Comment by mcjaeger** [comment]
(from discussion) it should work now for an umber of packages there were created in the past. open point is: it would be good to have a general check if the current location for creating the init is appropriate.

**Comment by mcjaeger** [comment]
it is actually still there also for other distros. Good solution is missing, because adding postgresql as dependency in the init chain for fossology would be inconsistent with deployments that use an "external" DB server.
