### ISSUE TITLE
Unable to render UI after install from latest source on Ubuntu 12.04LTS

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#445]
Building/installing from source - "commit b80b85846560fdc832a8ae7a4d2ae5f6bfd81c85" fails to render the /repo/ login page as expected.
Apache error log contains :
[Wed May 27 15:21:30 2015] [error] [client 10.24.140.19] PHP Warning:  pg_prepare(): Query failed: ERROR:  relation "users" does not exist\nLINE 1: SELECT users.*,group_name FROM users LEFT JOIN groups ON gro...\n                                       ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 62
[Wed May 27 15:21:30 2015] [error] [client 10.24.140.19] [2015-05-27 15:21:30] default.CRITICAL: ERROR:  relation "users" does not exist LINE 1: SELECT users.*,group_name FROM users LEFT JOIN groups ON gro...                                        ^ [] []
[Wed May 27 15:21:30 2015] [error] [client 10.24.140.19] PHP Fatal error:  Uncaught exception 'Fossology\\Lib\\Exception' with message 'error executing: SELECT users.*,group_name FROM users LEFT JOIN groups ON group_fk=group_pk WHERE user_name=$1 -- getUserAndDefaultGroupByUserName\n\nERROR:  relation "users" does not exist\nLINE 1: SELECT users.*,group_name FROM users LEFT JOIN groups ON gro...\n                                       ^' in /usr/local/share/fossology/lib/php/Db/DbManager.php:120\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Db/ModernDbManager.php(51): Fossology\\Lib\\Db\\DbManager->checkResult(false, 'SELECT users.*,...')\n#1 /usr/local/share/fossology/lib/php/Db/DbManager.php(139): Fossology\\Lib\\Db\\ModernDbManager->prepare('getUserAndDefau...', 'SELECT users.*,...')\n#2 /usr/local/share/fossology/lib/php/Dao/UserDao.php(267): Fossology\\Lib\\Db\\DbManager->getSingleRow('SELECT users.*,...', Array, 'getUserAndDefau...')\n#3 /usr/local/share/fossology/www/ui/core-auth.php(158): Fossology\\Lib\\Dao\\UserDao->getUserAndDefaultGroupByUserName('Default User')\n#4 /usr/local/share/foss in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 120

**Comment by bobgob** [comment]
I'm not able to reproduce this failure.  Did you run utils/fo-installdeps and install/fo-postinstall ?

**Comment by pguttmann** [comment]
Yes. I have automated install scripts that just git clone the source and run all required scripts ;) They worked fine last week ;)
fwiw I also see fo-postinstall errors this week :P I opened another case for that...

**Comment by bobgob** [comment]
We have automated tests inside the HP firewall too.  We really need to get our testing all together and running on servers that we can all access.

**Comment by steffen-weber** [comment]
I guess, the UI error after clean install has the same reason as #446.

**Comment by pguttmann** [comment]
Yep. Thanks for the fix(es) ! Seems to be working again as of commit 6dcf252309674ea4c81451e0eb9bbb850006844e
