### ISSUE TITLE
fo-postinstall script is failing in current code base b80b858465

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#446]
*** update the database and license_ref table ***
PHP Notice:  Undefined index: Release in /usr/local/lib/fossology/fossinit.php on line 142
Old release was 
PHP Warning:  pg_query(): Query failed: ERROR:  relation "uploadtree_a" does not exist
LINE 2:     CREATE TABLE uploadtree_b AS (SELECT * FROM uploadtree_a...
                                                        ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 81
[2015-05-27 15:49:24] /usr/local/share/fossology/lib/php/libschema.php.CRITICAL: ERROR:  relation "uploadtree_a" does not exist LINE 2:     CREATE TABLE uploadtree_b AS (SELECT * FROM uploadtree_a...                                                         ^ [] []
PHP Fatal error:  Uncaught exception 'Fossology\Lib\Exception' with message 'error executing: begin; 
    CREATE TABLE uploadtree_b AS (SELECT * FROM uploadtree_a);
    DROP TABLE uploadtree_a;
    CREATE TABLE uploadtree_a () INHERITS (uploadtree);
    ALTER TABLE uploadtree_a ADD CONSTRAINT uploadtree_a_pkey PRIMARY KEY (uploadtree_pk);
    INSERT INTO uploadtree_a SELECT * FROM uploadtree_b;
    DROP TABLE uploadtree_b;
    COMMIT;

ERROR:  relation "uploadtree_a" does not exist
LINE 2:     CREATE TABLE uploadtree_b AS (SELECT * FROM uploadtree_a...
                                                        ^' in /usr/local/share/fossology/lib/php/Db/DbManager.php:120
Stack trace:
#0 /usr/local/share/fossology/lib/php/Db/DbManager.php(160): Fossology\Lib\Db\DbManager->checkResult(false, 'begin; ?    CRE...')
#1 /usr/local/lib/fossology/fossinit.php(155): Fossology\Lib\Db\DbManager->queryOnce('begin; ?    CRE...', '/usr/local/lib/...')
#2 {main}
  thrown in /usr/local/share/fossology/lib/php/Db/DbManager.php on line 120
Database connectivity is good.

**Comment by steffen-weber** [comment]
With commits 56f20ccfe72166a790a07cebb7382adfa5fc722b and 6dcf252309674ea4c81451e0eb9bbb850006844e, both clean install and migration should work fine again.

**Comment by pguttmann** [comment]
Yep. Thanks for the fix(es) - Confirmed that fo-postinstall is running as expected once again at - commit 6dcf252309674ea4c81451e0eb9bbb850006844e
