### ISSUE TITLE
please make sure agents have the correct VERSION file(copyright, monk, etc)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#449]
ERROR agent.c.821: agent copyright has been invalidated by version information

src/scheduler/agent/agent.c

**Comment by yaobinshi** [comment]
the scheduler is trying to read the configuration from ~/mods-enabled/agent/VERSION

**Comment by fogninid** [comment]
I don't understand what mean. 
$DESTDIR/mods-enabled/agent/VERSION is installed by make install and it gets its parameters from git.
If your running scheduler has a version older than the agent that you installed you will get that message: restart the scheduler before running newer agent.

**Comment by yaobinshi** [comment]
sorry, it  is just the test problem. 
src/testing/db/create_test_database.php copy the source files  to $DESTDIR/mods-enabled/

**Comment by steffen-weber** [comment]
with 4cf8fc45b68f99fa56675152b0e1c14854bdfeb3
``make -C src/scheduler/agent_tests/Functional test``
was successful again
