### ISSUE TITLE
fixing adj2nest work around

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#45]
---

Author Name: **Alex Norton** 
Original Redmine Issue: 597, http://www.fossology.org/issues/597
Original Date: 2012/01/27
Original Assignee: Alex Norton

---

Some agents don't update the number of item processed quickly and for large uploads will go a very long time without changing this number. This results in the scheduler choosing to kill the agent because it believes that the agent has entered an infinite loop. There should be a way for an agent to turn off this feature when the scheduler deals with it or for the agent to correctly be able to update the number of items processed.

Adj2nest is currently the only agent that is having this problem and is currently using a dummy fo_scheduler_heart(1) to keep the scheduler from killing it when it is processing large distributions. This work around it not ideal and should be replace with a more long term solution.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/02/08 22:25:37 +0000

---

Agents should now be able to call fo_scheduler_heart(0) to inform the scheduler that they are still alive. This means that agents don't need to lie about processing items to convince the scheduler that they are still running. adj2nest should no longer need the work around described.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:06 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by steffen-weber** [comment]
this has already fix in 587c2e3903e837fc9150c11d7e4ae7197ada28d1
