### ISSUE TITLE
fail to create new folder when run cp2foss on a fresh install fossology(not event visit any GUI)

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#452]
the reason is because,'Software Repository' is added into table folder when visit GUI,
before the root folder is added into table folder, will fail to add new child folder.

admin-folder-create.php:: Create($ParentId, $NewFolder, $Desc)
no ParentId before 'Software Repository' is not populated.

**Comment by pguttmann** [comment]
Is this something that fo-postinstall script may be tweaked to address ?

**Comment by yaobinshi** [comment]
sure, fo-postinstall can do it.

**Comment by yaobinshi** [comment]
fixed in https://github.com/fossology/fossology/commit/a317f99000fd9d4b435d93999865c1a3bcc36df7
