### ISSUE TITLE
Concluded license count calculated wrongly

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#453]
It seems that Concluded License Count is doubled in a table in License Browser View,
see a snapshot from the table below. 
Master trunk, commit: [#2c45507]

![concluded-license-count](https://cloud.githubusercontent.com/assets/9692647/8003004/2accf1a8-0b7c-11e5-8fda-a1c20bd09d5b.png)

**Comment by steffen-weber** [comment]
Seems to work as intended. You concluded that more file has Apache-2.0 license than the scanner found. Can you provide a minimal set up where the count is wrong?

**Comment by rlintu** [comment]
Here is a snapshot from one subfolder.

![concluded-license-count-2](https://cloud.githubusercontent.com/assets/9692647/8004275/197da306-0b87-11e5-836d-2b7308ccca0f.png)

**Comment by rlintu** [comment]
This seems to relate to the case when a licenses is set in a folder level using [Edit] option.
I've been able to demonstrate the situation where Concluded license count is doubled
when license is set for files in a folder.
