### ISSUE TITLE
Filter selection shown only in Clear window when browsing folders

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#454]
When a user selects a filter in License Browser view, it is shown as follows
![filter-problem-1](https://cloud.githubusercontent.com/assets/9692647/8004506/f70a3e7c-0b88-11e5-8642-25491922a269.png)

Then if a user goes to a subfolder, the filter is still active but it is not shown in pop-up
Filter Selection but only in Filter clear window as shown below
![filter-problem](https://cloud.githubusercontent.com/assets/9692647/8004551/3c5bd71a-0b89-11e5-8e6c-210a47f5dc72.png)

This is confusing and the user may not notice that the filter selection is still in use.
Filter selection should be shown in the same place where it was selected in the first place.

**Comment by bobgob** [comment]
I agree.  I think I made this suggestion before the code was committed but then forgot about it and didn't file an issue.  My bad.  Thanks @rlintu
