### ISSUE TITLE
wget -qO - --post-file ./testfile http://locahost/repo/?mod=agent_nomos_once  get nothing

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#455]
wget -qO - --post-file ./testfile http://locahost/repo/?mod=agent_copyright_once also get nothing

should we still support this function ?

**Comment by mcjaeger** [comment]
I think we have closed the one shot nomos, so that is supposed to return nothing, shall the one shot nomos be activated again? - please reopen.
