### ISSUE TITLE
Please "enhance" the ECC scanner capabilities.

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#460]
Currently the ECC scanner strings are embedded in the source code. Please investigate how to dynamically load these from an external/config file or a database table.

**Comment by mcjaeger** [comment]
It think something is in the works to this regard. Not easy, because once ECC is changed, it makes also sense to apply the same change for the copyright regular expressions.

**Comment by pguttmann** [comment]
Perhaps some sort of "simplified" version control along the lines of sha1/md5 for the "collection" of regexes used for either copyright or ECC scans could also be used to track changes in the regexes scanned for ?
