### ISSUE TITLE
wget_agent can modify files

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#465]
wget_agent uses wget -k which can change the file content by modifying links.
For example, see http://www.fossology.org/boards/3/topics/645?r=681

The -k should be removed.

**Comment by pguttmann** [comment]
According to the source code (line 69 and 122 through 126) https://github.com/fossology/fossology/blob/master/src/wget_agent/agent/main.c
The -k option should be followed by an upload key value ;)

**Comment by bobgob** [comment]
The problem isn't the wget_agent -k option.  The problem is the wget -k option.
```
char WgetArgs[]="--no-check-certificate --progress=dot -rc -np -e robots=off -k";
```
