### ISSUE TITLE
interface.c WARNINGS while interacting with Admin Scheduler UI

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#47]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 627, http://www.fossology.org/issues/627
Original Date: 2012/01/30
Original Assignee: Dong Ma

---

2012-01-30 14:22:25 scheduler [12164] :: WARNING interface.c.126: INTERFACE: invalid command:

maryl> norton: do you know why I'm getting these warnings?...
<maryl> 2012-01-30 11:43:55 scheduler [9804] :: WARNING interface.c.126: INTERFACE: invalid command:
<maryl> norton: They are generated while using the Scheduler Administration UI
<norton> someone is sending the scheduler whitespace as a command
<norton> if you turn the verobse flag for the interface file on, you will get to see exactly how much white space was sent

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/02/17 18:53:15 +0000

---

This is not a scheduler issue.  it should be fixed n the UI.

<norton> maryl: http://www.fossology.org/issues/1095 and http://www.fossology.org/issues/627 should not be fixed in the scheduler, the ui is sending an extra '\n' when a message is sent when it shouldn't be

<norton> the scheduler should be reporting an error since what was sent wasn't a valid command

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:03 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
on `Version: [3.4.0], Branch: [master], Commit: [#6ad6a1]` executed all operations in the scheduler interface with the logs open:
* not a single message in `/var/log/apache2/error.log`
* not a single message (at least resulting from the scheulder bla bla, but from the missing mail config) in `/var/log/fossology/fossology.log`
