### ISSUE TITLE
SPDX XML Parsing Error

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#472]
#8093393
Opening SPDX2 file in firefox gives the following error.  Have these files been verified with the SPDX verifier tool?
```
XML Parsing Error: not well-formed
Location: file:///Users/bobg/Downloads/SPDX2_oxwall-1.5.1.zip_1435260108.rdf
Line Number 3740, Column 1:
```
![screen shot 2015-06-25 at 1 27 27 pm](https://cloud.githubusercontent.com/assets/8060442/8363737/42aad5a2-1b3e-11e5-85e5-38a495c9b20b.jpg)

**Comment by steffen-weber** [comment]
It looks like encoding is wrong which is not covered by tests. Can you try again with 72def4a84c45f3dc9d64fab608408242ad69461a?

**Comment by bobgob** [comment]
Tested with #abb949f

![screen shot 2015-07-24 at 2 49 53 pm](https://cloud.githubusercontent.com/assets/8060442/8884349/5af37812-3213-11e5-848f-c3a626bb8ae8.jpg)

**Comment by bobgob** [comment]
Ok, it doesn't work with a jar or probably other binary files.  That should be fixed, but it DOES work for for "real" uploads.  So I'm closing.

**Comment by bobgob** [comment]
Reopening.  Test with any upload that has binary files and you get garbage like in my screenshot above.  For example, an upload that contains image files.

**Comment by bobgob** [comment]
Test case.  Upload from URL:
http://ftp.osuosl.org/pub/mythtv/mythplugins-0.26.1.tar.bz2
then generate spdx

**Comment by steffen-weber** [comment]
I am not able to reproduce the error for mythplugins-0.26.1.tar.bz2, neither without any scanner nor with copyright/nomos/monk/ninka. Maybe commit 5f64f8b73ad0cfa10c1d963020e6e5a44c09694c helps.

**Comment by bobgob** [comment]
Tested good.  Closing
