### ISSUE TITLE
scheduler should test for running agents before killing itself

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#48]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 681, http://www.fossology.org/issues/681
Original Date: 2012/02/01
Original Assignee: Alex Norton

---

Killing the scheduler kills all the running agents.  I think we need to add a failsafe such as:

1) if there are running agents, the scheduler needs to tell the user and not do the kill.  It should also tell the user to use the -f (see #2 below) if the really want to force the kill.

2) add a new switch, like -f to force the scheduler to die (the current behavior).

3) add a new option to tell the scheduler to not schedule any new jobs and exit when the current ones are done.  That is, just finish running the current jobs, email the user who requested this option, then exit.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/02/01 16:34:48 +0000

---

/etc/init.d/fossology stop
should do  a graceful shutdown.  That is, it should finish the currently running jobs, email the user that it is shutting down, then shutdown.  It should also give the user a message that if they want an immediate shutdown to do an /etc/init.d/fossology kill

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/06/07 20:52:34 +0000

---

This is fixed with svn 

Changes the "stop" command from the use interface to wait till all currently executing agents have finished running before exiting the scheduler. Also added a new command: "die" that will cause the scheduler to kill all currently running agents then exit.

Currently the GUI uses the "stop" command and does not offer the "die" command to the users.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/06/14 22:51:02 +0000

---

Please update the test for this issue http://www.fossology.org/projects/fossology/wiki/Scheduler_Test_Cases#Scheduler-StartStop

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/06/18 20:54:51 +0000

---

added a test case for this. It can be found under src/scheduler/agent_tests/Functional/scheduler_testStop.php

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:04 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by bufferoverflow** [comment]
imported data with status resolved
