### ISSUE TITLE
X-Diff license analysis appears to be "broken".

### ISSUE THREAD

**Issue by pguttmann** [fossology/fossology#486]
The XML Diff tool at http://pages.cs.wisc.edu/~yuanwang/xdiff.html and downloadable from - http://pages.cs.wisc.edu/~yuanwang/off_research/xdiff-c-0.9.6.tar.gz appears to highlight a couple of "opportunities" -
1. Nomos is reporting this as BSD 2 clause. Unfortunately, the actual license text contains a 3rd clause which contains strong copyleft language : " 3. Redistributions in any form must be accompanied by information on how to obtain complete source code for the X-Diff software and any accompanying software that uses the X-Diff software."
2. Monk doesn't appear to identify any associated license(s) for any of the 22 files included.

**Comment by mcjaeger** [comment]
I think it is Ok, because the thrid clause is not the BSD-3-Clause reference text:
here:
```
  * 3. Redistributions in any form must be accompanied by information on
  * how to obtain complete source code for the X-Diff software and any
  * accompanying software that uses the X-Diff software.  The source code
  * must either be included in the distribution or be available for no
  * more than the cost of distribution plus a nominal fee, and must be
  * freely redistributable under reasonable conditions.  For an executable
  * file, complete source code means the source code for all modules it
  * contains.  It does not include source code for modules or files that
  * typically accompany the major components of the operating system on
  * which the executable file runs.
```

original BSD-3-Clause (from Fossology)
```
Neither the name of {{the ORGANIZATION nor the names of its contributors}} may be used to endorse or promote products derived from this software without specific prior written permission.
```

So, it appears Ok for me that Nomos sees only 2 of the 3 clauses and Monk does not see a relevant match here.

Close?

**Comment by mcjaeger** [comment]
it seems to be OK now:

![image](https://user-images.githubusercontent.com/3418977/53015371-35b8b600-344b-11e9-816b-33c79b308474.png)
