### ISSUE TITLE
SPDX needs tag version

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#488]
Currently the SPDX output is only in rdf format.  

According to Kate:
"UNO's tools generate tag value format,  as does Windriver, which is much friendlier for the developer crowd.    Goal is able to post-process and transform/extract - which is easier with grep/sed/awk, etc.  RDF tends to be the favorite of the tool creator crowd. "

**Comment by steffen-weber** [comment]
There are two possible solutions:
* writing an SPDXtag agent similar to the SPDXrdf agent, i.e., provide twig template for tag output (and maybe minor changes in the php)
* using SPDXtools to run the SPDXtag after the SPDXrdf, i.e., the new agent depends on the existing one and requires Java, but converting into Html or Spreadsheet will be also provided

**Comment by maximilianhuber** [comment]
Same as #548
