### ISSUE TITLE
License removed from clearing result is still shown in SPDX list

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#489]
If a scanner has found a license that is irrelevant, then a user may remove it
from the clearing result in Change concluded License view. As a result the license
is not shown in License Browser view in Edited results. 
However, the removed license is still shown in SPDX listing as 
LicenseInfoInFile. That should not be the case. 

As a practical example nomos identifies MPL license from following
text:
`Removed the solaris-specific atomic code, due to licence
concerns (it was MPL 1.0, and the author could not be contacted)`

Obviously MPL should be removed from concluded license but SPDX shows
this as 
`LicenseInfoInFile: LicenseRef-MPL`

It is good that FOSSology shows all the detected licenses and decisions related to them
but SPDX should only show valid licenses.

**Comment by maximilianhuber** [comment]
Hi @rlintu,

how do you have obtained this SPDX example in **Tag:Value** format? Have you used the SPDX-tools to convert the RDF file? I thought that this option was first introduced with the pull request #556.

**Comment by rlintu** [comment]
Yep, I used SPDX-tools.

**Comment by mcjaeger** [comment]
tested with 3.4:

* scanner found something, selecting "no license known": LicenseInfoInFile is there, but LicenseConcluded ist NOASSERTION
* scanner found something, selecting "irrelevant": LicenseInfoInFile is there, but LicenseConcluded ist NOASSERTION
* scanner found something, deleting scanner finding, selecting "identified": LicenseInfoInFile is there, but LicenseConcluded ist NOASSERTION

-> should be good for now
