### ISSUE TITLE
can not see the license text

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#49]
---

Author Name: **larry shi** 
Original Redmine Issue: 717, http://www.fossology.org/issues/717
Original Date: 2012/02/02
Original Assignee: larry shi

---

1. upload one file, analyze it with nomos
2. click [License Browser] to see the license info
3. click license name, for example: The Nomos license scanner found: GPL_v2, click [GPL_v2]
4. one window popup, the error msg 'Original license text is not in the FOSSology database.'

I am not sure it this issue can be fixed afer the license data is imported from fossology.org.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/02/02 15:58:05 +0000

---

license data is not getting installed (?)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/02/08 18:42:48 +0000

---

assigning target version and raising priority

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/03/26 18:36:08 +0000

---

please verify that this is still  a problem

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/03/28 07:28:10 +0000

---

fix in svn 5682.

Hi Bob,

  how about add /usr/local/lib/fossology/fossinit.php -l -c /usr/local/etc/fossology/  in /usr/local/lib/fossology/fo-postinstall?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/03/28 11:14:47 +0000

---

fo-postinstall can already call fossinit.  You mean add the -l switch.  Yes, I think it should use -l.  Just make sure you can call it with -l repeatedly without error since fo-postinstall can get run more than once.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/03/29 03:06:20 +0000

---

fix in svn 5689.
when runing sudo /usr/local/lib/fossology/fo-postinstall, will update the license_ref table with fossology supplied licenses when license_ref table is not updated.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/04/05 06:18:08 +0000

---

for now, still lots of licenses have no license text.
verified on debian 6.0/64bit single system, and http://fossology.usa.hp.com/repo/
such as GPL_v2, GPL, LGPL have no license text.
BSD has license text.

So more works are required to fix this defect, but I am not sure if we have to fix it in 2.0 or not, 
any suggestions, Mary/Bob/Vincent?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/04/05 15:53:20 +0000

---

It looks like GPL_v2 is in the database as GPL2.0 so that's why it doesn't match.  Also its URL is wrong.  The definitive text of the GPL v2 is on the FSF website.

GPL and LGPL have no text because they have no version number.

I don't know why "BSD" has text since there are different versions.

Spotchecking the data in the license admin tool, I can see there there needs to be lots of work done on this data.  :-(

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/04/05 16:43:18 +0000

---

Defer to 2.0.1 per Bob's comment

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:05 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by steffen-weber** [comment]
Author Name: larry shi
Original Date: 2012/03/29 03:06:20 +0000

fix in svn 5689.
