### ISSUE TITLE
Micromenu is not displayed for single file.

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#496]
Micromenus are not seen when click on file name of yellow banner for a single file upload.

![micromenu](https://cloud.githubusercontent.com/assets/10155976/9465899/3de7d78c-4b4e-11e5-964e-018eae40a37c.png)

**Comment by bobgob** [comment]
Exactly how did you get to this screen?  I have a single file upload.  Then click on "View" in the Browse action pulldown???

**Comment by shaheemazmalmmd** [comment]
Upload a single file and click on the job number takes you to the show jobs page for a single upload. When the status for all is "Completed". click on the upload name in the yellow banner.

**Comment by maximilianhuber** [comment]
The problem is, that it links to `...?mod=browse...` instead of `...?mod=view...`.

A first solution would be to link to `view` if it is no container.

Further, i would suggest to merge the mods `browse` and `view`.
