### ISSUE TITLE
copyright data is not truncated after 150 characters.

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#498]
tested on 8/25/2015
master branch [#25f4d65]

in testing copyright agent it was noticed that the copyright data is not getting truncated after 150 characters.

![copyright_trunkate](https://cloud.githubusercontent.com/assets/10155976/9467425/33b45f3c-4b59-11e5-8742-5ede647145c3.png)

**Comment by mcjaeger** [comment]
still there for 3.0.0

**Comment by steffen-weber** [comment]
Please explain why the data should be truncated.

**Comment by shaheemazmalmmd** [comment]
Now they are being truncated by 300 characters.
