### ISSUE TITLE
Creating Bucket Pools Page not found

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#50]
---

Author Name: **larry shi** 
Original Redmine Issue: 753, http://www.fossology.org/issues/753
Original Date: 2012/02/03
Original Assignee: Bob Gobeille

---

[Admin]-->[Buckets]-->[Duplicate Bucketpool], click the linke [Creating Bucket Pools], get one error page: Page not found

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:07 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2013/04/08 20:04:39 +0000

---

correct URL is http://www.fossology.org/projects/fossology/wiki/Buckets

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2013/05/30 12:27:16 +0000

---

Link fixed in svn 6660

**Comment by bufferoverflow** [comment]
as mentioned by @yaobinshi it's resolved
