### ISSUE TITLE
Logo Image URL not getting updated

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#500]
tested on 8/25/2015
master branch [#25f4d65]

in [Admin] ->. customize, Logo Image URL is not getting updated in database. all other fields are working fine.

**Comment by steffen-weber** [comment]
It works well for me.

Note that the Image URL must be available which is checked in lib/php/common-sysconfig.php:423

**Comment by maximilianhuber** [comment]
It also works well for me (on 7d6de33). I think we can close this issue.
