### ISSUE TITLE
Database page missing

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#501]
tested on 8/25/2015
master branch [#25f4d65]

admin-> Database page is missing in the menu list.

**Comment by bobgob** [comment]
What admin > Database page?  I'm not familiar with a "Database" menu option

**Comment by bobgob** [comment]
Ah, I see the problem in the test case http://www.fossology.org/projects/fossology/wiki/Admin
That Database stuff is VERY old.  I'll update the test page.
