### ISSUE TITLE
Not able to add the new license using add license

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#502]
tested on 8/25/2015
master branch [#25f4d65]

[Admin] -> license admin -> add license.

Fill all the required fields and click on "Add license" button. an empty page is getting displayed and license is not getting added to database.

**Comment by steffen-weber** [comment]
fixed with https://github.com/fossology/fossology/commit/39c91354d49f1fe577f39588205e3b2ab8495a8f
