### ISSUE TITLE
cp2foss command line upload not unpacking

### ISSUE THREAD

**Issue by ag4ums** [fossology/fossology#505]
master branch [#25f4d65]

Test Steps :
>cp2foss --username fossy --password fossy <package> 
or 
>cp2foss --username fossy --password fossy <package> -q all 

is not unpacking (screenshot attached
![cp2foss-upload](https://cloud.githubusercontent.com/assets/6360640/9489276/86f22022-4bfd-11e5-83d6-36f01b1d180d.png)
)

**Comment by shaheemazmalmmd** [comment]
Pull request https://github.com/fossology/fossology/pull/531 solves this issue. please test and close.

**Comment by maximilianhuber** [comment]
Yes, this is solved.
