### ISSUE TITLE
Document where to find agent logs in the repo

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#51]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 963, http://www.fossology.org/issues/963
Original Date: 2012/02/10
Original Assignee: Bob Gobeille

---

Mary's notes:
 All agent logs saved in the scheduler's repo in the subdirectory "logs":
 E.g.   /srv/fossology/repository/fluffy/logs/00/00/04/000004 corresponds to job 4

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:08 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/08/21 14:44:07 +0000

---

still need a brief wiki page or update to existing page

**Comment by mcjaeger** [comment]
is this priority high? - just asking because the tickets appears old.

**Comment by bobgob** [comment]
The agent logs are buried in repository/logs and encoded in the same type of directory structure the files are.  So I don't think documenting their location is very critical.  Unless you have the link to the log from Show Jobs, you probably won't be able to find the log.  So I'm just going to close this.  Feel free to reopen if you think it needs a more comprehensive treatment.
