### ISSUE TITLE
Produce Debian Copyright file

### ISSUE THREAD

**Issue by bobgob** [fossology/fossology#510]
Suggested by Dan Kegel on http://www.fossology.org/boards/3/topics/951:

Output a debian format machine readable copyright file (see  https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ )

This is a variant of our ReadMe_OSS that has the advantages:
-  Machine readable as well as human readable 
-  Conforms to an existing standard (all debian packages produce this)

**Comment by maximilianhuber** [comment]
I have started to work on this Issue. My approach is to add new templates to the spdx2 agent, which satisfy the DEP5 requirements

---

The differences between SPDX and DEP5 are collected at [wiki.debian.org/.../CopyrightFormat](https://wiki.debian.org/Proposals/CopyrightFormat).

This issue, resp. my approach,  is related to #488.

**Comment by maximilianhuber** [comment]
This implementation needs the pull request https://github.com/fossology/fossology/pull/538

**Comment by kestewart** [comment]
The information about SPDX in wiki.debian.org/.../CopyrightFormat refers to an earlier version of SPDX,  current version is SPDX 2.0.   Most fields are the same, but if there are ambiguties please mail me and I'll help.
