### ISSUE TITLE
Menu Display Glitches on IE10

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#511]
The display of some menus interferes with the jquery based table view in the main browse view. It stays usable, however, not looking nice: If the menu is overlapping the table will be before the menue, but should be behind the menu.

Tested on IE10 Version 10.0.9200.17457 (at microsoft, they have tens of builds per day? or how to do get 5-digit sub-minor version numbers?), Update Version 10.0.30

![2015-08-28 15_44_49-broken-browse](https://cloud.githubusercontent.com/assets/3418977/9552416/313bff06-4db8-11e5-88bf-9c5ebf34292d.png)

**Comment by mcjaeger** [comment]
same with another ticket: so who runs on side Fossology on Linux, but requires IE10?

**Comment by pguttmann** [comment]
FOSSology on Linux with browser access from IE10 may be common in the "Corporate" world ;)
Many corporations have "Standardized" on Windows desktops for the MSFT Office suite.
Within those corporations the open source development/compliance team(s) are more likely than not to be using Linux servers and some of those servers would be an obvious/likely home for FOSSology servers ;)

**Comment by mcjaeger** [comment]
well that is what I am asking. I am familiar with multiple corporate environments. And I am not aware currently of a corporate world environment that does allow using IE10 only. 

Thank therefore for your feedback. so you would say, there are many users who are forced to use IE 10?

Please remember that it is not about skipping this, but we need to find a way to come down from about 70 tickets for the next release because otherwise we need again nine months to create another super-large release.

**Comment by mcjaeger** [comment]
requires retest on IE11or later

**Comment by mcjaeger** [comment]
works on IE11 (tested with `Version: [3.1.0rc2], Branch: [master], Commit: [#ce48e5] 2017/03/13 15:48 UTC built @ 2017/03/13 21:11 UTC `)
