### ISSUE TITLE
Upload from Server: Wildcard in file path does not seem to get resolved

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#512]
testing the Fossology (5af3926 nightly package build of today, Aug 29th) test cases has revealed that "Upload from Server"
* a single file works
* but not wildcards '*'
No error message given, just apparently no files matched.

Attached some screenshot how the agent about it. Given files had 644 rights, should not have been the issue.

Interesting observation: If upload from server with "/home/vagrant/package/%.deb" instead "/home/vagrant/package/*.deb" (because the percent sign is used for searches as wildcard). The upload is refused. S, somewhere there is an understanding about the files.

![2015-08-28 19_19_01-show jobs](https://cloud.githubusercontent.com/assets/3418977/9552615/cd523a76-4db9-11e5-81b6-72418f408304.png)

**Comment by mcjaeger** [comment]
seems to be related with #349

**Comment by mcjaeger** [comment]
please retest since 349 seems to solve it

**Comment by maximilianhuber** [comment]
This problem is resolved in the current master.  (likely by the solution of #349)
