### ISSUE TITLE
Geeky Scan Details page broken in IE10

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#513]
At testing the "organize" test case (with Fossology commit 5af3926 nightly package build of today, Aug 29th) it was revealed that the geeky scan details page was broken in IE. Note that looking at the page source, the information is there. it appears to be a problem of interpretation of that page in IE10. Note that Firefox works fine. Attached a screenshot, showing the issue.

Tested on IE10 Version 10.0.9200.17457, Update Version 10.0.30

![screenshot error fossology ie10 2015-08-28 18_59_48-show jobs](https://cloud.githubusercontent.com/assets/3418977/9552965/3e383694-4dbc-11e5-9036-cb03adf5c2bb.png)

**Comment by mcjaeger** [comment]
we need to reduce tickets for 3.0.1 - are there persons who, on one side, run Fossology under Linux (obviously) and would like to access this using IE?

**Comment by pguttmann** [comment]
See comment in: https://github.com/fossology/fossology/issues/511

**Comment by mcjaeger** [comment]
requires retest on IE11or later

**Comment by mcjaeger** [comment]
Works on IE11
