### ISSUE TITLE
tag not returning to caller

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#52]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1011, http://www.fossology.org/issues/1011
Original Date: 2012/02/13

---

1) from any Browser
2) click on tag
3) write a tag to the file

at this point you should be returned back to the browser.  Instead you are left in the tag dialog.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:10 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
review required

**Comment by mcjaeger** [comment]
works now
