### ISSUE TITLE
bucket tag link not active

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#53]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1029, http://www.fossology.org/issues/1029
Original Date: 2012/02/14
Original Assignee: Bob Gobeille

---

The bucket browser has a tag link in the histogram, but the link is not active (it's just text).  The idea is to make it easy to tag all the items in a bucket.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/03/30 21:03:21 +0000

---

I modified bucket browser (ui-buckets.php svn 5721) to add a link to tag a bucket.  However, making this work well is going to take more code than we should disturbe v2.0 with at this (beta) stage.  So I'm moving this to 2.1.

Issues:
1) one could potentially tag many files in a single click.  This can take very long so should be done as an agent if the number of files is large.
2) we need to bring up the tag dialog box then return the user to where they left off.  This is probably best done with a popup which we don't currently support (except through a new target window).
3) there may be performance ramifications with large db's

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:06 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4593/buckettagnotlinked.gif

**Comment by mcjaeger** [comment]
closing because of no update since long period. also image link appears broken
