### ISSUE TITLE
The upload-pages should be consistend and based on the same template

### ISSUE THREAD

**Issue by maximilianhuber** [fossology/fossology#543]
The upload-pages:
* Upload **File**
  - `src/www/ui/page/UploadFilePage.php`  (based on `UploadPageBase`)
* Upload from **URL**
  - `src/www/ui/page/UploadUrlPage.php`  (based on `UploadPageBase`)
* Upload from **Server**
  - `src/www/ui/upload-srv-files.php` (based on `FO_Plugin`)
* Upload from **version control system**
  - `src/www/ui/upload-vcs.php` (based on `FO_Plugin`)

should be rewritten in such a way, that
* all pages are located in `src/www/ui/page/`
* all pages derive from `UploadPageBase`
* all pages use Twig with the same base-template
* all strings, which are used to build a shell command, should be escaped
* the upload permissions of the "Upload from Server" plugin should be restricted

**Comment by mcjaeger** [comment]
one of the reasons why the milestone has been renamed from 3.0.1 but 3.1.0
