### ISSUE TITLE
Product SPDX tag:value format file

### ISSUE THREAD

**Issue by kestewart** [fossology/fossology#548]
Currently FOSSology, will product the RDFa version.  However there are many tools (and its easier for people to read/grep) to have the tag:value version of the information produced directly.   Please consider adding an option to generate the tag:value directly.  It will be very similar to the Debian copyright format.

**Comment by maximilianhuber** [comment]
This is related to #510

**Comment by maximilianhuber** [comment]
First prototype is running and already 90% of RDF is translated to Tag/Value notation.

@kestewart: I am searching for an valid example of such a file, do you know a good example?

**Comment by kestewart** [comment]
@maximilianhuber :  https://drive.google.com/drive/folders/0B1x28UEwdzdOflRxdmQ0VW56Y2Q0T2FoS2VXYXp0Ui11cFNfeGRMY0dMTFVkVTlMdUhpbDg has a set from August and the bakeoff. 

Possibly worth comparing - time in particular is nice and small.    see: http://mirror.sdunix.com/gnu/time/

Is there something I can help with testing?
