### ISSUE TITLE
descriptions removed with multiple uploads of the same file

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#55]
---

Author Name: **Mark Donohoe** 
Original Redmine Issue: 1149, http://www.fossology.org/issues/1149
Original Date: 2012/02/18
Original Assignee: Bob Gobeille

---

If a file is uploaded multiple times (from file, from url, from server)  showjobs only displays that last comment.  For testing it's nice to see all the comments, for example, one of the uploads was the second try to see if things worked.  The comments can help sort out the different test scenarios.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:08 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by max-wittig** [comment]
works with 
Version: [3.1.0rc2], Branch: [master], Commit: [#5e78f5] 2017/03/07 08:54 CET built @ 2017/03/07 14:29 CET
