### ISSUE TITLE
Some buttons have ! but others do not

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#56]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 1227, http://www.fossology.org/issues/1227
Original Date: 2012/02/22
Original Assignee: Mary Laser

---

Upon selecting various "Upload" menu items, I noticed that some of the buttons have explanation points (!) and others do not:
- Upload from File (no - "Upload")
- Upload from Server (yes - "Upload!")
- Upload from URL (yes - "Upload!")
- One-Shot Analysis (yes - "Analyze!")
- One-Shot Copyright ... (no - "Upload and scan")

The buttons should be consistent re: the convention, with our without.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:12 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
reasonable.

**Comment by mcjaeger** [comment]
I could do this maybe. :D

**Comment by shaheemazmalmmd** [comment]
i think this issue is resolved with this commit https://github.com/fossology/fossology/commit/54f545d048880f73b6a6f854be391035aca95331. please test and close.
