### ISSUE TITLE
Update Shortnames in Admin License Candidates view

### ISSUE THREAD

**Issue by kgerloff** [fossology/fossology#566]
When reviewing license candidates, the field "Shortname" by default contains the shortname of the license candidate that was last reviewed. Example:
1. you review a license candidate with the shortname "BSD-3-Clause-MyBeautifulCompany". You compare this to the standard BSD 3-Clause license, and click on "Variant of license". 
2. you then move on to reviewing the next license candidate. On this page, the shortname field will now say "BSD-3-Clause-MyBeautifulCompany".

This is clearly not optimal. The shortname field should either contain the shortname of the license that you're currently reviewing (if available); or be empty.

**Comment by shaheemazmalmmd** [comment]
Retest required for this issue.
i have tested this and it works fine.(latest master)
what i have done here is
create 3 new license requests(BSD-3-Clause-MyBeautifulCompany, BSD-3-Clause-MyCompany, BSD-3-Clause-BeautifulCompany) . goto admin-> license admin -> candidates.

started reviewing first license BSD-3-Clause-MyBeautifulCompany compared it with existing license BSD-3-Clause and then clicked on  "Variant of license". 

then the second license name BSD-3-Clause-MyCompany. shortname field is with same name.

**Comment by NesrinCeylan** [comment]
Or Do you think the issu #938 fits this?

**Comment by mcjaeger** [comment]
actully even rested the behaviour reported by Karsten at `Version: [3.4.0], Branch: [master], Commit: [#6ad6a1]`doe snot show the short name glitch anymore
