### ISSUE TITLE
In Admin / License Candidate view, "edit" icon merges licenses

### ISSUE THREAD

**Issue by kgerloff** [fossology/fossology#568]
In Admin > License Admin > Candidates Overview, clicking on the "edit" icon merges licenses (based on unknown criteria) rather than opening them for review. 

Sample message after clicking on the edit icon: 

`Successfully merged candidate GPL-2.0-with-autoconf-exception (1) into see-test (2228)`

This occurs after I compared and merged a license candidate through the normal process.

In order to return the edit icon to its normal function, return to the Fossology main view, then go again to Admin > License Admin > License Candidates.

**Comment by NesrinCeylan** [comment]
Do you think the issu #938 fits this?
