### ISSUE TITLE
Pkgagent -v  and -vv output do not differ

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#57]
---

Author Name: **Mark Donohoe** 
Original Redmine Issue: 1251, http://www.fossology.org/issues/1251
Original Date: 2012/02/23
Original Assignee: Dong Ma

---

using svn 5531 on snape.ostt a file was processed with -C -v and -C -vv.  The output was compared and there were no differences.  The help message says -vv gives more information.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2012/03/16 07:59:04 +0000

---

Fixed with revision5635.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/04/01 07:20:58 +0000

---

tested on debian 6.0/64bit single system, svn 5724.
I still can not find the diffrence.

madong@bl460c-10:~/fossology2.0/fossology/src/delagent/agent$ ./delagent -F 1 -vv
Deleting upload 14
1. Deleting foldercontents
1. COMMIT;
1. BEGIN;
1. Getting list of pfiles to delete
1. Created pfile table: 1 entries
1. Deleting upload
1. Deleting from pfile
Deleted upload 14 from DB, now doing repository.
1. COMMIT
Deleted upload 14
Deleting upload 15
1. Deleting foldercontents
1. COMMIT;
1. BEGIN;
1. Getting list of pfiles to delete
1. Created pfile table: 3 entries
1. Deleting upload
1. Deleting from pfile
Deleted upload 15 from DB, now doing repository.
1. COMMIT
Deleted upload 15
INFO: Default folder not deleted.
madong@bl460c-10:~/fossology2.0/fossology/src/delagent/agent$ ./delagent -F 1 -v
Deleting upload 16
1. Deleting foldercontents
1. COMMIT;
1. BEGIN;
1. Getting list of pfiles to delete
1. Created pfile table: 1 entries
1. Deleting upload
1. Deleting from pfile
Deleted upload 16 from DB, now doing repository.
1. COMMIT
Deleted upload 16
Deleting upload 17
1. Deleting foldercontents
1. COMMIT;
1. BEGIN;
1. Getting list of pfiles to delete
1. Created pfile table: 3 entries
1. Deleting upload
1. Deleting from pfile
Deleted upload 17 from DB, now doing repository.
1. COMMIT
Deleted upload 17
INFO: Default folder not deleted.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/04/02 21:16:21 +0000

---

Sounds like we just need to change the usage message.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:13 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by maximilianhuber** [comment]
In the code there are the lines [pkgagent.c#L442](https://github.com/fossology/fossology/blob/2633dfbe9c412304648076f6b629fe7cedc8958f/src/pkgagent/agent/pkgagent.c#L442) and [pkgagent.c#L467](https://github.com/fossology/fossology/blob/2633dfbe9c412304648076f6b629fe7cedc8958f/src/pkgagent/agent/pkgagent.c#L467) where the `-vv` parameter makes a difference. Closing this issue.
