### ISSUE TITLE
Issue with license candidate and deb5 generation

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#578]
Please the attached PDF, there maybe  an issue with a PHP call that might not be successful when executing the DEB5 generation: seems to be that a relation "license candidate" is missing. Maybe it is also my lack of skills to install from source / current master?

Upload of single package (I doubt that this error depends on the package itself).

Mentioned it already: Fossology installed on bare ubuntu 64bit via source install (Did I mention that we have only 32bit package for ubuntu? otherwise I would have installed from package. what are 32bit packages for today? support of legacy systems?)

[036 OSS fossyng 20151201 screenshot agent deb5 crashes.pdf](https://github.com/fossology/fossology/files/49208/036.OSS.fossyng.20151201.screenshot.agent.deb5.crashes.pdf)

Update: looks like none of the reports (README_OSS and SPDX) work when install from source used steps: http://www.fossology.org/projects/fossology/wiki/SysConfigSrc

**Comment by mcjaeger** [comment]
ehem looks like it is really not dependent on a package (so no upload of jersey server src 1.8 useful)
![screen shot 2015-12-02 at 09 28 38](https://cloud.githubusercontent.com/assets/3418977/11525943/41daa8e8-98d7-11e5-9ea9-d8bc2cfdcbff.png)

**Comment by wuan** [comment]
Can you try to re-run fo-postinstall to ensure that the table `license_candidate` exists?

**Comment by mcjaeger** [comment]
sorry, I thinkI tried it (as thi is part of the source install instructions)  There. was a php error, wen running. Will check.

**Comment by mcjaeger** [comment]
dump again:
ubuntu@ip-10-0-0-150:~/source$ sudo /usr/local/lib/fossology/fo-postinstall 
*** Running postinstall for everything ***
*** Running postinstall for common actions***
*** Creating user and group ***
NOTE: group 'fossy' already exists, good.
NOTE: user 'fossy' already exists, good.
*** Making sure needed dirs exist with right ownership/permissions ***
*** clearing file cache ***
NOTE: Repository already exists at /srv/fossology/repository
NOTE: Running the PostgreSQL vacuum and analyze command can result in a large database performance improvement.  We suggest that you either configure postgres to run its autovacuum and autoanalyze daemons, or maintagent -D in a cron job, or run Admin > Maintenance on a regular basis.  Admin > Dashboard will show you the last time vacuum and analyze have been run.
*** Running postinstall for web-only actions***
*** Setting up the FOSSology database ***
NOTE: fossology database already exists, not creating
*** Checking for plpgsql support ***
NOTE: plpgsql already exists in fossology database, good
*** update the database and license_ref table ***
Old release was 0
  Applying database functions
DB schema has been updated for fossology.
Database schema update completed successfully.
Update reference licenses
Migrate data from 2.1 to 2.2 in /usr/local/lib/fossology
Rename license in /usr/local/lib/fossology
PHP Fatal error:  Call to undefined function renameLicense() in /usr/local/lib/fossology/fo_mapping_license.php on line 388
Database connectivity is good.
*** Setting up scheduler ***
*** Setting up the web interface ***
NOTE: Adding user www-data to group fossy
FOSSology postinstall complete, but sure to complete the remaining
  steps in the INSTALL instructions.
ubuntu@ip-10-0-0-150:~/source$

**Comment by wuan** [comment]
This error should be fixed by 3ddc3f883df8c83a2ead8abc6a4d135139906e09. Please pull and try again.

**Comment by mcjaeger** [comment]
magic, thanks, however:

from geeky agent details:

2015-12-02 12:57:37 dep5 [0] :: ERROR agent.c.325: META_DATA[dep5] invalid agent spawn check
2015-12-02 12:57:37 dep5 [0] :: ERROR: versions don't match: localhost(3.0.0-62-g214a102) != received: localhost(3.0.0-63-g3ddc3f8)
2015-12-02 12:57:37 dep5 [0] :: JOB[26].dep5[17191.localhost]: agent was killed by signal: 9.Killed

what happenend:
* make
* sudo make install
* sudo /usr/local/lib/fossology/fo-postinstall ...

**Comment by wuan** [comment]
To be sure to create new binaries after pulling, start with `make clean` please.

```
make clean
make
sudo make install
sudo /usr/local/lib/fossology/fo-postinstall
```

**Comment by maximilianhuber** [comment]
@mcjaeger: has the clean install solved your problem?

**Comment by maximilianhuber** [comment]
@mcjaeger: can you please close this issue if all problems are resolved?

**Comment by maximilianhuber** [comment]
I think i will close this issue due to inactivity, please reopen if it is still a problem
