### ISSUE TITLE
showjobs creates blank windows when next is pressed but no additional jobs are present

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#58]
---

Author Name: **Cat X** 
Original Redmine Issue: 1335, http://www.fossology.org/issues/1335
Original Date: 2012/02/28
Original Assignee: Bob Gobeille

---

The 'showjobs' window creates extra blank windows beyond the existing list of jobs when 'next' or the subsequent number is pressed.

In the attached screenshot, the only window that has jobs listed is #1.  If 'next' or the last number in the sequence is pressed, a new empty window, one greater in the sequence is generated.

I'm currently running FOSSology version 2.0.0-devel (code revision 5550)

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Cat X** 
Original Date: 2012/02/28 23:31:11 +0000

---

This problem also occurs with 'list files for licence' -- it seems not unlikely that it'll show up for anything else similar.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/03/02 16:23:38 +0000

---

Might be related to the issue reported by Larry, #1365

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2012/03/06 00:03:42 +0000

---

No

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:10 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by pguttmann** [comment]
Attachment - http://www.fossology.org/attachments/4587/Screenshot-Show_Jobs_-_Iceweasel.png

**Comment by mcjaeger** [comment]
confirming it is there.

**Comment by GMishx** [comment]
Fixed by #1338
