### ISSUE TITLE
Supported PHP versions

### ISSUE THREAD

**Issue by steffen-weber** [fossology/fossology#585]
PHP 5.3 and PHP 5.4 have reached End of life, i.e., the releases are no longer supported and users of these releases should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities, see http://php.net/supported-versions.php
Hence Fossology should not support these releases anymore to avoid responsibility for possible vulnerabilities.

Also the active support for PHP 5.5 is ended and only fixes for critical security issues will be provided. Latest test failures of Travis CI (https://travis-ci.org/fossology/fossology/builds/95226989) were caused by PHPUnit 5 requiring PHP 5.6. Since End of life is in 7 months, end supporting PHP 5.6 soon is highly recommended.

Any opinions? Should this question be send to the mailing list(s)?

**Comment by bufferoverflow** [comment]
Yes, I would say skip 5.3 and 5.4. Debian and Ubuntu is already on 5.6
Here is a list of php versions per distro: http://phpversions.info/operating-systems/

**Comment by rlintu** [comment]
That would mean to drop support for Ubuntu 12.04 LTS. I think there are so many important bug fixes coming for 3.0 that those should be available for Ubuntu 12.04 as well. Maybe the release with new features can then be available only for later releases.

**Comment by pguttmann** [comment]
"Any opinions? Should this question be send to the mailing list(s)?" - Given: "That would mean to drop support for Ubuntu 12.04 LTS. "
I think sending the question to the mailing list(s) would definitely be worthwhile.

**Comment by maximilianhuber** [comment]
Note: If we decide to drop support for 5.3 then some parts of the code introduced in the pull request #649 could be removed.

**Comment by maximilianhuber** [comment]
There is currently a PR (#689) which only works with PHP>=5.5.9 (i.e. not on Ubuntu 12.04, Debian 7 or RHEL 7.1).

@pguttmann: Was this question already discussed on the mailing list?

My opinion: drop support for PHP <5.5.9

**Comment by bufferoverflow** [comment]
according to http://php.net/eol.php we should drop all php versions < 5.6
