### ISSUE TITLE
UI to set up remote cluster

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#59]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1341, http://www.fossology.org/issues/1341
Original Date: 2012/02/29

---

Given all the problems we have setting up remote clusters, perhaps we need a UI to do it for us.  It can verify the connectivity, install agents, set up the conf files, etc.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:11 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
closing because of missing pickup
