### ISSUE TITLE
One shot analysis fails without any message if file is too large

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#600]
Using `mod=agent_nomos_once`, attempting to upload a file which is too big will fail, but no message is displayed and no results are shown.
Using version `3.0.0-107-g0cca7ce, commit: [#0cca7c]`.

**Comment by timurphy** [comment]
In contrast, using `mod=upload_file` produces this error message:

    The file "my_large_file" exceeds your upload_max_filesize ini directive (limit is 2048 KiB).

**Comment by mcjaeger** [comment]
actually the behaviour has changed: it is displaying the contents, but paging is broken on the page, so only the first page is shown properly.

Tested with 2GB, 700MB and 15MB files.

**Comment by GMishx** [comment]
Hello @timurphy,

It seems to be an issue with your PHP's ini settings. Can you please check the `upload_max_filesize` in you `php.ini` file? It will be located under `/etc/php.ini` on RedHat based systems and `/etc/php/<version>/apache2/php.ini` on Debian based systems.

You can also run this script located at [install/scripts/php-conf-fix.sh](https://github.com/fossology/fossology/blob/master/install/scripts/php-conf-fix.sh). The script also supports `--overwrite` flag if you want the script to update your settings.

**Comment by mcjaeger** [comment]
closing it because I also thing it seems to be an issue of PHP settings
