### ISSUE TITLE
Parse error in UploadSrvPage.php [master]

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#604]
FOSSology won't start and following error is reported:

Parse error: syntax error, unexpected '[' in /usr/local/share/fossology/www/ui/page/UploadSrvPage.php on line 51 Call Stack: 0.0002 660800 1. {main}() /usr/local/share/fossology/www/ui/index.php:0 0.0996 7912496 2. plugin_load() /usr/local/share/fossology/www/ui/index.php:53 

Version 3.0.0-109-g7d6de33
Ubuntu 12.04-64

No problem with 3.0.0.

**Comment by maximilianhuber** [comment]
Which PHP version did you use?

The used bracket syntax is suported in PHP >5.4. See also #585.
