### ISSUE TITLE
Users not restricted to top-level folder

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#612]
Tested on version `3.0.0-107-g0cca7ce`.
On the `mod=user_edit` page, the top-level folder includes this in the description: __Access is restricted to this folder__. This is not the case - any user can navigate to `?mod=browse&folder=1` where all folders are shown, and all public uploads _in any folder_ can be accessed.

To reproduce:
1. Create a new folder named `TestFolder`
2. Create a user `test` with a top-level directory of `TestFolder`
3. Create a new folder named `HiddenFolder`
4. As `fossy` user, upload any file to `HiddenFolder` and mark it as public
5. Log in as `test` and change URL to `?mod=browse&folder=1`
6. Navigate to `HiddenFolder` and view uploaded file

If this is the desired behaviour, the description on the `mod=user_edit` page should be changed.

**Comment by maximilianhuber** [comment]
You are right, a user whose access is **restricted to a sub folder** should not be able to navigate to `?mod=browse&folder=1`.
