### ISSUE TITLE
refactor(ui): rename `content_delete` to something like `content_unlink`

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#614]
The mod-name `content_delete` is confusing, since it only unlinks, i.e. deletes duplicates without removing the "real thing". In contrast to `?mod=admin_folder_delete` and `?mod=admin_upload_delete`.

**Comment by Aman-Codes** [comment]
The mod-name was changed from `content_delete` to `content_unlink` in #830 
So I believe we can close this issue if no more changes are required

**Comment by GMishx** [comment]
I guess yes. Can't find `content_delete` anywhere in the codebase.

Thanks for pointing @Aman-Codes
