### ISSUE TITLE
Bad error reporting for mod=copyright-view when file contents not available

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#615]
Tested on 3.0.0-125-g87c0413

When file contents are not available, `pageMenu` is set to `F` and `textView` is set to `i` - see http://i.imgur.com/WQYxzuT.png. To reproduce:
1. Upload any file
2. Make `/srv/fossology` inaccessible to the web server user: `sudo chmod g-x /srv/fossology`
3. View Copyright analysis for that file

It looks like this is caused by https://github.com/fossology/fossology/blob/master/src/www/ui/ui-view.php#L333 returning the string "File contents are not available in the repository." when it should be returning an array, causing the string to be interpreted as a char array.

**Comment by timurphy** [comment]
This function also returns strings for other error conditions.

**Comment by maximilianhuber** [comment]
Thank you for reporting this issue. Pleas create a PR with the solution mentioned above.

--

>The image above mentioned (http://i.imgur.com/WQYxzuT.png) is:
![wqyxzut](https://cloud.githubusercontent.com/assets/1187050/12412922/2c3d6f1e-be8b-11e5-9d0a-8ec2b9884bc3.png)

**Comment by timurphy** [comment]
PR above sets `pageMenu` to `Error` and `textView` to the string previously returned for that error condition.
