### ISSUE TITLE
Single quotes in license text prevents adding a new license

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#628]
I was trying to store Cygnus-eCos-1.0 license via Admin view (#623) but that failed with db error.

`Warning: pg_prepare(): Query failed: ERROR: syntax error at or near "s" LINE 65: Contributor's choice. The Source Code can be in a compressed ^ in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 62 `

In `admin-license-file.php` license text is trimmed using `trim` function before storing it to a database and while listing (reading) the license text is formatted using `htmlspecialchars`. If html operations are done in reverse order then at least the example license can be stored and read correctly. That is while storing (`Adddb`):
```
$trimmedLicense = trim($_POST['rf_text']);
$rf_text = htmlspecialchars($trimmedLicense, ENT_QUOTES);
```
and while reading (`LicenseList`):
```
$vetext = htmlspecialchars_decode($row['rf_text']);
```
However, that may break listing of some existing licenses.

**Comment by maximilianhuber** [comment]
The code you used is using the `pg_prepare` in an incorrect way. It should use a query with holes and the **license text should not be included**.
The license text should be added later as argument when you execute the prepared statement.

--

Where does this happen, i am not able to find the corresponding code snippet in the code base.

**Comment by rlintu** [comment]
I uninstalled and reinstalled the latest version (3.0.0-154-gd8c54cc). The same result.
Environment: ubuntu-14.04, PostgreSQL 9.3.10, PHP 5.5.9

**Comment by maximilianhuber** [comment]
I have found the bug and will add a PR immediately.
