### ISSUE TITLE
c library unit tests aren't running

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#63]
---

Author Name: **Alex Norton** 
Original Redmine Issue: 1527, http://www.fossology.org/issues/1527
Original Date: 2012/03/14
Original Assignee: Mark Donohoe

---

The nightly build is not running the unit tests for the c library functions. I figured this out because I went to check that some changes I made recently hadn't broken the tests for the fossconfig library and found that the tests for fossconfig and libfossscheduler didn't even build and haven't for several months.

The relevant tests can be found under src/lib/c/tests

I have fixed the tests so that they will now build but they don't run currently because of a failure in libfossdb.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mark Donohoe** 
Original Date: 2012/03/14 22:24:51 +0000

---

I will add these into the runs, thanks for catching this.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mark Donohoe** 
Original Date: 2012/03/14 22:47:39 +0000

---

Input file has been changed.  Tests should run tonight. 3/14.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:14 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by maximilianhuber** [comment]
This issue is outdated and the on the current master are all unit tests running, as far as i know.
