### ISSUE TITLE
Filenames containing special characters break SPDX RDF

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#639]
Tested using version `3.0.0-107-g0cca7ce`

If any file in a project contains special characters such as ampersand `&`, the generated SPDX file is invalid and cannot be parsed by spdx tools.

To reproduce:

1. Create a file called `a&b` containing the text `GPL`
2. Upload the file and schedule a nomos scan
3. Generate an SPDX RDF file

Opening the resulting file in Firefox will return throw an error like this:

    XML Parsing Error: not well-formed
    Location: file:///tmp/SPDX2_a&b_1456098516.rdf
    Line Number 4, Column 88:
    
    <spdx:SpdxDocument rdf:about="/srv/fossology/repository/report/SPDX2_a&b_1456098516.rdf#SPDXRef-DOCUMENT">
    ---------------------------------------------------------------------------------------^

**Comment by maximilianhuber** [comment]
Can you also upload the plaintext result?

**Comment by maximilianhuber** [comment]
I was able to reproduce the bug. One has to escape
```
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```
or use  CDATA sections

**Comment by maximilianhuber** [comment]
Will be fixed in PR #633. Thank you for mentioning this issue.
