### ISSUE TITLE
NOASSERT and NoLicenseConcluded same as No License Found in false positive case?

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#640]
Currently, there seems to be a difference between what is on the UI of Fossology and the DEP5 and SPDX formats.

In Fossology we distinguish between the following status for a file:

1. The clearing expert has not looked at the file and thus no clearing decision was created, so the file is untouched, just scan results are there.

2. The expert has looked at the file and concluded that no license information can be found - despite the scanner may have found a license false positive (for example Trademark.ref in C# assembly information files, or the famous  "IBM-possibilty" with some occurences of the word "source"...)

-> two different things,

In the generated DEP5 there is "License: NoLicenseConcluded" for both cases

In the generated SPDX there is "LicenseConcluded: NOASSERTION" for both cases.  

For clearing it would be good to have both cases covered differently, I have not a cool naming for the status ready, something like "false positve"?

**Comment by maximilianhuber** [comment]
In SPDX standart it says, that the possible choices for license information are
* A **valid SPDX License Expression** as defined in Appendix IV. 
* **NONE** should be used if there is no licensing information from which to conclude a license for the package. 
* **NOASSERTION**  should be used if: 
  1. the SPDX file creator has attempted to but cannot reach a reasonable objective 
determination of the Concluded License; 
  2. the SPDX file creator is uncomfortable concluding a license, despite some license 
information being available; 
  3. the SPDX file creator has made no attempt to determine a Concluded License; 
  4. the SPDX file creator has intentionally provided no information (no meaning should 
be implied by doing so). 

The keyword **NONE** may represent the correct information.

**Comment by maximilianhuber** [comment]
The **SPDX2 RDF** report already uses the **NONE** keyword, i.e. one obtains output like
```
[...]
            <spdx:hasFile>
            <spdx:hasFile>
              <spdx:File rdf:about="/srv/fossology/repository/report/SPDX2_time-1.7.tar.gz_1456244687.rdf#SPDXRef-item63631">
                <spdx:fileName>time-1.7.tar.gz/time-1.7.tar/time-1.7/getopt.c</spdx:fileName>
                <spdx:checksum>
                  <spdx:Checksum>
                    <spdx:algorithm rdf:resource="http://spdx.org/rdf/terms#checksumAlgorithm_sha1"/>
                    <spdx:checksumValue>4EEC2F371CDEA3FA5F96A37B44B200445609BC75</spdx:checksumValue>
                  </spdx:Checksum>
                </spdx:checksum>
                <spdx:checksum> 
                  <spdx:Checksum>
                    <spdx:algorithm rdf:resource="http://spdx.org/rdf/terms#checksumAlgorithm_md5"/>
                    <spdx:checksumValue>F761B8034250DEFEB6B89EC423FD5AF3</spdx:checksumValue>
                  </spdx:Checksum>
                </spdx:checksum>
                <spdx:licenseConcluded rdf:resource="http://spdx.org/rdf/terms#none" />
                <spdx:licenseInfoInFile rdf:resource="/srv/fossology/repository/report/SPDX2_time-1.7.tar.gz_1456244687.rdf#LicenseRef-FSF" />
                <spdx:copyrightText>
              </spdx:File>
[...]
```
where the scanner found **FSF** but no license was concluded. I am not sure whether this is the correct representation for the case, where **scanner has found something but no expert has touched the corresponding file**.

We use `<spdx:licenseInfoInFile rdf:resource=".....#NOASSERTATION" />` when the scanner has not found anything.

@kestewart: is this the correct behaviour?

**Comment by maximilianhuber** [comment]
### LicenseInfoInFile
**1.** When the scanners found **something** we should write 
```
LicenseInfoInFile: scanner-finding-1
LicenseInfoInFile: scanner-finding-2
```
**2.** When the scanners found **nothing** we should write 
```
LicenseInfoInFile: None
```

### LicenseConcluded
1. If the set of concluded Licenses is **empty**
  1. and the file is **cleared**, we should write  `LicenseConcluded: NONE`
  2. and the file is **not cleared**, we should write  `LicenseConcluded: NOASSERTION`
2. if the set of concluded Licenses is **not empty**
  1. and the file is **cleared**, we should write `LicenseConcluded: Concluded-License`
  2. and the file is **not cleared**, we should write `LicenseConcluded: NOASSERTION`

@kestewart: Is there a way to express the partial information in case **2. ii.**? Maybe something like 
```
LicenseConcluded: PartialLicensenInformation and NOASSERTION
```

**Comment by maximilianhuber** [comment]
### Proposed policy for DEP5 format:
* If it is *cleared* and *NONE* is concluded: **do not list the file (?)**
* if it is *cleared* and *licenses are concluded*: **list licenses** but do not list scanner findings (?)
* if it is *not cleared*: **show NoLicenseConcluded** and show potential scanner findings in the comment section (?)
