### ISSUE TITLE
feature(SPDX2): the SPDX output does not yet show license comments

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#645]
- SPDX2 supports **License Comments** (and File Comments)
- DEP5 only has file comments

See the discussion of #633

**Comment by NicolasToussaint** [comment]
I developped this feature: any comment added in the *comment* field of a file is automatically included in the SPDX report, according to the [SPDX specifications (chap 4.7)](https://spdx.org/spdx-specification-21-web-version#h.3l18frh)

```
##File

FileName: Build/KeePassLib_Distrib/KeePassLib.dll/.rsrc/version.txt
SPDXID: SPDXRef-item197
FileChecksum: SHA1: bf3ef3b33265675bba9bad6c2857fa7024e2d66a
FileChecksum: MD5: c694a47a9c904ff88328b74f07a284f4
LicenseConcluded: LicenseRef-Artistic-2.0-728fbdfdd6786bce18c8b87add4c1379
LicenseComments: Dream of a land, my soul is from
LicenseInfoInFile: NOASSERTION
FileCopyrightText: NOASSERTION
```

I will propose a pull request soon

**Comment by NicolasToussaint** [comment]
OK, good point.
Not sure what shape the "configuration dialog for the spdx export" should take though.
Should it be 
- an extra popup when exporting the report 
- an extra "upload property"
- a checkbox when entering the comment text to include it in the SPDX report ?

Or maybe would it be better to add an extra column in the license table name "SPDX Comments" or so?



(and it will surely be beyond my very limited PHP skills :))

**Comment by NicolasToussaint** [comment]
Hi,
I would like to move this forward, but I'm not sure how to make the behaviour wrt to the comment entries "configurable".

I would suggest adding a configuration checkbox in the Organize -> Uploads -> Edit Properties page:
![image](https://user-images.githubusercontent.com/22956329/47210685-ddd24b80-d393-11e8-9aa0-cffa289b11fa.png)

Adding the line: **5. Include License Comments to SPDX reports** 

Anyone has thought on this ?

**Comment by maxhbr** [comment]
This sounds like a good place for the option!

**Comment by NicolasToussaint** [comment]
Just a word: the option should be effective for both _SPDX: Tag-Value_ and _SPDX: RDF_ exports.

**Comment by ChristopheRequillart** [comment]
OK I will implement it.

**Comment by NicolasToussaint** [comment]
There seems to be a problem, as the options `License comment` and `Ignore files with no info in SPDX reports` are missing from the *Edit Uploaded File Properties* on the Master branch.

Looking at the [admin-upload-edit.php page history](https://github.com/fossology/fossology/commits/master/src/www/ui/admin-upload-edit.php], it looks like the commits were cancelled by:
- https://github.com/fossology/fossology/commit/453da1f130fcdb8d51f8c5aed9d7ab404be88720#diff-7dc4825c29b1b76462e7459c45abc810
- https://github.com/fossology/fossology/commit/3f2117c463a02d8e2f11832e894cef0e605ff8e7#diff-7dc4825c29b1b76462e7459c45abc810

Is that an mistake, or did I miss something ?

**Comment by GMishx** [comment]
Those options are moved to a new page called "Report Configuration". You can find it with the name `Conf` right next to the `Info` link in license browser. Since those options were related to just report, it was advisable to keep them separate from upload properties.

> Looking at the [admin-upload-edit.php page history](https://github.com/fossology/fossology/commits/master/src/www/ui/admin-upload-edit.php), it looks like the commits were cancelled by:
> 
>     * [453da1f#diff-7dc4825c29b1b76462e7459c45abc810](https://github.com/fossology/fossology/commit/453da1f130fcdb8d51f8c5aed9d7ab404be88720#diff-7dc4825c29b1b76462e7459c45abc810)

They were removed from there and added to https://github.com/fossology/fossology/pull/1356/commits/453da1f130fcdb8d51f8c5aed9d7ab404be88720#diff-63f110093440c62718745edccb966e38R165

**Comment by NicolasToussaint** [comment]
Excellent, thanks for the explanations, I totally missed that point.

Shouldn't this issue be closed now ?

**Comment by shaheemazmalmmd** [comment]
yes we can close this issue, If it works for you. thank you

**Comment by NicolasToussaint** [comment]
the option works well ;
However, there seems to be a problem with the initial value of the options in the report conf page, but I'll create a separate issue for this.
