### ISSUE TITLE
Bug(monk): Some functional tests of monkbulk fail randomly

### ISSUE THREAD

**Issue by maximilianhuber** [fossology/fossology#650]
This occured in travis builds of different PRs (e.g. #649).

The [failing line](https://github.com/fossology/fossology/blob/7e56b4f2e417d009cecc9591b8eb2de208bb8770/src/monk/agent_tests/Functional/bulkTest.php#L293) is

```
    $this->assertEquals(6, $this->getHeartCount($output));
```

The (relevant) travis output is:

```
[...]
$ phpunit -csrc/phpunit.xml --testsuite="$PHPTESTSUITE"
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
....................................F......HEART:  0
........HEART:  0
Time: 2.26 minutes, Memory: 204.50Mb
There was 1 failure:
1) MonkBulkTest::testRunMonkBulkScanWithMultipleLicenses
Failed asserting that 5 matches expected 6.
/home/travis/build/fossology/fossology/src/monk/agent_tests/Functional/bulkTest.php:293
FAILURES!
Tests: 51, Assertions: 190, Failures: 1.
```

Screenshot:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13629620/93a7c4ee-e5da-11e5-8064-9c36527a8d72.png)

**Comment by maximilianhuber** [comment]
Another line which creates the same fail is [bulkTest.php:224](https://github.com/fossology/fossology/blob/7e56b4f2e417d009cecc9591b8eb2de208bb8770/src/monk/agent_tests/Functional/bulkTest.php#L224)

Corresponding screenshot:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13635160/5d998ae8-e5fa-11e5-8ceb-228cee71a31b.png)

**Comment by fogninid** [comment]
I believe you are seeing a race between threads which try to increase [item_processed](https://github.com/fossology/fossology/blob/master/src/lib/c/libfossscheduler.c#L39) when calling [fo_scheduler_heart()](https://github.com/fossology/fossology/blob/master/src/monk/agent/monkbulk.c#L215) (the same problem affects [monk.c](https://github.com/fossology/fossology/blob/master/src/monk/agent/monk.c#L68))

You can try locking those two calls with the same pre-processor directives which protect `fo_RepMkPath()` [here](https://github.com/fossology/fossology/blob/master/src/monk/agent/match.c#L96).

**Comment by maximilianhuber** [comment]
Yes, I agree with you. That might be the problem.

One might also have to check, whether the preceding call of `matchPFileWithLicenses(..)` is really thread safe (although it already has some value `threadLocalState`).
