### ISSUE TITLE
Deleted uploads job is missing in UI(show jobs)

### ISSUE THREAD

**Issue by shaheemazmalmmd** [fossology/fossology#652]
tested on a latest commit of master. (**7e56b4f**)

**To Reproduce**
-> Upload a component
-> Delete a uploaded component from ?mod=admin_upload_delete.
-> A message gets displayed (

> Deletion added to job queue. View Jobs

) now click on view jobs.
-> Nothing gets displayed.

**Solution:**
Deleted job should get displayed in ui-(showjobs).

**Comment by maximilianhuber** [comment]
Every Job, related to an upload is removed from the list when the upload is removed. This includes the job which has removed the upload.

But I am also not sure whether this is the desired behaviour.

**Comment by max-wittig** [comment]
Clarification: If you click on `View Jobs` on the delete upload page, the correct information are shown.
But if you view the `?mod=showjobs` page the deletion is not shown.

**Comment by GMishx** [comment]
@shaheemazmalmmd I think the issue was resolved by #1761. Can you please check?

**Comment by shaheemazmalmmd** [comment]
@GMishx : yes this issue should be closed. just tested.
