### ISSUE TITLE
`showjobs` does not show all jobs

### ISSUE THREAD

**Issue by maximilianhuber** [fossology/fossology#662]
## Problem: showjobs broken
the showjobs does not show all items. Testet on clean `vagrant up` on cc73013.

#### How it was produced
1. As user `rw1` with write permissions upload file
2. As user `fossy` run all scanners on the upload (using the page `http://localhost:8081/repo/?mod=agent_add`)

### Result
- Only `rw1` is able to see the jobs created for uploading the file, i.e. related to step **1.** (this might be desireable)
- In the showjobs page neither `rw1` nor `fossy` (also with `&allusers=1`) see the jobs created in step **2.**
- both can visit the page `http://localhost:8081/repo/?mod=showjobs&upload=2` to see the missing jobs

#### Screenshots
fossy (i.e. admin with `showAllJobs` enabled) sees:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13989271/e4487840-f10f-11e5-8dd5-53fc1d64f4fa.png)

rw1 (i.e. user with rw permissions) sees:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13989293/06f527a8-f110-11e5-89d6-d406cac1514d.png)

**Both** can visit `http://localhost:8081/repo/?mod=showjobs&upload=2` and see:
![tmp](https://cloud.githubusercontent.com/assets/1187050/13989223/b5b853a6-f10f-11e5-94ee-595b549433f1.png)

**Comment by maximilianhuber** [comment]
I am no longer sure whether I understand `showjobs` in combination with `&allusers=1`. I thought that with this flag the `showjobs` page should show every single job. **Am I right?**

**Comment by shaheemazmalmmd** [comment]
I think it shows all uploads belongs to his group.

Here if fossy clicks on "show uploads from all users" then it should show all the uploads belongs to fossy group or any other group where fossy is involved.

**Comment by maximilianhuber** [comment]
Yes. I have already talked to @mcjaeger and he has explained it also to me. I will close that issue.

**Comment by steffen-weber** [comment]
It might be good to explain it on the showjobs page, too.
