### ISSUE TITLE
Remove unused indexes

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#67]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1755, http://www.fossology.org/issues/1755
Original Date: 2012/04/09
Original Assignee: Bob Gobeille

---

based on a scan of fo.usa, remove indexes from the db schema that are not used.  Specifically:
copyright.agent_fx_idx
attrib.attrib_key_fk_idx

 schemaname |     relname      |        indexrelname        |  idx_scan  | index_size 
------------+------------------+----------------------------+------------+------------
 public     | agent_lic_status | processed_idx              |          0 | 41 MB
 public     | copyright        | agent_fk_idx               |          0 | 2713 MB
 public     | report_cache     | report_cache_createdts     |          0 | 32 kB
 public     | attrib           | attrib_key_fk_idx          |          1 | 152 MB
 public     | agent_lic_status | inrepository_idx           |          4 | 41 MB

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/04/09 17:24:53 +0000

---

The query that shows index use is:

SELECT schemaname, relname, indexrelname,
  idx_scan, pg_size_pretty(pg_relation_size(i.indexrelid)) AS index_size
FROM
  pg_stat_user_indexes i
  JOIN pg_index USING (indexrelid)
WHERE
  indisunique IS false
ORDER BY idx_scan,relname;

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:17 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
closing because of missing pickup
