### ISSUE TITLE
Publish to Docker Registry

### ISSUE THREAD

**Issue by bufferoverflow** [fossology/fossology#674]
I currently have some issues to setup the automated build to the docker registry, I can not pull from https://github.com/fossology/fossology/ only from https://github.com/bufferoverflow/fossology/ with the automated build feature. I currently see the following options:
* push manually and forget about automated build for the moment
* ask docker people how to fix
* integrate with travis and push from there

@maximilianhuber @mcjaeger Could you please provide me your https://hub.docker.com username so I can add you as owner.

The big question is when do you plan to announce the RC or release?

**Comment by bufferoverflow** [comment]
I found the issue!
The build is queued: https://hub.docker.com/r/fossology/fossology/builds/

**Comment by maximilianhuber** [comment]
My account at hub.docker.com is **maximilianhuber**

**Comment by mcjaeger** [comment]
mine is mcjaeger same as with github, mcj do not work :(

**Comment by bufferoverflow** [comment]
just added you as owners!

**Comment by maximilianhuber** [comment]
We have tagged 3.1.0rc1 today. Will there automatically be a docker image related to this tag or does one have to trigger this by hand?

**Comment by bufferoverflow** [comment]
I've just added it here
https://hub.docker.com/r/fossology/fossology/~/settings/automated-builds/

might be that it get triggered automatically, we have to learn and figure out.

PS: I recommend to prefix the tag with v as described here http://semver.org/ 

according to semver the tag would look like `v3.1.0-rc.1`

**Comment by maximilianhuber** [comment]
that is a good suggestion. I have tried to be consistend with the previous tags.

**Comment by bufferoverflow** [comment]
I think it is more important to look forward and adopt best practices. Sometimes we just have to break consistency with old stuff and introduce new things and ways.
