### ISSUE TITLE
missing module conf files after source install

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#68]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1773, http://www.fossology.org/issues/1773
Original Date: 2012/04/10
Original Assignee: Bob Gobeille

---

Running cluster configuration tests from 2.0 source install (http://www.fossology.org/projects/fossology/wiki/Cluster_Test_Cases#Cluster-configuration-tests-Verify-agents-run-on-systems-as-configured)
fossology.log reports missing module conf files:

2012-04-10 11:55:11 scheduler [575] :: CONFIG: Could not find /usr/local/etc/fossology/mods-enabled/www/www.conf
2012-04-10 11:55:11 scheduler [575] :: CONFIG: Could not find /usr/local/etc/fossology/mods-enabled/scheduler/scheduler.conf
2012-04-10 11:55:11 scheduler [575] :: CONFIG: Could not find /usr/local/etc/fossology/mods-enabled/debug/debug.conf

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/04/12 20:35:08 +0000

---

Assigning to Mary so we have somebody looking at it.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/04/12 20:45:31 +0000

---

Moving to 2.0.1 since this isn't high/urgent.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2012/06/06 08:55:37 +0000

---

These three module didn't need module conf files, need to ask Alex how to handle this.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dong Ma** 
Original Date: 2012/06/11 23:55:06 +0000

---

Re-assigned to Bob

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/06/14 23:29:42 +0000

---

defer till next iteration

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2012/08/20 18:35:06 +0000

---

During startup, the scheduler reads the config file for each agent it initializes, INCLUDING www.conf, scheduler.conf and debug.conf.  However, config files for these 3 agents are not necessary and therefore, do not exist.  To address this issue, I suggest putting a stub file in the appropriate /usr/local/etc/fossology/mods-enabled/ directories to eliminate this confusing message.  This will maintain the mods_enabled structure without requiring startup code changes for special cases.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:17 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
requires testing in cluster mode.

**Comment by mcjaeger** [comment]
actually installed from source a numerous times now (vagrant based build) and did not see this error anymore in the `/var/log/fossology/fossology.log` - must have been fixed in the meantime.

tested with `Version: [3.4.0], Branch: [master], Commit: [#6ad6a1]`
