### ISSUE TITLE
"My Recent Jobs" list is empty for all non administrative users

### ISSUE THREAD

**Issue by gmeinwik** [fossology/fossology#681]
Version 3.1.0rc1, commit: [#ac9710]

The "My Recent Jobs" list  is empty for any user. User fossy or any user with administrative privileges can list all of his own jobs and also those jobs belonging to other (non administrative) users with selecting "All Recent Jobs".

**Comment by maximilianhuber** [comment]
This should already be fixed by https://github.com/fossology/fossology/pull/676 which is newer then your mentioned commit hash. Please reopen this issue if the problem still persists.
