### ISSUE TITLE
Project Builder Install, Modifications Required

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#688]
For improving on the package builder based build, the RPM has been improved. However, everything in the spec for the rpm package build, must be also applied to corresponding files for other distros.

For example: When building the packages, the composer must be installed. that could be added to the spec file (the build file for rpms), but the php/phar dependency is missing. It should be added for all package build descriptions. (see spec file rpm/fossology.spec).

Another issue is to have the composer install in the make file placed in src/, not putting the composer install in the package spec. (The developer should care for build dependencies from a package building perspective). It is tricky however, to have a dependency on a working Internet connection.= on build.

**Comment by bcornec** [comment]
There are for m some rules that should be respected:
1/ Buildig packges should "jut" consists into invoking the standard instll procedure of the project
2/ Building the software should be possible without Internet access at build time (means reproduceability)
3/ Dependencies should be provide as packages: either pre-existing one in your distro or in repository made extra for this distro (and documented in the buld process) or fossology should provide them under a packaged format in its own repo.

So here for me we should provide a version of composer.phar as part of the project. We may have a script to update it on a regular basis, but I consider it as a source file somehow that can be prt of the tree.
Another approach could be to provide it as a fossology-composer package, put a dependency on it in the other packages  and maintain it separately again from time to time.

I leave the decision to people more aware of the build process than myself of course.
