### ISSUE TITLE
Update README.Debian file 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#69]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 1803, http://www.fossology.org/issues/1803
Original Date: 2012/04/11
Original Assignee: Bob Gobeille

---

http://fossology.svn.sourceforge.net/viewvc/fossology/branches/fossology2.0/fossology/packaging/debian/fossology-common.README.Debian

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:17 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Mary Laser** 
Original Date: 2013/01/08 19:32:53 +0000

---

update/investigate this issue

**Comment by mcjaeger** [comment]
it should be updated:
https://github.com/fossology/fossology/tree/master/debian
