### ISSUE TITLE
Source Code install of 3.1.0-rc2 on Debian 8 fails for composer error

### ISSUE THREAD

**Issue by gmeinwik** [fossology/fossology#690]
Using a fresh installation of Debian 8 and latest version 3.1.0-rc2 as source install

running fo_installdeps fails for requiring postgres version 9.3 - but with latest updates installed postgres is version 9.4 now (editing file fo-installdeps to address version 9.4 solves this issue)

command "make" succeeds without error

command "make install" fails with the following error message:

current dir: '/home/gmeinwik/fossology-3.1.0rc2/src'
/usr/bin/install -D -m 644 composer.json composer.lock /usr/local/share/fossology
(cd /usr/local/share/fossology; composer install -q --no-dev)
Makefile:81: recipe for target 'composer_install' failed
make[1]: Leaving directory '/home/gmeinwik/fossology-3.1.0rc2/src'
Makefile:45: recipe for target 'install-src' failed

**Comment by mcjaeger** [comment]
Could you pls. try to execute "composer install -q --no-dev" in ""cd /usr/local/share/fossology"" directly and see what happens? You need to be in the dir where the composer.lock file is

**Comment by gmeinwik** [comment]
Hello Michael,

I tried to execute the compoaer command from the specifies directory, but
get the error message:

composer: command not found

Maybe I have a different problem in my installation? I followed the
instructions character by character!

What could I check now?

Best regards

Am 02.09.2016 16:14 schrieb "Michael" <notifications@github.com>:

**Comment by bcornec** [comment]
I think this is the same issue I've encounterd during package build.
You may want to look at my spec file which fixes the issue here: https://github.com/fossology/fossology/blob/f754272cfdecbb76b74b44f6e4621d55e4ead3b7/pbconf/fossology/rpm/fossology.spec 
and also this Bug Report: #692

**Comment by gmeinwik** [comment]
Yes, #692 describes exactly my problem. We use a man-in-the-middle proxy, which prevents the composer download.
Thanks for pointing to this issue.
When is it planned to include the composer into the package?

**Comment by heckj** [comment]
possibly related - I'm also behind a MITM firewall, and using the `docker-compose up` installation instructions in the README for this repo, the process failed on the `composer install` components as well:

```
/usr/bin/install -D -m 644 composer.json composer.lock /usr/local/share/fossology
(cd /usr/local/share/fossology; /tmp/composer/composer install -q --no-dev)
Makefile:87: recipe for target 'composer_install' failed
make[1]: Leaving directory '/fossology/src'
Makefile:45: recipe for target 'install-src' failed
/bin/sh: 1: /tmp/composer/composer: not found
make[1]: *** [composer_install] Error 127
make: *** [install-src] Error 2
ERROR: Service 'fossology-scheduler' failed to build: The command '/bin/sh -c set -x  && make install  && make clean' returned a non-zero code: 2
```

This was from the master branch at commit #f5ca99e91

**Comment by bcornec** [comment]
This may be linked to a recent change we did to separate composer download from composer usage.

To do that we created a new target composer_download which creates the composer binary under the /tmp. So the Dockerfile needs to be now adapted to make that work. I made the PR #731 to solve this problem.

**Comment by armijnhemel** [comment]
Is the fix for the Docker file the same for source code installs?

**Comment by leorthur** [comment]
I have the same issue, it still not working

**Comment by armijnhemel** [comment]
The latest Git seems to fix this issue for me.

**Comment by armijnhemel** [comment]
issuing "make composer_download" first fixes it for me (although doing it as root makes my skin crawl)

**Comment by mcjaeger** [comment]
test with (fresh) debian 8.7.1 current so install works now. recent pull request #738 seemed to have solved this issue.
