### ISSUE TITLE
Run Docker container as unprivileged user

### ISSUE THREAD

**Issue by bufferoverflow** [fossology/fossology#695]
The Docker container does not run as fossology user today, which is best practice, see https://docs.docker.com/engine/reference/builder/#user

**Comment by maximilianhuber** [comment]
In fact, the scheduler runs as user fossy which is created by the call [/docker-entrypoint.sh#L58](https://github.com/fossology/fossology/blob/c3929070ea1c555f0b2137ffcad2e1aea4a84f49/docker-entrypoint.sh#L58). This is handled by the service.

But apache is running as root.

In fact I am currently refactoring the compose setup to split the apache into its own container. Further is the repository currently not persistent in the container.

--

My suggested changes, which fix some of the above mentioned problems and do not rely on services running within containers, are found at in my repository as branch [dev/refactorDockerSupport](https://github.com/maximilianhuber/fossology/tree/dev/refactorDockerSupport). (There is still apache running as root)

These changes
- split the container into multiple ones:
  - one for the scheduler
  - one for the apache
  - one for the SW360 connection (not implemented yet) 
- (currently) break the support for running docker without compose.

**Comment by koa** [comment]
With some few modifications the apache can be started as user fossy

- chown to fossy of 
  - /var/run/apache2/
  - /var/lock/apache2/
  - /var/log/fossology
- use a non priviledged port (8080) for apache

But there is another problem: the fo-postinstall.sh (needed for initialize the database) need root to start.
Solution: 
- Skip root validation if there is only database initialitation
- do the rest of initialitations while building docker image (as root)

**Comment by bufferoverflow** [comment]
@maximilianhuber any update on this? Enable the Docker image able to run as unprivileged user before splitting into several containers makes sense.

**Comment by maximilianhuber** [comment]
@bufferoverflow: Sorry, but the PR #697 has some problems which could not yet been resolved.

Maybe one could extract the necessary changes as you have suggested. But the splitting of the containers is a necessary step, to enable connection to SW360. It also improves the logging (the scheduler log is captured by docker-logs) and makes it more modular.

**Comment by maximilianhuber** [comment]
the PR #697 also makes the fossology repository a volume, which allows to use the docker instance productively: not all uploaded files get removed after restart.

**Comment by bufferoverflow** [comment]
:+1: for the repository volume

**Comment by max-wittig** [comment]
should be resolved with the merge of PR #758
