### ISSUE TITLE
source install from tar.gz fails for 3.0.0

### ISSUE THREAD

**Issue by chindro** [fossology/fossology#698]
I downloaded 3.0.0 as a tar.gz from: https://github.com/fossology/fossology/releases/tag/3.0.0
I'm running debian 8.5.

Steps I did:
1 run utils/fo-installdeps
2 make
 -> an error is showing up: `pg_config: command not found`
 --> I fixed it by installing the package "libpq-dev" manually
3 make install
 ->`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.` and after some time there is this message: 

```
[RuntimeException]
  Failed to execute git checkout '84c0c150c1520995f09ea9e47e817068b353cb0f' -- && git reset --hard '84c0c150
  c1520995f09ea9e47e817068b353cb0f' --
  fatal: reference is not a tree: 84c0c150c1520995f09ea9e47e817068b353cb0f
```

Calling git seems rubbish as I didn't cloned the sources via git.

**Comment by mcjaeger** [comment]
please use 3.1rc2 instead. runs at least for debian 8.7
