### ISSUE TITLE
the -P option for fossjobs is just one placeholder

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#70]
---

Author Name: **larry shi** 
Original Redmine Issue: 1941, http://www.fossology.org/issues/1941
Original Date: 2012/05/10

---

I looked through -P option in the original code and 2.0 code, -P option for fossjobs is just one placeholder.

-P priority for the jobs

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:20 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
The -P option is not implemented, and apparently there is not much demand for this.

/src/cli/fossjobs.php
