### ISSUE TITLE
Link from Install from Source to Configuration and Tuning

### ISSUE THREAD

**Issue by saturnjct** [fossology/fossology#702]
Please make the change found here:

https://github.com/saturnjct/fossology/wiki/Install-from-Source/_compare/f762d240b7c43b773bb1e25b56b0f9bd190d2400...9c3daa67f8481663a2165119ff800359fcf12fb1

If only I had a way of doing a pull request for the Wiki.

**Comment by maximilianhuber** [comment]
Thank you for mentioning this typo. It is fixed.
