### ISSUE TITLE
Fix install docs link in `README.md`

### ISSUE THREAD

**Issue by silverhook** [fossology/fossology#708]
In the `README.md`, specifically under the the [Installation](https://github.com/fossology/fossology#installation) header, it seems to me that the link:

> For installation instructions see http://www.fossology.org/projects/fossology/wiki

should be replaced with the newer, e.g. by changing that line to:

> For further installation instructions see the hands-on documentation: https://wiki.fossology.org/handson#fossology_installation

**Comment by mcjaeger** [comment]
not quite. It would be better to take the version in the github wiki and enhance this further:

https://github.com/fossology/fossology/wiki/Install-from-Source

**Comment by silverhook** [comment]
Even better :)

**Comment by mcjaeger** [comment]
closed by !756
