### ISSUE TITLE
any method to add a fresh user except through GUI?

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#71]
---

Author Name: **larry shi** 
Original Redmine Issue: 1953, http://www.fossology.org/issues/1953
Original Date: 2012/05/14
Original Assignee: Bob Gobeille

---

any method to add a fresh user except through GUI?

if one user want to upload something through cp2foss, have to pass the authentication, but you know, 
after one user install fossology, there is not any user in USER table till the user visits UI(http://hostname/repo/), adding fossy/fossy.

also for test automation, after running testing/db/createTestDB.php, create one new DB and sysconf, you can not visit the GUI, so there is not any user in USER table,
more details according to your respone if needed.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:21 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by steffen-weber** [comment]
With 5b1b2725fc3382bbe42fcdef06fa4cb5150bfecd, fossinit calling Migrate_21_22 which creates user fossy.
