### ISSUE TITLE
Unable to install Fossology in 16.04 LTS

### ISSUE THREAD

**Issue by sheriffmanzoor** [fossology/fossology#714]
Hello,
            I am trying to install Fossology in my laptop which has Ubuntu 16.04 LTS. But I am unable to install due to some dependency issue. Has any one tried to install the Fossology in 16.04 LTS machine? If so please, then support me in the installation process.

Thanks
Manzoor

**Comment by bufferoverflow** [comment]
I did not but this should help https://github.com/fossology/fossology/blob/master/Vagrantfile

**Comment by sheriffmanzoor** [comment]
Thank you very much for your help. But i reinstalled my laptop with 14.04
since i have a stable support with this ubuntu version

**Comment by bcornec** [comment]
The dev/xenial branch should fix the installation issue on Ubuntu 16.04 for postgres
