### ISSUE TITLE
Detecting cases of "Copyright: ACME Ltd."

### ISSUE THREAD

**Issue by maxbrito** [fossology/fossology#719]
Hello,

It seems that a copyright declaration using a text line mentioning "**Copyright: ACME Ltd**" is not being detected.

Perhaps it can be added?

Many thanks!

**Comment by bufferoverflow** [comment]
patches are always welcome!

**Comment by nunobrito** [comment]
Would be happy too. But once started, would likely rewrite the kernel and no longer could the project be called fossology. :-) Maybe easier to just add a new regex on the copyright filter.

**Comment by bufferoverflow** [comment]
Yes, add a new regex sounds like a plan. 

recreate the world is usually more difficult than evolution...

**Comment by mcjaeger** [comment]
I did not believed that this was actually an issue. Now with proof:

<img width="451" alt="screen shot 2018-07-09 at 22 38 27" src="https://user-images.githubusercontent.com/3418977/42474778-e3fd6b72-83c8-11e8-8d54-e30daa04ca48.png">
