### ISSUE TITLE
Check for apache configuration for 2.4

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#728]
There is a new configuration style for apache 2.4. more on this here

http://serverfault.com/questions/549517/what-does-apaches-require-all-granted-really-do#549559

and here:

https://httpd.apache.org/docs/2.4/upgrading.html

Basically, it is about checking the configuration directives for the `fo-apache.conf` or `fossology.conf` virtual server configuration. Should be `Require all granted` instead the old ones. 

Workaround is to apply the modification manually.

Seen on Ubuntu 14.04 and CentOS7, presumably valid for other distros as well.

**Comment by maximilianhuber** [comment]
fixed by https://github.com/fossology/fossology/pull/734/files
