### ISSUE TITLE
code duplication cp2foss fossjobs

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#73]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 1983, http://www.fossology.org/issues/1983
Original Date: 2012/05/16
Original Assignee: larry shi

---

All the authentication code is duplicated in cp2foss and fossjobs.  This is a bad programming practice.  Make the authentication code a separate function.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:22 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
some folks run PHPCPD by Seb Bergmann 2.0.4 and it does not detect it, it is maybe just the case that each of these tools have their own auth routines and just do not use a common module.

**Comment by mcjaeger** [comment]
I am not sure if something will happen w.r.t. this issue
