### ISSUE TITLE
./scheduler/agent/fo_scheduler can not accept -c sysconfdir to run

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#74]
---

Author Name: **larry shi** 
Original Redmine Issue: 2007, http://www.fossology.org/issues/2007
Original Date: 2012/05/18
Original Assignee: Alex Norton

---

tested in svn 5867.
because this issue, I can not switch the default DB and sysconfdir my DB and sysconfdir, 
so can not test cp2foss and fossjobs properly.

also if create your DB and sysconfdir mannuly via ./testing/db/createTestDB.php, 
DB is fosstest2051435647, sysconfdir is:/srv/fossology/testDbConf2051435647/Db.conf
then want to stop the running scheduler, and run /usr/local/share/fossology/scheduler/agent/fo_scheduler --daemon --reset --verbose=1 -c /srv/fossology/testDbConf2051435647

it does not work, is not using you DB and sysconfdir.

it seems that the reason is because :

in scheduler/agent/database.c

/**
- Initializes any one-time attributes relating to the database. Currently this
- includes creating the db connection and checking the URL of the fossology
- instance out of the db.
  _/
  void database_init()
  {
  PGresult_ db_result;
  char _DBConfFile = NULL;  /_ use default Db.conf */
  char *ErrorBuf;
  
  /\* create the connection to the database */
  db_conn = fo_dbconnect(DBConfFile, &ErrorBuf);
  memset(fossy_url, '\0', sizeof(fossy_url));

the sysconfdir is not tranformed to fo_dbconnect(), so in 
fo_dbconnect(), always using the default sysconfdir.

suggestions?

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/05/18 16:08:37 +0000

---

The scheduler will now check the correct system configuration directory when creating the database connection.
This is fixed with svn 5872

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:24 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by bufferoverflow** [comment]
as mentioned by @yaobinshi it's resolved
