### ISSUE TITLE
Invalid 3DFX license info in SPDX:RDF file

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#744]
When scanning a file containing the 3DFX Glide license text (https://spdx.org/licenses/Glide.html), both Nomos and Monk correctly label the license as 3DFX. This can be seen in `?mod=view-license`. When an SPDX:RDF file is generated, the following is written to the file:

`<spdx:licenseInfoInFile rdf:resource="http://spdx.org/licenses/3DFX"/>`

This resource is invalid - it should be `https://spdx.org/licenses/Glide`. This causes problems when analyzing the file with spdx tools, as it does not recognize the license. Manually editing the RDF file to use the correct resource link fixes the problem.

Tested on: Version: [3.1.0rc2], Branch: [master], Commit: [#3b080b]

**Comment by maximilianhuber** [comment]
Yes you are right. The shortname of [3dfx Glide License](https://spdx.org/licenses/Glide.html) should be Glide
