### ISSUE TITLE
Inconsistent license naming in FOSSology and SPDX file

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#746]
LicenseRef licenses are listed without the "LicenseRef-" prefix on the FOSSology UI, but the prefix is kept in the generated SPDX file. This can cause confusion when analyzing files/projects with many licenses.

For example, when analyzing the file https://github.com/fossology/fossology/raw/master/install/db/licenseref.sql and generating an SPDX:RDF file, the file contains (among others):

 - GPL-2.0
 - GPL-2.0-with-bison-exception
 - LicenseRef-GPL-2.0+-with-bison-exception
 - LicenseRef-GPL-2.0+-with-classpath-exception
 - GPL-2.0-with-classpath-exception

Should the "LicenseRef-" prefix be removed in SPDX files, as it is in the UI? This would make it easier to compare the licenses using alphabetical ordering or string comparisons, for example.

**Comment by maximilianhuber** [comment]
The SPDX standart says that you are only allowed to drop the `LicenseRef-` prefix if the license is listed at https://spdx.org/licenses/.

The better solution would be, to ignore the prefix in your alphabetical ordering

**Comment by timurphy** [comment]
Thanks @maximilianhuber. Does that mean the prefix should be kept in the FOSSology UI? It's currently being stripped when using the license browser.

**Comment by maximilianhuber** [comment]
I do not think that this would be good. But we can discuss it. @mcjaeger what do you think?

**Comment by mcjaeger** [comment]
I think if we follow the SPDX stadard at this point, the prefix `LicenseRef-` is coming at a large number of licenses when presenting scanner findings. attached a screenshot to show this:

![036 oss fossy 20170220 screenshot fossology license ref prefix question](https://cloud.githubusercontent.com/assets/3418977/23134225/48e7fa6a-f794-11e6-9830-68358665baa8.png)

**Comment by timurphy** [comment]
Understood. Thanks for clarifying.
