### ISSUE TITLE
SPDX license names should not be url encoded

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#747]
Some SPDX licenses contain the `+` character, such as https://spdx.org/licenses/GPL-2.0+. When these licenses are found, the generated SPDX file contains the license ref with URL encoding (`%2B` instead of `+`):

`<spdx:licenseInfoInFile rdf:resource="http://spdx.org/licenses/GPL-2.0%2B"/>`

The SPDX standard defines the license name format in appendix IV. Essentially, the idstring can only contain characters `1*(ALPHA / DIGIT / "-" / "." )`, with some possible decorations. Trailing `+` characters are permitted:

`An SPDX License List Short Form Identifier with a unary"+" operator suffix to represent the current version of the license or any later version.  For example: GPL-2.0+`

Currently this is url encoded (code [here](https://github.com/fossology/fossology/blob/e65e734093a5376fa41c51cba03fbf07d173dea9/src/spdx2/agent/template/spdx2-file.xml.twig#L47)), which converts the `+` character. This makes the file invalid, and breaks spdx tools.

**Comment by mcjaeger** [comment]
(still there in 3.4)

**Comment by maxhbr** [comment]
> Currently this is url encoded (code here), which converts the + character. This makes the file invalid, and breaks spdx tools.

It is correct to apply url encoding to a url and might be necessary since we write more than only the allowed identifiers to some urls. If spdx-tools can not handle urls with urlencoding this is a bug in spdx-tools.
