### ISSUE TITLE
Incorrect link on the Duplicate Bucketpool page

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#75]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 2019, http://www.fossology.org/issues/2019
Original Date: 2012/05/19
Original Assignee: Mary Laser

---

The page displayed by http://<hostname>/repo/?mod=admin_bucket_pool, Duplicate Bucketpool, has an incorrect link.  "Creating Bucket Pools" points to http://fossology.org/buckets.

I _think_ it's suppose to point to http://www.fossology.org/projects/fossology/wiki/Buckets

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:39:15 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Guttmann** 
Original Date: 2013/05/30 12:28:10 +0000

---

Link fixed in svn 6660

**Comment by bufferoverflow** [comment]
as mentioned by @yaobinshi it's resolved
