### ISSUE TITLE
Only part of files contained in RPM are unpacked.

### ISSUE THREAD

**Issue by nobuoimada** [fossology/fossology#752]
When I upload "logstash-5.1.2.rpm" (URL: https://artifacts.elastic.co/downloads/logstash/logstash-5.1.2.rpm), 76 items are unpacked. This RPM file actually contains 50,000+ items. It seems that only files under usr/share/logstash/logstash-core/lib/com/fasterxml/jackson/core/jackson-annotations/2.7.0/jackson-annotations-2.7.0.jar are unpacked and others are ignored.

Tested on: Version: [3.1.0rc2], Branch: [pr/706], Commit: [#720af8]
(downloaded as a VM from https://wiki.fossology.org/handson)

**Comment by armijnhemel** [comment]
Just a suggestion for mcjaeger: perhaps recursion doesn't work correctly in traverse.c in the ununpack agent and it goes to TraverseEnd too soon?

**Comment by nobuoimada** [comment]
I tested this with Version: [3.4.0], Branch: [master], Commit: [#07ac3e] (installed from source code). The file "logstash-5.1.2.rpm" is unpacked correctly. My apologies for taking long time to respond.

**Comment by nobuoimada** [comment]
I would like to close this issue although I don't know if I have the authority to do that.
