### ISSUE TITLE
test system pulls test data from fonightly

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#76]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 2037, http://www.fossology.org/issues/2037
Original Date: 2012/05/22
Original Assignee: Dan Stangel

---

By pulling test data from fonightly we disallow any non-HP person from running tests.  As an open source project this is unacceptable.  The test data should be hosted on fossology.org.

I ran into this in src/ununpack/agent_tests/Unit/Makefile but it probably exists elsewhere as well.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dan Stangel** 
Original Date: 2012/06/18 21:46:05 +0000

---

Fixed in svn 5958.  I modified the Makefiles for the affected functional and unit tests (delagent, nomos, and ununpack) so that they retrieve remote test data files from fossology.org.

I also copied the files into the appropriate URLs on fossology.org

I also changed the retrieval mechanism from using rsync to using wget.

I also configured the Makefiles to look in /var/www/testfiles too, so that for the case when we're running tests on our CI server, it will not constantly be retrieving the same files over and over from fo.org.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/07/10 16:40:45 +0000

---

Tested on svn 6011.  make test gives warnings:
```
make -C ../../agent// all
make[1]: Entering directory `/home/bobg/fossology/trunk/fossology/src/ununpack/agent'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/bobg/fossology/trunk/fossology/src/ununpack/agent'
Retrieve test files
../unpack-test-data.tar.bz2 exists
ununpack agent functional test
cd ..; \
	tar -xf unpack-test-data.tar.bz2; \
	cd ./Functional; \
	phpunit --log-junit ununpack-Xunit.xml --configuration tests.xml 
PHPUnit 3.4.14 by Sebastian Bergmann.

Starting test functional ununpack agent 
....F.........WARNING pfile (null) Unable to extract permission
LOG pfile (null) WARNING: Unable to extract permission from ./test_result/ntfstest-image.dir/$Boot
..ending test functional ununpack agent 
.test unpack with an invalid parameter
.

Time: 34 seconds, Memory: 7.00Mb
```

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dan Stangel** 
Original Date: 2012/08/01 00:27:16 +0000

---

Dan needs to investigate and determine if this failure is related, or else file a new defect & update this one.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Dan Stangel** 
Original Date: 2012/08/02 15:56:54 +0000

---

Oops, put the estimate in the wrong field.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:26 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
not updated for a long time, guess this is lost.
