### ISSUE TITLE
Verbosity for an agent cannot be changed using the UI or fo_cli

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#77]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 2055, http://www.fossology.org/issues/2055
Original Date: 2012/05/24

---

I wanted to increase the verbosity for wget_agent during testing.  There are several calls to LOG_VERBOSE0, but I can't see a way to turn it on.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/08/06 19:19:39 +0000

---

Changing the verbosity of an agent is enabled through the cli at the very least. I do not know if the ui has implemented this feature yet.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Alex Norton** 
Original Date: 2012/08/06 19:19:51 +0000

---

changing version

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:27 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2013/09/23 22:35:26 +0000

---

This was marked as resolved a year ago.  Could you please test and close?  If it is not resolved, please change the assignee to Vincent or Larry and mark it new or in progress.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/11/25 08:00:18 +0000

---

I did testing long time ago, I can not list all the problems right now, just say this job is not finished.
possibly will fix it in next release.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/03/04 09:40:35 +0000

---

this issue is not critical, so shit it to next release.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2014/05/07 08:46:57 +0000

---

bob, do you think this issue is critical or not? 
this issue need a little more rework of agents.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2014/05/07 20:16:44 +0000

---

While this functionality was put into the scheduler in 2.1.0, the agents were never modified to use it.  Specifically, for the agents that only get a single upload_pk from the scheduler, they need to also call fo_scheduler_next() while processing the upload.  And that call should not block.  The idea is that the scheduler should be able to communicate with the agent while it is processing.  Although it would be very handy to turn verbosity on and off while an agent is running, I wouldn't call this critical.  There is also a performance cost for putting calls to fo_scheduler_next() in our processing loop.

**Comment by mcjaeger** [comment]
closing because of missing pickup
