### ISSUE TITLE
The package install automation page needs review and updating

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#78]
---

Author Name: **Mary Laser** 
Original Redmine Issue: 2085, http://www.fossology.org/issues/2085
Original Date: 2012/06/04
Original Assignee: Dong Ma

---

http://www.fossology.org/projects/fossology/wiki/Package_Install_Automation

**Comment by maximilianhuber** [comment]
The link is dead.

@mcjaeger: is this object migrated to the github wiki?

**Comment by pguttmann** [comment]
OK. I just "migrated" 3 pages from the redmine wiki to github wiki :
1. https://github.com/fossology/fossology/wiki/Package-Install-Automation
2. https://github.com/fossology/fossology/wiki/Package-Install-Testing
3. https://github.com/fossology/fossology/wiki/List-of-VM-Systems

Note that many embedded links in these pages refer to HP internal systems though...

**Comment by maximilianhuber** [comment]
@pguttmann : are this all pages and can we close that issue?

**Comment by pguttmann** [comment]
I guess "needs review and updating" still needs to be done. Presumably by someone familiar with the new/migrated build process we'll use moving forward.

**Comment by mcjaeger** [comment]
on a first look, it contains references to some machines from HP. maybe closing this for now.
