### ISSUE TITLE
db check too slow

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#79]
---

Author Name: **Bob Gobeille** 
Original Redmine Issue: 2097, http://www.fossology.org/issues/2097
Original Date: 2012/06/06

---

Ray Westphal mentioned that db check took 20 hours to complete (the UI timed out long before it was done).

Obviously, we need to run this from an agent.

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Bob Gobeille** 
Original Date: 2012/10/08 18:35:28 +0000

---

Change unranked issues to rank 99 so they show up in a ranking report at the bottom.  Otherwise, they show up on top.

**Comment by mcjaeger** [comment]
closing because of missing pickup
