### ISSUE TITLE
use editorconfig 

### ISSUE THREAD

**Issue by bufferoverflow** [fossology/fossology#794]
I think it would make sense to add an [editorconfig](http://editorconfig.org/) file to the project and use e.g. https://github.com/jedmao/eclint within the travis the check conformance. We use this on several projects and made good experiences.

**Comment by maximilianhuber** [comment]
> ... within the travis the check conformance.
Does Travis then only check the diff or all the code?

**Comment by bufferoverflow** [comment]
We can introduce it step wise, e.g. selenium tests, later the php code, etc.

```
  - npm install -g eclint
  - eclint check * "src/testing/selenium/**/*.js"
```
