### ISSUE TITLE
Syntax error in Autoload.php

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#795]
Syntax error found on master, which has been there for a few years:

```
$ find . -name \*.php -type f | xargs -L1 php -l | egrep -v '^No syntax errors detected in'

Parse error: parse error, expecting `')'' in ./src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php on line 31
Errors parsing ./src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php
```

This is an array declaration with a trailing comma and no `)` character. Is this file used anymore? Has the file been truncated at some point?

It might be worth running `php -l` on all php files as part of the build to pick up these errors.

**Comment by bufferoverflow** [comment]
The issue is within a testdata file, no problem. But I agree check files with such a command could make sense.

**Comment by timurphy** [comment]
The command above stopped scanning on first error. Other files also have syntax errors, though it looks like they are all test files:

```
Parse error: parse error, expecting `')'' in ./nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php on line 31
Parse error: parse error, expecting `"function (T_FUNCTION)"' in ./nomos/agent_tests/testdata/NomosTestfiles/Unlicense/bitcoin.php on line 260
Fatal error: Call-time pass-by-reference has been removed in ./testing/lib/fossologyTest.php on line 494
```

**Comment by timurphy** [comment]
I've written a script which runs a syntax check over all PHP files in `src`. Where should this be hooked into the build?
https://github.com/timurphy/fossology/blob/php_syntax_check-mur399/src/testing/syntax/syntaxtest.sh

**Comment by max-wittig** [comment]
Looks good. Maybe you could integrate it into Travis CI to be run, after each commit?
