### ISSUE TITLE
Highlight deleted row for better visiblity

### ISSUE THREAD

**Issue by max-wittig** [fossology/fossology#797]
When clearing in Copyright/Email/URL/Author Browser this feature would be helpful, to avoid mistakes
![image](https://cloud.githubusercontent.com/assets/6639323/24857885/1ef3555c-1dea-11e7-8c41-db80c3abcc91.png)

**Comment by ArijeetBanerjee** [comment]
Hey there 
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it

**Comment by shaheemazmalmmd** [comment]
@ArijeetBanerjee You can look into this issue.

**Comment by Bankar-Swapnil** [comment]
Hello is this issue still available? Can I work on this
