### ISSUE TITLE
Provide training on existing functionality (tagging, etc) 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#80]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2121, http://www.fossology.org/issues/2121
Original Date: 2012/06/12
Original Assignee: Bob Gobeille

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **Paul Holland** 
Original Date: 2012/06/15 18:53:47 +0000

---

Moving down in rank since tagging turned off for now.

**Comment by mcjaeger** [comment]
training is actually provided by the linux foundation, however not for tagging, contributions welcome, however for this specific: closing because of missing pickup
