### ISSUE TITLE
Fail Upload a New File

### ISSUE THREAD

**Issue by allen7lee** [fossology/fossology#816]
source install version 5/02/2017.
Linux trusty 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
When I upload a new file.Then it failed. 
FATAL wget_agent.c.141: upload 16 Failed to import /tmp/phpCQNRBF-uploaded from /tmp/phpCQNRBF-uploaded into repository gold B498E9C5D5DD3D250C0988A286F5961FDF636547.9CA123ABB1D92A075A307C12257C3346.2337

**Comment by max-wittig** [comment]
Could you please provide more information or a way to reproduce this issue. Thanks

**Comment by mcjaeger** [comment]
hello, thanks for you comment, could you pls. help: what exactly did you try to upload and which method did you choose?

**Comment by allen7lee** [comment]
upload a file from local host of Ubuntu.

**Comment by max-wittig** [comment]
Could you please provide the following information:
* The file you tried to upload (the exact file if possible or where you downloaded it from)
* The version of FOSSology you used
* Which browser you used

These information will help us fix the problem.
Thanks for your help

**Comment by allen7lee** [comment]
I try any files of my computer txt, .java and so.
The version is source  git get from 5/02/2017.
firefox brower
upload new file from local host

**Comment by danielursuu** [comment]
I think that @allen7lee  wanted to say that fossology can't upload a single file for scanning, but only archives. Sometimes also I want to upload a file in order to scan it, but I need to compress it. Can it be fixed? Thank you.

**Comment by max-wittig** [comment]
You can upload single files for scanning. You don't need to compress anything

**Comment by danielursuu** [comment]
@max-wittig, you are right! I found it, in File Browser. Thanks!

**Comment by mcjaeger** [comment]
@allen7lee Ok for closing?

**Comment by allen7lee** [comment]
I git the new source zip.Then reinstall it ,but the bug do not fix.How can I check it ?

**Comment by max-wittig** [comment]
If you could describe the bug in more detail that would help us understand and fix the issue.
It does sound like a problem with your local fossology instance.

**Comment by max-wittig** [comment]
We also got a workflow, which describes how the basics of fossology work on [fossology.org](https://www.fossology.org/get-started/basic-workflow). Hope this is helpful to you
@allen7lee

**Comment by mcjaeger** [comment]
@allen7lee I do not think that there is a general problem, but did you use these steps to install it?

https://github.com/fossology/fossology/wiki/Install-from-Source

**Comment by allen7lee** [comment]
Yes. I used these steps .But I get these info:
/usr/bin/install -D -m 644 composer.json composer.lock /usr/local/share/fossology
(cd /usr/local/share/fossology; export COMPOSER_HOME=/dev/null; composer install -q --no-dev)
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

**Comment by allen7lee** [comment]
If I try run  # make composer_download
make -C ./src composer_download
make[1]: Entering directory `/home/zte/fossology/src'
make[1]: *** No rule to make target `composer_download'.  Stop.
make[1]: Leaving directory `/home/zte/fossology/src'
make: *** [composer_download] Error 2
 
**Nobody just try to use these steps?!**

**Comment by allen7lee** [comment]
Error again
![error](https://user-images.githubusercontent.com/17740596/27568908-229554b0-5b27-11e7-9223-d651af39e8df.png)

**Comment by max-wittig** [comment]
You don't actually need to run the composer steps anymore. If you use the wiki in the Install from Source section there is an (only for old versions) hint. 
I tried these steps recently again with a clean debian 8 instance. Works just fine. 

Are you really using the fossology github wiki? `Install from source` section?

**Comment by allen7lee** [comment]
@max-wittig  I just try PR #859  again, but fail to upload a new file again.
 /etc/init.d/apache2 restart
 * Restarting web server apache2                                               [Tue Jun 27 14:32:41.178260 2017] [alias:warn] [pid 29799] AH00671: The Alias directive in /etc/apache2/sites-enabled/fossology.conf at line 3 will probably never match because it overlaps an earlier Alias.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

**Comment by max-wittig** [comment]
You can try these commands for testing (not production), but the installation of 3.1 works without these normally:
<pre>
sudo chmod 777 /usr/local/etc/fossology/Db.conf 
sudo chmod -R 777 /var/local/cache/fossology
sudo chmod -R 777 /srv/fossology/
</pre>

**Comment by allen7lee** [comment]
error again.I had restarted fossology server.

**Comment by max-wittig** [comment]
And didn't it work? If you goto 127.0.0.1/repo?

**Comment by allen7lee** [comment]
![error2](https://user-images.githubusercontent.com/17740596/27577594-e80f413e-5b53-11e7-80c8-618a42b6f4f5.png)

**Comment by allen7lee** [comment]
It don't work.

**Comment by GMishx** [comment]
Hello @allen7lee,
Are you still facing the same issue? If yes, can you please send the following information?
1.  `ls -l` on `/srv/fossology/`, `/srv/fossology/repository/localhost/gold/`
1.  `groups www-data`

**Comment by GMishx** [comment]
Closing the issue for now. Please reopen if issue still exists.
