### ISSUE TITLE
Some cleared licenses are reported incorrectly in SPDX exports.

### ISSUE THREAD

**Issue by swinslow** [fossology/fossology#826]
Issue:
When both (A) an archive contains multiple identical copies of a file, and (B) that file has been identified and cleared using the "Apply decision to all future occurrences of this file" option, then an SPDX export will report incorrect concluded license results for those files.

Steps to reproduce:
1) Upload an archive that contains multiple copies of the same file.  A sample archive is attached as [example.tar.gz](https://github.com/fossology/fossology/files/1007983/example.tar.gz); this archive contains three copies of the same file.
2) In the upload settings, select Monk and Nomos scanning options.
3) After the scan completes, manually go into the license browser and identify one of the files as "BSD".  Select the option "Apply decision to all future occurrences of this file" before hitting submit.
4) The other two identical files should also be cleared and marked as "BSD" in the license browser after this.
5) Go back to the "Browse" tab, and for the example.tar.gz upload, choose "-- select action --" => "Export SPDX tag:value".
6) After the SPDX tag:value report is generated, look at the LicenseConcluded tags for the three files in the archive.  

Expected result:
In the SPDX report, each of the three files should have the tag "LicenseConcluded: LicenseRef-BSD"

Actual result:
In the SPDX report, one of the three files has the tag "LicenseConcluded: LicenseRef-BSD AND LicenseRef-BSD AND LicenseRef-BSD".  The other two files have the tag "LicenseConcluded: NOASSERTION".

A copy of the SPDX report is here: [SPDX2TV_example.tar.gz_1495029013.txt](https://github.com/fossology/fossology/files/1008007/SPDX2TV_example.tar.gz_1495029013.txt).

**Comment by swinslow** [comment]
I've confirmed the same behavior is occurring with DEP5 exported reports.  See 
[DEP5_example.tar.gz_1495030615.txt](https://github.com/fossology/fossology/files/1008021/DEP5_example.tar.gz_1495030615.txt):

    . . .
    Files: example/file2.txt
    License: BSD AND BSD AND BSD
    
    Files: example/file1.txt
           example/file3.txt
    License: NoLicenseConcluded
    Comment: scanners found: NOASSERTION
    . . .

**Comment by mcjaeger** [comment]
I think that DEP5 and SPDX use the same implementation for querying the database so the second observation should be OK (otherwise a fix in one corner maybe forgotten at the other generation format)

**Comment by swinslow** [comment]
Thanks, Michael. Agreed -- when I first reported this issue I wasn't yet familiar with the SPDX and DEP5 implementation in FOSSology.

As I've dug into this further, I believe the problem is not with the SPDX reporting agent itself. The problem seems to be from the getFileClearingsFolder() function in /src/lib/php/Dao/ClearingDao.php (or possibly in the functions that getFileClearingsFolder() itself relies upon). I've opened a separate issue #866 for this problem.

**Comment by swinslow** [comment]
(cross-posting note from #866)

Hello all, I wanted to note that this issue (and/or the related issue #866) still appears to be present at least as of v3.2.0.

As another example, I tested this by running a scan on http://jqueryui.com/resources/download/jquery-ui-1.12.1.zip.  Another user or I may have previously matched the MIT license's standard text using the "Apply decision to all future occurrences of  this file" checkbox. 

After clearing all files in jquery-ui-1.12.1.zip, I then exported an  SPDX tag-value file. Within that file, jquery-ui-1.12.1/LICENSE.txt has  the following line: 
`LicenseConcluded: MIT AND MIT`

When looking into this last year, it had looked like this might be a  problem with what's getting returned from  clearingDao->getFileClearingsFolder(). Is anybody who's more familiar  with that code seeing similar problems?

**Comment by mcjaeger** [comment]
I have seen this too.

**Comment by swinslow** [comment]
Hi @GMishx, I'm no longer using Fossology regularly, so you (or others who have observed this issue) may want to retest to confirm whether it is still present. Thanks!

**Comment by shaheemazmalmmd** [comment]
Fixed with latest changes of SPDXID on latest master.
