### ISSUE TITLE
Update password hashing algorithm

### ISSUE THREAD

**Issue by max-wittig** [fossology/fossology#841]
SHA-1 was officially deprecated by NIST in 2011
<b>src/www/ui/core-auth.php</b>
``` php
if (!empty($row['user_seed']) && !empty($row['user_pass']))
{
      $passwordHash = sha1($row['user_seed'] . $password);
      if (strcmp($passwordHash, $row['user_pass']) != 0)
      {
        return false;
      }
}
```

**Comment by mcjaeger** [comment]
do not forget to write a migration script? 

some more background https://stackoverflow.com/questions/2235158/sha1-vs-md5-vs-sha256-which-to-use-for-a-php-login

**Comment by amanjain97** [comment]
Hi @mcjaeger I want to take up the issue. 
1. Should we use bycrypt (as mentioned above https://stackoverflow.com/questions/2235158/sha1-vs-md5-vs-sha256-which-to-use-for-a-php-login )as the updated tool for password hashing
2. How can migrate the passwords without the Migration script?

**Comment by amanjain97** [comment]
For migration script:  
http://php.net/manual/en/function.password-needs-rehash.php
- If the saved passwordHash is matched the output of new hash function then login the user.
- Else check with the old hash output, if it matches, then change the saved passwordHash to new passwordHash.
- Else if it did not match with any of the passwordHash, then user credentials are wrong. 
Please review the approach before making changes. @mcjaeger @max-wittig

**Comment by mcjaeger** [comment]
the approach looks fine for me. pls. consider the seed/salt begin used already

**Comment by Aman-Codes** [comment]
@amanjain97 @mcjaeger Can I work on this task ?

**Comment by GMishx** [comment]
Hello @Aman-Codes , you can certainly start working on this.
