### ISSUE TITLE
Fossology not working on stock installation

### ISSUE THREAD

**Issue by max-wittig** [fossology/fossology#856]
#### Found some issues, while trying a *really* clean install of fossology. From master branch on a blank virtual machine with debian 8

1. The file in fossology/install/src-install-apache-example.conf is not copied to `/etc/apache2/sites-available/` by default. That means that the user can't go to `127.0.0.1/repo` by default

2. First start only reveals a blank screen and Errorcode 500. On enabling error reporting this message can be seen: 
<pre>
Warning: file_put_contents(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 55
</pre>

3. The next error message after this one:
<pre>permission denied for configuration file common-db.php 57</pre>

4.  Now can be used and you can log in as fossy
But if you try to upload files you get this message:
<pre>
FATAL wget_agent.c.141: upload 14 Failed to import /tmp/phpiGmWJ7-uploaded from /tmp/phpiGmWJ7-uploaded into repository gold D08038579854946FB9AB6130AFAD124812F74499.5D246FF9554A02B782B3C33CA7D35406.372641 </pre>

### Solutions:
To develop again I just ran these commands on my local machine
<pre>
sudo cp fossology/install/src-install-apache-example.conf /etc/apache2/sites-available/
sudo chmod 777 /usr/local/etc/fossology/Db.conf 
sudo chmod -R 777 /var/local/cache/fossology
sudo chmod -R 777 /srv/fossology/
</pre>

I know that this is not a solution, because these permissions are far to lean for production use
That's why I'm opening this issue.
I think we should make it as easy as possible for new contributors. 

What permissions are really needed for these folders/files or who needs to own them(tried fossy and www-data and the current logged in user, no luck) **OR** what am I doing wrong when doing a clean install? I followed the wiki 1:1

**Comment by Lancelof** [comment]
e/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Tue Jun 19 02:32:35.096875 2018] [:error] [pid 33899] [client 192.168.217.141:44576] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Tue Jun 19 02:32:35.096919 2018] [:error] [pid 33899] [client 192.168.217.141:44576] PHP Fatal error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Tue Jun 19 02:32:35.554267 2018] [:error] [pid 33900] [client 192.168.217.141:44578] PHP Warning:  require_once(/var/local/cache/fossology/container.php): failed to open stream: Permission denied in /usr/local/share/fossology/lib/php/common-container.php on line 37
[Tue Jun 19 02:32:35.554333 2018] [:error] [pid 33900] [client 192.168.217.141:44578] PHP Fatal I 

Hello everyone,
I met some similar issue ,here is the information:

error:  require_once(): Failed opening required '/var/local/cache/fossology/container.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/local/share/fossology/lib/php/common-container.php on line 37


Could you please provide any suggestion?

Thanks in advance!

**Comment by mcjaeger** [comment]
sorry just seeing this now. So looking into common-container:

https://github.com/fossology/fossology/blob/a468f4cd2a3006f12aa22af773053034c91a92ac/src/lib/php/common-container.php#L37

shows that fossology would like tot create a file somewhere, presumeably in `/tmp`. I have seen this with SELinux secured systems that this is forbidden for fossology. If you run on such Linux, then you woul dneed to disable SElinux once, start fossology so it can create the cache file and then you could enable SElinux once again
