### ISSUE TITLE
How can I add a new keyword?

### ISSUE THREAD

**Issue by danielursuu** [fossology/fossology#858]
I have a quick question about nomos in Fossology. I want to add a new keyword to see it highlighted. I tried to add it in STRINGS.in from \src\nomos\agent\. For example, I added the word "based" and I want to see it gray in scanning mode. I don't want that word to suggest me a license, just to be highlighted. I found a tutorial about nomos (http://archive15.fossology.org/projects/fossology/wiki/Nomos), but it didn't help me about my enhancement.

Can you help me with a hint? Thank you!

**Comment by mcjaeger** [comment]
Hi, could you pls. point out what did not work and maybe paste a snippet how you changed Strings.in? (which would be the right place for that). I think generally, the tutorial is right an this.

**Comment by danielursuu** [comment]
```
#
%ENTRY% _BASED_ON_KEYWORD
%KEY%      "[Bb]ase(d)?.\son]" 
%STR%      "[Bb]ase(d)?.\son" 
#
```
I added this snippet in STRINGS.in.


Where must I paste this snippet in the parse.c? Which line?
```
else if (INFILE(_BASED_ON_KEYWORD)) {
    INTERESTING("Keyword");
  }
```

Can you help me with an example? Any keyword.

**Comment by danielursuu** [comment]
Also, I tried to change the %STR% from STRINGS.in, but no highlighting.

```
#
%ENTRY%	_KW_require
%KEY%	=NULL=
%STR%	"based"
#
```

I noticed that _KW_ entries don't have implementation in the code of parse.c

**Comment by maximilianhuber** [comment]
@danielursuu du you have closed this issue accidentally?

**Comment by danielursuu** [comment]
No, I fixed it. It was a problem with building. Before "sudo make install"
I must "sudo make clear" the nomos folder. I just added a KW entry in
STRINGS.in.

On Sat, Jul 29, 2017 at 11:15 PM, Maximilian Huber <notifications@github.com
