### ISSUE TITLE
can not view copyright page (debian9 / PHP7)

### ISSUE THREAD

**Issue by bill-auger** [fossology/fossology#860]
when signed in as user login: admin group:admin - clicking on the "copyright" link gives a javascript alert with "You are not logged in. Go to login page? - Cancel? - OK?"

clicking "OK" leads to the login page
clicking "Cancel" dismisses the alert but shows only "Processing..." indefinitely

```
compiled from git master commit 72f0be26b5312f1142574a2aff1d9305f10e85e9

$ uname -a
Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.25-1 (2017-05-02) x86_64 GNU/Linux

$ apt show apache2 | grep Version
Version: 2.4.25-3

$ php --version
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

same result with browsers:
firefox-esr 45.9.0
chrome 59.0.3071.86 
```

**Comment by maximilianhuber** [comment]
Could not be reproduced with current docker setup.

The problem might be the usage of PHP7 which is not yet supported (see #857 and your PR #861).

**Comment by bill-auger** [comment]
thanks max :) 

myself i am quite aware of those PRs and there are commits by me pending in both of them but i dont remember finding any symptoms so figured this should be verified independently - sry 28 days is a bit too long to remember the details but i still have the same setup installed if theres anything you suggest i could do to troubleshoot this

i will change the issue header to reflect this

**Comment by mcjaeger** [comment]
well, it seems to work now (with Safari and FF 63.0) on `Version: [3.4.0], Branch: [master], Commit: [#6ad6a1]`, but to list the details of the test system:

```
fossy@debian:~$ php -version
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
fossy@debian:~$ uname -a
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
fossy@debian:~$ apt show apache2 | grep Version
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Version: 2.4.25-3+deb9u6
```
