### ISSUE TITLE
Color mapping for "risk level"

### ISSUE THREAD

**Issue by deveaud-m** [fossology/fossology#878]
Currently the risk level in the license management UI is shown as a list of integers, from 0 to 5. 
This is not very explicit.

I would propose to use a more "human-readable" definition on the risk level:
* `0 => white`
* `1 => blue`
* `2 => green`
* `3 => yellow`
* `4 => orange`
* `5 => red`

The mapping should be implemented as public function in the `DB Manager` object.

**Comment by mcjaeger** [comment]
@ag4ums, @shaheemazmalmmd didn't we have it already?

**Comment by GMishx** [comment]
Done in #928
