### ISSUE TITLE
Fossology 3.0: mod=agent_nomos_once not available via wget

### ISSUE THREAD

**Issue by zxiiro** [fossology/fossology#880]
I tried using Fossology 3.0 using the `mod=agent_nomos_once` that was available in Fossology 2.0 and get "Module unavailable or your login session timed out.". Did the API URL change or we missed some setting?

**Comment by maximilianhuber** [comment]
The agent is still there:
![2017-07-23_12 50 02](https://user-images.githubusercontent.com/1187050/28498764-7e359d42-6fa5-11e7-9ba3-69046a404496.png)
The problem for you might be that it now needs authentication to access it.

**Comment by maximilianhuber** [comment]
The comment https://github.com/fossology/fossology/issues/592#issuecomment-163885186 might help with the authentication.

**Comment by zxiiro** [comment]
Ok that makes sense then. I was trying to use it anonymously. I guess there's security issues with having this anonymously allowed?

Some backstory is I'm trying to use this tool to validate our code submissions always has a license header attached to them via an automated process as part of code review.

**Comment by maximilianhuber** [comment]
Just an idea: If you have a clearly defined license header, it might be way simpler to test whether all source code files match some regex (or something like: the file should contain the lines of the license header in order within the first 10 lines).

**Comment by zxiiro** [comment]
Yes, that's another route we've been exploring and already have coded for. We wanted to compare that method with using fossology's API. I think we will likely continue with the regex route.
