### ISSUE TITLE
Fossology 3.1 really supports spdx 2.1?

### ISSUE THREAD

**Issue by vignesh-rajendran** [fossology/fossology#899]
As announced in the release,
https://github.com/fossology/fossology/wiki/FOSSology-3.1-Release-Announcement-(Working-Version)

Key features in FOSSology 3.1 are:
Support for SPDX 2.1 document formats(tag:value format now available as well as RDF)

Is really the latest version supports SPDX 2.1?
I have tried the fossology installation in the ways of docker as well as from source.
I can only find the SPDX 2.0 version generated.
Do I missing something?

**Comment by maxhbr** [comment]
You are right, the version in the template [is not updated connectly](https://github.com/fossology/fossology/blob/master/src/spdx2/agent/template/spdx2-document.xml.twig#L11) that is a bug. Thank you for reporting.

**Comment by nhariprasad9** [comment]
Thanks for the response @maxhbr i have reported same issue #902 
So we'll get this fix in the next version of Fossology or how do I get this fixed in my Fossology setup..?

**Comment by mcjaeger** [comment]
please note that the output seems compatible with 2.1 but, we are not using any of the features mentioned in:

https://spdx.org/spdx-specification-21-web-version#h.1sh8jn1fc5zw

**Comment by nhariprasad9** [comment]
Hello, 
Thanks for the info.
Is there any plans to use the features of SPDX 2.1 specification in future releases?

**Comment by vignesh-rajendran** [comment]
@mcjaeger, @maxhbr 

> please note that the output seems is compatible with 2.1 but, we are not using any of the features mentioned in:
> 
> https://spdx.org/spdx-specification-21-web-version#h.1sh8jn1fc5zw
Linking to Security Identifiers like CPE is out of scope in fossology?
https://spdx.org/spdx-specification-21-web-version#h.7i829o8ausxy
