### ISSUE TITLE
Consider changing repo layout to work with "large" (perhaps 16MB) files kind of like hadoop.

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#90]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2343, http://www.fossology.org/issues/2343
Original Date: 2012/06/15

---

Consider changing repo layout to work with "large" perhaps 16MB files kind of like hadoop. Using small files like now (avg size ~32k) makes repo deletes take forever and makes copying the repo take forever. For our repo, we could pack as many files as will fit wholly fit into ~16MB. Larger files would be saved as individual files. The whole point is to consolidate the tiny files to use fewer inodes and thus speed up delagent and repo copies.

**Comment by mcjaeger** [comment]
closing because of missing pickup. (and most of the deleted go reasonably fast today)
