### ISSUE TITLE
Access problems for read-only users

### ISSUE THREAD

**Issue by timurphy** [fossology/fossology#901]
Read-only users get login error messages when accessing various pages. To reproduce:

1. Create a new read-only user, and give that user access to an existing upload.
2. Navigate to the `View Copyright/Email/Url` page for that upload. You will see the following popup:
<img src="https://gist.githubusercontent.com/timurphy/945d05393fc9a1087d8904c9c0578329/raw/9a25e72633fab5ce8667279fbcac23728b00256e/foss_copyright-view.png"/>
Pressing `Cancel` twice allows you to view the page.

3. The same problem occurs for `mod=ecc-view`.
4. Navigate to `mod=view-license`. You will receive the error `Module unavailable or your login session timed out. Click here to continue.` and you will be logged out.

Tested on `Version: [3.1.0], Branch: [HEAD], Commit: [#db77c2]`

**Comment by timurphy** [comment]
Also, if you navigate to the Bucket browser where no data is available, you will see a `No data available` message with a `Schedule Agent` button. Clicking on that button does not schedule anything, and throws the following error as seen in the apache2 `error.log`:

```
[Mon Sep 11 12:28:37.448618 2017] [:error] [pid 421] [client 192.168.99.1:53723] PHP Fatal error:  Uncaught Error: Call to a member function AgentAdd() on null in /usr/local/share/fossology/www/ui/ajax-schedule-agent.php:76\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(392): ajax_schedule_agent->Output()\n#1 /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php(481): FO_Plugin->getResponse()\n#2 /usr/local/share/fossology/www/ui/index.php(62): FO_Plugin->execute()\n#3 {main}\n  thrown in /usr/local/share/fossology/www/ui/ajax-schedule-agent.php on line 76, referer: https://docker.localhost:4443/?mod=bucketbrowser&upload=2&item=2
```

**Comment by shaheemazmalmmd** [comment]
For read-only users the upload is only accessible through browse-page. They cannot view or modify upload contents though the upload is assigned to them.

Please have a look into this pages for more information : 
1) http://archive15.fossology.org/projects/fossology/wiki/User_Permissions
2) http://archive15.fossology.org/projects/fossology/wiki/Perms

**Comment by timurphy** [comment]
@shaheemazmalmmd if the file contents should not be accessible to read-only users then the links to those functions need to be removed, and the permission checking for those functions more robust. Receiving error messages about not being logged in or being logged out after trying to access a page is not acceptable from a user perspective.

**Comment by mcjaeger** [comment]
bucker effor is not coming anymore and also the message dialog `You are not logged in...` is not appearing anymore.
