### ISSUE TITLE
SPDX 2.1 files not generated with latest version of Fossology

### ISSUE THREAD

**Issue by nhariprasad9** [fossology/fossology#902]
I have installed latest version of fossology using Docker
When i generate SPDX reports, the reported generated have SPDX v2.0
But in the release notes it is mentioned that SPDX v2.1 is supported in the latest version
Please let me know how do i fix this and get SPDX v2.1 files

**Comment by mcjaeger** [comment]
it seems like the output is compatible with 2.1 but we are not using any of the features mentioned in:

https://spdx.org/spdx-specification-21-web-version#h.1sh8jn1fc5zw

**Comment by mcjaeger** [comment]
actually, let's continue at https://github.com/fossology/fossology/issues/899
