### ISSUE TITLE
Tag correctly docker releases

### ISSUE THREAD

**Issue by AndreaGiardini** [fossology/fossology#913]
The only tag available in the docker hub right now is `latest`. That's not sufficient for most of the people.

We should create a different tag for every release

**Comment by maxhbr** [comment]
Thank you for mentioning that. We will improve the docker tagging, or create tagged releases manually.

ping @bufferoverflow @max-wittig

**Comment by AndreaGiardini** [comment]
Let me know if I can help in any way. Just pointing me in the good direction would be of great help

**Comment by mcjaeger** [comment]
so it is to create a docker for every tag? because I updated for 3.2, or it is sufficient like this then?

**Comment by maxhbr** [comment]
looks sufficient at: https://hub.docker.com/r/fossology/fossology/tags/
