### ISSUE TITLE
fossology/install/docker-compose.docker-entrypoint.sh: Permission denied

### ISSUE THREAD

**Issue by NesrinCeylan** [fossology/fossology#917]
By executing the command 

```
# docker-compose up
```

I'm getting the error of "Permission denied", although I have changed the owner as you can see: 

```
-rw-rw-r--  1 ceylan ceylan  2543 Okt 14 10:04 docker-compose.docker-entrypoint.sh
-rw-rw-r--  1 ceylan ceylan  2950 Okt 14 10:04 docker-compose.Dockerfile
-rwxrwxrwx  1 ceylan ceylan  2441 Okt 18 13:28 docker-compose.yml
-rwxr-xr-x  1 ceylan ceylan  1018 Okt 14 10:04 easy-install
-rw-rw-r--  1 ceylan ceylan   443 Okt 14 10:04 fo-apache.conf
-rwxr-xr-x  1 ceylan ceylan  5435 Okt 14 10:04 fo_dbcheck.php
-rw-rw-r--  1 ceylan ceylan 11464 Okt 14 10:04 fo-postinstall.in
-rwxr-xr-x  1 ceylan ceylan 19350 Okt 14 10:04 fossinit.php
-rw-rw-r--  1 ceylan ceylan   123 Okt 14 10:04 INSTALL
-rw-rw-r--  1 ceylan ceylan   169 Okt 14 10:04 INSTALL.multi
-rw-rw-r--  1 ceylan ceylan  4933 Okt 14 10:04 Makefile
drwxrwxrwx  2 root   root    4096 Okt 18 09:42 _repository
```

The output looks like: 

```
ossology-base-image_1  | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-db_1          | 2017-10-18 13:55:34.331 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
fossology-db_1          | 2017-10-18 13:55:34.331 UTC [1] LOG:  listening on IPv6 address "::", port 5432
fossology-db_1          | 2017-10-18 13:55:34.405 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-base-image_1 exited with code 126
fossology-db_1          | 2017-10-18 13:55:34.677 UTC [23] LOG:  database system was shut down at 2017-10-18 13:51:41 UTC
fossology-web_1         | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-db_1          | 2017-10-18 13:55:34.728 UTC [1] LOG:  database system is ready to accept connections
install_fossology-scheduler_1 exited with code 126
install_fossology-web_1 exited with code 126
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-scheduler_1 exited with code 126
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
```
Thankful of any help. I'm searching the whole for solutions, but can't fix it.

**Comment by maxhbr** [comment]
The file `docker-compose.docker-entrypoint.sh` is not executable, maybe try `chmod  +x docker-compose.docker-entrypoint.sh`

**Comment by NesrinCeylan** [comment]
Yes, I tried but then the next error is displayed: 

ERROR: for fossology-db  Cannot start service fossology-db: driver failed programming external connectivity on endpoint install_fossology-db_1 (5bf44885918287b8745e33b0ffbcbc0ed16f19b5a289817e9e2b6febad3c56d8): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project. 


The o/p of netstat -nl -p tcp  | head tells:

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1439/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      4396/cupsd      
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1318/postgres  

As I understand, the problem is on port. So I tried to remove all container and start docker-compose up again, but already with the same issue.

**Comment by NesrinCeylan** [comment]
starting again. Same Error. 

ERROR: for fossology-db Cannot start service fossology-db: driver failed programming external connectivity on endpoint install_fossology-db_1 (5bf44885918287b8745e33b0ffbcbc0ed16f19b5a289817e9e2b6febad3c56d8): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
stopping service with 
 $ pkill postgres
starting docker-compose service again: 
$sudo docker-compose up

Displayed output: 

Starting install_fossology-db_1
Starting install_fossology-base-image_1
Creating install_fossology-scheduler_1
Creating install_fossology-web_1
Attaching to install_fossology-base-image_1, install_fossology-db_1, install_fossology-scheduler_1, install_fossology-web_1
fossology-base-image_1  | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-base-image_1 exited with code 126
fossology-db_1          | 2017-10-19 07:13:35.317 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
fossology-db_1          | 2017-10-19 07:13:35.317 UTC [1] LOG:  listening on IPv6 address "::", port 5432
fossology-db_1          | 2017-10-19 07:13:35.428 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
fossology-db_1          | 2017-10-19 07:13:35.657 UTC [22] LOG:  database system was shut down at 2017-10-18 13:56:32 UTC
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-db_1          | 2017-10-19 07:13:36.232 UTC [1] LOG:  database system is ready to accept connections
fossology-web_1         | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-scheduler_1 exited with code 126
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-web_1 exited with code 126
fossology-web_1         | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-web_1         | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-web_1         | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
install_fossology-scheduler_1 exited with code 126
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied
fossology-scheduler_1   | /bin/bash: /fossology/install/docker-compose.docker-entrypoint.sh: Permission denied

Although I have all permissions.

**Comment by maxhbr** [comment]
You should not run a postgres on the host, this might collide with the postgres in the `install_fossology-db_1` container, which is used by the docker-compose setup.

**Comment by NesrinCeylan** [comment]
So I have to uninstall postgres on host. okay, I'll try

**Comment by NesrinCeylan** [comment]
After uninstall postgres, reboot and try again, I got already the default: 

**:~**fossology-master/install$ sudo docker-compose up
Starting install_fossology-db_1
Starting install_fossology-base-image_1

ERROR: for fossology-db  Cannot start service fossology-db: driver failed programming external connectivity on endpoint install_fossology-db_1 (29516ff02a3c49b8b86801aabe7f9da3e237a9940ba510b05210a1fc5bd0fce8): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.

Taking loog for 

$ netstat -nl -p tcp | head

Output: 

tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::8080                 :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
udp        0      0 0.0.0.0:42901           0.0.0.0:*                           -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           -            

Stoping container, after updating and I try again to execute docker-compose: 

ERROR: for fossology-db  Cannot start service fossology-db: driver failed programming external connectivity on endpoint install_fossology-db_1 (8a0e2e5f312e28e901cf84559503ac8191297a3ffe905738db719d307dead178): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.

:(

**Comment by NesrinCeylan** [comment]
on another maschine it runs without any problems.

**Comment by maxhbr** [comment]
For debugging you could add the `set -x` switch to the top of the `docker-compose.docker-entrypoint.sh` script. That would add more debugging information and you would see, which command is failing.

**Comment by NesrinCeylan** [comment]
I've build up my maschine new. That soluted my problem. Not elegant but, I did't saw any other solutions. 
Thank you anyway.
