### ISSUE TITLE
Hardcoded php version

### ISSUE THREAD

**Issue by bcornec** [fossology/fossology#920]
In pbconf/fossology/deb/fossology-web.postinst (as well as in the debian directory) there is a hard coded version of PHP mentioned:

sed -r -i.bak 's/;? ?upload_max_filesize ?= ?[0-9]+[kmgKMG]*/upload_max_filesize = 750M/' /etc/php5/apache2/php.ini

But that file doesn't exist on Debian 9 as it's using PHP7.

**Comment by GMishx** [comment]
Fixed
https://github.com/fossology/fossology/blob/master/pbconf/fossology/deb/fossology-web.postinst#L27
