### ISSUE TITLE
Add license from kernel object modules (license from modsym) to license_file 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#93]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2367, http://www.fossology.org/issues/2367
Original Date: 2012/06/15
Original Assignee: Bob Gobeille

---

None

**Comment by yaobinshi** [comment]
---

Original Redmine Comment
Author Name: **larry shi** 
Original Date: 2013/01/07 08:57:56 +0000

---

bob, can you help to explain what does this issue want to say?
thanks

**Comment by mcjaeger** [comment]
closing because of missing pickup
