### ISSUE TITLE
Not recognizing "SPDX-License-Identifier:" with SPDX expressions in files.

### ISSUE THREAD

**Issue by kestewart** [fossology/fossology#932]
As more and more projects are adding the identifier at the file level, can we please recognize the licenses indicated as "detected in file".   Current scanners (nomos & monk) seem to be missing picking them up.

Ideally these should be considered the concluded license for a file, but just recognizing them and adding them as detected,  would be very helpful right now.

Apologies if this is a duplicate,  I looked but couldn't see a relevant one.  Just link to any pre-existing and close this one if it is.

**Comment by rlintu** [comment]
I'm preparing a nomos contribution which should cover also (at least some of) these issues.

**Comment by mcjaeger** [comment]
sorry for leaving this open for such a long time, but as  @rlintu mentioned, it is in - hooray!

![image](https://user-images.githubusercontent.com/3418977/46284703-21961a00-c579-11e8-931d-7897c83cdb3e.png)
