### ISSUE TITLE
C unit test compiling failed (Ubuntu 16.04)

### ISSUE THREAD

**Issue by rlintu** [fossology/fossology#939]
I changed my test environment to Ubuntu 16.04 and noticed that nomos/make test compiling failed.
```
run_tests.c:53:38: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     {"Testing process:", NULL, NULL, nomos_gap_testcases},
```
The reason seems to be that CU_SuiteInfo struct definition has changed. Ubuntu 16.04 has CU_VERSION "2.1-3", I do not recall which version the earlier Ubuntu version had. The change below in run_tests.c solved the compiling issue. 

```
CU_SuiteInfo suites[] =
 {
-    {"Testing process:", NULL, NULL, nomos_gap_testcases},
-    {"Testing doctor Buffer:", NULL, NULL, doctorBuffer_testcases},
+    {"Testing process:", NULL, NULL, NULL, NULL, nomos_gap_testcases},
+    {"Testing doctor Buffer:", NULL, NULL, NULL, NULL, doctorBuffer_testcases},
     CU_SUITE_INFO_NULL
 };
```
I didn't find any CUnit related definition in makefiles or configuration. Any suggestion how to handle this so that manual editing is not needed?

**Comment by GMishx** [comment]
Issue was fixed in #1050
