### ISSUE TITLE
License List no longer includes license

### ISSUE THREAD

**Issue by valerie7869** [fossology/fossology#943]
I just began using version 3.2, and have found the file created from 'License List' no longer contains any licenses or license information, and now contains only a list of files.  Even the 'No_license_found' notice is not present anywhere.  (also, the 'License List Download' is no longer present)

I get these described results upon using the fossology container from Docker with:
Version: [unknown], Branch: [master], Commit: [#56cf1a] 2017/11/07 15:43 UTC built @ 2017/11/07 16:05 UTC

and i get the same results using your public fossology instance at 
http://52.26.97.143/repo/
which is version:
Version: [3.2.0rc1], Branch: [master], Commit: [#30cf2e] 2017/10/20 13:55 UTC built @ 2017/10/23 00:41 UTC

Attached file illustrates the issue;  it is the .csv from a 'License List' download, and shows no license information anywhere (now saved as .xlsx).

Previously, I used version 3.0.0 and the License List Download feature works reliably there.

Thank you.
[zlib-1.2.8.tar.gz-20171113.xlsx](https://github.com/fossology/fossology/files/1468024/zlib-1.2.8.tar.gz-20171113.xlsx)

**Comment by mcjaeger** [comment]
I think it is still working. Do you expect a license list like in the screenshot? did you check the check boxes? Maybe the agent did not run properly.

![asdfasdasd](https://user-images.githubusercontent.com/3418977/33010024-34574e0e-cdd9-11e7-9500-9affa0f11877.png)

**Comment by valerie7869** [comment]
Thank you-- you are correct --- (I was always checking the 'Show directories and containers?' box, and that created the results I saw.)
Thanks very much for helping on this!
