### ISSUE TITLE
Remove bucket code that determines what bucket a container is in. 

### ISSUE THREAD

**Issue by yaobinshi** [fossology/fossology#95]
---

Author Name: **Paul Holland** 
Original Redmine Issue: 2379, http://www.fossology.org/issues/2379
Original Date: 2012/06/15

---

After implementation we decided that this feature was way too confusing for the user because of the hierarchical nature of bucket evaluation. This will speed up bucket scans. Remove bucket_container table.

**Comment by mcjaeger** [comment]
closing because of missing pickup
