### ISSUE TITLE
Upload Name 

### ISSUE THREAD

**Issue by NicolasToussaint** [fossology/fossology#959]
When uploading "From Server", the "Upload Name", as shown in the Browser, seems to be derived from the entered file path.
The problem is that if the depending on how the filesystem is organized on the server, this might not be relevant.
For example, Folder /workspaces/my-project/src/ => upload name is 'src'
With jokers, Folder /workspaces/my-project/src/* => upload name is '*'

Why not add an extra field, that could be filled by default with the path last part (as today) but could be overridden by hand ?

![image](https://user-images.githubusercontent.com/22956329/33934834-50e2acfc-dffa-11e7-8d60-bcead2bb7e77.png)

**Comment by mcjaeger** [comment]
(from discussion)
true this appears like a bug. If there are multiple files there could be a name field that a user can filled out optionally if she is afraid of having the actual path entered.

**Comment by amanjain97** [comment]
I would like to work on this ticket. Can you please address the following questions regarding the issue.

1. If filename is "*" then do we have to rename it to its parent directory name? Or Is this issue just regarding the upload from VCS and no ambiguous names of the folder can be there?
2. Should the name of the file be overridden by hand for all of the cases (files and folders).

**Comment by NicolasToussaint** [comment]
I think the problem only happens when uploading fro the server (Menu: Upload -> From Server) because this is where wildcards are accepted.

![image](https://user-images.githubusercontent.com/22956329/37656558-ac2ada2c-2c48-11e8-9fcc-3be140738c53.png)

What I could imagine is adding a new textfield in the above screen that is:
- Titled _Upload Name_ 
- Between _2. Enter the file path:_ and _3. (Optional) Enter a description of this file:_ 

If possible, it could be filled automatically from what has been entered in the 2nd textfield, but could then be overridden by the user if it does not look good.

And as an extra, I think we should rename "_Enter a description of this file:_" to "_Enter a description of this **upload**_" because the upload is not necessarily a file.

**Comment by amanjain97** [comment]
I think it should be similar to point 3 in "Upload from URL"
![image](https://user-images.githubusercontent.com/11582770/37682184-cd5eb4c8-2cae-11e8-9d8e-ba8f9efe2e7f.png)
Please confirm.

Also, I think we should rename "Enter a description of this file:" to "Enter a description of this upload" in "Upload from URL/Server/VCS" all of them.

**Comment by NicolasToussaint** [comment]
Aman,

First, I don't know the product that much myself (yet), please make sure the modifications are OK with our dear maintainers before spending to much time on it :-)

To "upload files from from server":
- First, you need to look (and possibly change) the following settings in Admin -> Customize:
![image](https://user-images.githubusercontent.com/22956329/37762781-9604ca66-2dbd-11e8-92ed-be6dcb3f7f97.png)

- Then, upload the files to be scanned on the server filesystem.
- Click Upload + "from Server".
![image](https://user-images.githubusercontent.com/22956329/37762689-5d8d70e8-2dbd-11e8-8aa2-b01f0ba9db53.png)

**Comment by amanjain97** [comment]
Thanks for the reply. I have also discussed this with Michael.

**Comment by GMishx** [comment]
Fixed by pull request #1048 .
