### ISSUE TITLE
Is there anyway to find out the Upload ID of an upload besides Geeky Scan Details?

### ISSUE THREAD

**Issue by W-Park** [fossology/fossology#971]
I wanted to get the Upload ID of an upload.
But when I get to the Geeky Scan Details page, the table was broken.
![image](https://user-images.githubusercontent.com/33045921/35087960-4b53531c-fc75-11e7-9b7f-89f057f86644.png)

I suppose it is related the issue in 2015 (https://github.com/fossology/fossology/issues/513)

Is there anyway to get the Upload ID besides the Geeky Scan Details?

I tried IE11, and Chrome 63.0.3239.132 and both didn't worked.

**Comment by mcjaeger** [comment]
hello, actually it is a problem maybe of an old version. Have you considered updating. It is wprking on current master and I guess also on earlier stages.
![image](https://user-images.githubusercontent.com/3418977/35721865-5c391ba0-07f4-11e8-9bae-d42a23540132.png)

**Comment by W-Park** [comment]
Thank you for reply.
I actually am considering updating.
Maybe when 3.2.0 is officially released, I will.

I was aware of that this issue was fixed (at least since 3.1.0) but I just wanted to wait until 3.2.0 is official.
