### ISSUE TITLE
Merging FOSSology instances

### ISSUE THREAD

**Issue by tykeal** [fossology/fossology#974]
Is there any way to merge instances? I've got a few folks that have been locally running FOSSology 3 in docker containers but we need to merge data into a hosted system we've got.

**Comment by mcjaeger** [comment]
I do not think merging would be easily possible. there is no comprehensive functionality in FOSSology to merge two instances. However, FOSSology has a couple of measures to support moving from one instance to another:

* users: FOSSology can export and import user and group information based on a CSV format. In essence, if you export the users files from one server, and import this to another, all required group assignments are covered. if you have set custom incoming folders, they will be created accordingly.
* Licenses: Just as with users, FOSSology allows for exporting and importing all licenses. So your created licenses on one server can be easily transferred by this. There is even a recognition for having the same text under different name when importing. However, there is no import / export of candidate licenses.
* Obligations: similar to licenses, also obligations can exported and imported again.

-> So, if you move to a clean server, all these aspects can be actually migrated.

Probably then main thing to to migration of data from one server to another is the use of the backup scripts. However, this does not allow for merging. Restoring from backup is pretty much overwriting diverging states.

please note that FOSSology offers for this case "Import Report" where you could take over licensing analysis for particular uploads. But this requires to have the actual upload in place where you import the licensing information to.

**Comment by mcjaeger** [comment]
@tykeal pls. indicate: is the answer Ok for you or shall we clarify something?
