### ISSUE TITLE
Search: wrong number of files matching the search criteria (>100)

### ISSUE THREAD

**Issue by dwojtasiuk** [fossology/fossology#985]
Hello,

The count in Search stops at 100, which is the max number of records per page. In case there are more than a hundred files matching the search criteria, you have to go to the last page of search results to see how many files are actually there.
![image](https://user-images.githubusercontent.com/36267903/35976763-689410ca-0ce1-11e8-8ba2-1228d8ec3f00.png)

Version: [3.2.0rc1], Commit: [#dc43fd]

**Comment by amanjain97** [comment]
@daniellandau @mcjaeger Apart from this, why there is an indentation in the search results (201 and 202). Is that an issue with UI or it is relevant to the application?

**Comment by amanjain97** [comment]
@mcjaeger Please review the PR #1004 and close the issue.

**Comment by GMishx** [comment]
Working fine now. Thanks @amanjain97 
![file-counter](https://user-images.githubusercontent.com/18077542/42694343-ba97a0d6-86cf-11e8-8975-7af3b62a5d54.png)
