### ISSUE TITLE
cp2foss -X parameter does not work (but it is a wget_agent bug)

### ISSUE THREAD

**Issue by alpianon** [fossology/fossology#988]
cp2foss manual says:
```
       -X  Items to exclude when the input archive is a directory. You can
           specify more than one -X.  For example, to exclude all svn and cvs
           directories, include the following before the archive's directory
           path: -X .svn -X .cvs
```
but such option does not work: directories that are supposed to be excluded are instead uploaded.

cp2foss uses wget_agent, which in turn uses tar to exclude directories (with the --exclude option).
However, wget_agent puts the exclude option at the very end of the parameters passed to tar command, **after the name of the dir to be compressed**, and therefore such option is ignored. 

I wrote a little wrapper script for the tar command, in order to log the parameters passed by wget_agent, and I found out that the following command:
```
cp2foss -s --username fossy --password fossy -X .git my_source/
```
calls wget_agent, which in turn calls tar with the following options:
```
tar -cf /srv/fossology/repository/fossology/wget/wget.17464 -C /home/user/my_source ./ --exclude .git
```
which does not work, in the sense that the .git subdirectory is not excluded from upload.

Wget_agent should be patched to put such option at the beginning.

**Comment by mcjaeger** [comment]
@maxhbr closing?

**Comment by maxhbr** [comment]
Yes
