### ISSUE TITLE
Docker container versions

### ISSUE THREAD

**Issue by tykeal** [fossology/fossology#990]
Currently there are two FOSSology docker containers labeled on Dockerhub.

latest (which looks like it's probably building off of the master HEAD) and 3.1.0rc1

We've had customers requesting that we run specific versions of FOSSology 3 and only upgrade when a major release comes out. The issue is that we've got no way to do this when we're running FOSSology out of containers since there aren't any version labeled containers currently existing.

Please update Dockerhub to add in at least v3.2.0 as a distinct container!

**Comment by mcjaeger** [comment]
Hm, the latest build (4 days ago) did run. (which matches also the last commit date) will have a look.

**Comment by mcjaeger** [comment]
should be there. Could you pls check?

![image](https://user-images.githubusercontent.com/3418977/36417334-f36553d2-162b-11e8-865c-1f00cbced397.png)

**Comment by tykeal** [comment]
Yes, I do see the tagged version now. Thanks for getting that in there!
