### ISSUE TITLE
Anonymous user : "not allowed without login" even when granted to

### ISSUE THREAD

**Issue by mhow2** [fossology/fossology#996]
Hi,
It looks like #994 was not enough to fix some other parts of the UI.

With the following upload config :
![screenshot-2018-3-7 edit uploaded file permissions](https://user-images.githubusercontent.com/9987241/37084711-872c6de4-21f3-11e8-96b8-436e40b74590.png)

I got a blank page when trying to click the link with that upload name on the browse page. Ie at URI `/repo/?mod=license&upload=3&folder=1&item=109&show=quick`

And again the same error in logs:

`
[Wed Mar 07 09:37:46.971314 2018] [:error] [pid 196] [client 172.18.0.1:55528] PHP Fatal error:  Uncaught exception 'Exception' with message 'not allowed without login' in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:323\nStack trace:\n#0 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(240): Fossology\\Lib\\Plugin\\DefaultPlugin->checkPrerequisites()\n#1 /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php(275): Fossology\\Lib\\Plugin\\DefaultPlugin->getResponse()\n#2 /usr/local/share/fossology/www/ui/index.php(62): Fossology\\Lib\\Plugin\\DefaultPlugin->execute()\n#3 {main}\n  thrown in /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php on line 323, referer: https://fossology.ow2.org/repo/?mod=browse
`

Overall the same error happens with:
```
/?mod=fileBrowse&upload=3&show=quick&item=109
/?mod=copyright-view&upload=3&show=quick&item=109
```

**Comment by maxhbr** [comment]
PR is created as https://github.com/fossology/fossology/pull/1043
