### ISSUE TITLE
Fossology does not show License

### ISSUE THREAD

**Issue by kohldampfer** [fossology/fossology#999]
Under **Organize -> Licenses** I created a new license. When I now start a check from Subversion (**Upload -> From Version Control System**) I get only an "UnclassifiedLicense" for these files. I assumed here, that I will see the newly added license, not an "UnclassifiedLicense".

**Comment by mcjaeger** [comment]
hello, thanks for your feedback. I guess without the files it will be hard to determined what is going on. Would it be possible to see some examples of the files where you get this result?

**Comment by ag4ums** [comment]
Adding a license from the UI does not mean it will detect license from a package, may be if there are full/partial match with the text then it will be detected by Monk, 
UnclassifiedLicense is detected by Nomos, as no match found with the existing license signatures.
This link (https://github.com/fossology/fossology/wiki/Nomos#how-to-add-a-new-license-signature), will be helpful to add a license signature with nomos.

**Comment by kohldampfer** [comment]
@ag4ums Sorry for the late response. Thank you for your answer. That helped me a lot!

From my perspective, this issue can be closed.
